export const amizades = {
  mensagensDiretas: "الرسائل المباشرة",
  nova: {
    titulo: "محادثة جديدة",
    detalhe: "اختر صديقًا لبدء المحادثة.",
    procurar: "ابحث عن صديق",
    semAmigos: "ليس لديك أصدقاء هنا بعد.",
    semResultado: "لا يوجد صديق بهذا الاسم.",
  },
  adicionar: {
    recado: "اكتب رسالة قصيرة (اختياري)",
    recadoDica: "ما تكتبه هنا يظهر أيضًا في محادثتكما إن صرتما صديقين.",
    enviadoPara: "تمّ! وصل طلب الصداقة إلى {{nome}}.",
    outrosLugares: "أماكن أخرى لتكوين صداقات",
    outrosLugaresDetalhe: "لا يخطر أحد ببالك؟ ألقِ نظرة على المجتمعات المفتوحة، هناك من يتحدّث في كل شيء تقريبًا.",
    explorarComunidades: "استكشاف المجتمعات",
    titulo: "إضافة صديق",
    detalhe: "يمكنك إضافة الأصدقاء باسم المستخدم الخاص بهم.",
    exemplo: "اسم المستخدم، مثل: thiago",
    enviando: "جارٍ الإرسال…",
    enviar: "إرسال الطلب",
  },
  gatinhoChorando: "قطة صغيرة تبكي",
  status: {
    emChamada: "في مكالمة",
    emVoz: "في الصوت",
  },
  menu: {
    chamada: "بدء مكالمة",
    fixar: "تثبيت في الأعلى",
    desafixar: "إلغاء التثبيت",
    silenciar: "كتم المحادثة",
    reativar: "إعادة تفعيل الإشعارات",
    copiarIdDoCanal: "نسخ معرّف القناة",
  },
  ativosAgora: "نشط الآن",
  procurando: "نرى من الموجود…",
  tudoTranquilo: "كل شيء هادئ الآن…",
  tudoTranquiloDetalhe: "عندما تنضم أنت أو صديق إلى مكالمة، ستظهر هنا — ويمكنك الانضمام بنقرة واحدة.",
  emVoz: "في محادثة صوتية",
  voce: "أنت",
  soVoce: "أنت فقط",
  pessoas: "{{quantas}} أشخاص",
  voltarParaChamada: "العودة إلى المكالمة",
  entrarNaChamada: "الانضمام إلى المكالمة",
  abrirCanal: "فتح {{canal}} في {{servidor}}",
  encontreConversa: "ابحث عن محادثة",
  amigos: "الأصدقاء",
  conversas: "المحادثات",
  semConversas: "لا توجد محادثات بعد. أضف صديقًا للبدء.",
  semConversaComEsseNome: "لا توجد محادثة بهذا الاسم.",
  abrirMenu: "فتح الخوادم والمحادثات",
  solicitacoes: "طلبات الرسائل",
  pedidos: "الطلبات",
  spam: "مزعج",
  pedidosPendentes: "طلبات معلقة",
  marcadosComoSpam: "موسومة كمزعجة",
  aceitar: "قبول",
  ignorar: "تجاهل",
  marcarSpam: "وسم كمزعج",
  semPedidos: "لا توجد طلبات في الانتظار.",
  semPedidosDetalhe: "من ليس صديقك لكنه يشاركك خادمًا يصل إلى هنا قبل أن يصل إلى محادثاتك.",
  semSpam: "لا شيء موسوم كمزعج.",
  semSpamDetalhe: "ما يفرزه مرشح المزعج، أو ما تسمه أنت، يبقى في هذا التبويب.",
  umServidorEmComum: "خادم مشترك واحد",
  servidoresEmComum: "{{quantos}} خوادم مشتركة",
  semServidoresEmComum: "لا توجد خوادم مشتركة",
};
