export const configuracoes = {
  efeitos: {
    titulo: "تأثيرات المؤشّر",
    detalhe: "أثر وشرر يُرسمان فوق التطبيق. يبدآن مطفأين، ويختفيان وحدهما إن طلبت حركة أقل.",
    rastro: "أثر المؤشّر",
    rastroDetalhe: "خط يتبع المؤشّر ويخفت خلفه.",
    faisca: "شرر عند النقر",
    faiscaDetalhe: "خطوط قصيرة تنطلق من موضع نقرتك.",
    cor: "اللون",
    espessura: "السماكة",
    comprimento: "الطول",
    tamanho: "الحجم",
    quantidade: "العدد",
  },
  email: {
    verificarTitulo: "أكّد بريدك الإلكتروني",
    verificarDetalhe: "بعض المجتمعات لا تسمح بالكتابة إلا لمن أكّد بريده. الأمر بنقرة واحدة.",
    enviar: "أرسل الرابط",
    enviado: "راجع صندوق الوارد. الرابط صالح ليوم واحد.",
    falhou: "تعذّر إرسال البريد.",
    confirmado: "تم تأكيد البريد",
    confirmadoDetalhe: "تمّ الأمر. صرت تكتب في أي مجتمع يشترط ذلك.",
    linkIncompleto: "رابط ناقص",
    linkIncompletoDetalhe: "ينقص الرمز في العنوان. افتح الرابط من البريد مباشرة.",
    confirmando: "جارٍ التأكيد…",
    expirou: "استُخدم هذا الرابط من قبل أو انتهت صلاحيته.",
    irParaOApp: "الذهاب إلى التطبيق",
  },
  tema: {
    indisponivel: "السمة غير متاحة",
    indisponivelDetalhe: "حذفها ناشرها، أو أن الرابط خاطئ.",
    indisponivelLinha: "السمة غير متاحة. حذفها ناشرها، أو أن الرابط خاطئ.",
    importar: "استيراد السمة",
    importarCurto: "استيراد",
    importarDetalhe: "سيحل هذا محل السمة الحالية. يمكنك تعديلها لاحقًا من الإعدادات > المظهر > استوديو السمات.",
    porAutor: "بواسطة {{autor}}",
    umaCorTrocada: "لون واحد مُبدَّل",
    coresTrocadas: "{{quantas}} لونًا مُبدَّلًا",
    avisoDeCss: "تحمل هذه السمة CSS من كاتبها، وCSS يطال أي ركن من الشاشة. لا تستوردها إلا ممن تثق بهم.",
    soCores: "هذه السمة تبدّل الألوان فقط. لا CSS خارجي فيها.",
    verCss: "عرض CSS",
    esconderCss: "إخفاء CSS",
    aplicar: "تطبيق",
    previaSemMotor: "المعاينة لا تشغّل المحرّك. ثبّتها لتراه.",
    motorAnimado: "{{motor}} متحرك",
  },
  sair: "تسجيل الخروج",
  versoes: {
    termos: "شروط الخدمة",
    privacidade: "سياسة الخصوصية",
    copiar: "انقر للنسخ",
    copiado: "تم النسخ",
  },
  appColors: {
    title: "ألوان التطبيق",
    detail: "اختر حتى ثلاثة ألوان ليأخذ التطبيق كله هذا التدرج.",
    locked: "محرر الألوان من مزايا {{plan}}.",
    color: "اللون {{number}}",
    addColor: "إضافة لون",
    removeColor: "إزالة اللون",
    surprise: "فاجئني",
    direction: "اتجاه التدرج",
    intensity: "الشدة",
    reset: "إعادة الضبط",
  },
  subscription: {
    colorsRow: "محرر ألوان التطبيق",
    seePlans: "عرض الخطط",
    upgradeSubtitle: "حدود أعلى وميزات حصرية للكتابة وإرسال الملفات والبث.",
    perMonth: "شهريًا",
    perYear: "سنويًا",
    save: "وفّر {{percent}}%",
    howToPay: "كيف تريد الدفع؟",
    legal: "يمكنك طلب استرداد خلال 7 أيام من الدفع. تعالج Stripe عملية الدفع؛ ولا نرى رقم بطاقتك أبدًا.",
    compare: "المجاني مقابل Infinity",
    featureColumn: "الميزة",
    freeColumn: "مجاني",
    messageRow: "حد أحرف الرسالة",
    attachmentRow: "حجم الملف المرسل",
    screenRow: "جودة الفيديو",
    megabytesValue: "{{value}} ميغابايت",
    screenValue: "{{resolution}} · {{fps}} إطار/ث",
    alreadyPremium: "لديك Infinity بالفعل حتى {{date}}.",
    upsell: "ارفع الحد مع Infinity",
    screenUpsell: "جودة أعلى مع Infinity",
    free: "أنت على الخطة المجانية.",
    activeUntil: "Infinity مفعّل حتى {{date}}.",
    renews: "يتجدد تلقائيًا في {{date}}.",
    endsAt: "أُلغي الاشتراك وينتهي في {{date}}.",
    pastDue: "فشلت آخر عملية دفع. حدّث بطاقتك حتى لا تفقد Infinity.",
    waiting: "جارٍ تأكيد الدفع…",
    subscribe: "اشترك",
    monthly: "شهري",
    yearly: "سنوي",
    automatic: "بطاقة",
    manage: "إدارة الدفع",
    refund: "طلب استرداد",
    refundDetail: "يمكنك الانسحاب خلال 7 أيام من الدفع: {{amount}}، حتى {{date}}.",
    refundConfirm: "طلب الاسترداد؟",
    refundConfirmDetail: "يعود المبلغ إلى وسيلة الدفع نفسها وينتهي Infinity فورًا.",
    refunded: "تم طلب الاسترداد.",
    unavailable: "الاشتراك غير متاح بعد.",
    success: "تم استلام الدفع. شكرًا لك!",
    canceled: "أُلغي الدفع.",
    error: "حدث خطأ. حاول مرة أخرى.",
    no: "لا",
    tagRow: "وسم مستخدم مخصص",
    guildProfilesRow: "ملفات شخصية لكل مجتمع",
    badgeRow: "شارة الملف الشخصي",
    communitiesRow: "المجتمعات",
    savedRow: "الرسائل المحفوظة",
    animatedEmojiRow: "الرموز التعبيرية المتحركة",
    expressionsRow: "الرموز والملصقات من أي مكان",
    animatedProfileRow: "صور رمزية ولافتات متحركة",
    earlyAccessRow: "وصول مبكر إلى الميزات الجديدة",
    themesRow: "سمات مخصصة",
    pixOption: "Pix",
    pixHint: "افتح تطبيق البنك، واختر Pix وامسح رمز QR أو استخدم النسخ واللصق.",
    pixQrAlt: "رمز QR لـ Pix",
    pixCopy: "نسخ رمز Pix",
    pixCopied: "نُسخ رمز Pix",
    pixWaiting: "بانتظار الدفع",
    pixExpiresIn: "ينتهي خلال {{time}}",
    pixExpired: "انتهت صلاحية Pix هذا. أنشئ واحدًا جديدًا للمتابعة.",
    pixNew: "إنشاء Pix جديد",
    pixPaid: "تم استلام Pix! أصبح Infinity مفعّلًا.",
    forMe: "لي",
    asGift: "كهدية",
    buyGift: "شراء هدية",
    giftReady: "الهدية جاهزة! انسخ الرابط وأرسله لمن تريد.",
    giftClaimed: "تم استخدام الهدية! أصبح Infinity في حسابك.",
    gifts: "الهدايا",
    giftsEmpty: "لم تشترِ أي هدية بعد.",
    giftCode: "رمز الهدية",
    giftRedeem: "استخدام",
    giftCopyLink: "نسخ الرابط",
    giftLinkCopied: "نُسخ الرابط",
    giftClaimedBy: "استخدمها {{name}}",
    giftHint: "لديك رمز هدية؟ استخدمه هنا. الهدايا التي اشتريتها تظهر أدناه.",
    cardPaid: "تمت الموافقة على الدفع! أصبح Infinity مفعّلًا.",
    payAmount: "ادفع {{amount}}",
    giftLinkTitle: "وصلتك هدية {{plan}}!",
    giftLinkDetail: "اضغط على استخدام وستُضاف الأيام إلى حسابك.",
    pageTitle: "افتح عالمًا من المزايا مع {{plan}}",
    pageStart: "الرئيسية",
    pageBest: "أفضل ما في Infinity",
    pageChoose: "اختر خطتك",
    fromPrice: "ابتداءً من {{amount}} شهريًا. ألغِ متى شئت.",
    filesTitle: "أرسل الملف كاملًا",
    filesText: "فيديو الحفلة، مشروع العمل، مجلد الصور: يذهب كله دفعة واحدة، بلا تقسيم ولا ضغط ولا رابط تخزين سحابي في المنتصف.",
    videoTitle: "ابثّ بدقة 1080p",
    videoText: "تصل شاشتك واضحة إلى من على الطرف الآخر، بضعف عدد الإطارات في الثانية. يمكن قراءة الشيفرة واللعب معًا دون أي تشويش.",
    messageTitle: "اكتب بلا قيود",
    messageText: "ضعف عدد الأحرف في كل رسالة، حين تكون الحكاية طويلة وتقسيمها إلى ثلاثة أجزاء يفسد متعتها.",
    colorsTitle: "تطبيق على ذوقك",
    colorsText: "اختر ألوان التطبيق واحدًا واحدًا، واحفظ السمة، وخذها إلى كل جهاز تدخل منه.",
    profileTitle: "ملف تعريف لكل مكان",
    profileText: "اسم آخر، وصورة أخرى، ووصف آخر في كل مجتمع — وصورة متحركة إن أردت.",
    freeDetail: "مجانية وستبقى كذلك.",
    currentPlan: "خطتك الحالية",
    popular: "الأكثر اختيارًا",
    yearlyDetail: "تعادل {{amount}} شهريًا، تُدفع مرة واحدة في السنة.",
    monthlyDetail: "تُدفع كل شهر، وتلغيها متى شئت.",
    groupStyle: "أظهر أسلوبك",
    groupLook: "اجعل التطبيق على هواك",
    groupLimits: "بلا حدود ضيقة",
    closingTitle: "ما الذي تنتظره؟",
    pagePlans: "الخطط",
    pageCompare: "المقارنة",
    giftClaimTitle: "تفعيل {{plan}}؟",
    giftClaimDetail: "ستُضاف {{days}} يومًا إلى حسابك الآن.",
    giftFrom: "من {{name}}",
    giftActivate: "تفعيل",
    giftHasPlanTitle: "لديك Infinity بالفعل",
    giftHasPlanDetail: "خطتك سارية حتى {{date}}. احتفظ بالرابط وأرسله إلى صديق.",
    giftUsedTitle: "استُخدمت هذه الهدية من قبل",
    giftUsedDetail: "استخدم أحدهم هذا الرمز سابقًا. اطلب رمزًا آخر.",
    giftNotFoundTitle: "لم يُعثر على الرمز",
    giftNotFoundDetail: "تحقق من الرمز أو اطلب الرابط مرة أخرى.",
    giftDoneTitle: "تم تفعيل {{plan}}!",
    giftOpenApp: "افتح التطبيق",
    giftSignIn: "سجّل الدخول للاستخدام",
    giftReviewStep: "الدفع · المراجعة",
    giftTotalToday: "إجمالي اليوم",
    giftCardWhy: "البطاقة فقط للتأكّد أنّك أنت. لا يُخصم شيء الآن ولا يتجدّد شيء من تلقاء نفسه.",
    giftAgree: "قرأت شروط الاستخدام وأوافق عليها",
    giftActivating: "جارٍ التفعيل…",
  },
  telas: {
    subscription: "Infinity",
    conta: "حسابي",
    privacidade: "الخصوصية",
    conexoes: "الاتصالات",
    voz: "الصوت",
    video: "الفيديو",
    avisos: "الإشعارات",
    aplicativos: "التطبيقات",
    aparencia: "المظهر",
    batePapo: "الدردشة",
    acessibilidade: "إمكانية الوصول",
    idioma: "اللغة",
    aplicativo: "تنزيل التطبيق",
    atalhos: "الاختصارات",
    desktop: "تطبيق سطح المكتب",
    avancado: "متقدم",
    servidor: "الخادم",
    comunicado: "بيان النظام",
    denuncias: "البلاغات",
    publicacoes: "عمليات النشر",
  },
  grupos: {
    conta: "الحساب",
    app: "إعدادات التطبيق",
    desenvolvedor: "المطوّر",
    administracao: "الإدارة",
  },
  secoes: {
    coresDoApp: "ألوان التطبيق",
    detalhesDeLogin: "بيانات تسجيل الدخول",
    dispositivos: "الأجهزة",
    usuariosBloqueados: "المستخدمون المحظورون",
    aplicativosAutorizados: "التطبيقات المصرّح لها",
    sessoes: "الجلسات",
    amigosEDms: "الأصدقاء والرسائل المباشرة",
    compartilhamentoDeAtividade: "مشاركة النشاط",
    visibilidadeDoPerfil: "ظهور الملف الشخصي",
    exportarDados: "تصدير البيانات",
    exclusaoDeDados: "حذف البيانات",
    tema: "السمة",
    corDeDestaque: "لون التمييز",
    interface: "الواجهة",
    listaDeCanais: "قائمة القنوات",
    zoomDoApp: "مستوى تكبير التطبيق",
    escalaDaFonte: "حجم خط الدردشة",
    modoStreamer: "خصوصية البث",
    cursores: "المؤشرات",
    movimento: "الحركة",
    textoEmVoz: "تحويل النص إلى كلام",
    teclado: "لوحة المفاتيح",
    formatoDaHora: "تنسيق الوقت",
    idiomaDaInterface: "لغة الواجهة",
    dispositivosDeVoz: "الأجهزة",
    testeDoMicrofone: "اختبار الميكروفون",
    modoDeEntrada: "وضع الإدخال",
    sensibilidade: "حساسية الإدخال",
    qualidade: "الجودة",
    camera: "الكاميرا",
    transmissao: "البث",
    exibicao: "العرض",
    entrada: "الإدخال",
    midia: "الوسائط",
    geral: "عام",
    preferenciaDeMencao: "تفضيل الإشارات",
    sons: "الأصوات",
  },
};
