export const amizades = {
  mensagensDiretas: "Messages privés",
  nova: {
    titulo: "Nouvelle conversation",
    detalhe: "Choisissez un ami et la conversation s'ouvre.",
    procurar: "Chercher un ami",
    semAmigos: "Vous n'avez pas encore d'amis ici.",
    semResultado: "Aucun ami de ce nom.",
  },
  adicionar: {
    recado: "Écrivez un petit mot (facultatif)",
    recadoDica: "Ce que vous écrivez ici apparaît aussi dans votre conversation, si vous devenez amis.",
    enviadoPara: "C'est fait. La demande d'ami est partie chez {{nome}}.",
    outrosLugares: "D'autres endroits pour se faire des amis",
    outrosLugaresDetalhe: "Personne ne vous vient à l'esprit ? Jetez un œil aux communautés ouvertes, on y parle de presque tout.",
    explorarComunidades: "Explorer les communautés",
    titulo: "Ajouter un ami",
    detalhe: "Vous pouvez ajouter des amis par leur nom d'utilisateur.",
    exemplo: "Nom d'utilisateur, ex. : thiago",
    enviando: "Envoi…",
    enviar: "Envoyer la demande",
  },
  gatinhoChorando: "Un chaton qui pleure",
  status: {
    emChamada: "En appel",
    emVoz: "En vocal",
  },
  menu: {
    chamada: "Démarrer un appel",
    fixar: "Épingler en haut",
    desafixar: "Désépingler",
    silenciar: "Rendre la conversation muette",
    reativar: "Réactiver les notifications",
    copiarIdDoCanal: "Copier l'ID du salon",
  },
  ativosAgora: "Actifs maintenant",
  procurando: "On regarde qui est là…",
  tudoTranquilo: "Tout est calme pour l'instant…",
  tudoTranquiloDetalhe: "Quand vous ou un ami rejoindrez un appel, il apparaîtra ici — et vous pourrez vous joindre en un clic.",
  emVoz: "En vocal",
  voce: "Vous",
  soVoce: "Vous seul",
  pessoas: "{{quantas}} personnes",
  voltarParaChamada: "Revenir à l'appel",
  entrarNaChamada: "Rejoindre l'appel",
  abrirCanal: "Ouvrir {{canal}} dans {{servidor}}",
  encontreConversa: "Trouver une conversation",
  amigos: "Amis",
  conversas: "Conversations",
  semConversas: "Aucune conversation pour l'instant. Ajoutez un ami pour commencer.",
  semConversaComEsseNome: "Aucune conversation à ce nom.",
  abrirMenu: "Ouvrir les serveurs et les conversations",
  solicitacoes: "Demandes de message",
  pedidos: "Demandes",
  spam: "Spam",
  pedidosPendentes: "Demandes en attente",
  marcadosComoSpam: "Marquées comme spam",
  aceitar: "Accepter",
  ignorar: "Ignorer",
  marcarSpam: "Marquer comme spam",
  semPedidos: "Aucune demande en attente.",
  semPedidosDetalhe: "Les personnes qui ne sont pas vos amies mais partagent un serveur avec vous arrivent ici avant vos conversations.",
  semSpam: "Rien de marqué comme spam.",
  semSpamDetalhe: "Ce que le filtre anti-spam écarte, ou ce que vous marquez, reste dans cet onglet.",
  umServidorEmComum: "1 serveur en commun",
  servidoresEmComum: "{{quantos}} serveurs en commun",
  semServidoresEmComum: "Aucun serveur en commun",
};
