export const comum = {
  voltar: "Retour",
  agoraNao: "Pas maintenant",
  erro: {
    tentarDeNovo: "Réessayer",
    recarregar: "Recharger",
    copiarDetalhes: "Copier les détails",
    parteQuebrou: "Cette partie de l'écran a cassé.",
    titulo: "Ravox Chat a trébuché.",
    detalhe: "Quelque chose a cassé en chemin et l'écran n'a pas pu se dessiner. Votre conversation n'est pas perdue — tout est sur le serveur.",
  },
  perdido: {
    titulo: "Cette adresse ne mène nulle part.",
    detalhe: "Soit le lien est erroné, soit la page a changé de place.",
  },
  conexao: {
    voltou: "De nouveau connecté",
    reconectando: "Reconnexion",
    tentativaSufixo: " · tentative {{numero}}",
    aSalvo: "La conversation est à l'abri sur le serveur. Tout revient tout seul dès que la connexion revient.",
  },
  avisoDoNavegador: {
    titulo: "Vous voulez être prévenu des messages ?",
    detalhe: "Quand Ravox Chat est derrière une autre fenêtre, il vous appelle.",
  },
  atualizacao: {
    titulo: "Mise à jour",
    semAuto: "Cette version de l'application ne sait pas se mettre à jour toute seule. Téléchargez le programme d'installation le plus récent ci-dessous et installez-le par-dessus.",
    versaoAtual: "Vous êtes en version {{versao}}.",
    instalando: "Installation de la version {{versao}}…",
    prontaVersao: "La version {{versao}} est prête à être installée",
    baixandoVersao: "Téléchargement de la version {{versao}}…",
    baixandoComProgresso: "Téléchargement de la version {{versao}}… {{porcento}} %",
    saiuVersao: "La version {{versao}} est sortie",
    saiuVersaoClique: "La version {{versao}} est sortie — cliquez pour la télécharger",
    instalarVersaoEReiniciar: "Installer la version {{versao}} et redémarrer",
    erroTenteDeNovo: "{{erro}} Cliquez pour réessayer.",
    procurando: "Recherche…",
    emDia: "Vous êtes à jour",
    vaiFechar: "L'application va se fermer dans un instant.",
    comoInstala: "L'application se ferme, change de version et se rouvre toute seule. Vous quitterez l'appel en cours, le cas échéant.",
    semServidor: "Je n'ai pas pu joindre le serveur de versions.",
    procuraSozinho: "L'application cherche d'elle-même au démarrage et toutes les six heures.",
    instalandoReticencias: "Installation…",
    instalandoCurto: "Installation",
    baixandoCurto: "Téléchargement",
    tentarDeNovo: "Réessayer",
    reiniciarAgora: "Redémarrer maintenant",
    instalarEReiniciar: "Installer et redémarrer",
    baixar: "Télécharger",
    procurar: "Vérifier",
    baixarApp: "Télécharger l'application",
    ariaBotao: "Mise à jour de l'application",
  },
  janela: {
    ajustarAltura: "Ajuster la hauteur",
    redimensionar: "Redimensionner la fenêtre",
    ajustarLargura: "Ajuster la largeur",
  },
  dica: {
    rotulo: "Astuce :",
    pularConfirmacao: "maintenez Maj en cliquant pour sauter cette confirmation.",
  },
  cor: {
    pescar: "Prélever une couleur à l'écran",
    hex: "Valeur hexadécimale",
  },
  imagem: {
    titulo: "Choisissez une image",
    enviar: "Envoyer une image",
    escolherGif: "Choisir un GIF",
    buscarGif: "Rechercher un GIF",
  },
  fonte: {
    rotulo: "Police du message",
    padrao: "Par défaut",
    comNome: "Police du message — {{fonte}}",
  },
  recorte: {
    titulo: "Recadrer l'icône",
    detalhe: "Faites glisser pour choisir la partie voulue et utilisez le curseur pour zoomer. L'icône est ronde partout dans l'application.",
    voltarAoComeco: "Revenir au début",
    usar: "Utiliser ce recadrage",
  },
  mais: "Plus",
  carregando: "Chargement…",
  salvar: "Enregistrer",
  salvando: "Enregistrement…",
  descartar: "Annuler",
  redefinir: "Réinitialiser",
  naoSalvo: "Vous avez des modifications non enregistrées.",
  fechar: "Fermer",
  criar: "Créer",
  nome: "Nom",
  emoji: "Émoji",
  previa: "Aperçu",
  cancelar: "Annuler",
  enviar: "Envoyer",
  apagar: "Supprimer",
  excluir: "Supprimer",
  remover: "Retirer",
  trocar: "Changer",
  loginNoApp: {
    titulo: "C'est tout bon !",
    detalhe: "Tu es connecté. Retourne sur Ravox Chat, l'application t'attend déjà.",
    abrir: "Ouvrir Ravox Chat",
    fecharAba: "Tu peux fermer cet onglet.",
    falhouTitulo: "La connexion a échoué",
    falhouDetalhe: "Retourne dans l'application et réessaie.",
    legenda: "Un robot qui salue",
    legendaFalhou: "Un chaton qui pleure",
  },
  ads: {
    label: "Publicité",
    title: "Annoncez ici",
    detail: "Parlez-nous et apparaissez auprès de ceux qui utilisent Ravox Chat.",
    action: "Je veux annoncer",
  },
};
