export const configuracoes = {
  efeitos: {
    titulo: "Effets du pointeur",
    detalhe: "Une traînée et des étincelles dessinées par-dessus l'application. Elles arrivent éteintes et se coupent seules si vous avez demandé moins d'animation.",
    rastro: "Traînée du curseur",
    rastroDetalhe: "Un trait qui suit le pointeur et s'efface derrière.",
    faisca: "Étincelle au clic",
    faiscaDetalhe: "De petits traits qui partent de l'endroit cliqué.",
    cor: "Couleur",
    espessura: "Épaisseur",
    comprimento: "Longueur",
    tamanho: "Taille",
    quantidade: "Nombre",
  },
  email: {
    verificarTitulo: "Confirmez votre e-mail",
    verificarDetalhe: "Certaines communautés ne laissent écrire que ceux qui ont confirmé. Un clic suffit.",
    enviar: "Envoyer le lien",
    enviado: "Regardez la boîte de réception. Le lien tient une journée.",
    falhou: "L'e-mail n'a pas pu être envoyé.",
    confirmado: "E-mail confirmé",
    confirmadoDetalhe: "C'est fait. Vous écrivez désormais dans toute communauté qui l'exige.",
    linkIncompleto: "Lien incomplet",
    linkIncompletoDetalhe: "Il manque le code dans l'adresse. Ouvrez le lien directement depuis l'e-mail.",
    confirmando: "Confirmation…",
    expirou: "Ce lien a déjà servi ou a dépassé sa validité.",
    irParaOApp: "Aller à l'application",
  },
  tema: {
    indisponivel: "Thème indisponible",
    indisponivelDetalhe: "La personne qui l'a publié l'a supprimé, ou le lien est faux.",
    indisponivelLinha: "Thème indisponible. La personne qui l'a publié l'a supprimé, ou le lien est faux.",
    importar: "Importer le thème",
    importarCurto: "Importer",
    importarDetalhe: "Cela remplace le thème que vous avez actuellement. Vous pourrez le modifier ensuite dans Réglages > Apparence > Studio de thèmes.",
    porAutor: "par {{autor}}",
    umaCorTrocada: "1 couleur remplacée",
    coresTrocadas: "{{quantas}} couleurs remplacées",
    avisoDeCss: "Ce thème apporte le CSS de son auteur, et le CSS touche à tous les recoins de l'écran. N'importez que depuis des gens en qui vous avez confiance.",
    soCores: "Ce thème ne change que les couleurs. Aucun CSS venu d'ailleurs.",
    verCss: "Voir le CSS",
    esconderCss: "Masquer le CSS",
    aplicar: "Appliquer",
    previaSemMotor: "L'aperçu ne lance pas le moteur. Installez-le pour le voir.",
    motorAnimado: "{{motor}} animé",
  },
  sair: "Se déconnecter",
  versoes: {
    termos: "Conditions d'utilisation",
    privacidade: "Politique de confidentialité",
    copiar: "Cliquez pour copier",
    copiado: "Copié",
  },
  appColors: {
    title: "Couleurs de l'app",
    detail: "Choisissez jusqu'à trois couleurs et toute l'app prend ce dégradé.",
    locked: "L'éditeur de couleurs fait partie de {{plan}}.",
    color: "Couleur {{number}}",
    addColor: "Ajouter une couleur",
    removeColor: "Retirer la couleur",
    surprise: "Surprenez-moi",
    direction: "Direction du dégradé",
    intensity: "Intensité",
    reset: "Réinitialiser",
  },
  subscription: {
    colorsRow: "Éditeur de couleurs de l'app",
    seePlans: "Voir les offres",
    upgradeSubtitle: "Des limites plus hautes et des fonctions exclusives pour écrire, envoyer des fichiers et diffuser.",
    perMonth: "par mois",
    perYear: "par an",
    save: "Économisez {{percent}} %",
    howToPay: "Comment voulez-vous payer ?",
    legal: "Vous pouvez demander un remboursement jusqu'à 7 jours après le paiement. Le paiement est traité par Stripe ; nous ne voyons jamais le numéro de votre carte.",
    compare: "Gratuit ou Infinity",
    featureColumn: "Fonction",
    freeColumn: "Gratuit",
    messageRow: "Limite de caractères par message",
    attachmentRow: "Taille des fichiers envoyés",
    screenRow: "Qualité vidéo",
    megabytesValue: "{{value}} Mo",
    screenValue: "{{resolution}} · {{fps}} i/s",
    alreadyPremium: "Vous avez déjà Infinity jusqu'au {{date}}.",
    upsell: "Augmenter la limite avec Infinity",
    screenUpsell: "Plus de qualité avec Infinity",
    free: "Vous êtes sur l'offre gratuite.",
    activeUntil: "Infinity actif jusqu'au {{date}}.",
    renews: "Renouvellement automatique le {{date}}.",
    endsAt: "L'abonnement a été annulé et se termine le {{date}}.",
    pastDue: "Le dernier prélèvement a échoué. Mettez à jour votre carte pour garder le Infinity.",
    waiting: "Confirmation du paiement…",
    subscribe: "S'abonner",
    monthly: "Mensuel",
    yearly: "Annuel",
    automatic: "Carte",
    manage: "Gérer le paiement",
    refund: "Demander un remboursement",
    refundDetail: "Vous pouvez vous rétracter jusqu'à 7 jours après le paiement : {{amount}}, jusqu'au {{date}}.",
    refundConfirm: "Demander le remboursement ?",
    refundConfirmDetail: "L'argent revient sur le même moyen de paiement et le Infinity s'arrête immédiatement.",
    refunded: "Remboursement demandé.",
    unavailable: "L'abonnement n'est pas encore disponible.",
    success: "Paiement reçu. Merci !",
    canceled: "Paiement annulé.",
    error: "Un problème est survenu. Réessayez.",
    no: "Non",
    tagRow: "Tag d'utilisateur personnalisé",
    guildProfilesRow: "Profils par communauté",
    badgeRow: "Badge de profil",
    communitiesRow: "Communautés",
    savedRow: "Messages enregistrés",
    animatedEmojiRow: "Utiliser des emojis animés",
    expressionsRow: "Accès global aux emojis et autocollants",
    animatedProfileRow: "Avatars et bannières de profil animés",
    earlyAccessRow: "Accès anticipé aux nouveautés",
    themesRow: "Thèmes personnalisés",
    pixOption: "Pix",
    pixHint: "Ouvrez l'app de votre banque, choisissez Pix et scannez le QR code ou copiez-collez le code.",
    pixQrAlt: "QR code Pix",
    pixCopy: "Copier le code Pix",
    pixCopied: "Code Pix copié",
    pixWaiting: "En attente du paiement",
    pixExpiresIn: "expire dans {{time}}",
    pixExpired: "Ce Pix a expiré. Générez-en un autre pour continuer.",
    pixNew: "Générer un autre Pix",
    pixPaid: "Pix reçu ! Votre Infinity est actif.",
    forMe: "Pour moi",
    asGift: "En cadeau",
    buyGift: "Offrir",
    giftReady: "Cadeau prêt ! Copiez le lien et envoyez-le à qui vous voulez.",
    giftClaimed: "Cadeau utilisé ! Infinity est sur votre compte.",
    gifts: "Cadeaux",
    giftsEmpty: "Vous n'avez encore acheté aucun cadeau.",
    giftCode: "Code du cadeau",
    giftRedeem: "Utiliser",
    giftCopyLink: "Copier le lien",
    giftLinkCopied: "Lien copié",
    giftClaimedBy: "utilisé par {{name}}",
    giftHint: "Vous avez un code cadeau ? Utilisez-le ici. Les cadeaux achetés apparaissent ci-dessous.",
    cardPaid: "Paiement approuvé ! Votre Infinity est actif.",
    payAmount: "Payer {{amount}}",
    giftLinkTitle: "Vous avez reçu un cadeau {{plan}} !",
    giftLinkDetail: "Touchez utiliser et les jours arrivent sur votre compte.",
    pageTitle: "Débloquez un monde d'avantages avec {{plan}}",
    pageStart: "Accueil",
    pageBest: "Le meilleur d'Infinity",
    pageChoose: "Choisissez votre offre",
    fromPrice: "À partir de {{amount}} par mois. Annulez quand vous voulez.",
    filesTitle: "Envoyez le fichier entier",
    filesText: "La vidéo de la fête, le projet du travail, le dossier de photos : tout part d'un coup, sans découper, sans compresser et sans lien cloud au milieu.",
    videoTitle: "Diffusez en 1080p",
    videoText: "Votre écran arrive net en face, avec deux fois plus d'images par seconde. On peut lire du code et jouer ensemble sans que tout devienne flou.",
    messageTitle: "Écrivez à volonté",
    messageText: "Deux fois plus de caractères par message, pour quand l'histoire est longue et que la couper en trois gâcherait tout.",
    colorsTitle: "L'app à votre image",
    colorsText: "Choisissez les couleurs de l'application une par une, enregistrez le thème et emportez-le sur tous les appareils où vous vous connectez.",
    profileTitle: "Un profil pour chaque endroit",
    profileText: "Un autre pseudo, une autre photo, une autre description dans chaque communauté — et une photo animée, si vous voulez.",
    freeDetail: "C'est gratuit et ça le reste.",
    currentPlan: "Votre offre actuelle",
    popular: "Le plus choisi",
    yearlyDetail: "Cela revient à {{amount}} par mois, facturé une fois par an.",
    monthlyDetail: "Facturé chaque mois, annulez quand vous voulez.",
    groupStyle: "Montrez votre style",
    groupLook: "L'app comme vous l'aimez",
    groupLimits: "Sans limites serrées",
    closingTitle: "Qu'est-ce que vous attendez ?",
    pagePlans: "Offres",
    pageCompare: "Comparer",
    giftClaimTitle: "Activer {{plan}} ?",
    giftClaimDetail: "Ce sont {{days}} jours ajoutés à votre compte maintenant.",
    giftFrom: "de {{name}}",
    giftActivate: "Activer",
    giftHasPlanTitle: "Vous avez déjà Infinity",
    giftHasPlanDetail: "Votre offre va jusqu'au {{date}}. Gardez le lien et envoyez-le à un ami.",
    giftUsedTitle: "Ce cadeau a déjà été utilisé",
    giftUsedDetail: "Quelqu'un a utilisé ce code avant. Demandez-en un autre.",
    giftNotFoundTitle: "Code introuvable",
    giftNotFoundDetail: "Vérifiez le code ou redemandez le lien.",
    giftDoneTitle: "{{plan}} activé !",
    giftOpenApp: "Ouvrir l'app",
    giftSignIn: "Se connecter pour utiliser",
    giftReviewStep: "Paiement · Vérifier",
    giftTotalToday: "Total aujourd'hui",
    giftCardWhy: "La carte sert seulement à confirmer que c'est bien vous. Rien n'est débité maintenant et rien ne se renouvelle tout seul.",
    giftAgree: "J'ai lu et j'accepte les conditions d'utilisation",
    giftActivating: "Activation…",
  },
  telas: {
    subscription: "Infinity",
    conta: "Mon compte",
    privacidade: "Confidentialité",
    conexoes: "Connexions",
    voz: "Audio",
    video: "Vidéo",
    avisos: "Notifications",
    aplicativos: "Applications",
    aparencia: "Apparence",
    batePapo: "Discussion",
    acessibilidade: "Accessibilité",
    idioma: "Langue",
    aplicativo: "Télécharger l'app",
    atalhos: "Raccourcis",
    desktop: "Application de bureau",
    avancado: "Avancé",
    servidor: "Serveur",
    comunicado: "Annonce du système",
    denuncias: "Signalements",
    publicacoes: "Déploiements",
  },
  grupos: {
    conta: "Compte",
    app: "Paramètres de l'app",
    desenvolvedor: "Développeur",
    administracao: "Administration",
  },
  secoes: {
    coresDoApp: "Couleurs de l'app",
    detalhesDeLogin: "Identifiants",
    dispositivos: "Appareils",
    usuariosBloqueados: "Utilisateurs bloqués",
    aplicativosAutorizados: "Applications autorisées",
    sessoes: "Sessions",
    amigosEDms: "Amis et messages privés",
    compartilhamentoDeAtividade: "Partage d'activité",
    visibilidadeDoPerfil: "Visibilité du profil",
    exportarDados: "Exporter les données",
    exclusaoDeDados: "Supprimer les données",
    tema: "Thème",
    corDeDestaque: "Couleur d'accentuation",
    interface: "Interface",
    listaDeCanais: "Liste des salons",
    zoomDoApp: "Niveau de zoom de l'app",
    escalaDaFonte: "Taille du texte du chat",
    modoStreamer: "Confidentialité en direct",
    cursores: "Curseurs",
    movimento: "Mouvement",
    textoEmVoz: "Synthèse vocale",
    teclado: "Clavier",
    formatoDaHora: "Format de l'heure",
    idiomaDaInterface: "Langue de l'interface",
    dispositivosDeVoz: "Périphériques",
    testeDoMicrofone: "Test du micro",
    modoDeEntrada: "Mode d'entrée",
    sensibilidade: "Sensibilité d'entrée",
    qualidade: "Qualité",
    camera: "Caméra",
    transmissao: "Diffusion",
    exibicao: "Affichage",
    entrada: "Saisie",
    midia: "Médias",
    geral: "Général",
    preferenciaDeMencao: "Préférence de mention",
    sons: "Sons",
  },
};
