export const amizades = {
  mensagensDiretas: "Личные сообщения",
  nova: {
    titulo: "Новый разговор",
    detalhe: "Выберите друга, и разговор откроется.",
    procurar: "Найти друга",
    semAmigos: "Здесь у вас пока нет друзей.",
    semResultado: "Друга с таким именем нет.",
  },
  adicionar: {
    recado: "Напишите пару слов (по желанию)",
    recadoDica: "То, что вы напишете здесь, появится и в вашем разговоре, если подружитесь.",
    enviadoPara: "Готово. Заявка в друзья ушла к {{nome}}.",
    outrosLugares: "Где ещё можно завести друзей",
    outrosLugaresDetalhe: "Никто не приходит в голову? Загляните в открытые сообщества, там говорят почти обо всём.",
    explorarComunidades: "Смотреть сообщества",
    titulo: "Добавить друга",
    detalhe: "Друзей можно добавлять по имени пользователя.",
    exemplo: "Имя пользователя, например: thiago",
    enviando: "Отправляю…",
    enviar: "Отправить запрос",
  },
  gatinhoChorando: "Плачущий котёнок",
  status: {
    emChamada: "В звонке",
    emVoz: "В голосовом",
  },
  menu: {
    chamada: "Начать звонок",
    fixar: "Закрепить вверху",
    desafixar: "Открепить",
    silenciar: "Отключить уведомления беседы",
    reativar: "Включить уведомления беседы",
    copiarIdDoCanal: "Копировать ID канала",
  },
  ativosAgora: "Сейчас активны",
  procurando: "Смотрим, кто рядом…",
  tudoTranquilo: "Пока тихо…",
  tudoTranquiloDetalhe: "Когда вы или друг зайдёте в звонок, он появится здесь — и вы присоединитесь одним щелчком.",
  emVoz: "В голосовом",
  voce: "Вы",
  soVoce: "Только вы",
  pessoas: "{{quantas}} человек",
  voltarParaChamada: "Вернуться в звонок",
  entrarNaChamada: "Присоединиться",
  abrirCanal: "Открыть {{canal}} на {{servidor}}",
  encontreConversa: "Найти беседу",
  amigos: "Друзья",
  conversas: "Беседы",
  semConversas: "Бесед пока нет. Добавьте друга, чтобы начать.",
  semConversaComEsseNome: "Беседы с таким названием нет.",
  abrirMenu: "Открыть серверы и беседы",
  solicitacoes: "Запросы на переписку",
  pedidos: "Запросы",
  spam: "Спам",
  pedidosPendentes: "Ожидающие запросы",
  marcadosComoSpam: "Помечены как спам",
  aceitar: "Принять",
  ignorar: "Игнорировать",
  marcarSpam: "Пометить как спам",
  semPedidos: "Нет ожидающих запросов.",
  semPedidosDetalhe: "Тот, кто вам не друг, но состоит с вами на одном сервере, попадает сюда, не доходя до ваших бесед.",
  semSpam: "Ничего не помечено как спам.",
  semSpamDetalhe: "То, что отсеет фильтр спама, или то, что вы пометите сами, останется на этой вкладке.",
  umServidorEmComum: "1 общий сервер",
  servidoresEmComum: "Общих серверов: {{quantos}}",
  semServidoresEmComum: "Общих серверов нет",
};
