export const configuracoes = {
  efeitos: {
    titulo: "Эффекты указателя",
    detalhe: "След и искры поверх приложения. Приходят выключенными и гаснут сами, если вы просили меньше движения.",
    rastro: "След курсора",
    rastroDetalhe: "Линия, что идёт за указателем и тает позади.",
    faisca: "Искры при щелчке",
    faiscaDetalhe: "Короткие чёрточки, что разлетаются от места щелчка.",
    cor: "Цвет",
    espessura: "Толщина",
    comprimento: "Длина",
    tamanho: "Размер",
    quantidade: "Количество",
  },
  email: {
    verificarTitulo: "Подтвердите свою почту",
    verificarDetalhe: "Некоторые сообщества пускают писать только подтверждённых. Это один щелчок.",
    enviar: "Отправить ссылку",
    enviado: "Загляните в почту. Ссылка живёт сутки.",
    falhou: "Письмо отправить не удалось.",
    confirmado: "Почта подтверждена",
    confirmadoDetalhe: "Готово. Теперь вы пишете в любом сообществе, где это требуют.",
    linkIncompleto: "Ссылка неполная",
    linkIncompletoDetalhe: "В адресе не хватает кода. Откройте ссылку прямо из письма.",
    confirmando: "Подтверждаем…",
    expirou: "Эта ссылка уже использована или просрочена.",
    irParaOApp: "В приложение",
  },
  tema: {
    indisponivel: "Тема недоступна",
    indisponivelDetalhe: "Тот, кто её опубликовал, удалил её, или ссылка неверная.",
    indisponivelLinha: "Тема недоступна. Тот, кто её опубликовал, удалил её, или ссылка неверная.",
    importar: "Импортировать тему",
    importarCurto: "Импортировать",
    importarDetalhe: "Это заменит вашу нынешнюю тему. Отредактировать её можно позже: Настройки > Внешний вид > Студия тем.",
    porAutor: "автор: {{autor}}",
    umaCorTrocada: "заменён 1 цвет",
    coresTrocadas: "заменено цветов: {{quantas}}",
    avisoDeCss: "Эта тема несёт CSS своего автора, а CSS достаёт до любого уголка экрана. Импортируйте только у тех, кому доверяете.",
    soCores: "Эта тема меняет только цвета. Никакого стороннего CSS.",
    verCss: "Показать CSS",
    esconderCss: "Скрыть CSS",
    aplicar: "Применить",
    previaSemMotor: "В предпросмотре движок не работает. Установите, чтобы увидеть.",
    motorAnimado: "{{motor}}, с анимацией",
  },
  sair: "Выйти",
  versoes: {
    termos: "Условия использования",
    privacidade: "Политика конфиденциальности",
    copiar: "Нажмите, чтобы копировать",
    copiado: "Скопировано",
  },
  appColors: {
    title: "Цвета приложения",
    detail: "Выберите до трёх цветов, и всё приложение получит этот градиент.",
    locked: "Редактор цветов входит в {{plan}}.",
    color: "Цвет {{number}}",
    addColor: "Добавить цвет",
    removeColor: "Убрать цвет",
    surprise: "Удиви меня",
    direction: "Направление градиента",
    intensity: "Интенсивность",
    reset: "Сбросить",
  },
  subscription: {
    colorsRow: "Редактор цветов приложения",
    seePlans: "Посмотреть планы",
    upgradeSubtitle: "Больше лимитов и эксклюзивные функции для сообщений, файлов и трансляций.",
    perMonth: "в месяц",
    perYear: "в год",
    save: "Экономия {{percent}}%",
    howToPay: "Как вы хотите оплатить?",
    legal: "Вернуть деньги можно в течение 7 дней после оплаты. Платёж обрабатывает Stripe; мы никогда не видим номер вашей карты.",
    compare: "Бесплатно и Infinity",
    featureColumn: "Функция",
    freeColumn: "Бесплатно",
    messageRow: "Лимит символов в сообщении",
    attachmentRow: "Размер отправляемого файла",
    screenRow: "Качество видео",
    megabytesValue: "{{value}} МБ",
    screenValue: "{{resolution}} · {{fps}} кадров/с",
    alreadyPremium: "У вас уже есть Infinity до {{date}}.",
    upsell: "Увеличить лимит с Infinity",
    screenUpsell: "Больше качества с Infinity",
    free: "У вас бесплатный план.",
    activeUntil: "Infinity активен до {{date}}.",
    renews: "Автоматически продлится {{date}}.",
    endsAt: "Подписка отменена и закончится {{date}}.",
    pastDue: "Последнее списание не прошло. Обновите карту, чтобы не потерять Infinity.",
    waiting: "Подтверждаем оплату…",
    subscribe: "Оформить подписку",
    monthly: "Ежемесячно",
    yearly: "Ежегодно",
    automatic: "Карта",
    manage: "Управлять оплатой",
    refund: "Запросить возврат",
    refundDetail: "Отказаться можно в течение 7 дней после оплаты: {{amount}}, до {{date}}.",
    refundConfirm: "Запросить возврат?",
    refundConfirmDetail: "Деньги вернутся тем же способом оплаты, а Infinity закончится сразу.",
    refunded: "Возврат запрошен.",
    unavailable: "Подписка пока недоступна.",
    success: "Оплата получена. Спасибо!",
    canceled: "Оплата отменена.",
    error: "Что-то пошло не так. Попробуйте ещё раз.",
    no: "Нет",
    tagRow: "Свой тег пользователя",
    guildProfilesRow: "Профили для сообществ",
    badgeRow: "Значок профиля",
    communitiesRow: "Сообщества",
    savedRow: "Сохранённые сообщения",
    animatedEmojiRow: "Анимированные эмодзи",
    expressionsRow: "Эмодзи и стикеры отовсюду",
    animatedProfileRow: "Анимированные аватары и баннеры",
    earlyAccessRow: "Ранний доступ к новинкам",
    themesRow: "Свои темы",
    pixOption: "Pix",
    pixHint: "Откройте приложение банка, выберите Pix и отсканируйте QR-код или скопируйте код.",
    pixQrAlt: "QR-код Pix",
    pixCopy: "Скопировать код Pix",
    pixCopied: "Код Pix скопирован",
    pixWaiting: "Ожидаем оплату",
    pixExpiresIn: "истекает через {{time}}",
    pixExpired: "Срок этого Pix истёк. Создайте новый, чтобы продолжить.",
    pixNew: "Создать новый Pix",
    pixPaid: "Pix получен! Infinity уже активен.",
    forMe: "Себе",
    asGift: "В подарок",
    buyGift: "Купить подарок",
    giftReady: "Подарок готов! Скопируйте ссылку и отправьте кому хотите.",
    giftClaimed: "Подарок активирован! Infinity уже на вашем аккаунте.",
    gifts: "Подарки",
    giftsEmpty: "Вы ещё не покупали подарки.",
    giftCode: "Код подарка",
    giftRedeem: "Активировать",
    giftCopyLink: "Скопировать ссылку",
    giftLinkCopied: "Ссылка скопирована",
    giftClaimedBy: "активировал {{name}}",
    giftHint: "Есть код подарка? Активируйте его здесь. Купленные подарки — ниже.",
    cardPaid: "Оплата прошла! Ваш Infinity активен.",
    payAmount: "Оплатить {{amount}}",
    giftLinkTitle: "Вам подарили {{plan}}!",
    giftLinkDetail: "Нажмите активировать, и дни появятся на вашем аккаунте.",
    pageTitle: "Откройте мир преимуществ с {{plan}}",
    pageStart: "Главная",
    pageBest: "Лучшее в Infinity",
    pageChoose: "Выберите свой план",
    fromPrice: "От {{amount}} в месяц. Отмените когда захотите.",
    filesTitle: "Отправляйте файл целиком",
    filesText: "Видео с вечеринки, рабочий проект, папка с фотографиями — всё уходит разом, без нарезки, без архивов и без ссылки на облако посередине.",
    videoTitle: "Транслируйте в 1080p",
    videoText: "Ваш экран приходит чётким к тому, кто смотрит, и с вдвое большим числом кадров в секунду. Можно читать код и играть вместе, а не разглядывать пятна.",
    messageTitle: "Пишите сколько угодно",
    messageText: "Вдвое больше символов в каждом сообщении — для тех случаев, когда история длинная, а разбить её на три части значит всё испортить.",
    colorsTitle: "Приложение с вашим лицом",
    colorsText: "Выбирайте цвета приложения по одному, сохраняйте тему и берите её на все устройства, где вы входите.",
    profileTitle: "Свой профиль для каждого места",
    profileText: "Другой ник, другое фото, другое описание в каждом сообществе — и анимированное фото, если захотите.",
    freeDetail: "Это бесплатно и таким останется.",
    currentPlan: "Ваш текущий план",
    popular: "Выбирают чаще",
    yearlyDetail: "Выходит {{amount}} в месяц, списывается раз в год.",
    monthlyDetail: "Списывается каждый месяц, отмена в любой момент.",
    groupStyle: "Покажите свой стиль",
    groupLook: "Настройте приложение под себя",
    groupLimits: "Без тесных лимитов",
    closingTitle: "Так чего же вы ждёте?",
    pagePlans: "Планы",
    pageCompare: "Сравнить",
    giftClaimTitle: "Активировать {{plan}}?",
    giftClaimDetail: "Это {{days}} дней, которые появятся на аккаунте сейчас.",
    giftFrom: "от {{name}}",
    giftActivate: "Активировать",
    giftHasPlanTitle: "У вас уже есть Infinity",
    giftHasPlanDetail: "Ваш план до {{date}}. Сохраните ссылку и отправьте другу.",
    giftUsedTitle: "Этот подарок уже использован",
    giftUsedDetail: "Кто-то активировал код раньше. Попросите другой.",
    giftNotFoundTitle: "Код не найден",
    giftNotFoundDetail: "Проверьте код или попросите ссылку снова.",
    giftDoneTitle: "{{plan}} активирован!",
    giftOpenApp: "Открыть приложение",
    giftSignIn: "Войдите, чтобы активировать",
    giftReviewStep: "Оплата · Проверка",
    giftTotalToday: "Итого сегодня",
    giftCardWhy: "Карта нужна только чтобы подтвердить, что это вы. Сейчас ничего не списывается и ничего не продлевается само.",
    giftAgree: "Я прочитал и принимаю условия использования",
    giftActivating: "Активируем…",
  },
  telas: {
    subscription: "Infinity",
    conta: "Мой аккаунт",
    privacidade: "Конфиденциальность",
    conexoes: "Подключения",
    voz: "Звук",
    video: "Видео",
    avisos: "Уведомления",
    aplicativos: "Приложения",
    aparencia: "Внешний вид",
    batePapo: "Чат",
    acessibilidade: "Доступность",
    idioma: "Язык",
    aplicativo: "Скачать приложение",
    atalhos: "Горячие клавиши",
    desktop: "Приложение для компьютера",
    avancado: "Дополнительно",
    servidor: "Сервер",
    comunicado: "Системное объявление",
    denuncias: "Жалобы",
    publicacoes: "Развёртывания",
  },
  grupos: {
    conta: "Аккаунт",
    app: "Настройки приложения",
    desenvolvedor: "Разработчик",
    administracao: "Администрирование",
  },
  secoes: {
    coresDoApp: "Цвета приложения",
    detalhesDeLogin: "Данные для входа",
    dispositivos: "Устройства",
    usuariosBloqueados: "Заблокированные пользователи",
    aplicativosAutorizados: "Авторизованные приложения",
    sessoes: "Сеансы",
    amigosEDms: "Друзья и личные сообщения",
    compartilhamentoDeAtividade: "Передача активности",
    visibilidadeDoPerfil: "Видимость профиля",
    exportarDados: "Экспорт данных",
    exclusaoDeDados: "Удаление данных",
    tema: "Тема",
    corDeDestaque: "Цвет акцента",
    interface: "Интерфейс",
    listaDeCanais: "Список каналов",
    zoomDoApp: "Масштаб приложения",
    escalaDaFonte: "Размер шрифта в чате",
    modoStreamer: "Приватность при трансляции",
    cursores: "Курсоры",
    movimento: "Движение",
    textoEmVoz: "Текст в речь",
    teclado: "Клавиатура",
    formatoDaHora: "Формат времени",
    idiomaDaInterface: "Язык интерфейса",
    dispositivosDeVoz: "Устройства",
    testeDoMicrofone: "Проверка микрофона",
    modoDeEntrada: "Режим ввода",
    sensibilidade: "Чувствительность ввода",
    qualidade: "Качество",
    camera: "Камера",
    transmissao: "Трансляция",
    exibicao: "Отображение",
    entrada: "Ввод",
    midia: "Медиа",
    geral: "Общие",
    preferenciaDeMencao: "Настройка упоминаний",
    sons: "Звуки",
  },
};
