export const amizades = {
  mensagensDiretas: "Tiesioginės žinutės",
  nova: {
    titulo: "Naujas pokalbis",
    detalhe: "Pasirinkite draugą ir pokalbis atsivers.",
    procurar: "Ieškoti draugo",
    semAmigos: "Čia dar neturite draugų.",
    semResultado: "Tokiu vardu draugo nėra.",
  },
  adicionar: {
    recado: "Parašykite porą žodžių (nebūtina)",
    recadoDica: "Tai, ką čia parašysite, matysis ir jūsų pokalbyje, jei susidraugausite.",
    enviadoPara: "Padaryta. Draugystės prašymas nukeliavo pas {{nome}}.",
    outrosLugares: "Kitos vietos naujoms pažintims",
    outrosLugaresDetalhe: "Niekas neateina į galvą? Užmeskite akį į atviras bendruomenes, ten kalbama beveik apie viską.",
    explorarComunidades: "Naršyti bendruomenes",
    titulo: "Pridėti draugą",
    detalhe: "Draugus galite pridėti pagal jų naudotojo vardą.",
    exemplo: "Naudotojo vardas, pvz.: thiago",
    enviando: "Siunčiama…",
    enviar: "Siųsti prašymą",
  },
  gatinhoChorando: "Verkiantis kačiukas",
  status: {
    emChamada: "Pokalbyje",
    emVoz: "Balso kanale",
  },
  menu: {
    chamada: "Pradėti skambutį",
    fixar: "Prisegti viršuje",
    desafixar: "Atsegti",
    silenciar: "Nutildyti pokalbį",
    reativar: "Vėl įjungti pranešimus",
    copiarIdDoCanal: "Kopijuoti kanalo ID",
  },
  ativosAgora: "Dabar aktyvūs",
  procurando: "Žiūrime, kas čia…",
  tudoTranquilo: "Kol kas ramu…",
  tudoTranquiloDetalhe: "Kai tu ar draugas prisijungsite prie skambučio, jis pasirodys čia — ir prisijungsi vienu paspaudimu.",
  emVoz: "Balso kanale",
  voce: "Tu",
  soVoce: "Tik tu",
  pessoas: "{{quantas}} žmonių",
  voltarParaChamada: "Grįžti į skambutį",
  entrarNaChamada: "Prisijungti prie skambučio",
  abrirCanal: "Atidaryti {{canal}} serveryje {{servidor}}",
  encontreConversa: "Rasti pokalbį",
  amigos: "Draugai",
  conversas: "Pokalbiai",
  semConversas: "Kol kas pokalbių nėra. Pridėk draugą ir pradėk.",
  semConversaComEsseNome: "Nėra pokalbio tokiu pavadinimu.",
  abrirMenu: "Atidaryti serverius ir pokalbius",
  solicitacoes: "Žinučių prašymai",
  pedidos: "Prašymai",
  spam: "Šlamštas",
  pedidosPendentes: "Laukiantys prašymai",
  marcadosComoSpam: "Pažymėti kaip šlamštas",
  aceitar: "Priimti",
  ignorar: "Nepaisyti",
  marcarSpam: "Pažymėti kaip šlamštą",
  semPedidos: "Laukiančių prašymų nėra.",
  semPedidosDetalhe: "Tas, kuris nėra tavo draugas, bet yra su tavimi tame pačiame serveryje, patenka čia, nepasiekęs tavo pokalbių.",
  semSpam: "Niekas nepažymėta kaip šlamštas.",
  semSpamDetalhe: "Tai, ką atrenka šlamšto filtras, arba tai, ką pažymi pats, lieka šioje kortelėje.",
  umServidorEmComum: "1 bendras serveris",
  servidoresEmComum: "Bendrų serverių: {{quantos}}",
  semServidoresEmComum: "Bendrų serverių nėra",
};
