export const comum = {
  voltar: "Atgal",
  agoraNao: "Ne dabar",
  erro: {
    tentarDeNovo: "Bandyti dar kartą",
    recarregar: "Įkelti iš naujo",
    copiarDetalhes: "Kopijuoti išsamią informaciją",
    parteQuebrou: "Ši ekrano dalis sugedo.",
    titulo: "Ravox Chat suklupo.",
    detalhe: "Kažkas sugedo pakeliui ir ekranas nesugebėjo nusipiešti. Jūsų pokalbis neprarastas — viskas yra serveryje.",
  },
  perdido: {
    titulo: "Šis adresas niekur neveda.",
    detalhe: "Arba nuoroda klaidinga, arba puslapis persikėlė.",
  },
  conexao: {
    voltou: "Vėl prisijungta",
    reconectando: "Jungiamasi iš naujo",
    tentativaSufixo: " · {{numero}} bandymas",
    aSalvo: "Pokalbis saugiai laikomas serveryje. Viskas grįš savaime, kai tik atsiras ryšys.",
  },
  avisoDoNavegador: {
    titulo: "Norite pranešimų apie žinutes?",
    detalhe: "Kai Ravox Chat yra už kito lango, jis jus pašauks.",
  },
  atualizacao: {
    titulo: "Atnaujinimas",
    semAuto: "Ši programos versija nemoka atsinaujinti pati. Atsisiųskite naujausią diegimo programą žemiau ir įdiekite ją ant viršaus.",
    versaoAtual: "Naudojate versiją {{versao}}.",
    instalando: "Diegiama versija {{versao}}…",
    prontaVersao: "Versija {{versao}} paruošta diegti",
    baixandoVersao: "Atsiunčiama versija {{versao}}…",
    baixandoComProgresso: "Atsiunčiama versija {{versao}}… {{porcento}} %",
    saiuVersao: "Išleista versija {{versao}}",
    saiuVersaoClique: "Išleista versija {{versao}} — spustelėkite, kad atsisiųstumėte",
    instalarVersaoEReiniciar: "Įdiegti versiją {{versao}} ir paleisti iš naujo",
    erroTenteDeNovo: "{{erro}} Spustelėkite, kad bandytumėte dar kartą.",
    procurando: "Ieškoma…",
    emDia: "Viskas naujausia",
    vaiFechar: "Programa netrukus užsidarys.",
    comoInstala: "Programa užsidaro, pakeičia versiją ir pati atsidaro iš naujo. Jei kalbate, pokalbį paliksite.",
    semServidor: "Nepavyko susisiekti su versijų serveriu.",
    procuraSozinho: "Programa pati tikrina paleidus ir kas šešias valandas.",
    instalandoReticencias: "Diegiama…",
    instalandoCurto: "Diegiama",
    baixandoCurto: "Atsiunčiama",
    tentarDeNovo: "Bandyti dar kartą",
    reiniciarAgora: "Paleisti iš naujo dabar",
    instalarEReiniciar: "Įdiegti ir paleisti iš naujo",
    baixar: "Atsisiųsti",
    procurar: "Tikrinti",
    baixarApp: "Atsisiųsti programą",
    ariaBotao: "Programos atnaujinimas",
  },
  janela: {
    ajustarAltura: "Reguliuoti aukštį",
    redimensionar: "Keisti lango dydį",
    ajustarLargura: "Reguliuoti plotį",
  },
  dica: {
    rotulo: "Patarimas:",
    pularConfirmacao: "spausdami laikykite Shift, kad praleistumėte šį patvirtinimą.",
  },
  cor: {
    pescar: "Paimti spalvą iš ekrano",
    hex: "Šešioliktainė reikšmė",
  },
  imagem: {
    titulo: "Pasirinkite paveikslėlį",
    enviar: "Siųsti paveikslėlį",
    escolherGif: "Pasirinkti GIF",
    buscarGif: "Ieškoti GIF",
  },
  fonte: {
    rotulo: "Žinutės šriftas",
    padrao: "Numatytasis",
    comNome: "Žinutės šriftas — {{fonte}}",
  },
  recorte: {
    titulo: "Apkirpti piktogramą",
    detalhe: "Vilkite, kad pasirinktumėte sritį, ir slankikliu priartinkite. Piktograma visur programoje yra apvali.",
    voltarAoComeco: "Grįžti į pradžią",
    usar: "Naudoti šį apkirpimą",
  },
  mais: "Daugiau",
  carregando: "Įkeliama…",
  salvar: "Išsaugoti",
  salvando: "Išsaugoma…",
  descartar: "Atmesti",
  redefinir: "Atstatyti",
  naoSalvo: "Turite neišsaugotų pakeitimų.",
  fechar: "Uždaryti",
  criar: "Sukurti",
  nome: "Pavadinimas",
  emoji: "Jaustukas",
  previa: "Peržiūra",
  cancelar: "Atšaukti",
  enviar: "Siųsti",
  apagar: "Ištrinti",
  excluir: "Ištrinti",
  remover: "Pašalinti",
  trocar: "Pakeisti",
  loginNoApp: {
    titulo: "Viskas paruošta!",
    detalhe: "Prisijungėte. Grįžkite į Ravox Chat, programa jau laukia.",
    abrir: "Atidaryti Ravox Chat",
    fecharAba: "Dabar galite uždaryti šį skirtuką.",
    falhouTitulo: "Prisijungti nepavyko",
    falhouDetalhe: "Grįžkite į programą ir bandykite prisijungti dar kartą.",
    legenda: "Mojuojantis robotas",
    legendaFalhou: "Verkiantis kačiukas",
  },
  ads: {
    label: "Reklama",
    title: "Reklamuokitės čia",
    detail: "Susisiekite su mumis ir pasirodykite tiems, kurie naudoja Ravox Chat.",
    action: "Noriu reklamuotis",
  },
};
