export const configuracoes = {
  efeitos: {
    titulo: "Žymeklio efektai",
    detalhe: "Pėdsakas ir kibirkštys, piešiami virš programėlės. Prasideda išjungti ir patys užgęsta, jei paprašėte mažiau judesio.",
    rastro: "Žymeklio pėdsakas",
    rastroDetalhe: "Linija, kuri seka žymeklį ir blėsta už jo.",
    faisca: "Kibirkštis spustelėjus",
    faiscaDetalhe: "Trumpi brūkšniai, išlekiantys iš spustelėjimo vietos.",
    cor: "Spalva",
    espessura: "Storis",
    comprimento: "Ilgis",
    tamanho: "Dydis",
    quantidade: "Kiekis",
  },
  email: {
    verificarTitulo: "Patvirtinkite savo el. paštą",
    verificarDetalhe: "Kai kurios bendruomenės leidžia rašyti tik patvirtinusiems. Užtenka spustelėti.",
    enviar: "Siųsti nuorodą",
    enviado: "Pažiūrėkite į gautuosius. Nuoroda galioja parą.",
    falhou: "Laiško išsiųsti nepavyko.",
    confirmado: "El. paštas patvirtintas",
    confirmadoDetalhe: "Padaryta. Dabar rašote bet kurioje bendruomenėje, kuri to prašo.",
    linkIncompleto: "Nepilna nuoroda",
    linkIncompletoDetalhe: "Adrese trūksta kodo. Atverkite nuorodą tiesiai iš laiško.",
    confirmando: "Tvirtinama…",
    expirou: "Ši nuoroda jau panaudota arba nebegalioja.",
    irParaOApp: "Į programėlę",
  },
  tema: {
    indisponivel: "Tema nepasiekiama",
    indisponivelDetalhe: "Ją paskelbęs žmogus ją ištrynė arba nuoroda klaidinga.",
    indisponivelLinha: "Tema nepasiekiama. Ją paskelbęs žmogus ją ištrynė arba nuoroda klaidinga.",
    importar: "Importuoti temą",
    importarCurto: "Importuoti",
    importarDetalhe: "Tai pakeis dabartinę jūsų temą. Vėliau ją galėsite redaguoti: Nustatymai > Išvaizda > Temų studija.",
    porAutor: "autorius {{autor}}",
    umaCorTrocada: "pakeista 1 spalva",
    coresTrocadas: "pakeistos {{quantas}} spalvos",
    avisoDeCss: "Ši tema atsineša savo autoriaus CSS, o CSS pasiekia kiekvieną ekrano kampą. Importuokite tik iš žmonių, kuriais pasitikite.",
    soCores: "Ši tema keičia tik spalvas. Jokio CSS iš šalies.",
    verCss: "Rodyti CSS",
    esconderCss: "Slėpti CSS",
    aplicar: "Taikyti",
    previaSemMotor: "Peržiūra variklio nepaleidžia. Įdiekite, kad pamatytumėte.",
    motorAnimado: "{{motor}} animuotas",
  },
  sair: "Atsijungti",
  versoes: {
    termos: "Paslaugų sąlygos",
    privacidade: "Privatumo politika",
    copiar: "Spustelėkite, kad nukopijuotumėte",
    copiado: "Nukopijuota",
  },
  appColors: {
    title: "Programos spalvos",
    detail: "Pasirinkite iki trijų spalvų ir visa programa gaus šį perėjimą.",
    locked: "Spalvų redaktorius yra {{plan}} dalis.",
    color: "{{number}} spalva",
    addColor: "Pridėti spalvą",
    removeColor: "Pašalinti spalvą",
    surprise: "Nustebink mane",
    direction: "Perėjimo kryptis",
    intensity: "Intensyvumas",
    reset: "Atstatyti",
  },
  subscription: {
    colorsRow: "Programos spalvų redaktorius",
    seePlans: "Peržiūrėti planus",
    upgradeSubtitle: "Didesni limitai ir išskirtinės funkcijos rašyti, siųsti failus ir transliuoti.",
    perMonth: "per mėnesį",
    perYear: "per metus",
    save: "Sutaupykite {{percent}} %",
    howToPay: "Kaip norite mokėti?",
    legal: "Grąžinimo galite paprašyti per 7 dienas nuo mokėjimo. Mokėjimą apdoroja Stripe; mes niekada nematome jūsų kortelės numerio.",
    compare: "Nemokamas ir Infinity",
    featureColumn: "Funkcija",
    freeColumn: "Nemokamas",
    messageRow: "Žinutės simbolių riba",
    attachmentRow: "Siunčiamo failo dydis",
    screenRow: "Vaizdo kokybė",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} kadrų/s",
    alreadyPremium: "Infinity jau turite iki {{date}}.",
    upsell: "Padidinkite limitą su Infinity",
    screenUpsell: "Geresnė kokybė su Infinity",
    free: "Naudojate nemokamą planą.",
    activeUntil: "Infinity aktyvus iki {{date}}.",
    renews: "Automatiškai atsinaujins {{date}}.",
    endsAt: "Prenumerata atšaukta ir baigsis {{date}}.",
    pastDue: "Paskutinis mokėjimas nepavyko. Atnaujinkite kortelę, kad neprarastumėte Infinity.",
    waiting: "Tvirtinamas mokėjimas…",
    subscribe: "Prenumeruoti",
    monthly: "Kas mėnesį",
    yearly: "Kas metus",
    automatic: "Kortelė",
    manage: "Tvarkyti mokėjimą",
    refund: "Prašyti grąžinimo",
    refundDetail: "Galite atsisakyti per 7 dienas nuo mokėjimo: {{amount}}, iki {{date}}.",
    refundConfirm: "Prašyti grąžinimo?",
    refundConfirmDetail: "Pinigai grįš tuo pačiu mokėjimo būdu, o Infinity baigsis iškart.",
    refunded: "Grąžinimo paprašyta.",
    unavailable: "Prenumerata dar neprieinama.",
    success: "Mokėjimas gautas. Ačiū!",
    canceled: "Mokėjimas atšauktas.",
    error: "Kažkas nepavyko. Bandykite dar kartą.",
    no: "Ne",
    tagRow: "Savo naudotojo žyma",
    guildProfilesRow: "Profiliai kiekvienai bendruomenei",
    badgeRow: "Profilio ženklelis",
    communitiesRow: "Bendruomenės",
    savedRow: "Išsaugotos žinutės",
    animatedEmojiRow: "Animuoti jaustukai",
    expressionsRow: "Jaustukai ir lipdukai iš visur",
    animatedProfileRow: "Animuoti avatarai ir profilio juostos",
    earlyAccessRow: "Ankstyva prieiga prie naujovių",
    themesRow: "Savos temos",
    pixOption: "Pix",
    pixHint: "Atidarykite banko programėlę, pasirinkite Pix ir nuskaitykite QR kodą arba nukopijuokite kodą.",
    pixQrAlt: "Pix QR kodas",
    pixCopy: "Kopijuoti Pix kodą",
    pixCopied: "Pix kodas nukopijuotas",
    pixWaiting: "Laukiama mokėjimo",
    pixExpiresIn: "baigsis po {{time}}",
    pixExpired: "Šis Pix nebegalioja. Sukurkite naują, kad tęstumėte.",
    pixNew: "Sukurti naują Pix",
    pixPaid: "Pix gautas! Infinity jau aktyvus.",
    forMe: "Sau",
    asGift: "Dovanų",
    buyGift: "Pirkti dovaną",
    giftReady: "Dovana paruošta! Nukopijuokite nuorodą ir nusiųskite kam norite.",
    giftClaimed: "Dovana panaudota! Infinity jau jūsų paskyroje.",
    gifts: "Dovanos",
    giftsEmpty: "Dar nepirkote jokių dovanų.",
    giftCode: "Dovanos kodas",
    giftRedeem: "Panaudoti",
    giftCopyLink: "Kopijuoti nuorodą",
    giftLinkCopied: "Nuoroda nukopijuota",
    giftClaimedBy: "panaudojo {{name}}",
    giftHint: "Turite dovanos kodą? Panaudokite jį čia. Pirktos dovanos – žemiau.",
    cardPaid: "Mokėjimas patvirtintas! Jūsų Infinity aktyvus.",
    payAmount: "Mokėti {{amount}}",
    giftLinkTitle: "Gavote {{plan}} dovaną!",
    giftLinkDetail: "Palieskite panaudoti ir dienos atsiras jūsų paskyroje.",
    pageTitle: "Atrakinkite privalumų pasaulį su {{plan}}",
    pageStart: "Pradžia",
    pageBest: "Geriausia, ką turi Infinity",
    pageChoose: "Pasirinkite planą",
    fromPrice: "Nuo {{amount}} per mėnesį. Atšaukite kada norite.",
    filesTitle: "Siųskite visą failą",
    filesText: "Vakarėlio vaizdo įrašas, darbo projektas, aplankas su nuotraukomis – viskas iškeliauja iš karto, nieko nekarpant, nespaudžiant ir be debesijos nuorodos tarpininko.",
    videoTitle: "Transliuokite 1080p raiška",
    videoText: "Jūsų ekranas kitoje pusėje matomas ryškiai, su dvigubai daugiau kadrų per sekundę. Galima skaityti kodą ir kartu žaisti, o vaizdas nevirsta dėme.",
    messageTitle: "Rašykite kiek norite",
    messageText: "Dvigubai daugiau ženklų kiekvienoje žinutėje – kai istorija ilga, o suskaidžius ją į tris dalis dingtų visas žavesys.",
    colorsTitle: "Programėlė pagal jus",
    colorsText: "Rinkitės programėlės spalvas po vieną, išsaugokite temą ir pasiimkite ją į visus įrenginius, kuriuose prisijungiate.",
    profileTitle: "Kiekvienai vietai – savas profilis",
    profileText: "Kitas slapyvardis, kita nuotrauka, kitas aprašymas kiekvienoje bendruomenėje – ir animuota nuotrauka, jei norite.",
    freeDetail: "Nemokama ir taip bus visada.",
    currentPlan: "Jūsų dabartinis planas",
    popular: "Populiariausias",
    yearlyDetail: "Išeina {{amount}} per mėnesį, apmokestinama kartą per metus.",
    monthlyDetail: "Apmokestinama kas mėnesį, atšaukiate kada norite.",
    groupStyle: "Parodykite savo stilių",
    groupLook: "Pritaikykite programėlę sau",
    groupLimits: "Jokių ankštų ribų",
    closingTitle: "Ko dar laukiate?",
    pagePlans: "Planai",
    pageCompare: "Palyginti",
    giftClaimTitle: "Aktyvuoti {{plan}}?",
    giftClaimDetail: "Tai {{days}} dienų, kurios dabar atsiras jūsų paskyroje.",
    giftFrom: "nuo {{name}}",
    giftActivate: "Aktyvuoti",
    giftHasPlanTitle: "Jūs jau turite Infinity",
    giftHasPlanDetail: "Jūsų planas galioja iki {{date}}. Išsaugokite nuorodą ir nusiųskite draugui.",
    giftUsedTitle: "Ši dovana jau panaudota",
    giftUsedDetail: "Kažkas kodą panaudojo anksčiau. Paprašykite kito.",
    giftNotFoundTitle: "Kodas nerastas",
    giftNotFoundDetail: "Patikrinkite kodą arba paprašykite nuorodos dar kartą.",
    giftDoneTitle: "{{plan}} aktyvuotas!",
    giftOpenApp: "Atidaryti programą",
    giftSignIn: "Prisijunkite, kad panaudotumėte",
    giftReviewStep: "Mokėjimas · Peržiūra",
    giftTotalToday: "Iš viso šiandien",
    giftCardWhy: "Kortelė reikalinga tik patvirtinti, kad tai tu. Dabar nieko nenuskaičiuojama ir niekas savaime neatsinaujina.",
    giftAgree: "Perskaičiau ir sutinku su naudojimo sąlygomis",
    giftActivating: "Aktyvuojama…",
  },
  telas: {
    subscription: "Infinity",
    conta: "Mano paskyra",
    privacidade: "Privatumas",
    conexoes: "Ryšiai",
    voz: "Garsas",
    video: "Vaizdas",
    avisos: "Pranešimai",
    aplicativos: "Programos",
    aparencia: "Išvaizda",
    batePapo: "Pokalbis",
    acessibilidade: "Prieinamumas",
    idioma: "Kalba",
    aplicativo: "Atsisiųsti programą",
    atalhos: "Spartieji klavišai",
    desktop: "Kompiuterio programa",
    avancado: "Išplėstiniai",
    servidor: "Serveris",
    comunicado: "Sistemos pranešimas",
    denuncias: "Pranešimai",
    publicacoes: "Diegimai",
  },
  grupos: {
    conta: "Paskyra",
    app: "Programos nustatymai",
    desenvolvedor: "Kūrėjas",
    administracao: "Administravimas",
  },
  secoes: {
    coresDoApp: "Programos spalvos",
    detalhesDeLogin: "Prisijungimo duomenys",
    dispositivos: "Įrenginiai",
    usuariosBloqueados: "Užblokuoti naudotojai",
    aplicativosAutorizados: "Įgaliotos programos",
    sessoes: "Seansai",
    amigosEDms: "Draugai ir asmeninės žinutės",
    compartilhamentoDeAtividade: "Veiklos bendrinimas",
    visibilidadeDoPerfil: "Profilio matomumas",
    exportarDados: "Eksportuoti duomenis",
    exclusaoDeDados: "Ištrinti duomenis",
    tema: "Tema",
    corDeDestaque: "Akcento spalva",
    interface: "Sąsaja",
    listaDeCanais: "Kanalų sąrašas",
    zoomDoApp: "Programos mastelis",
    escalaDaFonte: "Pokalbio šrifto dydis",
    modoStreamer: "Privatumas transliuojant",
    cursores: "Žymekliai",
    movimento: "Judesys",
    textoEmVoz: "Tekstas į kalbą",
    teclado: "Klaviatūra",
    formatoDaHora: "Laiko formatas",
    idiomaDaInterface: "Sąsajos kalba",
    dispositivosDeVoz: "Įrenginiai",
    testeDoMicrofone: "Mikrofono patikra",
    modoDeEntrada: "Įvesties režimas",
    sensibilidade: "Įvesties jautrumas",
    qualidade: "Kokybė",
    camera: "Kamera",
    transmissao: "Transliacija",
    exibicao: "Rodymas",
    entrada: "Įvestis",
    midia: "Medija",
    geral: "Bendra",
    preferenciaDeMencao: "Paminėjimų nuostata",
    sons: "Garsai",
  },
};
