export const amizades = {
  mensagensDiretas: "Közvetlen üzenetek",
  nova: {
    titulo: "Új beszélgetés",
    detalhe: "Válassz egy barátot, és megnyílik a beszélgetés.",
    procurar: "Barát keresése",
    semAmigos: "Itt még nincsenek barátaid.",
    semResultado: "Nincs ilyen nevű barát.",
  },
  adicionar: {
    recado: "Írj pár szót (nem kötelező)",
    recadoDica: "Amit ide írsz, megjelenik a beszélgetésetekben is, ha barátok lesztek.",
    enviadoPara: "Kész! A barátkérés megérkezett hozzá: {{nome}}.",
    outrosLugares: "Más helyek, ahol barátokra lelhetsz",
    outrosLugaresDetalhe: "Nem jut eszedbe senki? Nézd meg a nyitott közösségeket, ott szinte mindenről szó esik.",
    explorarComunidades: "Közösségek felfedezése",
    titulo: "Barát hozzáadása",
    detalhe: "Barátokat a felhasználónevük alapján adhatsz hozzá.",
    exemplo: "Felhasználónév, pl.: thiago",
    enviando: "Küldés…",
    enviar: "Kérés küldése",
  },
  gatinhoChorando: "Egy síró cica",
  status: {
    emChamada: "Hívásban",
    emVoz: "Hangban",
  },
  menu: {
    chamada: "Hívás indítása",
    fixar: "Kitűzés felülre",
    desafixar: "Kitűzés visszavonása",
    silenciar: "Beszélgetés némítása",
    reativar: "Némítás feloldása",
    copiarIdDoCanal: "Csatorna azonosítójának másolása",
  },
  ativosAgora: "Most aktív",
  procurando: "Nézzük, ki van itt…",
  tudoTranquilo: "Egyelőre csend van…",
  tudoTranquiloDetalhe: "Amikor te vagy egy barátod belép egy hívásba, itt jelenik meg — és egy kattintással csatlakozhatsz.",
  emVoz: "Hangcsatornán",
  voce: "Te",
  soVoce: "Csak te",
  pessoas: "{{quantas}} fő",
  voltarParaChamada: "Vissza a híváshoz",
  entrarNaChamada: "Csatlakozás a híváshoz",
  abrirCanal: "{{canal}} megnyitása itt: {{servidor}}",
  encontreConversa: "Beszélgetés keresése",
  amigos: "Barátok",
  conversas: "Beszélgetések",
  semConversas: "Még nincs beszélgetés. Adj hozzá egy barátot a kezdéshez.",
  semConversaComEsseNome: "Nincs ilyen nevű beszélgetés.",
  abrirMenu: "Szerverek és beszélgetések megnyitása",
  solicitacoes: "Üzenetkérelmek",
  pedidos: "Kérelmek",
  spam: "Spam",
  pedidosPendentes: "Függő kérelmek",
  marcadosComoSpam: "Spamként megjelölve",
  aceitar: "Elfogadás",
  ignorar: "Mellőzés",
  marcarSpam: "Megjelölés spamként",
  semPedidos: "Nincs várakozó kérelem.",
  semPedidosDetalhe: "Aki nem a barátod, de közös szerveren van veled, ide kerül, mielőtt elérné a beszélgetéseidet.",
  semSpam: "Semmi sincs spamként megjelölve.",
  semSpamDetalhe: "Amit a spamszűrő félretesz, vagy amit te jelölsz meg, ezen a fülön marad.",
  umServidorEmComum: "1 közös szerver",
  servidoresEmComum: "{{quantos}} közös szerver",
  semServidoresEmComum: "Nincs közös szerver",
};
