export const comum = {
  voltar: "Vissza",
  agoraNao: "Most nem",
  erro: {
    tentarDeNovo: "Újra",
    recarregar: "Újratöltés",
    copiarDetalhes: "Részletek másolása",
    parteQuebrou: "A képernyőnek ez a része eltört.",
    titulo: "A Ravox Chat megbotlott.",
    detalhe: "Valami eltört útközben, és a képernyő nem tudta kirajzolni magát. A beszélgetésed nem veszett el — minden a kiszolgálón van.",
  },
  perdido: {
    titulo: "Ez a cím nem vezet sehová.",
    detalhe: "Vagy rossz a hivatkozás, vagy az oldal elköltözött.",
  },
  conexao: {
    voltou: "Újra kapcsolódva",
    reconectando: "Újrakapcsolódás",
    tentativaSufixo: " · {{numero}}. próbálkozás",
    aSalvo: "A beszélgetés biztonságban van a kiszolgálón. Amint visszatér a kapcsolat, magától helyreáll.",
  },
  avisoDoNavegador: {
    titulo: "Kérsz értesítést az üzenetekről?",
    detalhe: "Ha a Ravox Chat másik ablak mögött van, akkor szól neked.",
  },
  atualizacao: {
    titulo: "Frissítés",
    semAuto: "Az alkalmazásnak ez a változata nem tudja magát frissíteni. Töltsd le lentről a legújabb telepítőt, és telepítsd fölé.",
    versaoAtual: "A(z) {{versao}} változatot használod.",
    instalando: "A(z) {{versao}} változat telepítése…",
    prontaVersao: "A(z) {{versao}} változat telepítésre kész",
    baixandoVersao: "A(z) {{versao}} változat letöltése…",
    baixandoComProgresso: "A(z) {{versao}} változat letöltése… {{porcento}}%",
    saiuVersao: "Megjelent a(z) {{versao}} változat",
    saiuVersaoClique: "Megjelent a(z) {{versao}} változat — kattints a letöltéshez",
    instalarVersaoEReiniciar: "A(z) {{versao}} változat telepítése és újraindítás",
    erroTenteDeNovo: "{{erro}} Kattints az újrapróbálkozáshoz.",
    procurando: "Keresés…",
    emDia: "Naprakész vagy",
    vaiFechar: "Az alkalmazás pillanatokon belül bezárul.",
    comoInstala: "Az alkalmazás bezárul, változatot cserél, majd magától újranyílik. Ha hívásban vagy, kilépsz belőle.",
    semServidor: "Nem értem el a változatok kiszolgálóját.",
    procuraSozinho: "Az alkalmazás induláskor és hatóránként magától keres.",
    instalandoReticencias: "Telepítés…",
    instalandoCurto: "Telepítés",
    baixandoCurto: "Letöltés",
    tentarDeNovo: "Újra",
    reiniciarAgora: "Újraindítás most",
    instalarEReiniciar: "Telepítés és újraindítás",
    baixar: "Letöltés",
    procurar: "Keresés",
    baixarApp: "Az alkalmazás letöltése",
    ariaBotao: "Az alkalmazás frissítése",
  },
  janela: {
    ajustarAltura: "Magasság beállítása",
    redimensionar: "Ablak átméretezése",
    ajustarLargura: "Szélesség beállítása",
  },
  dica: {
    rotulo: "Tipp:",
    pularConfirmacao: "tartsd nyomva a Shiftet kattintáskor, és kimarad ez a megerősítés.",
  },
  cor: {
    pescar: "Szín leolvasása a képernyőről",
    hex: "Hexadecimális érték",
  },
  imagem: {
    titulo: "Válassz képet",
    enviar: "Kép küldése",
    escolherGif: "GIF választása",
    buscarGif: "GIF keresése",
  },
  fonte: {
    rotulo: "Az üzenet betűtípusa",
    padrao: "Alapértelmezett",
    comNome: "Az üzenet betűtípusa — {{fonte}}",
  },
  recorte: {
    titulo: "Ikon levágása",
    detalhe: "Húzd a kívánt részletre, a csúszkával pedig nagyíts. Az ikon az alkalmazásban mindenhol kerek.",
    voltarAoComeco: "Vissza az elejére",
    usar: "Ezt a kivágást használom",
  },
  mais: "Több",
  carregando: "Betöltés…",
  salvar: "Mentés",
  salvando: "Mentés…",
  descartar: "Elvetés",
  redefinir: "Visszaállítás",
  naoSalvo: "Nem mentett módosításaid vannak.",
  fechar: "Bezárás",
  criar: "Létrehozás",
  nome: "Név",
  emoji: "Emodzsi",
  previa: "Előnézet",
  cancelar: "Mégse",
  enviar: "Küldés",
  apagar: "Törlés",
  excluir: "Törlés",
  remover: "Eltávolítás",
  trocar: "Csere",
  loginNoApp: {
    titulo: "Minden rendben!",
    detalhe: "Bejelentkeztél. Térj vissza a Ravox Chatba, az alkalmazás már vár.",
    abrir: "Ravox Chat megnyitása",
    fecharAba: "Most már bezárhatod ezt a lapot.",
    falhouTitulo: "A bejelentkezés nem sikerült",
    falhouDetalhe: "Térj vissza az alkalmazásba, és próbálj újra bejelentkezni.",
    legenda: "Integető robot",
    legendaFalhou: "Síró kiscica",
  },
  ads: {
    label: "Hirdetés",
    title: "Hirdess itt",
    detail: "Írj nekünk, és jelenj meg azok előtt, akik a Ravox Chatet használják.",
    action: "Hirdetni szeretnék",
  },
};
