export const configuracoes = {
  efeitos: {
    titulo: "Mutató hatásai",
    detalhe: "Csík és szikrák az alkalmazás fölé rajzolva. Kikapcsolva indulnak, és maguktól kimaradnak, ha kevesebb mozgást kértél.",
    rastro: "A mutató csíkja",
    rastroDetalhe: "Vonal, ami követi a mutatót, és mögötte elhalványul.",
    faisca: "Szikra kattintásra",
    faiscaDetalhe: "Rövid vonalak, amik a kattintás helyéről repülnek szét.",
    cor: "Szín",
    espessura: "Vastagság",
    comprimento: "Hossz",
    tamanho: "Méret",
    quantidade: "Mennyiség",
  },
  email: {
    verificarTitulo: "Erősítsd meg az e-mailed",
    verificarDetalhe: "Egyes közösségekben csak a megerősítettek írhatnak. Egy kattintás.",
    enviar: "Link küldése",
    enviado: "Nézd meg a postafiókot. A link egy napig él.",
    falhou: "Az e-mailt nem sikerült elküldeni.",
    confirmado: "E-mail megerősítve",
    confirmadoDetalhe: "Kész. Mostantól írhatsz bárhol, ahol ezt kérik.",
    linkIncompleto: "Hiányos hivatkozás",
    linkIncompletoDetalhe: "A címből hiányzik a kód. Nyisd meg a linket egyenesen az e-mailből.",
    confirmando: "Megerősítés…",
    expirou: "Ezt a hivatkozást már felhasználták, vagy lejárt.",
    irParaOApp: "Irány az alkalmazás",
  },
  tema: {
    indisponivel: "A téma nem érhető el",
    indisponivelDetalhe: "Aki közzétette, törölte, vagy hibás a hivatkozás.",
    indisponivelLinha: "A téma nem érhető el. Aki közzétette, törölte, vagy hibás a hivatkozás.",
    importar: "Téma importálása",
    importarCurto: "Importálás",
    importarDetalhe: "Ez lecseréli a mostani témádat. Utána a Beállítások > Megjelenés > Témastúdió alatt szerkesztheted.",
    porAutor: "készítette: {{autor}}",
    umaCorTrocada: "1 kicserélt szín",
    coresTrocadas: "{{quantas}} kicserélt szín",
    avisoDeCss: "Ez a téma a szerzője CSS-ét hozza magával, és a CSS a képernyő minden sarkába belenyúl. Csak olyantól importálj, akiben megbízol.",
    soCores: "Ez a téma csak színeket cserél. Semmi külső CSS.",
    verCss: "CSS megtekintése",
    esconderCss: "CSS elrejtése",
    aplicar: "Alkalmaz",
    previaSemMotor: "Az előnézet nem futtatja a motort. Telepítsd, hogy lásd.",
    motorAnimado: "{{motor}} animálva",
  },
  sair: "Kijelentkezés",
  versoes: {
    termos: "Szolgáltatási feltételek",
    privacidade: "Adatvédelmi irányelvek",
    copiar: "Kattints a másoláshoz",
    copiado: "Másolva",
  },
  appColors: {
    title: "Alkalmazás színei",
    detail: "Válassz legfeljebb három színt, és az egész app ezt a színátmenetet kapja.",
    locked: "A színszerkesztő az {{plan}} része.",
    color: "{{number}}. szín",
    addColor: "Szín hozzáadása",
    removeColor: "Szín eltávolítása",
    surprise: "Lepj meg",
    direction: "Színátmenet iránya",
    intensity: "Erősség",
    reset: "Visszaállítás",
  },
  subscription: {
    colorsRow: "Az app színszerkesztője",
    seePlans: "Csomagok megtekintése",
    upgradeSubtitle: "Nagyobb korlátok és exkluzív funkciók íráshoz, fájlküldéshez és közvetítéshez.",
    perMonth: "havonta",
    perYear: "évente",
    save: "{{percent}}% megtakarítás",
    howToPay: "Hogyan szeretnél fizetni?",
    legal: "A fizetéstől számított 7 napon belül kérhetsz visszatérítést. A fizetést a Stripe kezeli; a kártyaszámodat soha nem látjuk.",
    compare: "Ingyenes vs. Infinity",
    featureColumn: "Funkció",
    freeColumn: "Ingyenes",
    messageRow: "Üzenet karakterkorlátja",
    attachmentRow: "Feltölthető fájlméret",
    screenRow: "Videóminőség",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Már van Infinity előfizetésed eddig: {{date}}.",
    upsell: "Nagyobb korlát az Infinityvel",
    screenUpsell: "Jobb minőség az Infinityvel",
    free: "Az ingyenes csomagot használod.",
    activeUntil: "Infinity aktív eddig: {{date}}.",
    renews: "Automatikusan megújul: {{date}}.",
    endsAt: "Az előfizetést lemondtad, és ekkor ér véget: {{date}}.",
    pastDue: "Az utolsó terhelés sikertelen volt. Frissítsd a kártyádat, hogy megtartsd az Infinity előfizetést.",
    waiting: "Fizetés megerősítése…",
    subscribe: "Előfizetés",
    monthly: "Havi",
    yearly: "Éves",
    automatic: "Kártya",
    manage: "Fizetés kezelése",
    refund: "Visszatérítés kérése",
    refundDetail: "A fizetéstől számított 7 napon belül elállhatsz: {{amount}}, eddig: {{date}}.",
    refundConfirm: "Visszatérítést kérsz?",
    refundConfirmDetail: "A pénz ugyanarra a fizetési módra kerül vissza, és az Infinity azonnal megszűnik.",
    refunded: "Visszatérítés kérve.",
    unavailable: "Az előfizetés még nem érhető el.",
    success: "Fizetés megérkezett. Köszönjük!",
    canceled: "Fizetés megszakítva.",
    error: "Valami hiba történt. Próbáld újra.",
    no: "Nem",
    tagRow: "Egyedi felhasználói címke",
    guildProfilesRow: "Közösségenkénti profilok",
    badgeRow: "Profiljelvény",
    communitiesRow: "Közösségek",
    savedRow: "Mentett üzenetek",
    animatedEmojiRow: "Animált emojik",
    expressionsRow: "Emojik és matricák bárhonnan",
    animatedProfileRow: "Animált profilképek és bannerek",
    earlyAccessRow: "Korai hozzáférés az újdonságokhoz",
    themesRow: "Egyedi témák",
    pixOption: "Pix",
    pixHint: "Nyisd meg a banki appot, válaszd a Pixet, és olvasd be a QR-kódot vagy használd a másolás-beillesztést.",
    pixQrAlt: "Pix QR-kód",
    pixCopy: "Pix-kód másolása",
    pixCopied: "Pix-kód kimásolva",
    pixWaiting: "Várakozás a fizetésre",
    pixExpiresIn: "lejár: {{time}}",
    pixExpired: "Ez a Pix lejárt. Hozz létre újat a folytatáshoz.",
    pixNew: "Új Pix létrehozása",
    pixPaid: "Pix megérkezett! Az Infinity aktív.",
    forMe: "Magamnak",
    asGift: "Ajándékba",
    buyGift: "Ajándék vásárlása",
    giftReady: "Az ajándék kész! Másold ki a linket, és küldd el bárkinek.",
    giftClaimed: "Ajándék beváltva! Az Infinity a fiókodon van.",
    gifts: "Ajándékok",
    giftsEmpty: "Még nem vásároltál ajándékot.",
    giftCode: "Ajándékkód",
    giftRedeem: "Beváltás",
    giftCopyLink: "Link másolása",
    giftLinkCopied: "Link kimásolva",
    giftClaimedBy: "beváltotta: {{name}}",
    giftHint: "Van ajándékkódod? Váltsd be itt. A vásárolt ajándékok alább látszanak.",
    cardPaid: "Fizetés jóváhagyva! Az Infinity aktív.",
    payAmount: "{{amount}} fizetése",
    giftLinkTitle: "Kaptál egy {{plan}} ajándékot!",
    giftLinkDetail: "Koppints a beváltásra, és a napok a fiókodra kerülnek.",
    pageTitle: "Nyiss meg egy világnyi előnyt az {{plan}}-nyal",
    pageStart: "Kezdőlap",
    pageBest: "Az Infinity legjava",
    pageChoose: "Válaszd ki a csomagod",
    fromPrice: "Havi {{amount}} ártól. Bármikor lemondhatod.",
    filesTitle: "Küldd a teljes fájlt",
    filesText: "A bulis videó, a munkahelyi projekt, a fotókat rejtő mappa: minden egyben megy, darabolás, tömörítés és felhős link nélkül.",
    videoTitle: "Közvetíts 1080p-ben",
    videoText: "A képernyőd élesen érkezik meg a túloldalra, kétszer annyi képkockával másodpercenként. Kódot olvasni és együtt játszani is lehet, elmosódás nélkül.",
    messageTitle: "Írj, amennyit csak akarsz",
    messageText: "Kétszer annyi karakter minden üzenetben, azokra az esetekre, amikor hosszú a történet, és három részre törve elveszne a lényege.",
    colorsTitle: "Az app, ami rád hasonlít",
    colorsText: "Válaszd ki az alkalmazás színeit egyenként, mentsd el a témát, és vidd magaddal minden eszközre, ahol belépsz.",
    profileTitle: "Minden helyre külön profil",
    profileText: "Más becenév, más kép, más bemutatkozás minden közösségben — és mozgó kép is, ha úgy tartja kedved.",
    freeDetail: "Ingyenes, és az is marad.",
    currentPlan: "A jelenlegi csomagod",
    popular: "A legnépszerűbb",
    yearlyDetail: "Ez havi {{amount}}, évente egyszer levonva.",
    monthlyDetail: "Minden hónapban levonjuk, bármikor lemondhatod.",
    groupStyle: "Mutasd meg a stílusod",
    groupLook: "Alakítsd magadra az appot",
    groupLimits: "Szűk korlátok nélkül",
    closingTitle: "Mire vársz még?",
    pagePlans: "Csomagok",
    pageCompare: "Összehasonlítás",
    giftClaimTitle: "Aktiválod az {{plan}}-t?",
    giftClaimDetail: "Ez {{days}} nap, ami most a fiókodra kerül.",
    giftFrom: "tőle: {{name}}",
    giftActivate: "Aktiválás",
    giftHasPlanTitle: "Már van Infinityd",
    giftHasPlanDetail: "A csomagod eddig tart: {{date}}. Tartsd meg a linket, és küldd el egy barátodnak.",
    giftUsedTitle: "Ezt az ajándékot már felhasználták",
    giftUsedDetail: "Valaki korábban beváltotta a kódot. Kérj másikat.",
    giftNotFoundTitle: "A kód nem található",
    giftNotFoundDetail: "Nézd meg a kódot, vagy kérd el újra a linket.",
    giftDoneTitle: "{{plan}} aktiválva!",
    giftOpenApp: "App megnyitása",
    giftSignIn: "Jelentkezz be a beváltáshoz",
    giftReviewStep: "Fizetés · Áttekintés",
    giftTotalToday: "Mai összeg",
    giftCardWhy: "A kártya csak arra kell, hogy megerősítsük, te vagy az. Most semmit sem vonunk le, és semmi sem újul meg magától.",
    giftAgree: "Elolvastam és elfogadom a felhasználási feltételeket",
    giftActivating: "Aktiválás…",
  },
  telas: {
    subscription: "Infinity",
    conta: "Fiókom",
    privacidade: "Adatvédelem",
    conexoes: "Kapcsolatok",
    voz: "Hang",
    video: "Videó",
    avisos: "Értesítések",
    aplicativos: "Alkalmazások",
    aparencia: "Megjelenés",
    batePapo: "Csevegés",
    acessibilidade: "Kisegítő lehetőségek",
    idioma: "Nyelv",
    aplicativo: "Alkalmazás letöltése",
    atalhos: "Gyorsbillentyűk",
    desktop: "Asztali alkalmazás",
    avancado: "Speciális",
    servidor: "Kiszolgáló",
    comunicado: "Rendszerüzenet",
    denuncias: "Jelentések",
    publicacoes: "Telepítések",
  },
  grupos: {
    conta: "Fiók",
    app: "Alkalmazás beállításai",
    desenvolvedor: "Fejlesztő",
    administracao: "Adminisztráció",
  },
  secoes: {
    coresDoApp: "Alkalmazás színei",
    detalhesDeLogin: "Bejelentkezési adatok",
    dispositivos: "Eszközök",
    usuariosBloqueados: "Letiltott felhasználók",
    aplicativosAutorizados: "Engedélyezett alkalmazások",
    sessoes: "Munkamenetek",
    amigosEDms: "Barátok és közvetlen üzenetek",
    compartilhamentoDeAtividade: "Tevékenység megosztása",
    visibilidadeDoPerfil: "Profil láthatósága",
    exportarDados: "Adatok exportálása",
    exclusaoDeDados: "Adatok törlése",
    tema: "Téma",
    corDeDestaque: "Kiemelőszín",
    interface: "Felület",
    listaDeCanais: "Csatornalista",
    zoomDoApp: "Az alkalmazás nagyítása",
    escalaDaFonte: "Csevegés betűmérete",
    modoStreamer: "Adatvédelem közvetítés közben",
    cursores: "Kurzorok",
    movimento: "Mozgás",
    textoEmVoz: "Szövegfelolvasás",
    teclado: "Billentyűzet",
    formatoDaHora: "Időformátum",
    idiomaDaInterface: "A felület nyelve",
    dispositivosDeVoz: "Eszközök",
    testeDoMicrofone: "Mikrofonteszt",
    modoDeEntrada: "Bemeneti mód",
    sensibilidade: "Bemeneti érzékenység",
    qualidade: "Minőség",
    camera: "Kamera",
    transmissao: "Közvetítés",
    exibicao: "Megjelenítés",
    entrada: "Bevitel",
    midia: "Média",
    geral: "Általános",
    preferenciaDeMencao: "Említési beállítás",
    sons: "Hangok",
  },
};
