export const amizades = {
  mensagensDiretas: "Mensajes directos",
  nova: {
    titulo: "Charla nueva",
    detalhe: "Elegí un amigo y la charla se abre.",
    procurar: "Buscar un amigo",
    semAmigos: "Todavía no tenés amigos por acá.",
    semResultado: "Ningún amigo con ese nombre.",
  },
  adicionar: {
    recado: "Escribí un mensajito (opcional)",
    recadoDica: "Lo que escribas acá también aparece en la charla de ustedes, si se hacen amigos.",
    enviadoPara: "¡Listo! El pedido de amistad le llegó a {{nome}}.",
    outrosLugares: "Otros lugares para hacer amigos",
    outrosLugaresDetalhe: "¿No se te ocurre nadie? Mirá las comunidades abiertas, ahí se habla de casi todo.",
    explorarComunidades: "Explorar comunidades",
    titulo: "Agregar amigo",
    detalhe: "Podés agregar amigos por su nombre de usuario.",
    exemplo: "Nombre de usuario, ej.: thiago",
    enviando: "Enviando…",
    enviar: "Enviar solicitud",
  },
  gatinhoChorando: "Un gatito llorando",
  status: {
    emChamada: "En una llamada",
    emVoz: "En voz",
  },
  menu: {
    chamada: "Iniciar llamada",
    fixar: "Fijar arriba",
    desafixar: "Dejar de fijar",
    silenciar: "Silenciar conversación",
    reativar: "Reactivar los avisos",
    copiarIdDoCanal: "Copiar el ID del canal",
  },
  ativosAgora: "Activo ahora",
  procurando: "Viendo quién anda por ahí…",
  tudoTranquilo: "Todo tranquilo por ahora…",
  tudoTranquiloDetalhe: "Cuando vos o un amigo entren a una llamada, va a aparecer acá — y podés sumarte con un clic.",
  emVoz: "En voz",
  voce: "Vos",
  soVoce: "Solo vos",
  pessoas: "{{quantas}} personas",
  voltarParaChamada: "Volver a la llamada",
  entrarNaChamada: "Unirse a la llamada",
  abrirCanal: "Abrir {{canal}} en {{servidor}}",
  encontreConversa: "Buscá una conversación",
  amigos: "Amigos",
  conversas: "Conversaciones",
  semConversas: "Todavía no hay conversaciones. Agregá un amigo para empezar.",
  semConversaComEsseNome: "Ninguna conversación con ese nombre.",
  abrirMenu: "Abrir servidores y conversaciones",
  solicitacoes: "Solicitudes de mensajes",
  pedidos: "Solicitudes",
  spam: "Spam",
  pedidosPendentes: "Solicitudes pendientes",
  marcadosComoSpam: "Marcados como spam",
  aceitar: "Aceptar",
  ignorar: "Ignorar",
  marcarSpam: "Marcar como spam",
  semPedidos: "Ninguna solicitud esperando.",
  semPedidosDetalhe: "Quien no es tu amigo pero comparte un servidor con vos llega acá antes de entrar en tus conversaciones.",
  semSpam: "Nada marcado como spam.",
  semSpamDetalhe: "Lo que el filtro de spam aparte, o lo que marques, queda guardado en esta pestaña.",
  umServidorEmComum: "1 servidor en común",
  servidoresEmComum: "{{quantos}} servidores en común",
  semServidoresEmComum: "Sin servidores en común",
};
