export const comum = {
  voltar: "Volver",
  agoraNao: "Ahora no",
  erro: {
    tentarDeNovo: "Volver a intentar",
    recarregar: "Recargar",
    copiarDetalhes: "Copiar los detalles",
    parteQuebrou: "Esta parte de la pantalla se rompió.",
    titulo: "Ravox Chat tropezó.",
    detalhe: "Algo se rompió en el camino y la pantalla no pudo dibujarse. Tu conversación no se perdió — está todo en el servidor.",
  },
  perdido: {
    titulo: "Esta dirección no lleva a ninguna parte.",
    detalhe: "O el enlace vino mal, o la página cambió de lugar.",
  },
  conexao: {
    voltou: "Conectado de nuevo",
    reconectando: "Reconectando",
    tentativaSufixo: " · intento {{numero}}",
    aSalvo: "La conversación está a salvo en el servidor. Esto vuelve solo apenas regrese la conexión.",
  },
  avisoDoNavegador: {
    titulo: "¿Querés que te avise de los mensajes?",
    detalhe: "Con Ravox Chat detrás de otra ventana, te llama.",
  },
  atualizacao: {
    titulo: "Actualización",
    semAuto: "Esta versión de la app no sabe actualizarse sola. Descargá el instalador más nuevo de abajo e instalalo encima.",
    versaoAtual: "Estás en la versión {{versao}}.",
    instalando: "Instalando la versión {{versao}}…",
    prontaVersao: "La versión {{versao}} está lista para instalar",
    baixandoVersao: "Descargando la versión {{versao}}…",
    baixandoComProgresso: "Descargando la versión {{versao}}… {{porcento}}%",
    saiuVersao: "Salió la versión {{versao}}",
    saiuVersaoClique: "Salió la versión {{versao}} — hacé clic para descargar",
    instalarVersaoEReiniciar: "Instalar la versión {{versao}} y reiniciar",
    erroTenteDeNovo: "{{erro}} Hacé clic para volver a intentar.",
    procurando: "Buscando…",
    emDia: "Estás al día",
    vaiFechar: "La app se cierra en un momento.",
    comoInstala: "La app se cierra, cambia la versión y vuelve a abrirse sola. Si estás en una llamada, salís de ella.",
    semServidor: "No pude hablar con el servidor de versiones.",
    procuraSozinho: "La app busca sola al abrirse y cada seis horas.",
    instalandoReticencias: "Instalando…",
    instalandoCurto: "Instalando",
    baixandoCurto: "Descargando",
    tentarDeNovo: "Volver a intentar",
    reiniciarAgora: "Reiniciar ahora",
    instalarEReiniciar: "Instalar y reiniciar",
    baixar: "Descargar",
    procurar: "Buscar",
    baixarApp: "Descargar la app",
    ariaBotao: "Actualización de la app",
  },
  janela: {
    ajustarAltura: "Ajustar el alto",
    redimensionar: "Cambiar el tamaño de la ventana",
    ajustarLargura: "Ajustar el ancho",
  },
  dica: {
    rotulo: "Consejo:",
    pularConfirmacao: "mantené Shift al hacer clic para saltear esta confirmación.",
  },
  cor: {
    pescar: "Tomar un color de la pantalla",
    hex: "Valor hexadecimal",
  },
  imagem: {
    titulo: "Elegí una imagen",
    enviar: "Enviar imagen",
    escolherGif: "Elegir GIF",
    buscarGif: "Buscar GIF",
  },
  fonte: {
    rotulo: "Fuente del mensaje",
    padrao: "Predeterminada",
    comNome: "Fuente del mensaje — {{fonte}}",
  },
  recorte: {
    titulo: "Recortar el ícono",
    detalhe: "Arrastrá para elegir el pedazo y usá la barra para acercar. El ícono queda redondo en toda la app.",
    voltarAoComeco: "Volver al inicio",
    usar: "Usar este recorte",
  },
  mais: "Más",
  carregando: "Cargando…",
  salvar: "Guardar",
  salvando: "Guardando…",
  descartar: "Descartar",
  redefinir: "Restablecer",
  naoSalvo: "Tienes cambios sin guardar.",
  fechar: "Cerrar",
  criar: "Crear",
  nome: "Nombre",
  emoji: "Emoji",
  previa: "Vista previa",
  cancelar: "Cancelar",
  enviar: "Enviar",
  apagar: "Borrar",
  excluir: "Eliminar",
  remover: "Quitar",
  trocar: "Cambiar",
  loginNoApp: {
    titulo: "¡Todo listo!",
    detalhe: "Iniciaste sesión. Vuelve a Ravox Chat, la app ya te está esperando.",
    abrir: "Abrir Ravox Chat",
    fecharAba: "Ya puedes cerrar esta pestaña.",
    falhouTitulo: "No se pudo iniciar sesión",
    falhouDetalhe: "Vuelve a la app e inténtalo de nuevo.",
    legenda: "Un robot saludando",
    legendaFalhou: "Un gatito llorando",
  },
  ads: {
    label: "Publicidad",
    title: "Anúnciate aquí",
    detail: "Habla con nosotros y aparece ante quienes usan Ravox Chat.",
    action: "Quiero anunciarme",
  },
};
