export const amizades = {
  mensagensDiretas: "Лични съобщения",
  nova: {
    titulo: "Нов разговор",
    detalhe: "Изберете приятел, за да отворите разговора.",
    procurar: "Търсене на приятел",
    semAmigos: "Още нямате приятели тук.",
    semResultado: "Няма приятел с това име.",
  },
  adicionar: {
    recado: "Напишете няколко думи (по желание)",
    recadoDica: "Каквото напишете тук се вижда и в разговора ви, ако станете приятели.",
    enviadoPara: "Готово! Поканата за приятелство отиде при {{nome}}.",
    outrosLugares: "Други места за нови приятелства",
    outrosLugaresDetalhe: "Не се сещате за никого? Разгледайте отворените общности, там говорят почти за всичко.",
    explorarComunidades: "Разгледай общностите",
    titulo: "Добавяне на приятел",
    detalhe: "Можете да добавяте приятели по потребителското им име.",
    exemplo: "Потребителско име, напр.: thiago",
    enviando: "Изпращане…",
    enviar: "Изпрати покана",
  },
  gatinhoChorando: "Плачещо котенце",
  status: {
    emChamada: "В разговор",
    emVoz: "В гласов канал",
  },
  menu: {
    chamada: "Започни разговор",
    fixar: "Закачи най-отгоре",
    desafixar: "Откачи",
    silenciar: "Заглуши разговора",
    reativar: "Включи известията отново",
    copiarIdDoCanal: "Копирай ID на канала",
  },
  ativosAgora: "Активни сега",
  procurando: "Гледаме кой е наоколо…",
  tudoTranquilo: "Засега е тихо…",
  tudoTranquiloDetalhe: "Когато ти или приятел влезете в разговор, той ще се появи тук — и се включваш с едно щракване.",
  emVoz: "В гласов канал",
  voce: "Ти",
  soVoce: "Само ти",
  pessoas: "{{quantas}} души",
  voltarParaChamada: "Обратно към разговора",
  entrarNaChamada: "Влез в разговора",
  abrirCanal: "Отвори {{canal}} в {{servidor}}",
  encontreConversa: "Намери разговор",
  amigos: "Приятели",
  conversas: "Разговори",
  semConversas: "Още няма разговори. Добави приятел, за да започнеш.",
  semConversaComEsseNome: "Няма разговор с това име.",
  abrirMenu: "Отвори сървърите и разговорите",
  solicitacoes: "Заявки за съобщение",
  pedidos: "Заявки",
  spam: "Спам",
  pedidosPendentes: "Чакащи заявки",
  marcadosComoSpam: "Отбелязани като спам",
  aceitar: "Приеми",
  ignorar: "Игнорирай",
  marcarSpam: "Отбележи като спам",
  semPedidos: "Няма чакащи заявки.",
  semPedidosDetalhe: "Който не ти е приятел, но е с теб в общ сървър, стига дотук, преди да влезе в разговорите ти.",
  semSpam: "Нищо не е отбелязано като спам.",
  semSpamDetalhe: "Каквото филтърът за спам отдели или каквото ти отбележиш, остава в този раздел.",
  umServidorEmComum: "1 общ сървър",
  servidoresEmComum: "Общи сървъри: {{quantos}}",
  semServidoresEmComum: "Няма общи сървъри",
};
