export const comum = {
  voltar: "Назад",
  agoraNao: "Не сега",
  erro: {
    tentarDeNovo: "Опитай отново",
    recarregar: "Презареди",
    copiarDetalhes: "Копирай подробностите",
    parteQuebrou: "Тази част от екрана се счупи.",
    titulo: "Ravox Chat се препъна.",
    detalhe: "Нещо се счупи по пътя и екранът не успя да се начертае. Разговорът ви не е изгубен — всичко е на сървъра.",
  },
  perdido: {
    titulo: "Този адрес не води доникъде.",
    detalhe: "Или връзката е грешна, или страницата се е преместила.",
  },
  conexao: {
    voltou: "Връзката се върна",
    reconectando: "Свързване наново",
    tentativaSufixo: " · опит {{numero}}",
    aSalvo: "Разговорът е на сигурно място на сървъра. Това се оправя само, щом връзката се върне.",
  },
  avisoDoNavegador: {
    titulo: "Искате ли известия за съобщенията?",
    detalhe: "Когато Ravox Chat е зад друг прозорец, той ще ви извика.",
  },
  atualizacao: {
    titulo: "Обновяване",
    semAuto: "Тази версия на приложението не се обновява сама. Изтеглете най-новия инсталатор по-долу и го инсталирайте отгоре.",
    versaoAtual: "Използвате версия {{versao}}.",
    instalando: "Инсталиране на версия {{versao}}…",
    prontaVersao: "Версия {{versao}} е готова за инсталиране",
    baixandoVersao: "Изтегляне на версия {{versao}}…",
    baixandoComProgresso: "Изтегляне на версия {{versao}}… {{porcento}}%",
    saiuVersao: "Излезе версия {{versao}}",
    saiuVersaoClique: "Излезе версия {{versao}} — щракнете, за да я изтеглите",
    instalarVersaoEReiniciar: "Инсталирай версия {{versao}} и рестартирай",
    erroTenteDeNovo: "{{erro}} Щракнете, за да опитате отново.",
    procurando: "Търсене…",
    emDia: "Всичко е обновено",
    vaiFechar: "Приложението ще се затвори след малко.",
    comoInstala: "Приложението се затваря, сменя версията и се отваря само. Ако сте в разговор, ще излезете от него.",
    semServidor: "Не успях да се свържа със сървъра за версии.",
    procuraSozinho: "Приложението проверява само при стартиране и на всеки шест часа.",
    instalandoReticencias: "Инсталиране…",
    instalandoCurto: "Инсталиране",
    baixandoCurto: "Изтегляне",
    tentarDeNovo: "Опитай отново",
    reiniciarAgora: "Рестартирай сега",
    instalarEReiniciar: "Инсталирай и рестартирай",
    baixar: "Изтегли",
    procurar: "Провери",
    baixarApp: "Изтегли приложението",
    ariaBotao: "Обновяване на приложението",
  },
  janela: {
    ajustarAltura: "Настройка на височината",
    redimensionar: "Преоразмеряване на прозореца",
    ajustarLargura: "Настройка на ширината",
  },
  dica: {
    rotulo: "Съвет:",
    pularConfirmacao: "задръжте Shift при щракване, за да пропуснете това потвърждение.",
  },
  cor: {
    pescar: "Вземи цвят от екрана",
    hex: "Шестнайсетична стойност",
  },
  imagem: {
    titulo: "Изберете изображение",
    enviar: "Изпрати изображение",
    escolherGif: "Избери GIF",
    buscarGif: "Търсене на GIF",
  },
  fonte: {
    rotulo: "Шрифт на съобщението",
    padrao: "По подразбиране",
    comNome: "Шрифт на съобщението — {{fonte}}",
  },
  recorte: {
    titulo: "Изрязване на иконата",
    detalhe: "Плъзнете, за да изберете частта, и използвайте плъзгача за приближаване. Иконата е кръгла навсякъде в приложението.",
    voltarAoComeco: "Обратно в началото",
    usar: "Използвай това изрязване",
  },
  mais: "Още",
  carregando: "Зареждане…",
  salvar: "Запази",
  salvando: "Запазване…",
  descartar: "Отхвърли",
  redefinir: "Нулирай",
  naoSalvo: "Имаш незапазени промени.",
  fechar: "Затвори",
  criar: "Създай",
  nome: "Име",
  emoji: "Емоджи",
  previa: "Преглед",
  cancelar: "Отказ",
  enviar: "Изпрати",
  apagar: "Изтрий",
  excluir: "Изтрий",
  remover: "Премахни",
  trocar: "Смени",
  loginNoApp: {
    titulo: "Всичко е готово!",
    detalhe: "Влязохте в профила си. Върнете се в Ravox Chat, приложението вече ви чака.",
    abrir: "Отвори Ravox Chat",
    fecharAba: "Вече можете да затворите този раздел.",
    falhouTitulo: "Влизането не успя",
    falhouDetalhe: "Върнете се в приложението и опитайте отново.",
    legenda: "Робот, който маха",
    legendaFalhou: "Плачещо котенце",
  },
  ads: {
    label: "Реклама",
    title: "Рекламирайте тук",
    detail: "Свържете се с нас и се покажете на тези, които използват Ravox Chat.",
    action: "Искам да рекламирам",
  },
};
