export const configuracoes = {
  efeitos: {
    titulo: "Ефекти на показалеца",
    detalhe: "Следа и искри, рисувани върху приложението. Идват изключени и изчезват сами, ако сте поискали по-малко движение.",
    rastro: "Следа на курсора",
    rastroDetalhe: "Черта, която следва показалеца и гасне зад него.",
    faisca: "Искри при щракване",
    faiscaDetalhe: "Къси чертички, които излитат от мястото на щракването.",
    cor: "Цвят",
    espessura: "Дебелина",
    comprimento: "Дължина",
    tamanho: "Размер",
    quantidade: "Брой",
  },
  email: {
    verificarTitulo: "Потвърдете имейла си",
    verificarDetalhe: "Някои общности пускат да пишат само потвърдените. Става с едно щракване.",
    enviar: "Изпрати връзката",
    enviado: "Погледнете входящата поща. Връзката важи един ден.",
    falhou: "Имейлът не можа да бъде изпратен.",
    confirmado: "Имейлът е потвърден",
    confirmadoDetalhe: "Готово. Вече пишете във всяка общност, която го изисква.",
    linkIncompleto: "Непълна връзка",
    linkIncompletoDetalhe: "Липсва кодът в адреса. Отворете връзката направо от имейла.",
    confirmando: "Потвърждава се…",
    expirou: "Тази връзка вече е използвана или е изтекла.",
    irParaOApp: "Към приложението",
  },
  tema: {
    indisponivel: "Темата не е достъпна",
    indisponivelDetalhe: "Този, който я публикува, я изтри, или връзката е грешна.",
    indisponivelLinha: "Темата не е достъпна. Този, който я публикува, я изтри, или връзката е грешна.",
    importar: "Внасяне на тема",
    importarCurto: "Внеси",
    importarDetalhe: "Това заменя темата, която имате сега. После може да я редактирате в Настройки > Външен вид > Ателие за теми.",
    porAutor: "от {{autor}}",
    umaCorTrocada: "1 сменен цвят",
    coresTrocadas: "{{quantas}} сменени цвята",
    avisoDeCss: "Тази тема носи CSS от автора си, а CSS пипа всяко ъгълче на екрана. Внасяйте само от хора, на които вярвате.",
    soCores: "Тази тема сменя само цветове. Никакъв външен CSS.",
    verCss: "Покажи CSS",
    esconderCss: "Скрий CSS",
    aplicar: "Приложи",
    previaSemMotor: "Прегледът не пуска двигателя. Инсталирайте, за да го видите.",
    motorAnimado: "{{motor}} с анимация",
  },
  sair: "Изход",
  versoes: {
    termos: "Условия за ползване",
    privacidade: "Политика за поверителност",
    copiar: "Щракни, за да копираш",
    copiado: "Копирано",
  },
  appColors: {
    title: "Цветове на приложението",
    detail: "Изберете до три цвята и цялото приложение получава този градиент.",
    locked: "Редакторът на цветове е част от {{plan}}.",
    color: "Цвят {{number}}",
    addColor: "Добави цвят",
    removeColor: "Премахни цвета",
    surprise: "Изненадай ме",
    direction: "Посока на градиента",
    intensity: "Интензивност",
    reset: "Нулиране",
  },
  subscription: {
    colorsRow: "Редактор на цветовете",
    seePlans: "Виж плановете",
    upgradeSubtitle: "По-високи лимити и изключителни функции за писане, файлове и излъчване.",
    perMonth: "на месец",
    perYear: "на година",
    save: "Спестете {{percent}}%",
    howToPay: "Как искате да платите?",
    legal: "Можете да поискате възстановяване до 7 дни след плащането. Плащането се обработва от Stripe; никога не виждаме номера на картата ви.",
    compare: "Безплатен срещу Infinity",
    featureColumn: "Функция",
    freeColumn: "Безплатен",
    messageRow: "Лимит на знаците в съобщение",
    attachmentRow: "Размер на качения файл",
    screenRow: "Качество на видеото",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Вече имате Infinity до {{date}}.",
    upsell: "Увеличете лимита с Infinity",
    screenUpsell: "По-високо качество с Infinity",
    free: "Използвате безплатния план.",
    activeUntil: "Infinity е активен до {{date}}.",
    renews: "Подновява се автоматично на {{date}}.",
    endsAt: "Абонаментът е отказан и приключва на {{date}}.",
    pastDue: "Последното плащане не мина. Обновете картата си, за да запазите Infinity.",
    waiting: "Потвърждаване на плащането…",
    subscribe: "Абонирай се",
    monthly: "Месечно",
    yearly: "Годишно",
    automatic: "Карта",
    manage: "Управление на плащането",
    refund: "Поискай възстановяване",
    refundDetail: "Можете да се откажете до 7 дни след плащането: {{amount}}, до {{date}}.",
    refundConfirm: "Да поискате ли възстановяване?",
    refundConfirmDetail: "Парите се връщат по същия начин на плащане, а Infinity спира веднага.",
    refunded: "Поискано е възстановяване.",
    unavailable: "Абонаментът още не е наличен.",
    success: "Плащането е получено. Благодарим!",
    canceled: "Плащането е отказано.",
    error: "Нещо се обърка. Опитайте отново.",
    no: "Не",
    tagRow: "Персонален потребителски таг",
    guildProfilesRow: "Профили за всяка общност",
    badgeRow: "Значка в профила",
    communitiesRow: "Общности",
    savedRow: "Запазени съобщения",
    animatedEmojiRow: "Анимирани емоджита",
    expressionsRow: "Емоджита и стикери отвсякъде",
    animatedProfileRow: "Анимирани аватари и банери",
    earlyAccessRow: "Ранен достъп до нови функции",
    themesRow: "Собствени теми",
    pixOption: "Pix",
    pixHint: "Отворете приложението на банката, изберете Pix и сканирайте QR кода или копирайте кода.",
    pixQrAlt: "QR код за Pix",
    pixCopy: "Копирай кода за Pix",
    pixCopied: "Кодът за Pix е копиран",
    pixWaiting: "Чака се плащане",
    pixExpiresIn: "изтича след {{time}}",
    pixExpired: "Този Pix изтече. Генерирайте нов, за да продължите.",
    pixNew: "Генерирай нов Pix",
    pixPaid: "Pix е получен! Infinity вече е активен.",
    forMe: "За мен",
    asGift: "Като подарък",
    buyGift: "Купи подарък",
    giftReady: "Подаръкът е готов! Копирайте връзката и я изпратете на когото искате.",
    giftClaimed: "Подаръкът е активиран! Infinity вече е в акаунта ви.",
    gifts: "Подаръци",
    giftsEmpty: "Още не сте купували подаръци.",
    giftCode: "Код на подаръка",
    giftRedeem: "Активирай",
    giftCopyLink: "Копирай връзката",
    giftLinkCopied: "Връзката е копирана",
    giftClaimedBy: "активиран от {{name}}",
    giftHint: "Имате код за подарък? Активирайте го тук. Купените подаръци са отдолу.",
    cardPaid: "Плащането е одобрено! Вашият Infinity е активен.",
    payAmount: "Плати {{amount}}",
    giftLinkTitle: "Получихте подарък {{plan}}!",
    giftLinkDetail: "Докоснете активиране и дните влизат в акаунта ви.",
    pageTitle: "Отключете свят от предимства с {{plan}}",
    pageStart: "Начало",
    pageBest: "Най-доброто от Infinity",
    pageChoose: "Изберете своя план",
    fromPrice: "От {{amount}} на месец. Откажете се, когато поискате.",
    filesTitle: "Изпратете целия файл",
    filesText: "Видеото от купона, работният проект, папката със снимките: всичко тръгва наведнъж, без разделяне, без архивиране и без линк към облака по средата.",
    videoTitle: "Излъчвайте в 1080p",
    videoText: "Екранът ви стига ясен до отсрещната страна, с двойно повече кадри в секунда. Може да се чете код и да се играе заедно, без всичко да се размазва.",
    messageTitle: "Пишете на воля",
    messageText: "Двойно повече знаци във всяко съобщение — за когато историята е дълга и разделянето ѝ на три части би развалило удоволствието.",
    colorsTitle: "Приложението с вашия облик",
    colorsText: "Изберете цветовете на приложението един по един, запазете темата и я вземете на всяко устройство, от което влизате.",
    profileTitle: "Различен профил за всяко място",
    profileText: "Друг псевдоним, друга снимка, друго описание във всяка общност — и анимирана снимка, ако искате.",
    freeDetail: "Безплатен е и такъв остава.",
    currentPlan: "Вашият текущ план",
    popular: "Най-избиран",
    yearlyDetail: "Излиза {{amount}} на месец, таксувани веднъж годишно.",
    monthlyDetail: "Таксува се всеки месец, отказвате се, когато поискате.",
    groupStyle: "Покажете стила си",
    groupLook: "Нагласете приложението по свой вкус",
    groupLimits: "Без тесни ограничения",
    closingTitle: "Какво чакате?",
    pagePlans: "Планове",
    pageCompare: "Сравнение",
    giftClaimTitle: "Да активираме {{plan}}?",
    giftClaimDetail: "Това са {{days}} дни, които влизат в акаунта ви сега.",
    giftFrom: "от {{name}}",
    giftActivate: "Активирай",
    giftHasPlanTitle: "Вече имате Infinity",
    giftHasPlanDetail: "Планът ви е до {{date}}. Запазете връзката и я изпратете на приятел.",
    giftUsedTitle: "Този подарък вече е използван",
    giftUsedDetail: "Някой активира кода преди. Поискайте друг.",
    giftNotFoundTitle: "Кодът не е намерен",
    giftNotFoundDetail: "Проверете кода или поискайте връзката отново.",
    giftDoneTitle: "{{plan}} е активиран!",
    giftOpenApp: "Отвори приложението",
    giftSignIn: "Влезте, за да активирате",
    giftReviewStep: "Плащане · Преглед",
    giftTotalToday: "Общо днес",
    giftCardWhy: "Картата е само за да потвърдим, че си ти. Сега не се удържа нищо и нищо не се подновява само.",
    giftAgree: "Прочетох и приемам условията за ползване",
    giftActivating: "Активира се…",
  },
  telas: {
    subscription: "Infinity",
    conta: "Моят акаунт",
    privacidade: "Поверителност",
    conexoes: "Връзки",
    voz: "Звук",
    video: "Видео",
    avisos: "Известия",
    aplicativos: "Приложения",
    aparencia: "Външен вид",
    batePapo: "Чат",
    acessibilidade: "Достъпност",
    idioma: "Език",
    aplicativo: "Изтегли приложението",
    atalhos: "Клавишни комбинации",
    desktop: "Приложение за компютър",
    avancado: "Разширени",
    servidor: "Сървър",
    comunicado: "Системно съобщение",
    denuncias: "Сигнали",
    publicacoes: "Публикации",
  },
  grupos: {
    conta: "Акаунт",
    app: "Настройки на приложението",
    desenvolvedor: "Разработчик",
    administracao: "Администрация",
  },
  secoes: {
    coresDoApp: "Цветове на приложението",
    detalhesDeLogin: "Данни за вход",
    dispositivos: "Устройства",
    usuariosBloqueados: "Блокирани потребители",
    aplicativosAutorizados: "Оторизирани приложения",
    sessoes: "Сесии",
    amigosEDms: "Приятели и лични съобщения",
    compartilhamentoDeAtividade: "Споделяне на активност",
    visibilidadeDoPerfil: "Видимост на профила",
    exportarDados: "Експортиране на данни",
    exclusaoDeDados: "Изтриване на данни",
    tema: "Тема",
    corDeDestaque: "Акцентен цвят",
    interface: "Интерфейс",
    listaDeCanais: "Списък с канали",
    zoomDoApp: "Ниво на мащабиране",
    escalaDaFonte: "Размер на шрифта в чата",
    modoStreamer: "Поверителност при излъчване",
    cursores: "Курсори",
    movimento: "Движение",
    textoEmVoz: "Текст в реч",
    teclado: "Клавиатура",
    formatoDaHora: "Формат на часа",
    idiomaDaInterface: "Език на интерфейса",
    dispositivosDeVoz: "Устройства",
    testeDoMicrofone: "Тест на микрофона",
    modoDeEntrada: "Режим на въвеждане",
    sensibilidade: "Чувствителност на входа",
    qualidade: "Качество",
    camera: "Камера",
    transmissao: "Излъчване",
    exibicao: "Показване",
    entrada: "Въвеждане",
    midia: "Медия",
    geral: "Общи",
    preferenciaDeMencao: "Предпочитание за споменавания",
    sons: "Звуци",
  },
};
