export const amizades = {
  mensagensDiretas: "Απευθείας μηνύματα",
  nova: {
    titulo: "Νέα συνομιλία",
    detalhe: "Διαλέξτε έναν φίλο και η συνομιλία ανοίγει.",
    procurar: "Αναζήτηση φίλου",
    semAmigos: "Δεν έχετε ακόμα φίλους εδώ.",
    semResultado: "Κανένας φίλος με αυτό το όνομα.",
  },
  adicionar: {
    recado: "Γράψτε δυο λόγια (προαιρετικό)",
    recadoDica: "Ό,τι γράψετε εδώ φαίνεται και στη συνομιλία σας, αν γίνετε φίλοι.",
    enviadoPara: "Έτοιμο! Το αίτημα φιλίας έφτασε στον/στην {{nome}}.",
    outrosLugares: "Άλλα μέρη για να κάνετε φίλους",
    outrosLugaresDetalhe: "Δεν σας έρχεται κανείς στο μυαλό; Ρίξτε μια ματιά στις ανοιχτές κοινότητες, μιλάνε για σχεδόν τα πάντα.",
    explorarComunidades: "Εξερεύνηση κοινοτήτων",
    titulo: "Προσθήκη φίλου",
    detalhe: "Μπορείτε να προσθέσετε φίλους με το όνομα χρήστη τους.",
    exemplo: "Όνομα χρήστη, π.χ.: thiago",
    enviando: "Αποστολή…",
    enviar: "Αποστολή αιτήματος",
  },
  gatinhoChorando: "Ένα γατάκι που κλαίει",
  status: {
    emChamada: "Σε κλήση",
    emVoz: "Σε φωνή",
  },
  menu: {
    chamada: "Έναρξη κλήσης",
    fixar: "Καρφίτσωμα στην κορυφή",
    desafixar: "Ξεκαρφίτσωμα",
    silenciar: "Σίγαση συνομιλίας",
    reativar: "Ενεργοποίηση ειδοποιήσεων ξανά",
    copiarIdDoCanal: "Αντιγραφή ID καναλιού",
  },
  ativosAgora: "Ενεργοί τώρα",
  procurando: "Βλέπουμε ποιος είναι εδώ…",
  tudoTranquilo: "Προς το παρόν ησυχία…",
  tudoTranquiloDetalhe: "Όταν εσύ ή ένας φίλος μπείτε σε κλήση, θα εμφανιστεί εδώ — και μπαίνεις με ένα κλικ.",
  emVoz: "Σε φωνητικό",
  voce: "Εσύ",
  soVoce: "Μόνο εσύ",
  pessoas: "{{quantas}} άτομα",
  voltarParaChamada: "Πίσω στην κλήση",
  entrarNaChamada: "Μπες στην κλήση",
  abrirCanal: "Άνοιγμα {{canal}} στο {{servidor}}",
  encontreConversa: "Βρες μια συνομιλία",
  amigos: "Φίλοι",
  conversas: "Συνομιλίες",
  semConversas: "Καμία συνομιλία ακόμα. Πρόσθεσε έναν φίλο για να ξεκινήσεις.",
  semConversaComEsseNome: "Καμία συνομιλία με αυτό το όνομα.",
  abrirMenu: "Άνοιγμα διακομιστών και συνομιλιών",
  solicitacoes: "Αιτήματα μηνύματος",
  pedidos: "Αιτήματα",
  spam: "Ανεπιθύμητα",
  pedidosPendentes: "Αιτήματα σε αναμονή",
  marcadosComoSpam: "Σημειωμένα ως ανεπιθύμητα",
  aceitar: "Αποδοχή",
  ignorar: "Αγνόηση",
  marcarSpam: "Σήμανση ως ανεπιθύμητο",
  semPedidos: "Κανένα αίτημα σε αναμονή.",
  semPedidosDetalhe: "Όποιος δεν είναι φίλος σου αλλά μοιράζεται διακομιστή μαζί σου, καταλήγει εδώ πριν φτάσει στις συνομιλίες σου.",
  semSpam: "Τίποτα σημειωμένο ως ανεπιθύμητο.",
  semSpamDetalhe: "Ό,τι ξεχωρίσει το φίλτρο ανεπιθύμητων, ή ό,τι σημειώσεις εσύ, μένει σε αυτή την καρτέλα.",
  umServidorEmComum: "1 κοινός διακομιστής",
  servidoresEmComum: "{{quantos}} κοινοί διακομιστές",
  semServidoresEmComum: "Κανένας κοινός διακομιστής",
};
