export const configuracoes = {
  efeitos: {
    titulo: "Εφέ του δείκτη",
    detalhe: "Ίχνος και σπίθες ζωγραφισμένα πάνω από την εφαρμογή. Ξεκινούν σβηστά και χάνονται μόνα τους αν ζητήσατε λιγότερη κίνηση.",
    rastro: "Ίχνος του δείκτη",
    rastroDetalhe: "Μια γραμμή που ακολουθεί τον δείκτη και ξεθωριάζει πίσω του.",
    faisca: "Σπίθες στο κλικ",
    faiscaDetalhe: "Κοντές γραμμές που πετάγονται από εκεί που πατήσατε.",
    cor: "Χρώμα",
    espessura: "Πάχος",
    comprimento: "Μήκος",
    tamanho: "Μέγεθος",
    quantidade: "Πλήθος",
  },
  email: {
    verificarTitulo: "Επιβεβαιώστε το email σας",
    verificarDetalhe: "Κάποιες κοινότητες αφήνουν να γράψουν μόνο όσους επιβεβαίωσαν. Θέλει ένα κλικ.",
    enviar: "Στείλε τον σύνδεσμο",
    enviado: "Δείτε τα εισερχόμενα. Ο σύνδεσμος κρατά μία μέρα.",
    falhou: "Δεν έγινε να σταλεί το email.",
    confirmado: "Το email επιβεβαιώθηκε",
    confirmadoDetalhe: "Έτοιμο. Τώρα γράφετε σε κάθε κοινότητα που το ζητά.",
    linkIncompleto: "Μισός σύνδεσμος",
    linkIncompletoDetalhe: "Λείπει ο κωδικός από τη διεύθυνση. Ανοίξτε τον σύνδεσμο απευθείας από το email.",
    confirmando: "Γίνεται επιβεβαίωση…",
    expirou: "Αυτός ο σύνδεσμος χρησιμοποιήθηκε ήδη ή έληξε.",
    irParaOApp: "Στην εφαρμογή",
  },
  tema: {
    indisponivel: "Το θέμα δεν είναι διαθέσιμο",
    indisponivelDetalhe: "Όποιος το δημοσίευσε το έσβησε, ή ο σύνδεσμος είναι λάθος.",
    indisponivelLinha: "Το θέμα δεν είναι διαθέσιμο. Όποιος το δημοσίευσε το έσβησε, ή ο σύνδεσμος είναι λάθος.",
    importar: "Εισαγωγή θέματος",
    importarCurto: "Εισαγωγή",
    importarDetalhe: "Αυτό αντικαθιστά το θέμα που έχετε τώρα. Μπορείτε να το επεξεργαστείτε μετά στις Ρυθμίσεις > Εμφάνιση > Στούντιο θεμάτων.",
    porAutor: "από {{autor}}",
    umaCorTrocada: "1 χρώμα αλλαγμένο",
    coresTrocadas: "{{quantas}} χρώματα αλλαγμένα",
    avisoDeCss: "Αυτό το θέμα φέρνει CSS από όποιον το έγραψε, και το CSS πιάνει κάθε γωνιά της οθόνης. Κάντε εισαγωγή μόνο από άτομα που εμπιστεύεστε.",
    soCores: "Αυτό το θέμα αλλάζει μόνο χρώματα. Καθόλου εξωτερικό CSS.",
    verCss: "Προβολή CSS",
    esconderCss: "Απόκρυψη CSS",
    aplicar: "Εφαρμογή",
    previaSemMotor: "Η προεπισκόπηση δεν τρέχει τη μηχανή. Εγκαταστήστε το για να τη δείτε.",
    motorAnimado: "{{motor}} με κίνηση",
  },
  sair: "Αποσύνδεση",
  versoes: {
    termos: "Όροι χρήσης",
    privacidade: "Πολιτική απορρήτου",
    copiar: "Κάνε κλικ για αντιγραφή",
    copiado: "Αντιγράφηκε",
  },
  appColors: {
    title: "Χρώματα της εφαρμογής",
    detail: "Διαλέξτε έως τρία χρώματα και όλη η εφαρμογή παίρνει αυτή τη διαβάθμιση.",
    locked: "Ο επεξεργαστής χρωμάτων ανήκει στο {{plan}}.",
    color: "Χρώμα {{number}}",
    addColor: "Προσθήκη χρώματος",
    removeColor: "Αφαίρεση χρώματος",
    surprise: "Έκπληξέ με",
    direction: "Κατεύθυνση διαβάθμισης",
    intensity: "Ένταση",
    reset: "Επαναφορά",
  },
  subscription: {
    colorsRow: "Επεξεργαστής χρωμάτων",
    seePlans: "Δείτε τα πακέτα",
    upgradeSubtitle: "Μεγαλύτερα όρια και αποκλειστικές λειτουργίες για γραφή, αρχεία και μετάδοση.",
    perMonth: "τον μήνα",
    perYear: "τον χρόνο",
    save: "Εξοικονομήστε {{percent}}%",
    howToPay: "Πώς θέλετε να πληρώσετε;",
    legal: "Μπορείτε να ζητήσετε επιστροφή χρημάτων έως 7 ημέρες μετά την πληρωμή. Την πληρωμή επεξεργάζεται η Stripe· δεν βλέπουμε ποτέ τον αριθμό της κάρτας σας.",
    compare: "Δωρεάν ή Infinity",
    featureColumn: "Λειτουργία",
    freeColumn: "Δωρεάν",
    messageRow: "Όριο χαρακτήρων μηνύματος",
    attachmentRow: "Μέγεθος αρχείου για αποστολή",
    screenRow: "Ποιότητα βίντεο",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Έχετε ήδη Infinity έως {{date}}.",
    upsell: "Αυξήστε το όριο με το Infinity",
    screenUpsell: "Καλύτερη ποιότητα με το Infinity",
    free: "Χρησιμοποιείτε το δωρεάν πρόγραμμα.",
    activeUntil: "Το Infinity είναι ενεργό έως {{date}}.",
    renews: "Ανανεώνεται αυτόματα στις {{date}}.",
    endsAt: "Η συνδρομή ακυρώθηκε και λήγει στις {{date}}.",
    pastDue: "Η τελευταία χρέωση απέτυχε. Ενημερώστε την κάρτα σας για να κρατήσετε το Infinity.",
    waiting: "Επιβεβαίωση πληρωμής…",
    subscribe: "Εγγραφή",
    monthly: "Μηνιαία",
    yearly: "Ετήσια",
    automatic: "Κάρτα",
    manage: "Διαχείριση πληρωμής",
    refund: "Αίτημα επιστροφής χρημάτων",
    refundDetail: "Μπορείτε να υπαναχωρήσετε έως 7 ημέρες μετά την πληρωμή: {{amount}}, έως {{date}}.",
    refundConfirm: "Αίτημα επιστροφής χρημάτων;",
    refundConfirmDetail: "Τα χρήματα επιστρέφουν στον ίδιο τρόπο πληρωμής και το Infinity λήγει αμέσως.",
    refunded: "Το αίτημα επιστροφής στάλθηκε.",
    unavailable: "Η συνδρομή δεν είναι ακόμα διαθέσιμη.",
    success: "Η πληρωμή ελήφθη. Ευχαριστούμε!",
    canceled: "Η πληρωμή ακυρώθηκε.",
    error: "Κάτι πήγε στραβά. Δοκιμάστε ξανά.",
    no: "Όχι",
    tagRow: "Προσωπική ετικέτα χρήστη",
    guildProfilesRow: "Προφίλ ανά κοινότητα",
    badgeRow: "Σήμα προφίλ",
    communitiesRow: "Κοινότητες",
    savedRow: "Αποθηκευμένα μηνύματα",
    animatedEmojiRow: "Κινούμενα emoji",
    expressionsRow: "Emoji και αυτοκόλλητα από παντού",
    animatedProfileRow: "Κινούμενα άβαταρ και banner προφίλ",
    earlyAccessRow: "Πρόωρη πρόσβαση σε νέες λειτουργίες",
    themesRow: "Προσωπικά θέματα",
    pixOption: "Pix",
    pixHint: "Ανοίξτε την εφαρμογή της τράπεζας, επιλέξτε Pix και σαρώστε τον κωδικό QR ή κάντε αντιγραφή και επικόλληση.",
    pixQrAlt: "Κωδικός QR Pix",
    pixCopy: "Αντιγραφή κωδικού Pix",
    pixCopied: "Ο κωδικός Pix αντιγράφηκε",
    pixWaiting: "Αναμονή πληρωμής",
    pixExpiresIn: "λήγει σε {{time}}",
    pixExpired: "Αυτό το Pix έληξε. Δημιουργήστε νέο για να συνεχίσετε.",
    pixNew: "Δημιουργία νέου Pix",
    pixPaid: "Το Pix ελήφθη! Το Infinity είναι ενεργό.",
    forMe: "Για μένα",
    asGift: "Ως δώρο",
    buyGift: "Αγορά δώρου",
    giftReady: "Το δώρο είναι έτοιμο! Αντιγράψτε τον σύνδεσμο και στείλτε τον σε όποιον θέλετε.",
    giftClaimed: "Το δώρο εξαργυρώθηκε! Το Infinity είναι στον λογαριασμό σας.",
    gifts: "Δώρα",
    giftsEmpty: "Δεν έχετε αγοράσει ακόμη κανένα δώρο.",
    giftCode: "Κωδικός δώρου",
    giftRedeem: "Εξαργύρωση",
    giftCopyLink: "Αντιγραφή συνδέσμου",
    giftLinkCopied: "Ο σύνδεσμος αντιγράφηκε",
    giftClaimedBy: "εξαργυρώθηκε από {{name}}",
    giftHint: "Έχετε κωδικό δώρου; Εξαργυρώστε τον εδώ. Τα δώρα που αγοράσατε είναι πιο κάτω.",
    cardPaid: "Η πληρωμή εγκρίθηκε! Το Infinity σας είναι ενεργό.",
    payAmount: "Πληρωμή {{amount}}",
    giftLinkTitle: "Λάβατε ένα δώρο {{plan}}!",
    giftLinkDetail: "Πατήστε εξαργύρωση και οι μέρες μπαίνουν στον λογαριασμό σας.",
    pageTitle: "Ξεκλειδώστε έναν κόσμο προνομίων με το {{plan}}",
    pageStart: "Αρχική",
    pageBest: "Τα καλύτερα του Infinity",
    pageChoose: "Επιλέξτε το πακέτο σας",
    fromPrice: "Από {{amount}} τον μήνα. Ακυρώστε όποτε θέλετε.",
    filesTitle: "Στείλτε ολόκληρο το αρχείο",
    filesText: "Το βίντεο από το πάρτι, το έργο της δουλειάς, ο φάκελος με τις φωτογραφίες: φεύγουν όλα μαζί, χωρίς κόψιμο, χωρίς συμπίεση και χωρίς σύνδεσμο στο cloud στη μέση.",
    videoTitle: "Μεταδώστε σε 1080p",
    videoText: "Η οθόνη σας φτάνει καθαρή στην άλλη πλευρά, με διπλάσια καρέ ανά δευτερόλεπτο. Μπορείτε να διαβάζετε κώδικα και να παίζετε μαζί χωρίς να θολώνει τίποτα.",
    messageTitle: "Γράψτε όσο θέλετε",
    messageText: "Διπλάσιοι χαρακτήρες σε κάθε μήνυμα, για τις φορές που η ιστορία είναι μεγάλη και το σπάσιμο σε τρία μέρη θα χαλούσε τη χάρη.",
    colorsTitle: "Η εφαρμογή με το ύφος σας",
    colorsText: "Διαλέξτε τα χρώματα της εφαρμογής ένα ένα, αποθηκεύστε το θέμα και πάρτε το σε κάθε συσκευή από την οποία μπαίνετε.",
    profileTitle: "Ένα προφίλ για κάθε μέρος",
    profileText: "Άλλο ψευδώνυμο, άλλη φωτογραφία, άλλη περιγραφή σε κάθε κοινότητα — και κινούμενη φωτογραφία, αν θέλετε.",
    freeDetail: "Είναι δωρεάν και παραμένει δωρεάν.",
    currentPlan: "Το τρέχον πακέτο σας",
    popular: "Πιο δημοφιλές",
    yearlyDetail: "Βγαίνει {{amount}} τον μήνα, με μία χρέωση τον χρόνο.",
    monthlyDetail: "Χρεώνεται κάθε μήνα, ακυρώνετε όποτε θέλετε.",
    groupStyle: "Δείξτε το στιλ σας",
    groupLook: "Φτιάξτε την εφαρμογή στα μέτρα σας",
    groupLimits: "Χωρίς στενά όρια",
    closingTitle: "Τι περιμένετε;",
    pagePlans: "Πακέτα",
    pageCompare: "Σύγκριση",
    giftClaimTitle: "Ενεργοποίηση {{plan}};",
    giftClaimDetail: "Είναι {{days}} ημέρες που μπαίνουν τώρα στον λογαριασμό σας.",
    giftFrom: "από {{name}}",
    giftActivate: "Ενεργοποίηση",
    giftHasPlanTitle: "Έχετε ήδη Infinity",
    giftHasPlanDetail: "Το πακέτο σας ισχύει έως {{date}}. Κρατήστε τον σύνδεσμο και στείλτε τον σε φίλο.",
    giftUsedTitle: "Αυτό το δώρο χρησιμοποιήθηκε ήδη",
    giftUsedDetail: "Κάποιος εξαργύρωσε τον κωδικό πριν. Ζητήστε άλλον.",
    giftNotFoundTitle: "Ο κωδικός δεν βρέθηκε",
    giftNotFoundDetail: "Ελέγξτε τον κωδικό ή ζητήστε ξανά τον σύνδεσμο.",
    giftDoneTitle: "Το {{plan}} ενεργοποιήθηκε!",
    giftOpenApp: "Άνοιγμα εφαρμογής",
    giftSignIn: "Συνδεθείτε για εξαργύρωση",
    giftReviewStep: "Πληρωμή · Έλεγχος",
    giftTotalToday: "Σύνολο σήμερα",
    giftCardWhy: "Η κάρτα είναι μόνο για να επιβεβαιωθεί ότι είσαι εσύ. Δεν χρεώνεται τίποτα τώρα και τίποτα δεν ανανεώνεται μόνο του.",
    giftAgree: "Διάβασα και αποδέχομαι τους όρους χρήσης",
    giftActivating: "Ενεργοποίηση…",
  },
  telas: {
    subscription: "Infinity",
    conta: "Ο λογαριασμός μου",
    privacidade: "Απόρρητο",
    conexoes: "Συνδέσεις",
    voz: "Ήχος",
    video: "Βίντεο",
    avisos: "Ειδοποιήσεις",
    aplicativos: "Εφαρμογές",
    aparencia: "Εμφάνιση",
    batePapo: "Συνομιλία",
    acessibilidade: "Προσβασιμότητα",
    idioma: "Γλώσσα",
    aplicativo: "Λήψη της εφαρμογής",
    atalhos: "Συντομεύσεις",
    desktop: "Εφαρμογή υπολογιστή",
    avancado: "Για προχωρημένους",
    servidor: "Διακομιστής",
    comunicado: "Ανακοίνωση συστήματος",
    denuncias: "Αναφορές",
    publicacoes: "Αναπτύξεις",
  },
  grupos: {
    conta: "Λογαριασμός",
    app: "Ρυθμίσεις εφαρμογής",
    desenvolvedor: "Προγραμματιστής",
    administracao: "Διαχείριση",
  },
  secoes: {
    coresDoApp: "Χρώματα της εφαρμογής",
    detalhesDeLogin: "Στοιχεία σύνδεσης",
    dispositivos: "Συσκευές",
    usuariosBloqueados: "Αποκλεισμένοι χρήστες",
    aplicativosAutorizados: "Εξουσιοδοτημένες εφαρμογές",
    sessoes: "Συνεδρίες",
    amigosEDms: "Φίλοι και άμεσα μηνύματα",
    compartilhamentoDeAtividade: "Κοινή χρήση δραστηριότητας",
    visibilidadeDoPerfil: "Ορατότητα προφίλ",
    exportarDados: "Εξαγωγή δεδομένων",
    exclusaoDeDados: "Διαγραφή δεδομένων",
    tema: "Θέμα",
    corDeDestaque: "Χρώμα τονισμού",
    interface: "Διεπαφή",
    listaDeCanais: "Λίστα καναλιών",
    zoomDoApp: "Επίπεδο ζουμ της εφαρμογής",
    escalaDaFonte: "Μέγεθος γραμματοσειράς συνομιλίας",
    modoStreamer: "Απόρρητο κατά τη μετάδοση",
    cursores: "Δείκτες",
    movimento: "Κίνηση",
    textoEmVoz: "Κείμενο σε ομιλία",
    teclado: "Πληκτρολόγιο",
    formatoDaHora: "Μορφή ώρας",
    idiomaDaInterface: "Γλώσσα διεπαφής",
    dispositivosDeVoz: "Συσκευές",
    testeDoMicrofone: "Δοκιμή μικροφώνου",
    modoDeEntrada: "Λειτουργία εισόδου",
    sensibilidade: "Ευαισθησία εισόδου",
    qualidade: "Ποιότητα",
    camera: "Κάμερα",
    transmissao: "Μετάδοση",
    exibicao: "Προβολή",
    entrada: "Εισαγωγή",
    midia: "Πολυμέσα",
    geral: "Γενικά",
    preferenciaDeMencao: "Προτίμηση αναφορών",
    sons: "Ήχοι",
  },
};
