export const amizades = {
  mensagensDiretas: "Izravne poruke",
  nova: {
    titulo: "Novi razgovor",
    detalhe: "Odaberi prijatelja i razgovor se otvara.",
    procurar: "Nađi prijatelja",
    semAmigos: "Ovdje još nemaš prijatelja.",
    semResultado: "Nema prijatelja s tim imenom.",
  },
  adicionar: {
    recado: "Napiši par riječi (nije obavezno)",
    recadoDica: "Ono što napišeš ovdje pojavljuje se i u vašem razgovoru, ako se sprijateljite.",
    enviadoPara: "Gotovo! Zahtjev za prijateljstvo stigao je do {{nome}}.",
    outrosLugares: "Druga mjesta za nova poznanstva",
    outrosLugaresDetalhe: "Nitko ti ne pada na pamet? Pogledaj otvorene zajednice, ondje se priča gotovo o svemu.",
    explorarComunidades: "Istraži zajednice",
    titulo: "Dodaj prijatelja",
    detalhe: "Prijatelje možeš dodati po njihovu korisničkom imenu.",
    exemplo: "Korisničko ime, npr.: thiago",
    enviando: "Šaljem…",
    enviar: "Pošalji zahtjev",
  },
  gatinhoChorando: "Mače koje plače",
  status: {
    emChamada: "U pozivu",
    emVoz: "U glasovnom",
  },
  menu: {
    chamada: "Pokreni poziv",
    fixar: "Prikvači na vrh",
    desafixar: "Otkvači",
    silenciar: "Utišaj razgovor",
    reativar: "Uključi obavijesti",
    copiarIdDoCanal: "Kopiraj ID kanala",
  },
  ativosAgora: "Sada aktivni",
  procurando: "Gledamo tko je tu…",
  tudoTranquilo: "Za sada je mirno…",
  tudoTranquiloDetalhe: "Kad se ti ili prijatelj uključite u poziv, pojavit će se ovdje — i pridružuješ se jednim klikom.",
  emVoz: "Na glasovnom",
  voce: "Ti",
  soVoce: "Samo ti",
  pessoas: "{{quantas}} osoba",
  voltarParaChamada: "Natrag na poziv",
  entrarNaChamada: "Pridruži se pozivu",
  abrirCanal: "Otvori {{canal}} na {{servidor}}",
  encontreConversa: "Pronađi razgovor",
  amigos: "Prijatelji",
  conversas: "Razgovori",
  semConversas: "Još nema razgovora. Dodaj prijatelja da počneš.",
  semConversaComEsseNome: "Nema razgovora s tim imenom.",
  abrirMenu: "Otvori poslužitelje i razgovore",
  solicitacoes: "Zahtjevi za poruku",
  pedidos: "Zahtjevi",
  spam: "Spam",
  pedidosPendentes: "Zahtjevi na čekanju",
  marcadosComoSpam: "Označeni kao spam",
  aceitar: "Prihvati",
  ignorar: "Zanemari",
  marcarSpam: "Označi kao spam",
  semPedidos: "Nema zahtjeva na čekanju.",
  semPedidosDetalhe: "Tko ti nije prijatelj, ali dijeli poslužitelj s tobom, stiže ovdje prije nego dođe do tvojih razgovora.",
  semSpam: "Ništa nije označeno kao spam.",
  semSpamDetalhe: "Ono što filtar spama izdvoji, ili što sam označiš, ostaje na ovoj kartici.",
  umServidorEmComum: "1 zajednički poslužitelj",
  servidoresEmComum: "Zajedničkih poslužitelja: {{quantos}}",
  semServidoresEmComum: "Nema zajedničkih poslužitelja",
};
