export const comum = {
  voltar: "Natrag",
  agoraNao: "Ne sada",
  erro: {
    tentarDeNovo: "Pokušaj ponovno",
    recarregar: "Učitaj ponovno",
    copiarDetalhes: "Kopiraj pojedinosti",
    parteQuebrou: "Ovaj se dio zaslona pokvario.",
    titulo: "Ravox Chat se spotaknuo.",
    detalhe: "Nešto se putem pokvarilo i zaslon se nije uspio iscrtati. Tvoj razgovor nije izgubljen — sve je na poslužitelju.",
  },
  perdido: {
    titulo: "Ova adresa ne vodi nikamo.",
    detalhe: "Ili je poveznica pogrešna, ili se stranica premjestila.",
  },
  conexao: {
    voltou: "Opet povezano",
    reconectando: "Ponovno se povezujem",
    tentativaSufixo: " · pokušaj {{numero}}",
    aSalvo: "Razgovor je na sigurnom na poslužitelju. Sve se vraća samo čim se veza vrati.",
  },
  avisoDoNavegador: {
    titulo: "Želiš obavijesti o porukama?",
    detalhe: "Kad je Ravox Chat iza drugog prozora, javit će ti se.",
  },
  atualizacao: {
    titulo: "Ažuriranje",
    semAuto: "Ova se verzija aplikacije ne zna sama ažurirati. Preuzmi najnoviji instalacijski program ispod i instaliraj ga preko.",
    versaoAtual: "Imaš verziju {{versao}}.",
    instalando: "Instalira se verzija {{versao}}…",
    prontaVersao: "Verzija {{versao}} spremna je za instalaciju",
    baixandoVersao: "Preuzima se verzija {{versao}}…",
    baixandoComProgresso: "Preuzima se verzija {{versao}}… {{porcento}} %",
    saiuVersao: "Izašla je verzija {{versao}}",
    saiuVersaoClique: "Izašla je verzija {{versao}} — klikni za preuzimanje",
    instalarVersaoEReiniciar: "Instaliraj verziju {{versao}} i ponovno pokreni",
    erroTenteDeNovo: "{{erro}} Klikni da pokušaš ponovno.",
    procurando: "Tražim…",
    emDia: "Sve je ažurno",
    vaiFechar: "Aplikacija se zatvara za koji trenutak.",
    comoInstala: "Aplikacija se zatvara, mijenja verziju i sama se ponovno otvara. Ako si u pozivu, izaći ćeš iz njega.",
    semServidor: "Nisam uspio doći do poslužitelja verzija.",
    procuraSozinho: "Aplikacija sama provjerava pri pokretanju i svakih šest sati.",
    instalandoReticencias: "Instaliram…",
    instalandoCurto: "Instaliram",
    baixandoCurto: "Preuzimam",
    tentarDeNovo: "Pokušaj ponovno",
    reiniciarAgora: "Ponovno pokreni odmah",
    instalarEReiniciar: "Instaliraj i ponovno pokreni",
    baixar: "Preuzmi",
    procurar: "Provjeri",
    baixarApp: "Preuzmi aplikaciju",
    ariaBotao: "Ažuriranje aplikacije",
  },
  janela: {
    ajustarAltura: "Prilagodi visinu",
    redimensionar: "Promijeni veličinu prozora",
    ajustarLargura: "Prilagodi širinu",
  },
  dica: {
    rotulo: "Savjet:",
    pularConfirmacao: "drži Shift dok klikaš da preskočiš ovu potvrdu.",
  },
  cor: {
    pescar: "Uzmi boju sa zaslona",
    hex: "Heksadecimalna vrijednost",
  },
  imagem: {
    titulo: "Odaberi sliku",
    enviar: "Pošalji sliku",
    escolherGif: "Odaberi GIF",
    buscarGif: "Traži GIF",
  },
  fonte: {
    rotulo: "Font poruke",
    padrao: "Zadano",
    comNome: "Font poruke — {{fonte}}",
  },
  recorte: {
    titulo: "Izreži ikonu",
    detalhe: "Povuci da odabereš dio i klizačem približi. Ikona je okrugla svugdje u aplikaciji.",
    voltarAoComeco: "Natrag na početak",
    usar: "Upotrijebi ovaj izrez",
  },
  mais: "Više",
  carregando: "Učitavanje…",
  salvar: "Spremi",
  salvando: "Spremanje…",
  descartar: "Odbaci",
  redefinir: "Vrati",
  naoSalvo: "Imaš nespremljene promjene.",
  fechar: "Zatvori",
  criar: "Stvori",
  nome: "Naziv",
  emoji: "Emoji",
  previa: "Pregled",
  cancelar: "Odustani",
  enviar: "Pošalji",
  apagar: "Obriši",
  excluir: "Obriši",
  remover: "Ukloni",
  trocar: "Promijeni",
  loginNoApp: {
    titulo: "Sve je spremno!",
    detalhe: "Prijavljeni ste. Vratite se u Ravox Chat, aplikacija vas već čeka.",
    abrir: "Otvori Ravox Chat",
    fecharAba: "Sada možete zatvoriti ovu karticu.",
    falhouTitulo: "Prijava nije uspjela",
    falhouDetalhe: "Vratite se u aplikaciju i pokušajte ponovno.",
    legenda: "Robot koji maše",
    legendaFalhou: "Mače koje plače",
  },
  ads: {
    label: "Oglas",
    title: "Oglašavajte ovdje",
    detail: "Javite nam se i pokažite se onima koji koriste Ravox Chat.",
    action: "Želim oglašavati",
  },
};
