export const amizades = {
  mensagensDiretas: "Mesaje directe",
  nova: {
    titulo: "Discuție nouă",
    detalhe: "Alege un prieten și discuția se deschide.",
    procurar: "Caută un prieten",
    semAmigos: "Încă nu ai prieteni pe aici.",
    semResultado: "Niciun prieten cu numele ăsta.",
  },
  adicionar: {
    recado: "Scrie două vorbe (opțional)",
    recadoDica: "Ce scrii aici apare și în discuția voastră, dacă ajungeți prieteni.",
    enviadoPara: "Gata. Cererea de prietenie a ajuns la {{nome}}.",
    outrosLugares: "Alte locuri unde poți lega prietenii",
    outrosLugaresDetalhe: "Nu-ți vine nimeni în minte? Aruncă un ochi pe comunitățile deschise, se vorbește acolo despre aproape orice.",
    explorarComunidades: "Explorează comunitățile",
    titulo: "Adaugă un prieten",
    detalhe: "Poți adăuga prieteni după numele lor de utilizator.",
    exemplo: "Nume de utilizator, ex.: thiago",
    enviando: "Trimit…",
    enviar: "Trimite cererea",
  },
  gatinhoChorando: "Un pisoi care plânge",
  status: {
    emChamada: "Într-un apel",
    emVoz: "În voce",
  },
  menu: {
    chamada: "Începe un apel",
    fixar: "Fixează în partea de sus",
    desafixar: "Anulează fixarea",
    silenciar: "Dezactivează sunetul conversației",
    reativar: "Reactivează notificările",
    copiarIdDoCanal: "Copiază ID-ul canalului",
  },
  ativosAgora: "Activi acum",
  procurando: "Vedem cine e pe aici…",
  tudoTranquilo: "Deocamdată e liniște…",
  tudoTranquiloDetalhe: "Când tu sau un prieten intrați într-un apel, apare aici — și te alături cu un clic.",
  emVoz: "În vocal",
  voce: "Tu",
  soVoce: "Doar tu",
  pessoas: "{{quantas}} persoane",
  voltarParaChamada: "Înapoi la apel",
  entrarNaChamada: "Intră în apel",
  abrirCanal: "Deschide {{canal}} pe {{servidor}}",
  encontreConversa: "Găsește o conversație",
  amigos: "Prieteni",
  conversas: "Conversații",
  semConversas: "Încă nicio conversație. Adaugă un prieten ca să începi.",
  semConversaComEsseNome: "Nicio conversație cu numele acesta.",
  abrirMenu: "Deschide serverele și conversațiile",
  solicitacoes: "Cereri de mesaj",
  pedidos: "Cereri",
  spam: "Spam",
  pedidosPendentes: "Cereri în așteptare",
  marcadosComoSpam: "Marcate ca spam",
  aceitar: "Acceptă",
  ignorar: "Ignoră",
  marcarSpam: "Marchează ca spam",
  semPedidos: "Nicio cerere în așteptare.",
  semPedidosDetalhe: "Cine nu îți e prieten, dar are un server în comun cu tine, ajunge aici înainte să ajungă în conversațiile tale.",
  semSpam: "Nimic marcat ca spam.",
  semSpamDetalhe: "Ce separă filtrul de spam, sau ce marchezi tu, rămâne în această filă.",
  umServidorEmComum: "1 server în comun",
  servidoresEmComum: "{{quantos}} servere în comun",
  semServidoresEmComum: "Niciun server în comun",
};
