export const comum = {
  voltar: "Înapoi",
  agoraNao: "Nu acum",
  erro: {
    tentarDeNovo: "Încearcă din nou",
    recarregar: "Reîncarcă",
    copiarDetalhes: "Copiază detaliile",
    parteQuebrou: "Partea asta a ecranului s-a stricat.",
    titulo: "Ravox Chat s-a împiedicat.",
    detalhe: "Ceva s-a stricat pe drum și ecranul n-a reușit să se deseneze. Conversația ta nu s-a pierdut — totul e pe server.",
  },
  perdido: {
    titulo: "Adresa asta nu duce nicăieri.",
    detalhe: "Ori linkul e greșit, ori pagina s-a mutat.",
  },
  conexao: {
    voltou: "Conectat din nou",
    reconectando: "Mă reconectez",
    tentativaSufixo: " · încercarea {{numero}}",
    aSalvo: "Conversația e în siguranță pe server. Totul revine singur imediat ce se întoarce conexiunea.",
  },
  avisoDoNavegador: {
    titulo: "Vrei să fii anunțat de mesaje?",
    detalhe: "Cu Ravox Chat în spatele altei ferestre, el te strigă.",
  },
  atualizacao: {
    titulo: "Actualizare",
    semAuto: "Această versiune a aplicației nu știe să se actualizeze singură. Descarcă mai jos cel mai nou program de instalare și instalează-l peste.",
    versaoAtual: "Ești pe versiunea {{versao}}.",
    instalando: "Se instalează versiunea {{versao}}…",
    prontaVersao: "Versiunea {{versao}} e gata de instalare",
    baixandoVersao: "Se descarcă versiunea {{versao}}…",
    baixandoComProgresso: "Se descarcă versiunea {{versao}}… {{porcento}}%",
    saiuVersao: "A ieșit versiunea {{versao}}",
    saiuVersaoClique: "A ieșit versiunea {{versao}} — dă clic ca să o descarci",
    instalarVersaoEReiniciar: "Instalează versiunea {{versao}} și repornește",
    erroTenteDeNovo: "{{erro}} Dă clic ca să încerci din nou.",
    procurando: "Caut…",
    emDia: "Ești la zi",
    vaiFechar: "Aplicația se închide într-o clipă.",
    comoInstala: "Aplicația se închide, schimbă versiunea și se redeschide singură. Dacă ești într-un apel, ieși din el.",
    semServidor: "N-am reușit să ajung la serverul de versiuni.",
    procuraSozinho: "Aplicația caută singură la pornire și o dată la șase ore.",
    instalandoReticencias: "Se instalează…",
    instalandoCurto: "Se instalează",
    baixandoCurto: "Se descarcă",
    tentarDeNovo: "Încearcă din nou",
    reiniciarAgora: "Repornește acum",
    instalarEReiniciar: "Instalează și repornește",
    baixar: "Descarcă",
    procurar: "Verifică",
    baixarApp: "Descarcă aplicația",
    ariaBotao: "Actualizarea aplicației",
  },
  janela: {
    ajustarAltura: "Ajustează înălțimea",
    redimensionar: "Redimensionează fereastra",
    ajustarLargura: "Ajustează lățimea",
  },
  dica: {
    rotulo: "Sfat:",
    pularConfirmacao: "ține Shift apăsat când dai clic ca să sari peste confirmarea asta.",
  },
  cor: {
    pescar: "Ia o culoare de pe ecran",
    hex: "Valoare hexazecimală",
  },
  imagem: {
    titulo: "Alege o imagine",
    enviar: "Trimite o imagine",
    escolherGif: "Alege un GIF",
    buscarGif: "Caută GIF-uri",
  },
  fonte: {
    rotulo: "Fontul mesajului",
    padrao: "Implicit",
    comNome: "Fontul mesajului — {{fonte}}",
  },
  recorte: {
    titulo: "Decupează pictograma",
    detalhe: "Trage ca să alegi bucata și folosește cursorul ca să apropii. Pictograma e rotundă peste tot în aplicație.",
    voltarAoComeco: "Înapoi la început",
    usar: "Folosește acest decupaj",
  },
  mais: "Mai multe",
  carregando: "Se încarcă…",
  salvar: "Salvează",
  salvando: "Se salvează…",
  descartar: "Renunță",
  redefinir: "Resetează",
  naoSalvo: "Ai modificări nesalvate.",
  fechar: "Închide",
  criar: "Creează",
  nome: "Nume",
  emoji: "Emoji",
  previa: "Previzualizare",
  cancelar: "Anulează",
  enviar: "Trimite",
  apagar: "Șterge",
  excluir: "Șterge",
  remover: "Elimină",
  trocar: "Schimbă",
  loginNoApp: {
    titulo: "Totul e gata!",
    detalhe: "Te-ai conectat. Revino în Ravox Chat, aplicația te așteaptă deja.",
    abrir: "Deschide Ravox Chat",
    fecharAba: "Poți închide această filă.",
    falhouTitulo: "Conectarea nu a reușit",
    falhouDetalhe: "Revino în aplicație și încearcă din nou.",
    legenda: "Un robot care face cu mâna",
    legendaFalhou: "Un pisoi care plânge",
  },
  ads: {
    label: "Publicitate",
    title: "Fă reclamă aici",
    detail: "Vorbește cu noi și apari în fața celor care folosesc Ravox Chat.",
    action: "Vreau să fac reclamă",
  },
};
