export const configuracoes = {
  efeitos: {
    titulo: "Efectele indicatorului",
    detalhe: "Urmă și scântei desenate peste aplicație. Pornesc oprite și se sting singure dacă ai cerut mai puțină mișcare.",
    rastro: "Urma cursorului",
    rastroDetalhe: "O linie care urmează indicatorul și se stinge în spate.",
    faisca: "Scântei la clic",
    faiscaDetalhe: "Liniuțe care pornesc din locul unde ai dat clic.",
    cor: "Culoare",
    espessura: "Grosime",
    comprimento: "Lungime",
    tamanho: "Mărime",
    quantidade: "Câte",
  },
  email: {
    verificarTitulo: "Confirmă-ți e-mailul",
    verificarDetalhe: "Unele comunități lasă să scrie doar pe cei care au confirmat. E un clic.",
    enviar: "Trimite legătura",
    enviado: "Uită-te în inbox. Legătura ține o zi.",
    falhou: "E-mailul nu a putut fi trimis.",
    confirmado: "E-mail confirmat",
    confirmadoDetalhe: "Gata. Acum scrii în orice comunitate care cere asta.",
    linkIncompleto: "Legătură incompletă",
    linkIncompletoDetalhe: "Lipsește codul din adresă. Deschide legătura direct din e-mail.",
    confirmando: "Se confirmă…",
    expirou: "Această legătură a fost deja folosită sau a expirat.",
    irParaOApp: "Mergi la aplicație",
  },
  tema: {
    indisponivel: "Tema nu e disponibilă",
    indisponivelDetalhe: "Cine a publicat-o a șters-o, ori linkul e greșit.",
    indisponivelLinha: "Tema nu e disponibilă. Cine a publicat-o a șters-o, ori linkul e greșit.",
    importar: "Importă tema",
    importarCurto: "Importă",
    importarDetalhe: "Asta înlocuiește tema pe care o ai acum. O poți edita după aceea în Setări > Aspect > Studio de teme.",
    porAutor: "de {{autor}}",
    umaCorTrocada: "1 culoare schimbată",
    coresTrocadas: "{{quantas}} culori schimbate",
    avisoDeCss: "Tema asta vine cu CSS de la cine a scris-o, iar CSS-ul ajunge în orice colț al ecranului. Importă doar de la oameni în care ai încredere.",
    soCores: "Tema asta schimbă doar culori. Niciun CSS din afară.",
    verCss: "Vezi CSS-ul",
    esconderCss: "Ascunde CSS-ul",
    aplicar: "Aplică",
    previaSemMotor: "Previzualizarea nu rulează motorul. Instaleaz-o ca să-l vezi.",
    motorAnimado: "{{motor}} animat",
  },
  sair: "Deconectare",
  versoes: {
    termos: "Termenii serviciului",
    privacidade: "Politica de confidențialitate",
    copiar: "Dă clic ca să copiezi",
    copiado: "Copiat",
  },
  appColors: {
    title: "Culorile aplicației",
    detail: "Alege până la trei culori și toată aplicația primește acel degrade.",
    locked: "Editorul de culori face parte din {{plan}}.",
    color: "Culoarea {{number}}",
    addColor: "Adaugă culoare",
    removeColor: "Elimină culoarea",
    surprise: "Surprinde-mă",
    direction: "Direcția degradeului",
    intensity: "Intensitate",
    reset: "Resetează",
  },
  subscription: {
    colorsRow: "Editorul de culori al aplicației",
    seePlans: "Vezi planurile",
    upgradeSubtitle: "Limite mai mari și funcții exclusive pentru scris, trimis fișiere și transmis.",
    perMonth: "pe lună",
    perYear: "pe an",
    save: "Economisești {{percent}}%",
    howToPay: "Cum vrei să plătești?",
    legal: "Poți cere rambursarea în 7 zile de la plată. Plata este procesată de Stripe; nu vedem niciodată numărul cardului tău.",
    compare: "Gratuit vs. Infinity",
    featureColumn: "Funcție",
    freeColumn: "Gratuit",
    messageRow: "Limită de caractere pe mesaj",
    attachmentRow: "Mărimea fișierului trimis",
    screenRow: "Calitate video",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Ai deja Infinity până la {{date}}.",
    upsell: "Mărește limita cu Infinity",
    screenUpsell: "Calitate mai bună cu Infinity",
    free: "Folosești planul gratuit.",
    activeUntil: "Infinity activ până la {{date}}.",
    renews: "Se reînnoiește automat pe {{date}}.",
    endsAt: "Abonamentul a fost anulat și se încheie pe {{date}}.",
    pastDue: "Ultima plată a eșuat. Actualizează cardul ca să nu pierzi Infinity.",
    waiting: "Se confirmă plata…",
    subscribe: "Abonează-te",
    monthly: "Lunar",
    yearly: "Anual",
    automatic: "Card",
    manage: "Gestionează plata",
    refund: "Cere rambursare",
    refundDetail: "Poți renunța în 7 zile de la plată: {{amount}}, până la {{date}}.",
    refundConfirm: "Ceri rambursarea?",
    refundConfirmDetail: "Banii se întorc prin aceeași metodă de plată, iar Infinity se încheie imediat.",
    refunded: "Rambursare cerută.",
    unavailable: "Abonamentul nu este încă disponibil.",
    success: "Plată primită. Mulțumim!",
    canceled: "Plată anulată.",
    error: "Ceva n-a mers. Încearcă din nou.",
    no: "Nu",
    tagRow: "Etichetă de utilizator personalizată",
    guildProfilesRow: "Profiluri pe comunitate",
    badgeRow: "Insignă de profil",
    communitiesRow: "Comunități",
    savedRow: "Mesaje salvate",
    animatedEmojiRow: "Emoji animate",
    expressionsRow: "Emoji și stickere de oriunde",
    animatedProfileRow: "Avatare și bannere de profil animate",
    earlyAccessRow: "Acces timpuriu la noutăți",
    themesRow: "Teme personalizate",
    pixOption: "Pix",
    pixHint: "Deschide aplicația băncii, alege Pix și scanează codul QR sau folosește copiere și lipire.",
    pixQrAlt: "Cod QR Pix",
    pixCopy: "Copiază codul Pix",
    pixCopied: "Codul Pix a fost copiat",
    pixWaiting: "Se așteaptă plata",
    pixExpiresIn: "expiră în {{time}}",
    pixExpired: "Acest Pix a expirat. Generează altul ca să continui.",
    pixNew: "Generează alt Pix",
    pixPaid: "Pix primit! Infinity e activ.",
    forMe: "Pentru mine",
    asGift: "Cadou",
    buyGift: "Cumpără cadou",
    giftReady: "Cadoul e gata! Copiază linkul și trimite-l cui vrei.",
    giftClaimed: "Cadou revendicat! Infinity e în contul tău.",
    gifts: "Cadouri",
    giftsEmpty: "Încă nu ai cumpărat niciun cadou.",
    giftCode: "Codul cadoului",
    giftRedeem: "Revendică",
    giftCopyLink: "Copiază linkul",
    giftLinkCopied: "Link copiat",
    giftClaimedBy: "revendicat de {{name}}",
    giftHint: "Ai un cod cadou? Revendică-l aici. Cadourile cumpărate apar mai jos.",
    cardPaid: "Plată aprobată! Infinity e activ.",
    payAmount: "Plătește {{amount}}",
    giftLinkTitle: "Ai primit un cadou {{plan}}!",
    giftLinkDetail: "Atinge revendică și zilele ajung în contul tău.",
    pageTitle: "Deblochează o lume de avantaje cu {{plan}}",
    pageStart: "Acasă",
    pageBest: "Ce are Infinity mai bun",
    pageChoose: "Alege-ți planul",
    fromPrice: "De la {{amount}} pe lună. Anulezi când vrei.",
    filesTitle: "Trimite fișierul întreg",
    filesText: "Filmul de la petrecere, proiectul de la muncă, folderul cu poze: pleacă toate dintr-o dată, fără să le tai, fără să le arhivezi și fără link de cloud la mijloc.",
    videoTitle: "Transmite în 1080p",
    videoText: "Ecranul tău ajunge clar la cine se uită, cu de două ori mai multe cadre pe secundă. Se poate citi cod și juca împreună fără ca totul să devină o pată.",
    messageTitle: "Scrie în voie",
    messageText: "De două ori mai multe caractere în fiecare mesaj, pentru când povestea e lungă, iar ruptă în trei și-ar pierde tot hazul.",
    colorsTitle: "Aplicația cu chipul tău",
    colorsText: "Alege culorile aplicației una câte una, salvează tema și ia-o cu tine pe toate dispozitivele pe care intri.",
    profileTitle: "Un profil pentru fiecare loc",
    profileText: "Alt nume, altă poză, altă descriere în fiecare comunitate — și poză animată, dacă vrei.",
    freeDetail: "E gratis și așa rămâne.",
    currentPlan: "Planul tău actual",
    popular: "Cel mai ales",
    yearlyDetail: "Iese {{amount}} pe lună, taxat o dată pe an.",
    monthlyDetail: "Taxat în fiecare lună, anulezi când vrei.",
    groupStyle: "Arată-ți stilul",
    groupLook: "Fă aplicația pe gustul tău",
    groupLimits: "Fără limite strâmte",
    closingTitle: "Ce mai aștepți?",
    pagePlans: "Planuri",
    pageCompare: "Compară",
    giftClaimTitle: "Activezi {{plan}}?",
    giftClaimDetail: "Sunt {{days}} de zile care intră acum în contul tău.",
    giftFrom: "de la {{name}}",
    giftActivate: "Activează",
    giftHasPlanTitle: "Ai deja Infinity",
    giftHasPlanDetail: "Planul tău ține până la {{date}}. Păstrează linkul și trimite-l unui prieten.",
    giftUsedTitle: "Cadoul a fost deja folosit",
    giftUsedDetail: "Cineva a revendicat codul înainte. Cere altul.",
    giftNotFoundTitle: "Cod negăsit",
    giftNotFoundDetail: "Verifică codul sau cere linkul din nou.",
    giftDoneTitle: "{{plan}} activat!",
    giftOpenApp: "Deschide aplicația",
    giftSignIn: "Conectează-te ca să revendici",
    giftReviewStep: "Plată · Verificare",
    giftTotalToday: "Total azi",
    giftCardWhy: "Cardul e doar ca să confirmăm că ești tu. Nu se percepe nimic acum și nimic nu se reînnoiește singur.",
    giftAgree: "Am citit și accept termenii de utilizare",
    giftActivating: "Se activează…",
  },
  telas: {
    subscription: "Infinity",
    conta: "Contul meu",
    privacidade: "Confidențialitate",
    conexoes: "Conexiuni",
    voz: "Audio",
    video: "Video",
    avisos: "Notificări",
    aplicativos: "Aplicații",
    aparencia: "Aspect",
    batePapo: "Chat",
    acessibilidade: "Accesibilitate",
    idioma: "Limbă",
    aplicativo: "Descarcă aplicația",
    atalhos: "Scurtături",
    desktop: "Aplicație desktop",
    avancado: "Avansat",
    servidor: "Server",
    comunicado: "Anunț de sistem",
    denuncias: "Raportări",
    publicacoes: "Implementări",
  },
  grupos: {
    conta: "Cont",
    app: "Setările aplicației",
    desenvolvedor: "Dezvoltator",
    administracao: "Administrare",
  },
  secoes: {
    coresDoApp: "Culorile aplicației",
    detalhesDeLogin: "Date de conectare",
    dispositivos: "Dispozitive",
    usuariosBloqueados: "Utilizatori blocați",
    aplicativosAutorizados: "Aplicații autorizate",
    sessoes: "Sesiuni",
    amigosEDms: "Prieteni și mesaje directe",
    compartilhamentoDeAtividade: "Partajarea activității",
    visibilidadeDoPerfil: "Vizibilitatea profilului",
    exportarDados: "Exportă datele",
    exclusaoDeDados: "Șterge datele",
    tema: "Temă",
    corDeDestaque: "Culoare de accent",
    interface: "Interfață",
    listaDeCanais: "Lista de canale",
    zoomDoApp: "Nivel de zoom al aplicației",
    escalaDaFonte: "Scara fontului din chat",
    modoStreamer: "Confidențialitate la transmisiune",
    cursores: "Cursoare",
    movimento: "Mișcare",
    textoEmVoz: "Text în vorbire",
    teclado: "Tastatură",
    formatoDaHora: "Formatul orei",
    idiomaDaInterface: "Limba interfeței",
    dispositivosDeVoz: "Dispozitive",
    testeDoMicrofone: "Testul microfonului",
    modoDeEntrada: "Mod de intrare",
    sensibilidade: "Sensibilitatea intrării",
    qualidade: "Calitate",
    camera: "Cameră",
    transmissao: "Transmisiune",
    exibicao: "Afișare",
    entrada: "Introducere",
    midia: "Media",
    geral: "General",
    preferenciaDeMencao: "Preferință de menționare",
    sons: "Sunete",
  },
};
