export const amizades = {
  mensagensDiretas: "Direkte beskeder",
  nova: {
    titulo: "Ny samtale",
    detalhe: "Vælg en ven, så åbner samtalen.",
    procurar: "Find en ven",
    semAmigos: "Du har ingen venner her endnu.",
    semResultado: "Ingen ven med det navn.",
  },
  adicionar: {
    recado: "Skriv et par ord (valgfrit)",
    recadoDica: "Det du skriver her, dukker også op i jeres samtale, hvis I bliver venner.",
    enviadoPara: "Sådan! Venneanmodningen røg af sted til {{nome}}.",
    outrosLugares: "Andre steder at møde folk",
    outrosLugaresDetalhe: "Kan du ikke komme på nogen? Kig på de åbne fællesskaber, der snakkes om næsten alt.",
    explorarComunidades: "Udforsk fællesskaber",
    titulo: "Tilføj ven",
    detalhe: "Du kan tilføje venner ved hjælp af deres brugernavn.",
    exemplo: "Brugernavn, fx: thiago",
    enviando: "Sender…",
    enviar: "Send anmodning",
  },
  gatinhoChorando: "En grædende killing",
  status: {
    emChamada: "I et opkald",
    emVoz: "I tale",
  },
  menu: {
    chamada: "Start et opkald",
    fixar: "Fastgør øverst",
    desafixar: "Frigør",
    silenciar: "Slå samtalen fra",
    reativar: "Slå notifikationer til igen",
    copiarIdDoCanal: "Kopiér kanalens ID",
  },
  ativosAgora: "Aktive nu",
  procurando: "Ser efter hvem der er her…",
  tudoTranquilo: "Der er stille lige nu…",
  tudoTranquiloDetalhe: "Når du eller en ven går ind i et opkald, dukker det op her — og du kan hoppe med i ét klik.",
  emVoz: "I tale",
  voce: "Dig",
  soVoce: "Kun dig",
  pessoas: "{{quantas}} personer",
  voltarParaChamada: "Tilbage til opkaldet",
  entrarNaChamada: "Deltag i opkaldet",
  abrirCanal: "Åbn {{canal}} på {{servidor}}",
  encontreConversa: "Find en samtale",
  amigos: "Venner",
  conversas: "Samtaler",
  semConversas: "Ingen samtaler endnu. Tilføj en ven for at komme i gang.",
  semConversaComEsseNome: "Ingen samtale med det navn.",
  abrirMenu: "Åbn servere og samtaler",
  solicitacoes: "Beskedanmodninger",
  pedidos: "Anmodninger",
  spam: "Spam",
  pedidosPendentes: "Ventende anmodninger",
  marcadosComoSpam: "Markeret som spam",
  aceitar: "Accepter",
  ignorar: "Ignorer",
  marcarSpam: "Markér som spam",
  semPedidos: "Ingen anmodninger venter.",
  semPedidosDetalhe: "Den der ikke er din ven, men deler en server med dig, lander her, før det når dine samtaler.",
  semSpam: "Intet markeret som spam.",
  semSpamDetalhe: "Det spamfilteret sorterer fra, eller det du selv markerer, bliver i denne fane.",
  umServidorEmComum: "1 fælles server",
  servidoresEmComum: "{{quantos}} fælles servere",
  semServidoresEmComum: "Ingen fælles servere",
};
