export const comum = {
  voltar: "Tilbage",
  agoraNao: "Ikke nu",
  erro: {
    tentarDeNovo: "Prøv igen",
    recarregar: "Genindlæs",
    copiarDetalhes: "Kopiér detaljer",
    parteQuebrou: "Denne del af skærmen gik i stykker.",
    titulo: "Ravox Chat snublede.",
    detalhe: "Noget gik i stykker undervejs, og skærmen kunne ikke tegne sig selv. Din samtale er ikke tabt — det hele ligger på serveren.",
  },
  perdido: {
    titulo: "Den her adresse fører ingen steder hen.",
    detalhe: "Enten er linket forkert, eller også er siden flyttet.",
  },
  conexao: {
    voltou: "Forbundet igen",
    reconectando: "Forbinder igen",
    tentativaSufixo: " · forsøg {{numero}}",
    aSalvo: "Samtalen ligger sikkert på serveren. Det kommer af sig selv, så snart forbindelsen er tilbage.",
  },
  avisoDoNavegador: {
    titulo: "Vil du have besked om beskeder?",
    detalhe: "Når Ravox Chat ligger bag et andet vindue, giver den lyd fra sig.",
  },
  atualizacao: {
    titulo: "Opdatering",
    semAuto: "Denne version af appen kan ikke opdatere sig selv. Hent det nyeste installationsprogram nedenfor, og installér oven i.",
    versaoAtual: "Du har version {{versao}}.",
    instalando: "Installerer version {{versao}}…",
    prontaVersao: "Version {{versao}} er klar til installation",
    baixandoVersao: "Henter version {{versao}}…",
    baixandoComProgresso: "Henter version {{versao}}… {{porcento}} %",
    saiuVersao: "Version {{versao}} er kommet",
    saiuVersaoClique: "Version {{versao}} er kommet — klik for at hente",
    instalarVersaoEReiniciar: "Installér version {{versao}} og genstart",
    erroTenteDeNovo: "{{erro}} Klik for at prøve igen.",
    procurando: "Leder…",
    emDia: "Du er helt opdateret",
    vaiFechar: "Appen lukker om et øjeblik.",
    comoInstala: "Appen lukker, skifter version og åbner igen af sig selv. Er du i et opkald, forlader du det.",
    semServidor: "Jeg kunne ikke få fat i versionsserveren.",
    procuraSozinho: "Appen leder selv ved opstart og hver sjette time.",
    instalandoReticencias: "Installerer…",
    instalandoCurto: "Installerer",
    baixandoCurto: "Henter",
    tentarDeNovo: "Prøv igen",
    reiniciarAgora: "Genstart nu",
    instalarEReiniciar: "Installér og genstart",
    baixar: "Hent",
    procurar: "Søg efter opdatering",
    baixarApp: "Hent appen",
    ariaBotao: "Opdatering af appen",
  },
  janela: {
    ajustarAltura: "Juster højden",
    redimensionar: "Tilpas vinduets størrelse",
    ajustarLargura: "Juster bredden",
  },
  dica: {
    rotulo: "Tip:",
    pularConfirmacao: "hold Shift nede, når du klikker, for at springe denne bekræftelse over.",
  },
  cor: {
    pescar: "Hent en farve fra skærmen",
    hex: "Hexadecimal værdi",
  },
  imagem: {
    titulo: "Vælg et billede",
    enviar: "Send billede",
    escolherGif: "Vælg GIF",
    buscarGif: "Søg efter GIF",
  },
  fonte: {
    rotulo: "Beskedens skrifttype",
    padrao: "Standard",
    comNome: "Beskedens skrifttype — {{fonte}}",
  },
  recorte: {
    titulo: "Beskær ikonet",
    detalhe: "Træk for at vælge udsnittet, og brug skyderen til at zoome. Ikonet er rundt overalt i appen.",
    voltarAoComeco: "Tilbage til start",
    usar: "Brug dette udsnit",
  },
  mais: "Mere",
  carregando: "Indlæser…",
  salvar: "Gem",
  salvando: "Gemmer…",
  descartar: "Kassér",
  redefinir: "Nulstil",
  naoSalvo: "Du har ugemte ændringer.",
  fechar: "Luk",
  criar: "Opret",
  nome: "Navn",
  emoji: "Emoji",
  previa: "Forhåndsvisning",
  cancelar: "Annuller",
  enviar: "Send",
  apagar: "Slet",
  excluir: "Slet",
  remover: "Fjern",
  trocar: "Skift",
  loginNoApp: {
    titulo: "Alt er klar!",
    detalhe: "Du er logget ind. Gå tilbage til Ravox Chat, appen venter på dig.",
    abrir: "Åbn Ravox Chat",
    fecharAba: "Du kan lukke denne fane nu.",
    falhouTitulo: "Login mislykkedes",
    falhouDetalhe: "Gå tilbage til appen og prøv at logge ind igen.",
    legenda: "En robot der vinker",
    legendaFalhou: "En grædende killing",
  },
  ads: {
    label: "Annonce",
    title: "Annoncér her",
    detail: "Tal med os, og bliv set af dem, der bruger Ravox Chat.",
    action: "Jeg vil annoncere",
  },
};
