export const amizades = {
  mensagensDiretas: "Mensajes directos",
  nova: {
    titulo: "Charla nueva",
    detalhe: "Elige un amigo y la charla se abre.",
    procurar: "Buscar un amigo",
    semAmigos: "Aún no tienes amigos por aquí.",
    semResultado: "Ningún amigo con ese nombre.",
  },
  adicionar: {
    recado: "Escribe un mensajito (opcional)",
    recadoDica: "Lo que escribas aquí también aparece en vuestra charla, si os hacéis amigos.",
    enviadoPara: "¡Listo! La solicitud de amistad le ha llegado a {{nome}}.",
    outrosLugares: "Otros lugares para hacer amigos",
    outrosLugaresDetalhe: "¿No se te ocurre nadie? Mira las comunidades abiertas, allí se habla de casi todo.",
    explorarComunidades: "Explorar comunidades",
    titulo: "Añadir amigo",
    detalhe: "Puedes añadir amigos por su nombre de usuario.",
    exemplo: "Nombre de usuario, p. ej.: thiago",
    enviando: "Enviando…",
    enviar: "Enviar solicitud",
  },
  gatinhoChorando: "Un gatito llorando",
  status: {
    emChamada: "En una llamada",
    emVoz: "En voz",
  },
  menu: {
    chamada: "Iniciar llamada",
    fixar: "Fijar arriba",
    desafixar: "Dejar de fijar",
    silenciar: "Silenciar conversación",
    reativar: "Reactivar los avisos",
    copiarIdDoCanal: "Copiar el ID del canal",
  },
  ativosAgora: "Activo ahora",
  procurando: "Viendo quién anda por ahí…",
  tudoTranquilo: "Todo tranquilo por ahora…",
  tudoTranquiloDetalhe: "Cuando tú o un amigo entréis en una llamada, aparecerá aquí — y podrás unirte con un clic.",
  emVoz: "En voz",
  voce: "Tú",
  soVoce: "Solo tú",
  pessoas: "{{quantas}} personas",
  voltarParaChamada: "Volver a la llamada",
  entrarNaChamada: "Unirse a la llamada",
  abrirCanal: "Abrir {{canal}} en {{servidor}}",
  encontreConversa: "Busca una conversación",
  amigos: "Amigos",
  conversas: "Conversaciones",
  semConversas: "Todavía no hay conversaciones. Añade un amigo para empezar.",
  semConversaComEsseNome: "Ninguna conversación con ese nombre.",
  abrirMenu: "Abrir servidores y conversaciones",
  solicitacoes: "Solicitudes de mensajes",
  pedidos: "Solicitudes",
  spam: "Spam",
  pedidosPendentes: "Solicitudes pendientes",
  marcadosComoSpam: "Marcados como spam",
  aceitar: "Aceptar",
  ignorar: "Ignorar",
  marcarSpam: "Marcar como spam",
  semPedidos: "Ninguna solicitud esperando.",
  semPedidosDetalhe: "Quien no es tu amigo pero comparte un servidor contigo llega aquí antes de entrar en tus conversaciones.",
  semSpam: "Nada marcado como spam.",
  semSpamDetalhe: "Lo que el filtro de spam aparte, o lo que tú marques, se guarda en esta pestaña.",
  umServidorEmComum: "1 servidor en común",
  servidoresEmComum: "{{quantos}} servidores en común",
  semServidoresEmComum: "Sin servidores en común",
};
