export const comum = {
  voltar: "Volver",
  agoraNao: "Ahora no",
  erro: {
    tentarDeNovo: "Intentar de nuevo",
    recarregar: "Recargar",
    copiarDetalhes: "Copiar los detalles",
    parteQuebrou: "Esta parte de la pantalla se ha roto.",
    titulo: "Ravox Chat ha tropezado.",
    detalhe: "Algo se rompió por el camino y la pantalla no pudo dibujarse. Tu conversación no se ha perdido — está todo en el servidor.",
  },
  perdido: {
    titulo: "Esta dirección no lleva a ninguna parte.",
    detalhe: "O el enlace vino mal, o la página cambió de sitio.",
  },
  conexao: {
    voltou: "Conectado de nuevo",
    reconectando: "Reconectando",
    tentativaSufixo: " · intento {{numero}}",
    aSalvo: "La conversación está a salvo en el servidor. Esto vuelve solo en cuanto regrese la conexión.",
  },
  avisoDoNavegador: {
    titulo: "¿Quieres que te avise de los mensajes?",
    detalhe: "Con Ravox Chat detrás de otra ventana, te llama.",
  },
  atualizacao: {
    titulo: "Actualización",
    semAuto: "Esta versión de la aplicación no sabe actualizarse sola. Descarga el instalador más nuevo de abajo e instálalo encima.",
    versaoAtual: "Estás en la versión {{versao}}.",
    instalando: "Instalando la versión {{versao}}…",
    prontaVersao: "La versión {{versao}} está lista para instalar",
    baixandoVersao: "Descargando la versión {{versao}}…",
    baixandoComProgresso: "Descargando la versión {{versao}}… {{porcento}} %",
    saiuVersao: "Ha salido la versión {{versao}}",
    saiuVersaoClique: "Ha salido la versión {{versao}} — haz clic para descargar",
    instalarVersaoEReiniciar: "Instalar la versión {{versao}} y reiniciar",
    erroTenteDeNovo: "{{erro}} Haz clic para intentarlo de nuevo.",
    procurando: "Buscando…",
    emDia: "Estás al día",
    vaiFechar: "La aplicación se cerrará en un momento.",
    comoInstala: "La aplicación se cierra, cambia la versión y vuelve a abrirse sola. Si estás en una llamada, saldrás de ella.",
    semServidor: "No he podido hablar con el servidor de versiones.",
    procuraSozinho: "La aplicación busca sola al abrirse y cada seis horas.",
    instalandoReticencias: "Instalando…",
    instalandoCurto: "Instalando",
    baixandoCurto: "Descargando",
    tentarDeNovo: "Intentar de nuevo",
    reiniciarAgora: "Reiniciar ahora",
    instalarEReiniciar: "Instalar y reiniciar",
    baixar: "Descargar",
    procurar: "Buscar",
    baixarApp: "Descargar la aplicación",
    ariaBotao: "Actualización de la aplicación",
  },
  janela: {
    ajustarAltura: "Ajustar el alto",
    redimensionar: "Cambiar el tamaño de la ventana",
    ajustarLargura: "Ajustar el ancho",
  },
  dica: {
    rotulo: "Consejo:",
    pularConfirmacao: "mantén Shift al hacer clic para saltarte esta confirmación.",
  },
  cor: {
    pescar: "Tomar un color de la pantalla",
    hex: "Valor hexadecimal",
  },
  imagem: {
    titulo: "Elige una imagen",
    enviar: "Enviar imagen",
    escolherGif: "Elegir GIF",
    buscarGif: "Buscar GIF",
  },
  fonte: {
    rotulo: "Fuente del mensaje",
    padrao: "Predeterminada",
    comNome: "Fuente del mensaje — {{fonte}}",
  },
  recorte: {
    titulo: "Recortar el icono",
    detalhe: "Arrastra para elegir el trozo y usa la barra para acercar. El icono queda redondo en toda la aplicación.",
    voltarAoComeco: "Volver al principio",
    usar: "Usar este recorte",
  },
  mais: "Más",
  carregando: "Cargando…",
  salvar: "Guardar",
  salvando: "Guardando…",
  descartar: "Descartar",
  redefinir: "Restablecer",
  naoSalvo: "Tienes cambios sin guardar.",
  fechar: "Cerrar",
  criar: "Crear",
  nome: "Nombre",
  emoji: "Emoji",
  previa: "Vista previa",
  cancelar: "Cancelar",
  enviar: "Enviar",
  apagar: "Borrar",
  excluir: "Eliminar",
  remover: "Quitar",
  trocar: "Cambiar",
  loginNoApp: {
    titulo: "¡Todo listo!",
    detalhe: "Has iniciado sesión. Vuelve a Ravox Chat, la aplicación ya te está esperando.",
    abrir: "Abrir Ravox Chat",
    fecharAba: "Ya puedes cerrar esta pestaña.",
    falhouTitulo: "No se pudo iniciar sesión",
    falhouDetalhe: "Vuelve a la aplicación e inténtalo de nuevo.",
    legenda: "Un robot saludando",
    legendaFalhou: "Un gatito llorando",
  },
  ads: {
    label: "Publicidad",
    title: "Anúnciate aquí",
    detail: "Habla con nosotros y aparece ante quien usa Ravox Chat.",
    action: "Quiero anunciarme",
  },
};
