export const configuracoes = {
  efeitos: {
    titulo: "Efectos del puntero",
    detalhe: "Rastro y chispas dibujados encima de la aplicación. Vienen apagados y se apagan solos si pediste menos animación.",
    rastro: "Rastro del cursor",
    rastroDetalhe: "Una línea que sigue al puntero y se va borrando detrás.",
    faisca: "Chispa al hacer clic",
    faiscaDetalhe: "Líneas cortas que salen del punto donde has hecho clic.",
    cor: "Color",
    espessura: "Grosor",
    comprimento: "Largo",
    tamanho: "Tamaño",
    quantidade: "Cantidad",
  },
  email: {
    verificarTitulo: "Confirma tu correo",
    verificarDetalhe: "Algunas comunidades solo dejan escribir a quien lo ha confirmado. Es un clic.",
    enviar: "Enviar el enlace",
    enviado: "Mira la bandeja de entrada. El enlace dura un día.",
    falhou: "No se ha podido enviar el correo.",
    confirmado: "Correo confirmado",
    confirmadoDetalhe: "Listo. Ya escribes en cualquier comunidad que lo pida.",
    linkIncompleto: "Enlace incompleto",
    linkIncompletoDetalhe: "Falta el código en la dirección. Abre el enlace directo del correo.",
    confirmando: "Confirmando…",
    expirou: "Este enlace ya se ha usado o ha caducado.",
    irParaOApp: "Ir a la aplicación",
  },
  tema: {
    indisponivel: "Tema no disponible",
    indisponivelDetalhe: "Quien lo publicó lo borró, o el enlace está mal.",
    indisponivelLinha: "Tema no disponible. Quien lo publicó lo borró, o el enlace está mal.",
    importar: "Importar tema",
    importarCurto: "Importar",
    importarDetalhe: "Esto sustituye el tema que tienes ahora. Puedes editarlo después en Ajustes > Apariencia > Estudio de temas.",
    porAutor: "por {{autor}}",
    umaCorTrocada: "1 color cambiado",
    coresTrocadas: "{{quantas}} colores cambiados",
    avisoDeCss: "Este tema trae CSS de quien lo escribió, y el CSS toca cualquier rincón de la pantalla. Impórtalo solo de gente en la que confíes.",
    soCores: "Este tema solo cambia colores. Nada de CSS de fuera.",
    verCss: "Ver el CSS",
    esconderCss: "Ocultar el CSS",
    aplicar: "Aplicar",
    previaSemMotor: "La vista previa no ejecuta el motor. Instálalo para verlo.",
    motorAnimado: "{{motor}} animado",
  },
  sair: "Cerrar sesión",
  versoes: {
    termos: "Términos del servicio",
    privacidade: "Política de privacidad",
    copiar: "Haz clic para copiar",
    copiado: "Copiado",
  },
  appColors: {
    title: "Colores de la app",
    detail: "Elige hasta tres colores y toda la app toma ese degradado.",
    locked: "El editor de colores es de {{plan}}.",
    color: "Color {{number}}",
    addColor: "Añadir color",
    removeColor: "Quitar color",
    surprise: "Sorpréndeme",
    direction: "Dirección del degradado",
    intensity: "Intensidad",
    reset: "Restablecer",
  },
  subscription: {
    colorsRow: "Editor de colores de la app",
    seePlans: "Ver planes",
    upgradeSubtitle: "Límites más altos y funciones exclusivas para escribir, enviar archivos y transmitir.",
    perMonth: "al mes",
    perYear: "al año",
    save: "Ahorra un {{percent}}%",
    howToPay: "¿Cómo quieres pagar?",
    legal: "Puedes pedir un reembolso hasta 7 días después del pago. El pago lo procesa Stripe; nunca vemos el número de tu tarjeta.",
    compare: "Gratis vs. Infinity",
    featureColumn: "Función",
    freeColumn: "Gratis",
    messageRow: "Límite de caracteres del mensaje",
    attachmentRow: "Tamaño de archivo para enviar",
    screenRow: "Calidad de vídeo",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Ya tienes Infinity hasta el {{date}}.",
    upsell: "Aumentar el límite con Infinity",
    screenUpsell: "Más calidad con Infinity",
    free: "Estás en el plan gratuito.",
    activeUntil: "Infinity activo hasta el {{date}}.",
    renews: "Se renueva automáticamente el {{date}}.",
    endsAt: "La suscripción se canceló y termina el {{date}}.",
    pastDue: "Falló el último cobro. Actualiza la tarjeta para no perder el Infinity.",
    waiting: "Confirmando el pago…",
    subscribe: "Suscribirse",
    monthly: "Mensual",
    yearly: "Anual",
    automatic: "Tarjeta",
    manage: "Gestionar el pago",
    refund: "Pedir reembolso",
    refundDetail: "Puedes desistir hasta 7 días después del pago: {{amount}}, hasta el {{date}}.",
    refundConfirm: "¿Pedir el reembolso?",
    refundConfirmDetail: "El dinero vuelve al mismo medio de pago y el Infinity termina en el acto.",
    refunded: "Reembolso solicitado.",
    unavailable: "La suscripción aún no está disponible.",
    success: "Pago recibido. ¡Gracias!",
    canceled: "Pago cancelado.",
    error: "Algo salió mal. Inténtalo de nuevo.",
    no: "No",
    tagRow: "Etiqueta de usuario personalizada",
    guildProfilesRow: "Perfiles por comunidad",
    badgeRow: "Insignia del perfil",
    communitiesRow: "Comunidades",
    savedRow: "Mensajes guardados",
    animatedEmojiRow: "Usar emojis animados",
    expressionsRow: "Acceso global a emojis y stickers",
    animatedProfileRow: "Avatares y banners de perfil animados",
    earlyAccessRow: "Acceso anticipado a novedades",
    themesRow: "Temas personalizados",
    pixOption: "Pix",
    pixHint: "Abre la app de tu banco, elige Pix y escanea el código QR o usa copiar y pegar.",
    pixQrAlt: "Código QR de Pix",
    pixCopy: "Copiar código Pix",
    pixCopied: "Código Pix copiado",
    pixWaiting: "Esperando el pago",
    pixExpiresIn: "vence en {{time}}",
    pixExpired: "Este Pix ha vencido. Genera otro para continuar.",
    pixNew: "Generar otro Pix",
    pixPaid: "¡Pix recibido! Tu Infinity ya está activo.",
    forMe: "Para mí",
    asGift: "De regalo",
    buyGift: "Comprar regalo",
    giftReady: "¡Regalo listo! Copia el enlace y envíalo a quien quieras.",
    giftClaimed: "¡Regalo canjeado! Infinity ya está en tu cuenta.",
    gifts: "Regalos",
    giftsEmpty: "Todavía no has comprado ningún regalo.",
    giftCode: "Código del regalo",
    giftRedeem: "Canjear",
    giftCopyLink: "Copiar enlace",
    giftLinkCopied: "Enlace copiado",
    giftClaimedBy: "canjeado por {{name}}",
    giftHint: "¿Tienes un código de regalo? Cánjealo aquí. Abajo aparecen los regalos que compraste.",
    cardPaid: "¡Pago aprobado! Tu Infinity ya está activo.",
    payAmount: "Pagar {{amount}}",
    giftLinkTitle: "¡Has recibido un regalo de {{plan}}!",
    giftLinkDetail: "Toca canjear y los días entran en tu cuenta.",
    pageTitle: "Desbloquea un mundo de ventajas con {{plan}}",
    pageStart: "Inicio",
    pageBest: "Lo mejor de Infinity",
    pageChoose: "Elige tu plan",
    fromPrice: "Desde {{amount}} al mes. Cancela cuando quieras.",
    filesTitle: "Envía el archivo entero",
    filesText: "El vídeo de la fiesta, el proyecto del trabajo, la carpeta con las fotos: va todo de una vez, sin cortar, sin comprimir y sin enlace de nube por medio.",
    videoTitle: "Transmite en 1080p",
    videoText: "Tu pantalla llega nítida al otro lado, con el doble de fotogramas por segundo. Se puede leer código y jugar juntos sin que todo se vuelva un borrón.",
    messageTitle: "Escribe a gusto",
    messageText: "El doble de caracteres en cada mensaje, para cuando la historia es larga y partirla en tres le quitaría la gracia.",
    colorsTitle: "La app con tu sello",
    colorsText: "Elige los colores de la aplicación uno a uno, guarda el tema y llévatelo a todos los dispositivos donde entras.",
    profileTitle: "Un perfil para cada sitio",
    profileText: "Otro apodo, otra foto, otra descripción en cada comunidad — y foto animada, si te apetece.",
    freeDetail: "Es gratis y lo seguirá siendo.",
    currentPlan: "Tu plan actual",
    popular: "El más elegido",
    yearlyDetail: "Sale a {{amount}} al mes, con un cobro una vez al año.",
    monthlyDetail: "Se cobra cada mes, cancela cuando quieras.",
    groupStyle: "Enseña tu estilo",
    groupLook: "Deja la app a tu gusto",
    groupLimits: "Sin límites estrechos",
    closingTitle: "¿A qué estás esperando?",
    pagePlans: "Planes",
    pageCompare: "Comparar",
    giftClaimTitle: "¿Activar {{plan}}?",
    giftClaimDetail: "Son {{days}} días que entran en tu cuenta ahora.",
    giftFrom: "de {{name}}",
    giftActivate: "Activar",
    giftHasPlanTitle: "Ya tienes Infinity",
    giftHasPlanDetail: "Tu plan vale hasta el {{date}}. Guarda el enlace y mándaselo a un amigo.",
    giftUsedTitle: "Este regalo ya se usó",
    giftUsedDetail: "Alguien canjeó este código antes. Pide otro.",
    giftNotFoundTitle: "Código no encontrado",
    giftNotFoundDetail: "Revisa el código o pide el enlace otra vez.",
    giftDoneTitle: "¡{{plan}} activado!",
    giftOpenApp: "Abrir la app",
    giftSignIn: "Inicia sesión para canjear",
    giftReviewStep: "Pago · Revisar",
    giftTotalToday: "Total de hoy",
    giftCardWhy: "La tarjeta es solo para confirmar que eres tú. No se cobra nada ahora ni se renueva solo.",
    giftAgree: "He leído y acepto los términos de uso",
    giftActivating: "Activando…",
  },
  telas: {
    subscription: "Infinity",
    conta: "Mi cuenta",
    privacidade: "Privacidad",
    conexoes: "Conexiones",
    voz: "Audio",
    video: "Vídeo",
    avisos: "Notificaciones",
    aplicativos: "Aplicaciones",
    aparencia: "Apariencia",
    batePapo: "Chat",
    acessibilidade: "Accesibilidad",
    idioma: "Idioma",
    aplicativo: "Descargar la app",
    atalhos: "Atajos",
    desktop: "App de escritorio",
    avancado: "Avanzado",
    servidor: "Servidor",
    comunicado: "Comunicado del sistema",
    denuncias: "Denuncias",
    publicacoes: "Despliegues",
  },
  grupos: {
    conta: "Cuenta",
    app: "Ajustes de la app",
    desenvolvedor: "Desarrollador",
    administracao: "Administración",
  },
  secoes: {
    coresDoApp: "Colores de la app",
    detalhesDeLogin: "Datos de acceso",
    dispositivos: "Dispositivos",
    usuariosBloqueados: "Usuarios bloqueados",
    aplicativosAutorizados: "Aplicaciones autorizadas",
    sessoes: "Sesiones",
    amigosEDms: "Amigos y mensajes directos",
    compartilhamentoDeAtividade: "Compartir actividad",
    visibilidadeDoPerfil: "Visibilidad del perfil",
    exportarDados: "Exportar datos",
    exclusaoDeDados: "Eliminar datos",
    tema: "Tema",
    corDeDestaque: "Color de acento",
    interface: "Interfaz",
    listaDeCanais: "Lista de canales",
    zoomDoApp: "Nivel de zoom de la app",
    escalaDaFonte: "Escala de la fuente del chat",
    modoStreamer: "Privacidad en directo",
    cursores: "Cursores",
    movimento: "Movimiento",
    textoEmVoz: "Texto a voz",
    teclado: "Teclado",
    formatoDaHora: "Formato de hora",
    idiomaDaInterface: "Idioma de la interfaz",
    dispositivosDeVoz: "Dispositivos",
    testeDoMicrofone: "Prueba del micrófono",
    modoDeEntrada: "Modo de entrada",
    sensibilidade: "Sensibilidad de entrada",
    qualidade: "Calidad",
    camera: "Cámara",
    transmissao: "Retransmisión",
    exibicao: "Visualización",
    entrada: "Entrada",
    midia: "Multimedia",
    geral: "General",
    preferenciaDeMencao: "Preferencia de mención",
    sons: "Sonidos",
  },
};
