export const amizades = {
  mensagensDiretas: "Directe berichten",
  nova: {
    titulo: "Nieuw gesprek",
    detalhe: "Kies een vriend, dan gaat het gesprek open.",
    procurar: "Een vriend zoeken",
    semAmigos: "Je hebt hier nog geen vrienden.",
    semResultado: "Geen vriend met die naam.",
  },
  adicionar: {
    recado: "Schrijf er iets bij (mag je overslaan)",
    recadoDica: "Wat je hier schrijft, verschijnt ook in jullie gesprek als jullie vrienden worden.",
    enviadoPara: "Klaar. Het vriendschapsverzoek is bij {{nome}} aangekomen.",
    outrosLugares: "Andere plekken om mensen te leren kennen",
    outrosLugaresDetalhe: "Schiet je niemand te binnen? Kijk eens bij de open community's, daar wordt over bijna alles gepraat.",
    explorarComunidades: "Community's verkennen",
    titulo: "Vriend toevoegen",
    detalhe: "Je kunt vrienden toevoegen op hun gebruikersnaam.",
    exemplo: "Gebruikersnaam, bijv.: thiago",
    enviando: "Versturen…",
    enviar: "Verzoek sturen",
  },
  gatinhoChorando: "Een huilend katje",
  status: {
    emChamada: "In gesprek",
    emVoz: "In spraak",
  },
  menu: {
    chamada: "Gesprek starten",
    fixar: "Bovenaan vastzetten",
    desafixar: "Losmaken",
    silenciar: "Gesprek dempen",
    reativar: "Meldingen weer aanzetten",
    copiarIdDoCanal: "Kanaal-ID kopiëren",
  },
  ativosAgora: "Nu actief",
  procurando: "Kijken wie er is…",
  tudoTranquilo: "Even helemaal rustig…",
  tudoTranquiloDetalhe: "Als jij of een vriend een gesprek start, verschijnt het hier — en kun je met één klik meedoen.",
  emVoz: "In spraak",
  voce: "Jij",
  soVoce: "Alleen jij",
  pessoas: "{{quantas}} mensen",
  voltarParaChamada: "Terug naar het gesprek",
  entrarNaChamada: "Deelnemen aan gesprek",
  abrirCanal: "{{canal}} openen in {{servidor}}",
  encontreConversa: "Zoek een gesprek",
  amigos: "Vrienden",
  conversas: "Gesprekken",
  semConversas: "Nog geen gesprekken. Voeg een vriend toe om te beginnen.",
  semConversaComEsseNome: "Geen gesprek met die naam.",
  abrirMenu: "Servers en gesprekken openen",
  solicitacoes: "Berichtverzoeken",
  pedidos: "Verzoeken",
  spam: "Spam",
  pedidosPendentes: "Openstaande verzoeken",
  marcadosComoSpam: "Als spam gemarkeerd",
  aceitar: "Accepteren",
  ignorar: "Negeren",
  marcarSpam: "Markeren als spam",
  semPedidos: "Geen verzoeken in de wacht.",
  semPedidosDetalhe: "Wie geen vriend is maar wel een server met je deelt, komt hier terecht voordat het je gesprekken bereikt.",
  semSpam: "Niets als spam gemarkeerd.",
  semSpamDetalhe: "Wat het spamfilter apart zet, of wat jij markeert, blijft in dit tabblad.",
  umServidorEmComum: "1 gedeelde server",
  servidoresEmComum: "{{quantos}} gedeelde servers",
  semServidoresEmComum: "Geen gedeelde servers",
};
