export const comum = {
  voltar: "Terug",
  agoraNao: "Nu even niet",
  erro: {
    tentarDeNovo: "Opnieuw proberen",
    recarregar: "Opnieuw laden",
    copiarDetalhes: "Details kopiëren",
    parteQuebrou: "Dit stuk van het scherm ging stuk.",
    titulo: "Ravox Chat struikelde.",
    detalhe: "Er ging onderweg iets stuk en het scherm kon zichzelf niet tekenen. Je gesprek is niet weg — alles staat op de server.",
  },
  perdido: {
    titulo: "Dit adres leidt nergens heen.",
    detalhe: "Of de link klopt niet, of de pagina is verplaatst.",
  },
  conexao: {
    voltou: "Weer verbonden",
    reconectando: "Opnieuw verbinden",
    tentativaSufixo: " · poging {{numero}}",
    aSalvo: "Het gesprek staat veilig op de server. Dit komt vanzelf terug zodra de verbinding er weer is.",
  },
  avisoDoNavegador: {
    titulo: "Wil je bericht krijgen van berichten?",
    detalhe: "Staat Ravox Chat achter een ander venster, dan roept het je.",
  },
  atualizacao: {
    titulo: "Update",
    semAuto: "Deze versie van de app kan zichzelf niet bijwerken. Download hieronder het nieuwste installatieprogramma en installeer eroverheen.",
    versaoAtual: "Je hebt versie {{versao}}.",
    instalando: "Versie {{versao}} wordt geïnstalleerd…",
    prontaVersao: "Versie {{versao}} staat klaar om te installeren",
    baixandoVersao: "Versie {{versao}} wordt gedownload…",
    baixandoComProgresso: "Versie {{versao}} wordt gedownload… {{porcento}}%",
    saiuVersao: "Versie {{versao}} is uit",
    saiuVersaoClique: "Versie {{versao}} is uit — klik om te downloaden",
    instalarVersaoEReiniciar: "Versie {{versao}} installeren en opnieuw starten",
    erroTenteDeNovo: "{{erro}} Klik om het opnieuw te proberen.",
    procurando: "Zoeken…",
    emDia: "Je bent bij",
    vaiFechar: "De app sluit zo.",
    comoInstala: "De app sluit, wisselt van versie en opent uit zichzelf weer. Zit je in een gesprek, dan verlaat je het.",
    semServidor: "Ik kon de versieserver niet bereiken.",
    procuraSozinho: "De app kijkt zelf bij het opstarten en om de zes uur.",
    instalandoReticencias: "Installeren…",
    instalandoCurto: "Installeren",
    baixandoCurto: "Downloaden",
    tentarDeNovo: "Opnieuw proberen",
    reiniciarAgora: "Nu opnieuw starten",
    instalarEReiniciar: "Installeren en opnieuw starten",
    baixar: "Downloaden",
    procurar: "Controleren",
    baixarApp: "De app downloaden",
    ariaBotao: "Update van de app",
  },
  janela: {
    ajustarAltura: "Hoogte aanpassen",
    redimensionar: "Venstergrootte aanpassen",
    ajustarLargura: "Breedte aanpassen",
  },
  dica: {
    rotulo: "Tip:",
    pularConfirmacao: "houd Shift ingedrukt bij het klikken om deze bevestiging over te slaan.",
  },
  cor: {
    pescar: "Een kleur van het scherm plukken",
    hex: "Hexadecimale waarde",
  },
  imagem: {
    titulo: "Kies een afbeelding",
    enviar: "Afbeelding sturen",
    escolherGif: "GIF kiezen",
    buscarGif: "GIF zoeken",
  },
  fonte: {
    rotulo: "Lettertype van het bericht",
    padrao: "Standaard",
    comNome: "Lettertype van het bericht — {{fonte}}",
  },
  recorte: {
    titulo: "Pictogram bijsnijden",
    detalhe: "Sleep om het stuk te kiezen en gebruik de schuifregelaar om in te zoomen. Het pictogram is overal in de app rond.",
    voltarAoComeco: "Terug naar het begin",
    usar: "Deze uitsnede gebruiken",
  },
  mais: "Meer",
  carregando: "Laden…",
  salvar: "Opslaan",
  salvando: "Bezig met opslaan…",
  descartar: "Verwerpen",
  redefinir: "Herstellen",
  naoSalvo: "Je hebt niet-opgeslagen wijzigingen.",
  fechar: "Sluiten",
  criar: "Aanmaken",
  nome: "Naam",
  emoji: "Emoji",
  previa: "Voorbeeld",
  cancelar: "Annuleren",
  enviar: "Versturen",
  apagar: "Verwijderen",
  excluir: "Verwijderen",
  remover: "Weghalen",
  trocar: "Wijzigen",
  loginNoApp: {
    titulo: "Helemaal klaar!",
    detalhe: "Je bent ingelogd. Ga terug naar Ravox Chat, de app wacht al op je.",
    abrir: "Ravox Chat openen",
    fecharAba: "Je kunt dit tabblad nu sluiten.",
    falhouTitulo: "Inloggen is mislukt",
    falhouDetalhe: "Ga terug naar de app en probeer opnieuw in te loggen.",
    legenda: "Een zwaaiende robot",
    legendaFalhou: "Een huilend katje",
  },
  ads: {
    label: "Advertentie",
    title: "Adverteer hier",
    detail: "Praat met ons en verschijn bij wie Ravox Chat gebruikt.",
    action: "Ik wil adverteren",
  },
};
