export const configuracoes = {
  efeitos: {
    titulo: "Effecten van de aanwijzer",
    detalhe: "Een spoor en vonken over de app getekend. Ze beginnen uit en gaan vanzelf uit als je om minder beweging vroeg.",
    rastro: "Spoor van de aanwijzer",
    rastroDetalhe: "Een lijn die de aanwijzer volgt en erachter vervaagt.",
    faisca: "Vonk bij klikken",
    faiscaDetalhe: "Korte streepjes die wegschieten vanaf je klik.",
    cor: "Kleur",
    espessura: "Dikte",
    comprimento: "Lengte",
    tamanho: "Grootte",
    quantidade: "Aantal",
  },
  email: {
    verificarTitulo: "Bevestig je e-mailadres",
    verificarDetalhe: "Sommige community's laten alleen bevestigde mensen schrijven. Eén klik volstaat.",
    enviar: "Stuur de link",
    enviado: "Kijk in de inbox. De link houdt een dag stand.",
    falhou: "De e-mail kon niet verstuurd worden.",
    confirmado: "E-mailadres bevestigd",
    confirmadoDetalhe: "Klaar. Nu schrijf je in elke community die erom vraagt.",
    linkIncompleto: "Onvolledige link",
    linkIncompletoDetalhe: "De code ontbreekt in het adres. Open de link rechtstreeks uit de e-mail.",
    confirmando: "Bezig met bevestigen…",
    expirou: "Deze link is al gebruikt of verlopen.",
    irParaOApp: "Naar de app",
  },
  tema: {
    indisponivel: "Thema niet beschikbaar",
    indisponivelDetalhe: "Wie het publiceerde heeft het verwijderd, of de link klopt niet.",
    indisponivelLinha: "Thema niet beschikbaar. Wie het publiceerde heeft het verwijderd, of de link klopt niet.",
    importar: "Thema importeren",
    importarCurto: "Importeren",
    importarDetalhe: "Dit vervangt het thema dat je nu hebt. Je kunt het daarna aanpassen in Instellingen > Weergave > Themastudio.",
    porAutor: "door {{autor}}",
    umaCorTrocada: "1 kleur gewisseld",
    coresTrocadas: "{{quantas}} kleuren gewisseld",
    avisoDeCss: "Dit thema brengt CSS mee van wie het schreef, en CSS komt in elke hoek van het scherm. Importeer alleen van mensen die je vertrouwt.",
    soCores: "Dit thema wisselt alleen kleuren. Geen CSS van buiten.",
    verCss: "CSS bekijken",
    esconderCss: "CSS verbergen",
    aplicar: "Toepassen",
    previaSemMotor: "De voorbeeldweergave draait de motor niet. Installeer om hem te zien.",
    motorAnimado: "{{motor}} geanimeerd",
  },
  sair: "Uitloggen",
  versoes: {
    termos: "Servicevoorwaarden",
    privacidade: "Privacybeleid",
    copiar: "Klik om te kopiëren",
    copiado: "Gekopieerd",
  },
  appColors: {
    title: "App-kleuren",
    detail: "Kies maximaal drie kleuren en de hele app krijgt dat verloop.",
    locked: "De kleureneditor hoort bij {{plan}}.",
    color: "Kleur {{number}}",
    addColor: "Kleur toevoegen",
    removeColor: "Kleur verwijderen",
    surprise: "Verras me",
    direction: "Richting van het verloop",
    intensity: "Intensiteit",
    reset: "Herstellen",
  },
  subscription: {
    colorsRow: "Kleureneditor van de app",
    seePlans: "Abonnementen bekijken",
    upgradeSubtitle: "Hogere limieten en exclusieve functies voor schrijven, bestanden sturen en streamen.",
    perMonth: "per maand",
    perYear: "per jaar",
    save: "Bespaar {{percent}}%",
    howToPay: "Hoe wil je betalen?",
    legal: "Je kunt binnen 7 dagen na betaling een terugbetaling aanvragen. De betaling wordt verwerkt door Stripe; wij zien je kaartnummer nooit.",
    compare: "Gratis vs. Infinity",
    featureColumn: "Functie",
    freeColumn: "Gratis",
    messageRow: "Tekenlimiet per bericht",
    attachmentRow: "Bestandsgrootte bij uploaden",
    screenRow: "Videokwaliteit",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Je hebt Infinity al tot {{date}}.",
    upsell: "Limiet verhogen met Infinity",
    screenUpsell: "Meer kwaliteit met Infinity",
    free: "Je gebruikt het gratis abonnement.",
    activeUntil: "Infinity actief tot {{date}}.",
    renews: "Wordt automatisch verlengd op {{date}}.",
    endsAt: "Het abonnement is opgezegd en eindigt op {{date}}.",
    pastDue: "De laatste afschrijving is mislukt. Werk je kaart bij om Infinity te houden.",
    waiting: "Betaling bevestigen…",
    subscribe: "Abonneren",
    monthly: "Maandelijks",
    yearly: "Jaarlijks",
    automatic: "Kaart",
    manage: "Betaling beheren",
    refund: "Terugbetaling aanvragen",
    refundDetail: "Je kunt binnen 7 dagen na betaling herroepen: {{amount}}, tot {{date}}.",
    refundConfirm: "Terugbetaling aanvragen?",
    refundConfirmDetail: "Het geld gaat terug naar dezelfde betaalmethode en Infinity stopt meteen.",
    refunded: "Terugbetaling aangevraagd.",
    unavailable: "Abonnementen zijn nog niet beschikbaar.",
    success: "Betaling ontvangen. Bedankt!",
    canceled: "Betaling geannuleerd.",
    error: "Er ging iets mis. Probeer het opnieuw.",
    no: "Nee",
    tagRow: "Eigen gebruikerstag",
    guildProfilesRow: "Profielen per community",
    badgeRow: "Profielbadge",
    communitiesRow: "Community's",
    savedRow: "Opgeslagen berichten",
    animatedEmojiRow: "Geanimeerde emoji's gebruiken",
    expressionsRow: "Overal emoji's en stickers gebruiken",
    animatedProfileRow: "Geanimeerde avatars en profielbanners",
    earlyAccessRow: "Vroege toegang tot nieuwe functies",
    themesRow: "Eigen thema's",
    pixOption: "Pix",
    pixHint: "Open je bank-app, kies Pix en scan de QR-code of gebruik kopiëren en plakken.",
    pixQrAlt: "Pix-QR-code",
    pixCopy: "Pix-code kopiëren",
    pixCopied: "Pix-code gekopieerd",
    pixWaiting: "Wachten op betaling",
    pixExpiresIn: "verloopt over {{time}}",
    pixExpired: "Deze Pix is verlopen. Maak een nieuwe om door te gaan.",
    pixNew: "Nieuwe Pix maken",
    pixPaid: "Pix ontvangen! Je Infinity is nu actief.",
    forMe: "Voor mij",
    asGift: "Als cadeau",
    buyGift: "Cadeau kopen",
    giftReady: "Cadeau klaar! Kopieer de link en stuur hem naar wie je wilt.",
    giftClaimed: "Cadeau ingewisseld! Infinity staat op je account.",
    gifts: "Cadeaus",
    giftsEmpty: "Je hebt nog geen cadeaus gekocht.",
    giftCode: "Cadeaucode",
    giftRedeem: "Inwisselen",
    giftCopyLink: "Link kopiëren",
    giftLinkCopied: "Link gekopieerd",
    giftClaimedBy: "ingewisseld door {{name}}",
    giftHint: "Heb je een cadeaucode? Wissel hem hier in. Gekochte cadeaus staan hieronder.",
    cardPaid: "Betaling goedgekeurd! Je Infinity is actief.",
    payAmount: "{{amount}} betalen",
    giftLinkTitle: "Je hebt een {{plan}}-cadeau gekregen!",
    giftLinkDetail: "Tik op inwisselen en de dagen komen op je account.",
    pageTitle: "Ontgrendel een wereld aan voordelen met {{plan}}",
    pageStart: "Start",
    pageBest: "Het beste van Infinity",
    pageChoose: "Kies je abonnement",
    fromPrice: "Vanaf {{amount}} per maand. Stop wanneer je wilt.",
    filesTitle: "Stuur het hele bestand",
    filesText: "De video van het feest, het werkproject, de map met foto's: alles gaat in één keer mee, zonder knippen, zonder inpakken en zonder cloudlink ertussen.",
    videoTitle: "Stream in 1080p",
    videoText: "Je scherm komt scherp aan bij de ander, met het dubbele aantal beelden per seconde. Je kunt code lezen en samen gamen zonder dat het een waas wordt.",
    messageTitle: "Schrijf zoveel je wilt",
    messageText: "Het dubbele aantal tekens per bericht, voor als het verhaal lang is en het in drieën knippen de lol eruit haalt.",
    colorsTitle: "De app in jouw kleuren",
    colorsText: "Kies de kleuren van de app stuk voor stuk, sla het thema op en neem het mee naar elk apparaat waarop je inlogt.",
    profileTitle: "Een profiel voor elke plek",
    profileText: "Een andere bijnaam, een andere foto, een andere beschrijving in elke community — en een bewegende foto, als je wilt.",
    freeDetail: "Het is gratis en dat blijft zo.",
    currentPlan: "Je huidige abonnement",
    popular: "Meest gekozen",
    yearlyDetail: "Dat is {{amount}} per maand, één keer per jaar afgeschreven.",
    monthlyDetail: "Elke maand afgeschreven, stop wanneer je wilt.",
    groupStyle: "Laat je stijl zien",
    groupLook: "Maak de app van jou",
    groupLimits: "Geen krappe limieten",
    closingTitle: "Waar wacht je nog op?",
    pagePlans: "Abonnementen",
    pageCompare: "Vergelijken",
    giftClaimTitle: "{{plan}} activeren?",
    giftClaimDetail: "Dat zijn {{days}} dagen die nu op je account komen.",
    giftFrom: "van {{name}}",
    giftActivate: "Activeren",
    giftHasPlanTitle: "Je hebt Infinity al",
    giftHasPlanDetail: "Je abonnement loopt tot {{date}}. Bewaar de link en stuur hem naar een vriend.",
    giftUsedTitle: "Dit cadeau is al gebruikt",
    giftUsedDetail: "Iemand heeft deze code al ingewisseld. Vraag om een nieuwe.",
    giftNotFoundTitle: "Code niet gevonden",
    giftNotFoundDetail: "Controleer de code of vraag de link opnieuw.",
    giftDoneTitle: "{{plan}} geactiveerd!",
    giftOpenApp: "App openen",
    giftSignIn: "Inloggen om in te wisselen",
    giftReviewStep: "Betaling · Controleren",
    giftTotalToday: "Totaal vandaag",
    giftCardWhy: "De kaart is alleen om te bevestigen dat jij het bent. Er wordt nu niets afgeschreven en niets verlengt vanzelf.",
    giftAgree: "Ik heb de gebruiksvoorwaarden gelezen en accepteer ze",
    giftActivating: "Bezig met activeren…",
  },
  telas: {
    subscription: "Infinity",
    conta: "Mijn account",
    privacidade: "Privacy",
    conexoes: "Verbindingen",
    voz: "Audio",
    video: "Video",
    avisos: "Meldingen",
    aplicativos: "Applicaties",
    aparencia: "Weergave",
    batePapo: "Chat",
    acessibilidade: "Toegankelijkheid",
    idioma: "Taal",
    aplicativo: "App downloaden",
    atalhos: "Sneltoetsen",
    desktop: "Desktop-app",
    avancado: "Geavanceerd",
    servidor: "Server",
    comunicado: "Systeemmededeling",
    denuncias: "Meldingen",
    publicacoes: "Implementaties",
  },
  grupos: {
    conta: "Account",
    app: "App-instellingen",
    desenvolvedor: "Ontwikkelaar",
    administracao: "Beheer",
  },
  secoes: {
    coresDoApp: "App-kleuren",
    detalhesDeLogin: "Inloggegevens",
    dispositivos: "Apparaten",
    usuariosBloqueados: "Geblokkeerde gebruikers",
    aplicativosAutorizados: "Geautoriseerde apps",
    sessoes: "Sessies",
    amigosEDms: "Vrienden en directe berichten",
    compartilhamentoDeAtividade: "Activiteit delen",
    visibilidadeDoPerfil: "Profielzichtbaarheid",
    exportarDados: "Gegevens exporteren",
    exclusaoDeDados: "Gegevens verwijderen",
    tema: "Thema",
    corDeDestaque: "Accentkleur",
    interface: "Interface",
    listaDeCanais: "Kanalenlijst",
    zoomDoApp: "Zoomniveau van de app",
    escalaDaFonte: "Lettergrootte in de chat",
    modoStreamer: "Streamingprivacy",
    cursores: "Cursors",
    movimento: "Beweging",
    textoEmVoz: "Tekst naar spraak",
    teclado: "Toetsenbord",
    formatoDaHora: "Tijdnotatie",
    idiomaDaInterface: "Taal van de interface",
    dispositivosDeVoz: "Apparaten",
    testeDoMicrofone: "Microfoontest",
    modoDeEntrada: "Invoermodus",
    sensibilidade: "Invoergevoeligheid",
    qualidade: "Kwaliteit",
    camera: "Camera",
    transmissao: "Uitzending",
    exibicao: "Weergave",
    entrada: "Invoer",
    midia: "Media",
    geral: "Algemeen",
    preferenciaDeMencao: "Vermeldingsvoorkeur",
    sons: "Geluiden",
  },
};
