export const comum = {
  voltar: "Geri",
  agoraNao: "Şimdi değil",
  erro: {
    tentarDeNovo: "Yeniden dene",
    recarregar: "Yeniden yükle",
    copiarDetalhes: "Ayrıntıları kopyala",
    parteQuebrou: "Ekranın bu bölümü bozuldu.",
    titulo: "Ravox Chat tökezledi.",
    detalhe: "Yolda bir şey bozuldu ve ekran kendini çizemedi. Sohbetin kaybolmadı — hepsi sunucuda.",
  },
  perdido: {
    titulo: "Bu adres hiçbir yere çıkmıyor.",
    detalhe: "Ya bağlantı yanlış geldi ya da sayfa yer değiştirdi.",
  },
  conexao: {
    voltou: "Yeniden bağlanıldı",
    reconectando: "Yeniden bağlanılıyor",
    tentativaSufixo: " · {{numero}}. deneme",
    aSalvo: "Sohbet sunucuda güvende. Bağlantı döner dönmez her şey kendiliğinden geri gelir.",
  },
  avisoDoNavegador: {
    titulo: "Mesajlardan haberdar olmak ister misin?",
    detalhe: "Ravox Chat başka bir pencerenin arkasındayken seni çağırır.",
  },
  atualizacao: {
    titulo: "Güncelleme",
    semAuto: "Uygulamanın bu sürümü kendini güncelleyemiyor. Aşağıdan en yeni kurulum dosyasını indir ve üstüne kur.",
    versaoAtual: "{{versao}} sürümünü kullanıyorsun.",
    instalando: "{{versao}} sürümü kuruluyor…",
    prontaVersao: "{{versao}} sürümü kuruluma hazır",
    baixandoVersao: "{{versao}} sürümü indiriliyor…",
    baixandoComProgresso: "{{versao}} sürümü indiriliyor… %{{porcento}}",
    saiuVersao: "{{versao}} sürümü çıktı",
    saiuVersaoClique: "{{versao}} sürümü çıktı — indirmek için tıkla",
    instalarVersaoEReiniciar: "{{versao}} sürümünü kur ve yeniden başlat",
    erroTenteDeNovo: "{{erro}} Yeniden denemek için tıkla.",
    procurando: "Aranıyor…",
    emDia: "Her şey güncel",
    vaiFechar: "Uygulama birazdan kapanacak.",
    comoInstala: "Uygulama kapanır, sürümü değiştirir ve kendi kendine yeniden açılır. Bir görüşmedeysen ondan çıkarsın.",
    semServidor: "Sürüm sunucusuna ulaşamadım.",
    procuraSozinho: "Uygulama açılışta ve altı saatte bir kendi kendine bakar.",
    instalandoReticencias: "Kuruluyor…",
    instalandoCurto: "Kuruluyor",
    baixandoCurto: "İndiriliyor",
    tentarDeNovo: "Yeniden dene",
    reiniciarAgora: "Şimdi yeniden başlat",
    instalarEReiniciar: "Kur ve yeniden başlat",
    baixar: "İndir",
    procurar: "Denetle",
    baixarApp: "Uygulamayı indir",
    ariaBotao: "Uygulama güncellemesi",
  },
  janela: {
    ajustarAltura: "Yüksekliği ayarla",
    redimensionar: "Pencereyi yeniden boyutlandır",
    ajustarLargura: "Genişliği ayarla",
  },
  dica: {
    rotulo: "İpucu:",
    pularConfirmacao: "tıklarken Shift'e basılı tut, bu onay atlanır.",
  },
  cor: {
    pescar: "Ekrandan renk al",
    hex: "On altılık değer",
  },
  imagem: {
    titulo: "Bir görsel seç",
    enviar: "Görsel gönder",
    escolherGif: "GIF seç",
    buscarGif: "GIF ara",
  },
  fonte: {
    rotulo: "Mesaj yazı tipi",
    padrao: "Varsayılan",
    comNome: "Mesaj yazı tipi — {{fonte}}",
  },
  recorte: {
    titulo: "Simgeyi kırp",
    detalhe: "İstediğin parçayı seçmek için sürükle, yakınlaştırmak için kaydırıcıyı kullan. Simge uygulamanın her yerinde yuvarlak görünür.",
    voltarAoComeco: "Başa dön",
    usar: "Bu kırpmayı kullan",
  },
  mais: "Daha fazla",
  carregando: "Yükleniyor…",
  salvar: "Kaydet",
  salvando: "Kaydediliyor…",
  descartar: "Vazgeç",
  redefinir: "Sıfırla",
  naoSalvo: "Kaydedilmemiş değişikliklerin var.",
  fechar: "Kapat",
  criar: "Oluştur",
  nome: "Ad",
  emoji: "Emoji",
  previa: "Önizleme",
  cancelar: "Vazgeç",
  enviar: "Gönder",
  apagar: "Sil",
  excluir: "Sil",
  remover: "Kaldır",
  trocar: "Değiştir",
  loginNoApp: {
    titulo: "Her şey hazır!",
    detalhe: "Giriş yaptın. Ravox Chat'ye geri dön, uygulama seni bekliyor.",
    abrir: "Ravox Chat'yi aç",
    fecharAba: "Bu sekmeyi artık kapatabilirsin.",
    falhouTitulo: "Giriş yapılamadı",
    falhouDetalhe: "Uygulamaya dön ve tekrar giriş yapmayı dene.",
    legenda: "El sallayan bir robot",
    legendaFalhou: "Ağlayan bir yavru kedi",
  },
  ads: {
    label: "Reklam",
    title: "Burada reklam verin",
    detail: "Bizimle konuşun ve Ravox Chat kullananlara görünün.",
    action: "Reklam vermek istiyorum",
  },
};
