export const configuracoes = {
  efeitos: {
    titulo: "İşaretçi efektleri",
    detalhe: "Uygulamanın üstüne çizilen iz ve kıvılcım. Kapalı gelirler ve daha az hareket istediysen kendiliğinden sönerler.",
    rastro: "İşaretçi izi",
    rastroDetalhe: "İşaretçiyi izleyen ve arkada solan bir çizgi.",
    faisca: "Tıklamada kıvılcım",
    faiscaDetalhe: "Tıkladığın noktadan fırlayan kısa çizgiler.",
    cor: "Renk",
    espessura: "Kalınlık",
    comprimento: "Uzunluk",
    tamanho: "Boyut",
    quantidade: "Adet",
  },
  email: {
    verificarTitulo: "E-postanı doğrula",
    verificarDetalhe: "Bazı topluluklar yalnızca doğrulayanların yazmasına izin verir. Tek tık yeter.",
    enviar: "Bağlantıyı yolla",
    enviado: "Gelen kutuna bak. Bağlantı bir gün geçerli.",
    falhou: "E-posta gönderilemedi.",
    confirmado: "E-posta doğrulandı",
    confirmadoDetalhe: "Tamamdır. Artık bunu isteyen her toplulukta yazabilirsin.",
    linkIncompleto: "Eksik bağlantı",
    linkIncompletoDetalhe: "Adreste kod eksik. Bağlantıyı doğrudan e-postadan aç.",
    confirmando: "Doğrulanıyor…",
    expirou: "Bu bağlantı kullanılmış ya da süresi geçmiş.",
    irParaOApp: "Uygulamaya git",
  },
  tema: {
    indisponivel: "Tema kullanılamıyor",
    indisponivelDetalhe: "Yayımlayan kişi sildi ya da bağlantı yanlış.",
    indisponivelLinha: "Tema kullanılamıyor. Yayımlayan kişi sildi ya da bağlantı yanlış.",
    importar: "Temayı içe aktar",
    importarCurto: "İçe aktar",
    importarDetalhe: "Bu, şu anki temanın yerine geçer. Sonrasında Ayarlar > Görünüm > Tema stüdyosu üzerinden düzenleyebilirsin.",
    porAutor: "{{autor}} tarafından",
    umaCorTrocada: "1 renk değişti",
    coresTrocadas: "{{quantas}} renk değişti",
    avisoDeCss: "Bu tema yazarının CSS'ini de getiriyor ve CSS ekranın her köşesine dokunur. Yalnızca güvendiğin kişilerden içe aktar.",
    soCores: "Bu tema sadece renkleri değiştiriyor. Dışarıdan CSS yok.",
    verCss: "CSS'i göster",
    esconderCss: "CSS'i gizle",
    aplicar: "Uygula",
    previaSemMotor: "Önizleme motoru çalıştırmaz. Görmek için kur.",
    motorAnimado: "{{motor}} animasyonlu",
  },
  sair: "Çıkış yap",
  versoes: {
    termos: "Hizmet şartları",
    privacidade: "Gizlilik politikası",
    copiar: "Kopyalamak için tıkla",
    copiado: "Kopyalandı",
  },
  appColors: {
    title: "Uygulama renkleri",
    detail: "En fazla üç renk seç, tüm uygulama o geçişi alsın.",
    locked: "Renk düzenleyici {{plan}} özelliğidir.",
    color: "{{number}}. renk",
    addColor: "Renk ekle",
    removeColor: "Rengi kaldır",
    surprise: "Şaşırt beni",
    direction: "Geçiş yönü",
    intensity: "Yoğunluk",
    reset: "Sıfırla",
  },
  subscription: {
    colorsRow: "Uygulama renk düzenleyicisi",
    seePlans: "Planları gör",
    upgradeSubtitle: "Yazmak, dosya göndermek ve yayın yapmak için daha yüksek sınırlar ve özel özellikler.",
    perMonth: "aylık",
    perYear: "yıllık",
    save: "%{{percent}} tasarruf",
    howToPay: "Nasıl ödemek istersin?",
    legal: "Ödemeden sonraki 7 gün içinde iade isteyebilirsin. Ödeme Stripe tarafından işlenir; kart numaranı asla görmeyiz.",
    compare: "Ücretsiz ve Infinity",
    featureColumn: "Özellik",
    freeColumn: "Ücretsiz",
    messageRow: "Mesaj karakter sınırı",
    attachmentRow: "Gönderilen dosya boyutu",
    screenRow: "Video kalitesi",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Zaten {{date}} tarihine kadar Infinity'un var.",
    upsell: "Sınırı Infinity ile artır",
    screenUpsell: "Infinity ile daha yüksek kalite",
    free: "Ücretsiz plandasın.",
    activeUntil: "Infinity {{date}} tarihine kadar etkin.",
    renews: "{{date}} tarihinde otomatik yenilenir.",
    endsAt: "Abonelik iptal edildi, {{date}} tarihinde sona erecek.",
    pastDue: "Son ödeme alınamadı. Infinity'u kaybetmemek için kartını güncelle.",
    waiting: "Ödeme onaylanıyor…",
    subscribe: "Abone ol",
    monthly: "Aylık",
    yearly: "Yıllık",
    automatic: "Kart",
    manage: "Ödemeyi yönet",
    refund: "İade iste",
    refundDetail: "Ödemeden sonraki 7 gün içinde vazgeçebilirsin: {{amount}}, {{date}} tarihine kadar.",
    refundConfirm: "İade istensin mi?",
    refundConfirmDetail: "Para aynı ödeme yöntemine iade edilir ve Infinity hemen sona erer.",
    refunded: "İade istendi.",
    unavailable: "Abonelik henüz kullanılamıyor.",
    success: "Ödeme alındı. Teşekkürler!",
    canceled: "Ödeme iptal edildi.",
    error: "Bir sorun oluştu. Tekrar dene.",
    no: "Hayır",
    tagRow: "Özel kullanıcı etiketi",
    guildProfilesRow: "Topluluğa özel profiller",
    badgeRow: "Profil rozeti",
    communitiesRow: "Topluluklar",
    savedRow: "Kaydedilen mesajlar",
    animatedEmojiRow: "Hareketli emojiler",
    expressionsRow: "Her yerden emoji ve çıkartma",
    animatedProfileRow: "Hareketli avatar ve profil afişleri",
    earlyAccessRow: "Yeniliklere erken erişim",
    themesRow: "Özel temalar",
    pixOption: "Pix",
    pixHint: "Banka uygulamanı aç, Pix'i seç ve QR kodu okut ya da kopyala-yapıştır kullan.",
    pixQrAlt: "Pix QR kodu",
    pixCopy: "Pix kodunu kopyala",
    pixCopied: "Pix kodu kopyalandı",
    pixWaiting: "Ödeme bekleniyor",
    pixExpiresIn: "{{time}} içinde sona erer",
    pixExpired: "Bu Pix'in süresi doldu. Devam etmek için yenisini oluştur.",
    pixNew: "Yeni Pix oluştur",
    pixPaid: "Pix alındı! Infinity artık aktif.",
    forMe: "Benim için",
    asGift: "Hediye olarak",
    buyGift: "Hediye al",
    giftReady: "Hediye hazır! Bağlantıyı kopyala ve istediğine gönder.",
    giftClaimed: "Hediye kullanıldı! Infinity hesabında.",
    gifts: "Hediyeler",
    giftsEmpty: "Henüz hiç hediye almadın.",
    giftCode: "Hediye kodu",
    giftRedeem: "Kullan",
    giftCopyLink: "Bağlantıyı kopyala",
    giftLinkCopied: "Bağlantı kopyalandı",
    giftClaimedBy: "{{name}} kullandı",
    giftHint: "Hediye kodun var mı? Burada kullan. Aldığın hediyeler aşağıda.",
    cardPaid: "Ödeme onaylandı! Infinity'n aktif.",
    payAmount: "{{amount}} öde",
    giftLinkTitle: "Bir {{plan}} hediyesi aldın!",
    giftLinkDetail: "Kullan'a dokun, günler hesabına gelsin.",
    pageTitle: "{{plan}} ile avantaj dolu bir dünyanın kilidini aç",
    pageStart: "Başlangıç",
    pageBest: "Infinity’nin en iyisi",
    pageChoose: "Planını seç",
    fromPrice: "Ayda {{amount}} başlangıç fiyatıyla. İstediğin zaman iptal et.",
    filesTitle: "Dosyanın tamamını gönder",
    filesText: "Partinin videosu, işteki proje, fotoğrafların olduğu klasör: hepsi tek seferde gider; bölmeden, sıkıştırmadan ve araya bulut bağlantısı koymadan.",
    videoTitle: "1080p yayın yap",
    videoText: "Ekranın karşı taraftakine net ulaşır, saniyedeki kare sayısı iki katına çıkar. Kod okunur, birlikte oyun oynanır; hiçbir şey bulanıklaşmaz.",
    messageTitle: "Gönlünce yaz",
    messageText: "Her mesajda iki kat karakter; hikâye uzun olduğunda ve üçe bölmek bütün tadını kaçıracağında.",
    colorsTitle: "Sana benzeyen bir uygulama",
    colorsText: "Uygulamanın renklerini tek tek seç, temayı kaydet ve girdiğin bütün cihazlara taşı.",
    profileTitle: "Her yere ayrı bir profil",
    profileText: "Her toplulukta başka bir takma ad, başka bir fotoğraf, başka bir açıklama — istersen hareketli fotoğraf da.",
    freeDetail: "Ücretsiz ve öyle kalıyor.",
    currentPlan: "Mevcut planın",
    popular: "En çok seçilen",
    yearlyDetail: "Ayda {{amount}} eder, yılda bir kez tahsil edilir.",
    monthlyDetail: "Her ay tahsil edilir, istediğin zaman iptal edersin.",
    groupStyle: "Tarzını göster",
    groupLook: "Uygulamayı kendine göre ayarla",
    groupLimits: "Dar sınırlar yok",
    closingTitle: "Daha ne bekliyorsun?",
    pagePlans: "Planlar",
    pageCompare: "Karşılaştır",
    giftClaimTitle: "{{plan}} etkinleştirilsin mi?",
    giftClaimDetail: "Hesabına şimdi {{days}} gün eklenecek.",
    giftFrom: "{{name}} gönderdi",
    giftActivate: "Etkinleştir",
    giftHasPlanTitle: "Zaten Infinity'n var",
    giftHasPlanDetail: "Planın {{date}} tarihine kadar geçerli. Bağlantıyı sakla ve bir arkadaşına gönder.",
    giftUsedTitle: "Bu hediye zaten kullanıldı",
    giftUsedDetail: "Bu kodu daha önce biri kullandı. Başka bir tane iste.",
    giftNotFoundTitle: "Kod bulunamadı",
    giftNotFoundDetail: "Kodu kontrol et ya da bağlantıyı yeniden iste.",
    giftDoneTitle: "{{plan}} etkinleştirildi!",
    giftOpenApp: "Uygulamayı aç",
    giftSignIn: "Kullanmak için giriş yap",
    giftReviewStep: "Ödeme · Gözden geçir",
    giftTotalToday: "Bugünün toplamı",
    giftCardWhy: "Kart yalnızca senin olduğunu doğrulamak için. Şimdi hiçbir şey tahsil edilmez ve hiçbir şey kendi kendine yenilenmez.",
    giftAgree: "Kullanım koşullarını okudum ve kabul ediyorum",
    giftActivating: "Etkinleştiriliyor…",
  },
  telas: {
    subscription: "Infinity",
    conta: "Hesabım",
    privacidade: "Gizlilik",
    conexoes: "Bağlantılar",
    voz: "Ses",
    video: "Video",
    avisos: "Bildirimler",
    aplicativos: "Uygulamalar",
    aparencia: "Görünüm",
    batePapo: "Sohbet",
    acessibilidade: "Erişilebilirlik",
    idioma: "Dil",
    aplicativo: "Uygulamayı indir",
    atalhos: "Kısayollar",
    desktop: "Masaüstü uygulaması",
    avancado: "Gelişmiş",
    servidor: "Sunucu",
    comunicado: "Sistem duyurusu",
    denuncias: "Şikayetler",
    publicacoes: "Dağıtımlar",
  },
  grupos: {
    conta: "Hesap",
    app: "Uygulama ayarları",
    desenvolvedor: "Geliştirici",
    administracao: "Yönetim",
  },
  secoes: {
    coresDoApp: "Uygulama renkleri",
    detalhesDeLogin: "Giriş bilgileri",
    dispositivos: "Cihazlar",
    usuariosBloqueados: "Engellenen kullanıcılar",
    aplicativosAutorizados: "Yetkili uygulamalar",
    sessoes: "Oturumlar",
    amigosEDms: "Arkadaşlar ve doğrudan mesajlar",
    compartilhamentoDeAtividade: "Etkinlik paylaşımı",
    visibilidadeDoPerfil: "Profil görünürlüğü",
    exportarDados: "Verileri dışa aktar",
    exclusaoDeDados: "Verileri sil",
    tema: "Tema",
    corDeDestaque: "Vurgu rengi",
    interface: "Arayüz",
    listaDeCanais: "Kanal listesi",
    zoomDoApp: "Uygulama yakınlaştırma düzeyi",
    escalaDaFonte: "Sohbet yazı tipi ölçeği",
    modoStreamer: "Yayın gizliliği",
    cursores: "İmleçler",
    movimento: "Hareket",
    textoEmVoz: "Metinden konuşmaya",
    teclado: "Klavye",
    formatoDaHora: "Saat biçimi",
    idiomaDaInterface: "Arayüz dili",
    dispositivosDeVoz: "Cihazlar",
    testeDoMicrofone: "Mikrofon testi",
    modoDeEntrada: "Giriş modu",
    sensibilidade: "Giriş hassasiyeti",
    qualidade: "Kalite",
    camera: "Kamera",
    transmissao: "Yayın",
    exibicao: "Görüntüleme",
    entrada: "Giriş",
    midia: "Medya",
    geral: "Genel",
    preferenciaDeMencao: "Bahsetme tercihi",
    sons: "Sesler",
  },
};
