export const amizades = {
  mensagensDiretas: "Direktnachrichten",
  nova: {
    titulo: "Neues Gespräch",
    detalhe: "Wähl jemanden aus, dann geht das Gespräch auf.",
    procurar: "Freund suchen",
    semAmigos: "Hier hast du noch keine Freunde.",
    semResultado: "Niemand mit diesem Namen.",
  },
  adicionar: {
    recado: "Schreib ein paar Worte dazu (freiwillig)",
    recadoDica: "Was du hier schreibst, taucht auch in eurem Gespräch auf, wenn ihr Freunde werdet.",
    enviadoPara: "Fertig! Die Freundschaftsanfrage ist bei {{nome}} gelandet.",
    outrosLugares: "Andere Orte, um Leute kennenzulernen",
    outrosLugaresDetalhe: "Fällt dir niemand ein? Schau in die offenen Communitys, dort wird über fast alles geredet.",
    explorarComunidades: "Communitys entdecken",
    titulo: "Freund hinzufügen",
    detalhe: "Du kannst Freunde über ihren Benutzernamen hinzufügen.",
    exemplo: "Benutzername, z. B.: thiago",
    enviando: "Wird gesendet…",
    enviar: "Anfrage senden",
  },
  gatinhoChorando: "Ein weinendes Kätzchen",
  status: {
    emChamada: "In einem Anruf",
    emVoz: "In Sprache",
  },
  menu: {
    chamada: "Anruf starten",
    fixar: "Oben anheften",
    desafixar: "Lösen",
    silenciar: "Unterhaltung stummschalten",
    reativar: "Benachrichtigungen wieder aktivieren",
    copiarIdDoCanal: "Kanal-ID kopieren",
  },
  ativosAgora: "Jetzt aktiv",
  procurando: "Mal sehen, wer da ist…",
  tudoTranquilo: "Gerade ist alles ruhig…",
  tudoTranquiloDetalhe: "Wenn du oder ein Freund einem Anruf beitritt, erscheint er hier — und du kannst mit einem Klick dazukommen.",
  emVoz: "Im Sprachkanal",
  voce: "Du",
  soVoce: "Nur du",
  pessoas: "{{quantas}} Personen",
  voltarParaChamada: "Zurück zum Anruf",
  entrarNaChamada: "Anruf beitreten",
  abrirCanal: "{{canal}} in {{servidor}} öffnen",
  encontreConversa: "Unterhaltung finden",
  amigos: "Freunde",
  conversas: "Unterhaltungen",
  semConversas: "Noch keine Unterhaltungen. Füge einen Freund hinzu, um zu starten.",
  semConversaComEsseNome: "Keine Unterhaltung mit diesem Namen.",
  abrirMenu: "Server und Unterhaltungen öffnen",
  solicitacoes: "Nachrichtenanfragen",
  pedidos: "Anfragen",
  spam: "Spam",
  pedidosPendentes: "Offene Anfragen",
  marcadosComoSpam: "Als Spam markiert",
  aceitar: "Annehmen",
  ignorar: "Ignorieren",
  marcarSpam: "Als Spam markieren",
  semPedidos: "Keine Anfragen offen.",
  semPedidosDetalhe: "Wer nicht dein Freund ist, aber einen Server mit dir teilt, landet hier, bevor er deine Unterhaltungen erreicht.",
  semSpam: "Nichts als Spam markiert.",
  semSpamDetalhe: "Was der Spamfilter aussortiert oder was du markierst, bleibt in diesem Tab.",
  umServidorEmComum: "1 gemeinsamer Server",
  servidoresEmComum: "{{quantos}} gemeinsame Server",
  semServidoresEmComum: "Keine gemeinsamen Server",
};
