export const comum = {
  voltar: "Zurück",
  agoraNao: "Jetzt nicht",
  erro: {
    tentarDeNovo: "Erneut versuchen",
    recarregar: "Neu laden",
    copiarDetalhes: "Details kopieren",
    parteQuebrou: "Dieser Teil des Bildschirms ist kaputtgegangen.",
    titulo: "Ravox Chat ist gestolpert.",
    detalhe: "Unterwegs ist etwas kaputtgegangen und der Bildschirm konnte sich nicht zeichnen. Deine Unterhaltung ist nicht verloren — alles liegt auf dem Server.",
  },
  perdido: {
    titulo: "Diese Adresse führt nirgendwohin.",
    detalhe: "Entweder stimmt der Link nicht, oder die Seite ist umgezogen.",
  },
  conexao: {
    voltou: "Wieder verbunden",
    reconectando: "Verbinde neu",
    tentativaSufixo: " · Versuch {{numero}}",
    aSalvo: "Die Unterhaltung liegt sicher auf dem Server. Sobald die Verbindung zurück ist, geht es von selbst weiter.",
  },
  avisoDoNavegador: {
    titulo: "Möchtest du über Nachrichten benachrichtigt werden?",
    detalhe: "Wenn Ravox Chat hinter einem anderen Fenster liegt, meldet es sich.",
  },
  atualizacao: {
    titulo: "Aktualisierung",
    semAuto: "Diese Version der App kann sich nicht selbst aktualisieren. Lade unten das neueste Installationsprogramm herunter und installiere es darüber.",
    versaoAtual: "Du hast Version {{versao}}.",
    instalando: "Version {{versao}} wird installiert…",
    prontaVersao: "Version {{versao}} ist bereit zur Installation",
    baixandoVersao: "Version {{versao}} wird geladen…",
    baixandoComProgresso: "Version {{versao}} wird geladen… {{porcento}} %",
    saiuVersao: "Version {{versao}} ist da",
    saiuVersaoClique: "Version {{versao}} ist da — zum Herunterladen klicken",
    instalarVersaoEReiniciar: "Version {{versao}} installieren und neu starten",
    erroTenteDeNovo: "{{erro}} Zum erneuten Versuch klicken.",
    procurando: "Suche…",
    emDia: "Du bist auf dem neuesten Stand",
    vaiFechar: "Die App schließt gleich.",
    comoInstala: "Die App schließt sich, tauscht die Version und öffnet sich von selbst wieder. Ein laufender Anruf wird beendet.",
    semServidor: "Der Versionsserver war nicht erreichbar.",
    procuraSozinho: "Die App sucht beim Start und alle sechs Stunden von selbst.",
    instalandoReticencias: "Wird installiert…",
    instalandoCurto: "Installation",
    baixandoCurto: "Download",
    tentarDeNovo: "Erneut versuchen",
    reiniciarAgora: "Jetzt neu starten",
    instalarEReiniciar: "Installieren und neu starten",
    baixar: "Herunterladen",
    procurar: "Suchen",
    baixarApp: "App herunterladen",
    ariaBotao: "Aktualisierung der App",
  },
  janela: {
    ajustarAltura: "Höhe anpassen",
    redimensionar: "Fenstergröße ändern",
    ajustarLargura: "Breite anpassen",
  },
  dica: {
    rotulo: "Tipp:",
    pularConfirmacao: "Halte beim Klicken die Umschalttaste gedrückt, um diese Bestätigung zu überspringen.",
  },
  cor: {
    pescar: "Farbe vom Bildschirm aufnehmen",
    hex: "Hexadezimalwert",
  },
  imagem: {
    titulo: "Bild auswählen",
    enviar: "Bild senden",
    escolherGif: "GIF auswählen",
    buscarGif: "GIF suchen",
  },
  fonte: {
    rotulo: "Schrift der Nachricht",
    padrao: "Standard",
    comNome: "Schrift der Nachricht — {{fonte}}",
  },
  recorte: {
    titulo: "Symbol zuschneiden",
    detalhe: "Zieh den Ausschnitt zurecht und zoome mit dem Regler. Das Symbol ist überall in der App rund.",
    voltarAoComeco: "Zurück zum Anfang",
    usar: "Diesen Ausschnitt verwenden",
  },
  mais: "Mehr",
  carregando: "Wird geladen…",
  salvar: "Speichern",
  salvando: "Wird gespeichert…",
  descartar: "Verwerfen",
  redefinir: "Zurücksetzen",
  naoSalvo: "Du hast ungespeicherte Änderungen.",
  fechar: "Schließen",
  criar: "Erstellen",
  nome: "Name",
  emoji: "Emoji",
  previa: "Vorschau",
  cancelar: "Abbrechen",
  enviar: "Senden",
  apagar: "Löschen",
  excluir: "Löschen",
  remover: "Entfernen",
  trocar: "Ändern",
  loginNoApp: {
    titulo: "Alles erledigt!",
    detalhe: "Du bist angemeldet. Geh zurück zu Ravox Chat, die App wartet schon auf dich.",
    abrir: "Ravox Chat öffnen",
    fecharAba: "Du kannst diesen Tab jetzt schließen.",
    falhouTitulo: "Anmeldung fehlgeschlagen",
    falhouDetalhe: "Geh zurück zur App und versuch es noch einmal.",
    legenda: "Ein winkender Roboter",
    legendaFalhou: "Ein weinendes Kätzchen",
  },
  ads: {
    label: "Werbung",
    title: "Hier werben",
    detail: "Sprich mit uns und zeig dich denen, die Ravox Chat nutzen.",
    action: "Ich möchte werben",
  },
};
