export const configuracoes = {
  efeitos: {
    titulo: "Zeigereffekte",
    detalhe: "Spur und Funken über der App gezeichnet. Sie starten aus und verschwinden von selbst, wenn du weniger Bewegung willst.",
    rastro: "Spur des Zeigers",
    rastroDetalhe: "Ein Strich, der dem Zeiger folgt und hinten verblasst.",
    faisca: "Funken beim Klicken",
    faiscaDetalhe: "Kurze Striche, die von der Klickstelle wegfliegen.",
    cor: "Farbe",
    espessura: "Dicke",
    comprimento: "Länge",
    tamanho: "Größe",
    quantidade: "Anzahl",
  },
  email: {
    verificarTitulo: "Bestätige deine E-Mail",
    verificarDetalhe: "Manche Communitys lassen nur Bestätigte schreiben. Ein Klick reicht.",
    enviar: "Link schicken",
    enviado: "Schau ins Postfach. Der Link gilt einen Tag.",
    falhou: "Die E-Mail ließ sich nicht senden.",
    confirmado: "E-Mail bestätigt",
    confirmadoDetalhe: "Erledigt. Jetzt schreibst du überall, wo das verlangt wird.",
    linkIncompleto: "Unvollständiger Link",
    linkIncompletoDetalhe: "In der Adresse fehlt der Code. Öffne den Link direkt aus der E-Mail.",
    confirmando: "Wird bestätigt …",
    expirou: "Dieser Link wurde schon benutzt oder ist abgelaufen.",
    irParaOApp: "Zur App",
  },
  tema: {
    indisponivel: "Design nicht verfügbar",
    indisponivelDetalhe: "Wer es veröffentlicht hat, hat es gelöscht, oder der Link stimmt nicht.",
    indisponivelLinha: "Design nicht verfügbar. Wer es veröffentlicht hat, hat es gelöscht, oder der Link stimmt nicht.",
    importar: "Design importieren",
    importarCurto: "Importieren",
    importarDetalhe: "Das ersetzt dein aktuelles Design. Bearbeiten kannst du es danach unter Einstellungen > Erscheinungsbild > Design-Studio.",
    porAutor: "von {{autor}}",
    umaCorTrocada: "1 getauschte Farbe",
    coresTrocadas: "{{quantas}} getauschte Farben",
    avisoDeCss: "Dieses Design bringt CSS von seinem Autor mit, und CSS greift in jede Ecke des Bildschirms. Importiere nur von Leuten, denen du vertraust.",
    soCores: "Dieses Design tauscht nur Farben. Kein fremdes CSS.",
    verCss: "CSS anzeigen",
    esconderCss: "CSS ausblenden",
    aplicar: "Anwenden",
    previaSemMotor: "Die Vorschau lässt den Motor nicht laufen. Installiere es, um ihn zu sehen.",
    motorAnimado: "{{motor}} animiert",
  },
  sair: "Abmelden",
  versoes: {
    termos: "Nutzungsbedingungen",
    privacidade: "Datenschutzerklärung",
    copiar: "Zum Kopieren klicken",
    copiado: "Kopiert",
  },
  appColors: {
    title: "App-Farben",
    detail: "Wähle bis zu drei Farben, und die ganze App bekommt diesen Verlauf.",
    locked: "Der Farbeditor gehört zu {{plan}}.",
    color: "Farbe {{number}}",
    addColor: "Farbe hinzufügen",
    removeColor: "Farbe entfernen",
    surprise: "Überrasch mich",
    direction: "Verlaufsrichtung",
    intensity: "Intensität",
    reset: "Zurücksetzen",
  },
  subscription: {
    colorsRow: "Farbeditor der App",
    seePlans: "Pläne ansehen",
    upgradeSubtitle: "Höhere Grenzen und exklusive Funktionen zum Schreiben, Senden von Dateien und Übertragen.",
    perMonth: "pro Monat",
    perYear: "pro Jahr",
    save: "Spare {{percent}} %",
    howToPay: "Wie möchtest du bezahlen?",
    legal: "Du kannst innerhalb von 7 Tagen nach der Zahlung eine Erstattung anfordern. Die Zahlung wird von Stripe abgewickelt; wir sehen deine Kartennummer nie.",
    compare: "Kostenlos vs. Infinity",
    featureColumn: "Funktion",
    freeColumn: "Kostenlos",
    messageRow: "Zeichenlimit pro Nachricht",
    attachmentRow: "Dateigröße beim Hochladen",
    screenRow: "Videoqualität",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Du hast Infinity bereits bis {{date}}.",
    upsell: "Grenze mit Infinity erhöhen",
    screenUpsell: "Mehr Qualität mit Infinity",
    free: "Du nutzt den kostenlosen Plan.",
    activeUntil: "Infinity aktiv bis {{date}}.",
    renews: "Verlängert sich automatisch am {{date}}.",
    endsAt: "Das Abo wurde gekündigt und endet am {{date}}.",
    pastDue: "Die letzte Abbuchung ist fehlgeschlagen. Aktualisiere deine Karte, um Infinity zu behalten.",
    waiting: "Zahlung wird bestätigt…",
    subscribe: "Abonnieren",
    monthly: "Monatlich",
    yearly: "Jährlich",
    automatic: "Karte",
    manage: "Zahlung verwalten",
    refund: "Erstattung anfordern",
    refundDetail: "Du kannst innerhalb von 7 Tagen nach der Zahlung widerrufen: {{amount}}, bis {{date}}.",
    refundConfirm: "Erstattung anfordern?",
    refundConfirmDetail: "Das Geld geht an dieselbe Zahlungsart zurück und Infinity endet sofort.",
    refunded: "Erstattung angefordert.",
    unavailable: "Abos sind noch nicht verfügbar.",
    success: "Zahlung erhalten. Danke!",
    canceled: "Zahlung abgebrochen.",
    error: "Das hat nicht geklappt. Versuch es noch einmal.",
    no: "Nein",
    tagRow: "Eigener Benutzer-Tag",
    guildProfilesRow: "Profile pro Community",
    badgeRow: "Profilabzeichen",
    communitiesRow: "Communitys",
    savedRow: "Gespeicherte Nachrichten",
    animatedEmojiRow: "Animierte Emojis nutzen",
    expressionsRow: "Emojis und Sticker überall nutzen",
    animatedProfileRow: "Animierte Avatare und Profilbanner",
    earlyAccessRow: "Früher Zugang zu neuen Funktionen",
    themesRow: "Eigene Themes",
    pixOption: "Pix",
    pixHint: "Öffne deine Banking-App, wähle Pix und scanne den QR-Code oder nutze Kopieren und Einfügen.",
    pixQrAlt: "Pix-QR-Code",
    pixCopy: "Pix-Code kopieren",
    pixCopied: "Pix-Code kopiert",
    pixWaiting: "Warte auf die Zahlung",
    pixExpiresIn: "läuft ab in {{time}}",
    pixExpired: "Dieser Pix ist abgelaufen. Erstelle einen neuen, um fortzufahren.",
    pixNew: "Neuen Pix erstellen",
    pixPaid: "Pix erhalten! Dein Infinity ist jetzt aktiv.",
    forMe: "Für mich",
    asGift: "Als Geschenk",
    buyGift: "Geschenk kaufen",
    giftReady: "Geschenk fertig! Kopiere den Link und schick ihn an wen du willst.",
    giftClaimed: "Geschenk eingelöst! Infinity ist jetzt auf deinem Konto.",
    gifts: "Geschenke",
    giftsEmpty: "Du hast noch keine Geschenke gekauft.",
    giftCode: "Geschenkcode",
    giftRedeem: "Einlösen",
    giftCopyLink: "Link kopieren",
    giftLinkCopied: "Link kopiert",
    giftClaimedBy: "eingelöst von {{name}}",
    giftHint: "Hast du einen Geschenkcode? Löse ihn hier ein. Gekaufte Geschenke stehen unten.",
    cardPaid: "Zahlung bestätigt! Dein Infinity ist aktiv.",
    payAmount: "{{amount}} bezahlen",
    giftLinkTitle: "Du hast ein {{plan}}-Geschenk bekommen!",
    giftLinkDetail: "Tippe auf Einlösen und die Tage landen auf deinem Konto.",
    pageTitle: "Schalte eine Welt voller Vorteile mit {{plan}} frei",
    pageStart: "Start",
    pageBest: "Das Beste von Infinity",
    pageChoose: "Wähle deinen Plan",
    fromPrice: "Ab {{amount}} pro Monat. Kündige, wann du willst.",
    filesTitle: "Schick die ganze Datei",
    filesText: "Das Video von der Feier, das Projekt aus der Arbeit, der Ordner mit den Fotos: alles geht auf einmal raus, ohne Zerteilen, ohne Packen und ohne Cloud-Link dazwischen.",
    videoTitle: "Übertrage in 1080p",
    videoText: "Dein Bildschirm kommt auf der anderen Seite gestochen scharf an, mit doppelt so vielen Bildern pro Sekunde. Code lesen und zusammen spielen geht, ohne dass alles verschwimmt.",
    messageTitle: "Schreib so viel du willst",
    messageText: "Doppelt so viele Zeichen in jeder Nachricht — für die langen Geschichten, die in drei Teilen ihren Reiz verlieren würden.",
    colorsTitle: "Die App in deiner Handschrift",
    colorsText: "Wähle die Farben der App einzeln aus, speichere das Thema und nimm es auf jedes Gerät mit, an dem du dich anmeldest.",
    profileTitle: "Ein Profil für jeden Ort",
    profileText: "Ein anderer Spitzname, ein anderes Bild, eine andere Beschreibung in jeder Community — und ein bewegtes Bild, wenn du magst.",
    freeDetail: "Er ist kostenlos und bleibt es auch.",
    currentPlan: "Dein aktueller Plan",
    popular: "Am häufigsten gewählt",
    yearlyDetail: "Das sind {{amount}} pro Monat, einmal im Jahr abgerechnet.",
    monthlyDetail: "Wird jeden Monat abgerechnet, kündbar wann du willst.",
    groupStyle: "Zeig deinen Stil",
    groupLook: "Mach die App zu deiner",
    groupLimits: "Keine engen Grenzen",
    closingTitle: "Worauf wartest du noch?",
    pagePlans: "Pläne",
    pageCompare: "Vergleichen",
    giftClaimTitle: "{{plan}} aktivieren?",
    giftClaimDetail: "Das sind {{days}} Tage, die jetzt auf dein Konto kommen.",
    giftFrom: "von {{name}}",
    giftActivate: "Aktivieren",
    giftHasPlanTitle: "Du hast Infinity schon",
    giftHasPlanDetail: "Dein Plan läuft bis {{date}}. Behalte den Link und schick ihn einem Freund.",
    giftUsedTitle: "Dieses Geschenk wurde schon genutzt",
    giftUsedDetail: "Jemand hat den Code vorher eingelöst. Frag nach einem neuen.",
    giftNotFoundTitle: "Code nicht gefunden",
    giftNotFoundDetail: "Prüfe den Code oder frag noch mal nach dem Link.",
    giftDoneTitle: "{{plan}} aktiviert!",
    giftOpenApp: "App öffnen",
    giftSignIn: "Anmelden zum Einlösen",
    giftReviewStep: "Zahlung · Prüfen",
    giftTotalToday: "Summe heute",
    giftCardWhy: "Die Karte dient nur dazu, zu bestätigen, dass du es bist. Es wird nichts abgebucht und nichts verlängert sich von selbst.",
    giftAgree: "Ich habe die Nutzungsbedingungen gelesen und akzeptiere sie",
    giftActivating: "Wird aktiviert…",
  },
  telas: {
    subscription: "Infinity",
    conta: "Mein Konto",
    privacidade: "Privatsphäre",
    conexoes: "Verbindungen",
    voz: "Audio",
    video: "Video",
    avisos: "Benachrichtigungen",
    aplicativos: "Anwendungen",
    aparencia: "Erscheinungsbild",
    batePapo: "Chat",
    acessibilidade: "Barrierefreiheit",
    idioma: "Sprache",
    aplicativo: "App herunterladen",
    atalhos: "Tastenkürzel",
    desktop: "Desktop-App",
    avancado: "Erweitert",
    servidor: "Server",
    comunicado: "Systemmitteilung",
    denuncias: "Meldungen",
    publicacoes: "Bereitstellungen",
  },
  grupos: {
    conta: "Konto",
    app: "App-Einstellungen",
    desenvolvedor: "Entwickler",
    administracao: "Verwaltung",
  },
  secoes: {
    coresDoApp: "App-Farben",
    detalhesDeLogin: "Anmeldedaten",
    dispositivos: "Geräte",
    usuariosBloqueados: "Blockierte Nutzer",
    aplicativosAutorizados: "Autorisierte Apps",
    sessoes: "Sitzungen",
    amigosEDms: "Freunde und Direktnachrichten",
    compartilhamentoDeAtividade: "Aktivitätsfreigabe",
    visibilidadeDoPerfil: "Profil-Sichtbarkeit",
    exportarDados: "Daten exportieren",
    exclusaoDeDados: "Daten löschen",
    tema: "Design",
    corDeDestaque: "Akzentfarbe",
    interface: "Oberfläche",
    listaDeCanais: "Kanalliste",
    zoomDoApp: "Zoomstufe der App",
    escalaDaFonte: "Schriftgröße im Chat",
    modoStreamer: "Streaming-Privatsphäre",
    cursores: "Cursor",
    movimento: "Bewegung",
    textoEmVoz: "Sprachausgabe",
    teclado: "Tastatur",
    formatoDaHora: "Zeitformat",
    idiomaDaInterface: "Sprache der Oberfläche",
    dispositivosDeVoz: "Geräte",
    testeDoMicrofone: "Mikrofontest",
    modoDeEntrada: "Eingabemodus",
    sensibilidade: "Eingabeempfindlichkeit",
    qualidade: "Qualität",
    camera: "Kamera",
    transmissao: "Übertragung",
    exibicao: "Anzeige",
    entrada: "Eingabe",
    midia: "Medien",
    geral: "Allgemein",
    preferenciaDeMencao: "Erwähnungseinstellung",
    sons: "Töne",
  },
};
