export const amizades = {
  mensagensDiretas: "Yksityisviestit",
  nova: {
    titulo: "Uusi keskustelu",
    detalhe: "Valitse kaveri, niin keskustelu aukeaa.",
    procurar: "Etsi kaveri",
    semAmigos: "Sinulla ei ole täällä vielä kavereita.",
    semResultado: "Ei kaveria tällä nimellä.",
  },
  adicionar: {
    recado: "Kirjoita pari sanaa (vapaaehtoinen)",
    recadoDica: "Se, mitä tähän kirjoitat, näkyy myös keskustelussanne, jos teistä tulee kavereita.",
    enviadoPara: "Valmista. Kaveripyyntö lähti henkilölle {{nome}}.",
    outrosLugares: "Muita paikkoja tutustua ihmisiin",
    outrosLugaresDetalhe: "Eikö kukaan tule mieleen? Katso avoimia yhteisöjä, siellä puhutaan lähes kaikesta.",
    explorarComunidades: "Tutustu yhteisöihin",
    titulo: "Lisää kaveri",
    detalhe: "Voit lisätä kavereita heidän käyttäjänimellään.",
    exemplo: "Käyttäjänimi, esim. thiago",
    enviando: "Lähetetään…",
    enviar: "Lähetä pyyntö",
  },
  gatinhoChorando: "Itkevä kissanpentu",
  status: {
    emChamada: "Puhelussa",
    emVoz: "Äänessä",
  },
  menu: {
    chamada: "Aloita puhelu",
    fixar: "Kiinnitä ylimmäksi",
    desafixar: "Irrota",
    silenciar: "Mykistä keskustelu",
    reativar: "Poista mykistys",
    copiarIdDoCanal: "Kopioi kanavan tunnus",
  },
  ativosAgora: "Nyt paikalla",
  procurando: "Katsotaan ketä on paikalla…",
  tudoTranquilo: "Nyt on rauhallista…",
  tudoTranquiloDetalhe: "Kun sinä tai kaveri liitytte puheluun, se näkyy täällä — ja pääset mukaan yhdellä klikkauksella.",
  emVoz: "Äänessä",
  voce: "Sinä",
  soVoce: "Vain sinä",
  pessoas: "{{quantas}} henkilöä",
  voltarParaChamada: "Takaisin puheluun",
  entrarNaChamada: "Liity puheluun",
  abrirCanal: "Avaa {{canal}} palvelimella {{servidor}}",
  encontreConversa: "Etsi keskustelu",
  amigos: "Kaverit",
  conversas: "Keskustelut",
  semConversas: "Ei vielä keskusteluja. Lisää kaveri päästäksesi alkuun.",
  semConversaComEsseNome: "Ei sen nimistä keskustelua.",
  abrirMenu: "Avaa palvelimet ja keskustelut",
  solicitacoes: "Viestipyynnöt",
  pedidos: "Pyynnöt",
  spam: "Roskaposti",
  pedidosPendentes: "Odottavat pyynnöt",
  marcadosComoSpam: "Merkitty roskapostiksi",
  aceitar: "Hyväksy",
  ignorar: "Ohita",
  marcarSpam: "Merkitse roskapostiksi",
  semPedidos: "Ei odottavia pyyntöjä.",
  semPedidosDetalhe: "Se joka ei ole kaverisi mutta on kanssasi samalla palvelimella, päätyy tänne ennen kuin pääsee keskusteluihisi.",
  semSpam: "Mitään ei ole merkitty roskapostiksi.",
  semSpamDetalhe: "Se minkä roskapostisuodatin erottelee, tai minkä itse merkitset, jää tälle välilehdelle.",
  umServidorEmComum: "1 yhteinen palvelin",
  servidoresEmComum: "{{quantos}} yhteistä palvelinta",
  semServidoresEmComum: "Ei yhteisiä palvelimia",
};
