export const comum = {
  voltar: "Takaisin",
  agoraNao: "Ei nyt",
  erro: {
    tentarDeNovo: "Yritä uudelleen",
    recarregar: "Lataa uudelleen",
    copiarDetalhes: "Kopioi tiedot",
    parteQuebrou: "Tämä osa näkymästä hajosi.",
    titulo: "Ravox Chat kompastui.",
    detalhe: "Jokin hajosi matkalla eikä näkymä pystynyt piirtymään. Keskustelusi ei kadonnut — kaikki on palvelimella.",
  },
  perdido: {
    titulo: "Tämä osoite ei vie mihinkään.",
    detalhe: "Joko linkki on väärä tai sivu on siirtynyt.",
  },
  conexao: {
    voltou: "Yhteys palasi",
    reconectando: "Yhdistetään uudelleen",
    tentativaSufixo: " · yritys {{numero}}",
    aSalvo: "Keskustelu on turvassa palvelimella. Tämä palaa itsestään heti kun yhteys palaa.",
  },
  avisoDoNavegador: {
    titulo: "Haluatko ilmoitukset viesteistä?",
    detalhe: "Kun Ravox Chat on toisen ikkunan takana, se huutaa sinulle.",
  },
  atualizacao: {
    titulo: "Päivitys",
    semAuto: "Tämä sovelluksen versio ei osaa päivittää itseään. Lataa alta uusin asennusohjelma ja asenna se päälle.",
    versaoAtual: "Käytössäsi on versio {{versao}}.",
    instalando: "Asennetaan versiota {{versao}}…",
    prontaVersao: "Versio {{versao}} on valmis asennettavaksi",
    baixandoVersao: "Ladataan versiota {{versao}}…",
    baixandoComProgresso: "Ladataan versiota {{versao}}… {{porcento}} %",
    saiuVersao: "Versio {{versao}} on julkaistu",
    saiuVersaoClique: "Versio {{versao}} on julkaistu — lataa napsauttamalla",
    instalarVersaoEReiniciar: "Asenna versio {{versao}} ja käynnistä uudelleen",
    erroTenteDeNovo: "{{erro}} Yritä uudelleen napsauttamalla.",
    procurando: "Etsitään…",
    emDia: "Kaikki on ajan tasalla",
    vaiFechar: "Sovellus sulkeutuu hetken kuluttua.",
    comoInstala: "Sovellus sulkeutuu, vaihtaa version ja avautuu itsestään uudelleen. Poistut samalla mahdollisesta puhelusta.",
    semServidor: "En saanut yhteyttä versiopalvelimeen.",
    procuraSozinho: "Sovellus tarkistaa itse käynnistyessään ja kuuden tunnin välein.",
    instalandoReticencias: "Asennetaan…",
    instalandoCurto: "Asennetaan",
    baixandoCurto: "Ladataan",
    tentarDeNovo: "Yritä uudelleen",
    reiniciarAgora: "Käynnistä uudelleen nyt",
    instalarEReiniciar: "Asenna ja käynnistä uudelleen",
    baixar: "Lataa",
    procurar: "Tarkista",
    baixarApp: "Lataa sovellus",
    ariaBotao: "Sovelluksen päivitys",
  },
  janela: {
    ajustarAltura: "Säädä korkeutta",
    redimensionar: "Muuta ikkunan kokoa",
    ajustarLargura: "Säädä leveyttä",
  },
  dica: {
    rotulo: "Vinkki:",
    pularConfirmacao: "pidä Shift pohjassa klikatessasi, niin tämä varmistus ohitetaan.",
  },
  cor: {
    pescar: "Poimi väri näytöltä",
    hex: "Heksadesimaaliarvo",
  },
  imagem: {
    titulo: "Valitse kuva",
    enviar: "Lähetä kuva",
    escolherGif: "Valitse GIF",
    buscarGif: "Hae GIF-kuvia",
  },
  fonte: {
    rotulo: "Viestin kirjasin",
    padrao: "Oletus",
    comNome: "Viestin kirjasin — {{fonte}}",
  },
  recorte: {
    titulo: "Rajaa kuvake",
    detalhe: "Vedä valitaksesi kohdan ja zoomaa liukusäätimellä. Kuvake on pyöreä kaikkialla sovelluksessa.",
    voltarAoComeco: "Takaisin alkuun",
    usar: "Käytä tätä rajausta",
  },
  mais: "Lisää",
  carregando: "Ladataan…",
  salvar: "Tallenna",
  salvando: "Tallennetaan…",
  descartar: "Hylkää",
  redefinir: "Palauta",
  naoSalvo: "Sinulla on tallentamattomia muutoksia.",
  fechar: "Sulje",
  criar: "Luo",
  nome: "Nimi",
  emoji: "Emoji",
  previa: "Esikatselu",
  cancelar: "Peruuta",
  enviar: "Lähetä",
  apagar: "Poista",
  excluir: "Poista",
  remover: "Poista",
  trocar: "Vaihda",
  loginNoApp: {
    titulo: "Kaikki valmista!",
    detalhe: "Olet kirjautunut sisään. Palaa Ravox Chathen, sovellus odottaa jo.",
    abrir: "Avaa Ravox Chat",
    fecharAba: "Voit sulkea tämän välilehden.",
    falhouTitulo: "Kirjautuminen epäonnistui",
    falhouDetalhe: "Palaa sovellukseen ja yritä kirjautua uudelleen.",
    legenda: "Vilkuttava robotti",
    legendaFalhou: "Itkevä kissanpentu",
  },
  ads: {
    label: "Mainos",
    title: "Mainosta tässä",
    detail: "Ota yhteyttä ja näy niille, jotka käyttävät Ravox Chatia.",
    action: "Haluan mainostaa",
  },
};
