export const configuracoes = {
  efeitos: {
    titulo: "Osoittimen tehosteet",
    detalhe: "Jälki ja kipinät piirretään sovelluksen päälle. Ne alkavat pois päältä ja sammuvat itsestään, jos pyysit vähemmän liikettä.",
    rastro: "Osoittimen jälki",
    rastroDetalhe: "Viiva, joka seuraa osoitinta ja haalistuu takana.",
    faisca: "Kipinä napsautuksesta",
    faiscaDetalhe: "Lyhyitä viivoja, jotka lentävät napsautuskohdasta.",
    cor: "Väri",
    espessura: "Paksuus",
    comprimento: "Pituus",
    tamanho: "Koko",
    quantidade: "Määrä",
  },
  email: {
    verificarTitulo: "Vahvista sähköpostisi",
    verificarDetalhe: "Osa yhteisöistä päästää kirjoittamaan vain vahvistaneet. Yksi klikkaus riittää.",
    enviar: "Lähetä linkki",
    enviado: "Katso postilaatikkoa. Linkki kestää vuorokauden.",
    falhou: "Sähköpostia ei saatu lähetettyä.",
    confirmado: "Sähköposti vahvistettu",
    confirmadoDetalhe: "Valmista. Nyt kirjoitat jokaisessa yhteisössä, joka sitä vaatii.",
    linkIncompleto: "Vajaa linkki",
    linkIncompletoDetalhe: "Osoitteesta puuttuu koodi. Avaa linkki suoraan sähköpostista.",
    confirmando: "Vahvistetaan…",
    expirou: "Tämä linkki on jo käytetty tai vanhentunut.",
    irParaOApp: "Sovellukseen",
  },
  tema: {
    indisponivel: "Teema ei ole saatavilla",
    indisponivelDetalhe: "Julkaisija poisti sen, tai linkki on väärä.",
    indisponivelLinha: "Teema ei ole saatavilla. Julkaisija poisti sen, tai linkki on väärä.",
    importar: "Tuo teema",
    importarCurto: "Tuo",
    importarDetalhe: "Tämä korvaa nykyisen teemasi. Voit muokata sitä jälkeenpäin kohdassa Asetukset > Ulkoasu > Teemastudio.",
    porAutor: "tekijä {{autor}}",
    umaCorTrocada: "1 vaihdettu väri",
    coresTrocadas: "{{quantas}} vaihdettua väriä",
    avisoDeCss: "Tämä teema tuo mukanaan tekijänsä CSS:n, ja CSS ylettyy näytön joka nurkkaan. Tuo vain sellaisilta, joihin luotat.",
    soCores: "Tämä teema vaihtaa vain värit. Ei ulkopuolista CSS:ää.",
    verCss: "Näytä CSS",
    esconderCss: "Piilota CSS",
    aplicar: "Käytä",
    previaSemMotor: "Esikatselu ei aja moottoria. Asenna nähdäksesi sen.",
    motorAnimado: "{{motor}} animoituna",
  },
  sair: "Kirjaudu ulos",
  versoes: {
    termos: "Käyttöehdot",
    privacidade: "Tietosuojakäytäntö",
    copiar: "Kopioi napsauttamalla",
    copiado: "Kopioitu",
  },
  appColors: {
    title: "Sovelluksen värit",
    detail: "Valitse enintään kolme väriä, ja koko sovellus saa sen liukuvärin.",
    locked: "Värieditori kuuluu {{plan}}-tilaukseen.",
    color: "Väri {{number}}",
    addColor: "Lisää väri",
    removeColor: "Poista väri",
    surprise: "Yllätä minut",
    direction: "Liukuvärin suunta",
    intensity: "Voimakkuus",
    reset: "Palauta",
  },
  subscription: {
    colorsRow: "Sovelluksen värieditori",
    seePlans: "Katso tilaukset",
    upgradeSubtitle: "Isommat rajat ja omat ominaisuudet kirjoittamiseen, tiedostoihin ja lähetyksiin.",
    perMonth: "kuukaudessa",
    perYear: "vuodessa",
    save: "Säästä {{percent}} %",
    howToPay: "Miten haluat maksaa?",
    legal: "Voit pyytää hyvitystä 7 päivän kuluessa maksusta. Maksun käsittelee Stripe; emme koskaan näe korttisi numeroa.",
    compare: "Ilmainen vs. Infinity",
    featureColumn: "Ominaisuus",
    freeColumn: "Ilmainen",
    messageRow: "Viestin merkkiraja",
    attachmentRow: "Lähetettävän tiedoston koko",
    screenRow: "Videon laatu",
    megabytesValue: "{{value}} Mt",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Sinulla on jo Infinity {{date}} asti.",
    upsell: "Nosta rajaa Infinityllä",
    screenUpsell: "Parempi laatu Infinityllä",
    free: "Käytät ilmaista tasoa.",
    activeUntil: "Infinity voimassa {{date}} asti.",
    renews: "Uusiutuu automaattisesti {{date}}.",
    endsAt: "Tilaus on peruttu ja päättyy {{date}}.",
    pastDue: "Viimeisin veloitus epäonnistui. Päivitä korttisi, jotta Infinity säilyy.",
    waiting: "Vahvistetaan maksua…",
    subscribe: "Tilaa",
    monthly: "Kuukausittain",
    yearly: "Vuosittain",
    automatic: "Kortti",
    manage: "Hallitse maksua",
    refund: "Pyydä hyvitystä",
    refundDetail: "Voit perua 7 päivän kuluessa maksusta: {{amount}}, {{date}} asti.",
    refundConfirm: "Pyydetäänkö hyvitys?",
    refundConfirmDetail: "Rahat palautetaan samalle maksutavalle ja Infinity päättyy heti.",
    refunded: "Hyvitystä pyydetty.",
    unavailable: "Tilaukset eivät ole vielä saatavilla.",
    success: "Maksu vastaanotettu. Kiitos!",
    canceled: "Maksu peruttu.",
    error: "Jokin meni vikaan. Yritä uudelleen.",
    no: "Ei",
    tagRow: "Oma käyttäjätunniste",
    guildProfilesRow: "Yhteisökohtaiset profiilit",
    badgeRow: "Profiilimerkki",
    communitiesRow: "Yhteisöt",
    savedRow: "Tallennetut viestit",
    animatedEmojiRow: "Animoidut emojit",
    expressionsRow: "Emojit ja tarrat kaikkialla",
    animatedProfileRow: "Animoidut profiilikuvat ja bannerit",
    earlyAccessRow: "Uudet ominaisuudet ensimmäisenä",
    themesRow: "Omat teemat",
    pixOption: "Pix",
    pixHint: "Avaa pankkisovellus, valitse Pix ja skannaa QR-koodi tai käytä kopioi ja liitä.",
    pixQrAlt: "Pix-QR-koodi",
    pixCopy: "Kopioi Pix-koodi",
    pixCopied: "Pix-koodi kopioitu",
    pixWaiting: "Odotetaan maksua",
    pixExpiresIn: "vanhenee {{time}} kuluttua",
    pixExpired: "Tämä Pix on vanhentunut. Luo uusi jatkaaksesi.",
    pixNew: "Luo uusi Pix",
    pixPaid: "Pix vastaanotettu! Infinity on nyt käytössä.",
    forMe: "Itselleni",
    asGift: "Lahjaksi",
    buyGift: "Osta lahja",
    giftReady: "Lahja on valmis! Kopioi linkki ja lähetä se kenelle haluat.",
    giftClaimed: "Lahja lunastettu! Infinity on nyt tililläsi.",
    gifts: "Lahjat",
    giftsEmpty: "Et ole vielä ostanut lahjoja.",
    giftCode: "Lahjakoodi",
    giftRedeem: "Lunasta",
    giftCopyLink: "Kopioi linkki",
    giftLinkCopied: "Linkki kopioitu",
    giftClaimedBy: "lunastanut {{name}}",
    giftHint: "Onko sinulla lahjakoodi? Lunasta se tässä. Ostamasi lahjat näkyvät alla.",
    cardPaid: "Maksu hyväksytty! Infinity on käytössä.",
    payAmount: "Maksa {{amount}}",
    giftLinkTitle: "Sait {{plan}}-lahjan!",
    giftLinkDetail: "Napauta lunasta, niin päivät siirtyvät tilillesi.",
    pageTitle: "Avaa etujen maailma {{plan}}illa",
    pageStart: "Etusivu",
    pageBest: "Infinityn parhaat puolet",
    pageChoose: "Valitse tilauksesi",
    fromPrice: "Alkaen {{amount}} kuukaudessa. Voit lopettaa milloin haluat.",
    filesTitle: "Lähetä koko tiedosto",
    filesText: "Juhlavideo, työprojekti, kuvakansio: kaikki lähtee kerralla, ilman paloittelua, pakkaamista tai pilvilinkkiä välissä.",
    videoTitle: "Lähetä 1080p-tarkkuudella",
    videoText: "Näyttösi näkyy terävänä toisella puolella, kaksinkertaisella kuvataajuudella. Koodia voi lukea ja pelata yhdessä ilman että kuva puuroutuu.",
    messageTitle: "Kirjoita rauhassa",
    messageText: "Kaksinkertainen määrä merkkejä joka viestiin, niitä kertoja varten kun tarina on pitkä ja kolmeen osaan pilkkominen pilaisi sen.",
    colorsTitle: "Sovellus sinun näköiseksi",
    colorsText: "Valitse sovelluksen värit yksitellen, tallenna teema ja ota se mukaan kaikille laitteille, joilla kirjaudut sisään.",
    profileTitle: "Oma profiili joka paikkaan",
    profileText: "Eri nimimerkki, eri kuva ja eri esittely jokaisessa yhteisössä — ja liikkuva kuva, jos haluat.",
    freeDetail: "Se on ilmainen ja pysyy ilmaisena.",
    currentPlan: "Nykyinen tilauksesi",
    popular: "Valituin",
    yearlyDetail: "Se on {{amount}} kuukaudessa, veloitetaan kerran vuodessa.",
    monthlyDetail: "Veloitetaan joka kuukausi, voit lopettaa milloin haluat.",
    groupStyle: "Näytä tyylisi",
    groupLook: "Muokkaa sovellus omaksesi",
    groupLimits: "Ei tiukkoja rajoja",
    closingTitle: "Mitä vielä odotat?",
    pagePlans: "Tilaukset",
    pageCompare: "Vertaa",
    giftClaimTitle: "Aktivoidaanko {{plan}}?",
    giftClaimDetail: "Tilillesi tulee nyt {{days}} päivää.",
    giftFrom: "lähettäjä {{name}}",
    giftActivate: "Aktivoi",
    giftHasPlanTitle: "Sinulla on jo Infinity",
    giftHasPlanDetail: "Tilauksesi kestää {{date}} asti. Säilytä linkki ja lähetä se kaverille.",
    giftUsedTitle: "Tämä lahja on jo käytetty",
    giftUsedDetail: "Joku lunasti koodin aiemmin. Pyydä uusi.",
    giftNotFoundTitle: "Koodia ei löytynyt",
    giftNotFoundDetail: "Tarkista koodi tai pyydä linkki uudelleen.",
    giftDoneTitle: "{{plan}} aktivoitu!",
    giftOpenApp: "Avaa sovellus",
    giftSignIn: "Kirjaudu lunastaaksesi",
    giftReviewStep: "Maksu · Tarkistus",
    giftTotalToday: "Yhteensä tänään",
    giftCardWhy: "Kortti on vain sen vahvistamiseksi, että olet sinä. Nyt ei veloiteta mitään eikä mikään uusiudu itsestään.",
    giftAgree: "Olen lukenut käyttöehdot ja hyväksyn ne",
    giftActivating: "Aktivoidaan…",
  },
  telas: {
    subscription: "Infinity",
    conta: "Oma tili",
    privacidade: "Yksityisyys",
    conexoes: "Yhteydet",
    voz: "Ääni",
    video: "Video",
    avisos: "Ilmoitukset",
    aplicativos: "Sovellukset",
    aparencia: "Ulkoasu",
    batePapo: "Keskustelu",
    acessibilidade: "Saavutettavuus",
    idioma: "Kieli",
    aplicativo: "Lataa sovellus",
    atalhos: "Pikanäppäimet",
    desktop: "Työpöytäsovellus",
    avancado: "Lisäasetukset",
    servidor: "Palvelin",
    comunicado: "Järjestelmätiedote",
    denuncias: "Raportit",
    publicacoes: "Julkaisut",
  },
  grupos: {
    conta: "Tili",
    app: "Sovelluksen asetukset",
    desenvolvedor: "Kehittäjä",
    administracao: "Hallinta",
  },
  secoes: {
    coresDoApp: "Sovelluksen värit",
    detalhesDeLogin: "Kirjautumistiedot",
    dispositivos: "Laitteet",
    usuariosBloqueados: "Estetyt käyttäjät",
    aplicativosAutorizados: "Valtuutetut sovellukset",
    sessoes: "Istunnot",
    amigosEDms: "Kaverit ja yksityisviestit",
    compartilhamentoDeAtividade: "Toiminnan jakaminen",
    visibilidadeDoPerfil: "Profiilin näkyvyys",
    exportarDados: "Vie tiedot",
    exclusaoDeDados: "Poista tiedot",
    tema: "Teema",
    corDeDestaque: "Korostusväri",
    interface: "Käyttöliittymä",
    listaDeCanais: "Kanavaluettelo",
    zoomDoApp: "Sovelluksen zoomaustaso",
    escalaDaFonte: "Keskustelun fonttikoko",
    modoStreamer: "Yksityisyys lähetyksessä",
    cursores: "Osoittimet",
    movimento: "Liike",
    textoEmVoz: "Teksti puheeksi",
    teclado: "Näppäimistö",
    formatoDaHora: "Ajan muoto",
    idiomaDaInterface: "Käyttöliittymän kieli",
    dispositivosDeVoz: "Laitteet",
    testeDoMicrofone: "Mikrofonitesti",
    modoDeEntrada: "Syöttötila",
    sensibilidade: "Syötön herkkyys",
    qualidade: "Laatu",
    camera: "Kamera",
    transmissao: "Lähetys",
    exibicao: "Näyttö",
    entrada: "Syöttö",
    midia: "Media",
    geral: "Yleiset",
    preferenciaDeMencao: "Mainintojen asetus",
    sons: "Äänet",
  },
};
