export const amizades = {
  mensagensDiretas: "ダイレクトメッセージ",
  nova: {
    titulo: "新しい会話",
    detalhe: "友だちを選ぶと会話が開きます。",
    procurar: "友だちを探す",
    semAmigos: "ここにはまだ友だちがいません。",
    semResultado: "その名前の友だちはいません。",
  },
  adicionar: {
    recado: "ひとこと添える（任意）",
    recadoDica: "ここに書いたことは、友だちになったら二人の会話にも出ます。",
    enviadoPara: "送りました。友だち申請は {{nome}} に届いています。",
    outrosLugares: "友だちを見つけられる場所",
    outrosLugaresDetalhe: "思い当たる人がいませんか。開いているコミュニティをのぞいてみてください。ほとんど何の話でもしています。",
    explorarComunidades: "コミュニティを見る",
    titulo: "友だちを追加",
    detalhe: "ユーザー名で友だちを追加できます。",
    exemplo: "ユーザー名（例: thiago）",
    enviando: "送信中…",
    enviar: "リクエストを送る",
  },
  gatinhoChorando: "泣いている子猫",
  status: {
    emChamada: "通話中",
    emVoz: "ボイス中",
  },
  menu: {
    chamada: "通話を始める",
    fixar: "上部にピン留め",
    desafixar: "ピン留めを外す",
    silenciar: "会話をミュート",
    reativar: "通知をオンに戻す",
    copiarIdDoCanal: "チャンネルIDをコピー",
  },
  ativosAgora: "アクティブ",
  procurando: "だれがいるか確認中…",
  tudoTranquilo: "今のところ静かです…",
  tudoTranquiloDetalhe: "あなたか友だちが通話に入ると、ここに表示されます。ワンクリックで参加できます。",
  emVoz: "ボイス中",
  voce: "あなた",
  soVoce: "あなただけ",
  pessoas: "{{quantas}}人",
  voltarParaChamada: "通話に戻る",
  entrarNaChamada: "通話に参加",
  abrirCanal: "{{servidor}} の {{canal}} を開く",
  encontreConversa: "会話を探す",
  amigos: "フレンド",
  conversas: "会話",
  semConversas: "まだ会話がありません。フレンドを追加して始めましょう。",
  semConversaComEsseNome: "その名前の会話はありません。",
  abrirMenu: "サーバーと会話を開く",
  solicitacoes: "メッセージリクエスト",
  pedidos: "リクエスト",
  spam: "スパム",
  pedidosPendentes: "保留中のリクエスト",
  marcadosComoSpam: "スパムとして マーク済み",
  aceitar: "承認",
  ignorar: "無視",
  marcarSpam: "スパムにする",
  semPedidos: "保留中のリクエストはありません。",
  semPedidosDetalhe: "フレンドではないけれど同じサーバーにいる人は、あなたの会話に届く前にここに入ります。",
  semSpam: "スパムにしたものはありません。",
  semSpamDetalhe: "スパムフィルターが分けたもの、またはあなたがマークしたものは、このタブに残ります。",
  umServidorEmComum: "共通サーバー 1つ",
  servidoresEmComum: "共通サーバー {{quantos}}つ",
  semServidoresEmComum: "共通のサーバーなし",
};
