export const comum = {
  voltar: "戻る",
  agoraNao: "今はやめておく",
  erro: {
    tentarDeNovo: "もう一度",
    recarregar: "再読み込み",
    copiarDetalhes: "詳細をコピー",
    parteQuebrou: "画面のこの部分が壊れました。",
    titulo: "Ravox Chat がつまずきました。",
    detalhe: "途中で何かが壊れ、画面を描けませんでした。会話は失われていません — すべてサーバーにあります。",
  },
  perdido: {
    titulo: "このアドレスはどこにもつながりません。",
    detalhe: "リンクが間違っているか、ページが移動しました。",
  },
  conexao: {
    voltou: "また接続しました",
    reconectando: "再接続中",
    tentativaSufixo: " ・{{numero}} 回目",
    aSalvo: "会話はサーバーに無事あります。接続が戻れば自動で元どおりになります。",
  },
  avisoDoNavegador: {
    titulo: "メッセージの通知を受け取りますか？",
    detalhe: "Ravox Chat が別のウィンドウの後ろにあるとき、知らせてくれます。",
  },
  atualizacao: {
    titulo: "アップデート",
    semAuto: "このバージョンのアプリは自動で更新できません。下から最新のインストーラーを入手して、上書きインストールしてください。",
    versaoAtual: "現在のバージョンは {{versao}} です。",
    instalando: "バージョン {{versao}} をインストール中…",
    prontaVersao: "バージョン {{versao}} のインストール準備ができました",
    baixandoVersao: "バージョン {{versao}} をダウンロード中…",
    baixandoComProgresso: "バージョン {{versao}} をダウンロード中… {{porcento}}%",
    saiuVersao: "バージョン {{versao}} が出ました",
    saiuVersaoClique: "バージョン {{versao}} が出ました — クリックでダウンロード",
    instalarVersaoEReiniciar: "バージョン {{versao}} をインストールして再起動",
    erroTenteDeNovo: "{{erro}} クリックでもう一度お試しください。",
    procurando: "確認中…",
    emDia: "最新の状態です",
    vaiFechar: "まもなくアプリが閉じます。",
    comoInstala: "アプリが閉じ、バージョンを入れ替えて自動で開き直します。通話中の場合は退出します。",
    semServidor: "バージョンサーバーに接続できませんでした。",
    procuraSozinho: "アプリは起動時と6時間ごとに自動で確認します。",
    instalandoReticencias: "インストール中…",
    instalandoCurto: "インストール中",
    baixandoCurto: "ダウンロード中",
    tentarDeNovo: "もう一度",
    reiniciarAgora: "今すぐ再起動",
    instalarEReiniciar: "インストールして再起動",
    baixar: "ダウンロード",
    procurar: "確認",
    baixarApp: "アプリをダウンロード",
    ariaBotao: "アプリのアップデート",
  },
  janela: {
    ajustarAltura: "高さを調整",
    redimensionar: "ウィンドウの大きさを変える",
    ajustarLargura: "幅を調整",
  },
  dica: {
    rotulo: "ヒント:",
    pularConfirmacao: "Shift を押しながらクリックすると、この確認を飛ばせます。",
  },
  cor: {
    pescar: "画面から色を拾う",
    hex: "16進数の値",
  },
  imagem: {
    titulo: "画像を選ぶ",
    enviar: "画像を送る",
    escolherGif: "GIF を選ぶ",
    buscarGif: "GIF を検索",
  },
  fonte: {
    rotulo: "メッセージのフォント",
    padrao: "標準",
    comNome: "メッセージのフォント — {{fonte}}",
  },
  recorte: {
    titulo: "アイコンを切り抜く",
    detalhe: "ドラッグして範囲を決め、スライダーで拡大します。アイコンはアプリのどこでも丸く表示されます。",
    voltarAoComeco: "最初に戻す",
    usar: "この切り抜きを使う",
  },
  mais: "その他",
  carregando: "読み込み中…",
  salvar: "保存",
  salvando: "保存中…",
  descartar: "破棄",
  redefinir: "リセット",
  naoSalvo: "保存していない変更があります。",
  fechar: "閉じる",
  criar: "作成",
  nome: "名前",
  emoji: "絵文字",
  previa: "プレビュー",
  cancelar: "キャンセル",
  enviar: "送信",
  apagar: "削除",
  excluir: "削除",
  remover: "外す",
  trocar: "変更",
  loginNoApp: {
    titulo: "準備完了！",
    detalhe: "ログインしました。Ravox Chat に戻ってください。アプリが待っています。",
    abrir: "Ravox Chat を開く",
    fecharAba: "このタブは閉じてかまいません。",
    falhouTitulo: "ログインできませんでした",
    falhouDetalhe: "アプリに戻って、もう一度ログインしてください。",
    legenda: "手を振るロボット",
    legendaFalhou: "泣いている子猫",
  },
  ads: {
    label: "広告",
    title: "ここに広告を",
    detail: "ご連絡ください。Ravox Chat を使う人たちに届きます。",
    action: "広告を出したい",
  },
};
