export const amizades = {
  mensagensDiretas: "Особисті повідомлення",
  nova: {
    titulo: "Нова розмова",
    detalhe: "Оберіть друга, і розмова відкриється.",
    procurar: "Знайти друга",
    semAmigos: "Тут у вас поки немає друзів.",
    semResultado: "Друга з таким іменем немає.",
  },
  adicionar: {
    recado: "Напишіть кілька слів (за бажанням)",
    recadoDica: "Те, що ви напишете тут, з'явиться і у вашій розмові, якщо потоваришуєте.",
    enviadoPara: "Готово. Запит у друзі пішов до {{nome}}.",
    outrosLugares: "Де ще можна познайомитися",
    outrosLugaresDetalhe: "Ніхто не спадає на думку? Зазирніть у відкриті спільноти, там говорять майже про все.",
    explorarComunidades: "Переглянути спільноти",
    titulo: "Додати друга",
    detalhe: "Друзів можна додавати за їхнім іменем користувача.",
    exemplo: "Ім'я користувача, наприклад: thiago",
    enviando: "Надсилаю…",
    enviar: "Надіслати запит",
  },
  gatinhoChorando: "Кошеня, що плаче",
  status: {
    emChamada: "У дзвінку",
    emVoz: "У голосовому",
  },
  menu: {
    chamada: "Почати дзвінок",
    fixar: "Закріпити вгорі",
    desafixar: "Відкріпити",
    silenciar: "Вимкнути звук розмови",
    reativar: "Увімкнути звук розмови",
    copiarIdDoCanal: "Копіювати ID каналу",
  },
  ativosAgora: "Зараз активні",
  procurando: "Дивимось, хто поруч…",
  tudoTranquilo: "Поки тихо…",
  tudoTranquiloDetalhe: "Коли ви або друг зайдете в дзвінок, він з'явиться тут — і ви приєднаєтесь одним кліком.",
  emVoz: "У голосовому",
  voce: "Ви",
  soVoce: "Тільки ви",
  pessoas: "{{quantas}} осіб",
  voltarParaChamada: "Повернутися до дзвінка",
  entrarNaChamada: "Приєднатися",
  abrirCanal: "Відкрити {{canal}} на {{servidor}}",
  encontreConversa: "Знайти розмову",
  amigos: "Друзі",
  conversas: "Розмови",
  semConversas: "Розмов поки немає. Додайте друга, щоб почати.",
  semConversaComEsseNome: "Немає розмови з такою назвою.",
  abrirMenu: "Відкрити сервери та розмови",
  solicitacoes: "Запити на листування",
  pedidos: "Запити",
  spam: "Спам",
  pedidosPendentes: "Запити, що очікують",
  marcadosComoSpam: "Позначені як спам",
  aceitar: "Прийняти",
  ignorar: "Ігнорувати",
  marcarSpam: "Позначити як спам",
  semPedidos: "Немає запитів в очікуванні.",
  semPedidosDetalhe: "Той, хто вам не друг, але перебуває з вами на одному сервері, потрапляє сюди, не доходячи до ваших розмов.",
  semSpam: "Нічого не позначено як спам.",
  semSpamDetalhe: "Те, що відсіє фільтр спаму, або те, що позначите ви, залишиться на цій вкладці.",
  umServidorEmComum: "1 спільний сервер",
  servidoresEmComum: "Спільних серверів: {{quantos}}",
  semServidoresEmComum: "Спільних серверів немає",
};
