export const comum = {
  voltar: "Назад",
  agoraNao: "Не зараз",
  erro: {
    tentarDeNovo: "Спробувати ще раз",
    recarregar: "Перезавантажити",
    copiarDetalhes: "Скопіювати подробиці",
    parteQuebrou: "Ця частина екрана зламалася.",
    titulo: "Ravox Chat перечепився.",
    detalhe: "Дорогою щось зламалося, і екран не зміг намалюватися. Ваша розмова не загубилася — усе на сервері.",
  },
  perdido: {
    titulo: "Ця адреса нікуди не веде.",
    detalhe: "Або посилання хибне, або сторінка переїхала.",
  },
  conexao: {
    voltou: "Знову на зв'язку",
    reconectando: "Перепідключаюся",
    tentativaSufixo: " · спроба {{numero}}",
    aSalvo: "Розмова в безпеці на сервері. Усе повернеться саме, щойно з'явиться зв'язок.",
  },
  avisoDoNavegador: {
    titulo: "Хочете сповіщення про повідомлення?",
    detalhe: "Коли Ravox Chat за іншим вікном, він вас покличе.",
  },
  atualizacao: {
    titulo: "Оновлення",
    semAuto: "Ця версія застосунку не вміє оновлюватися сама. Завантажте нижче найновіший інсталятор і встановіть його поверх.",
    versaoAtual: "У вас версія {{versao}}.",
    instalando: "Встановлюється версія {{versao}}…",
    prontaVersao: "Версія {{versao}} готова до встановлення",
    baixandoVersao: "Завантажується версія {{versao}}…",
    baixandoComProgresso: "Завантажується версія {{versao}}… {{porcento}} %",
    saiuVersao: "Вийшла версія {{versao}}",
    saiuVersaoClique: "Вийшла версія {{versao}} — натисніть, щоб завантажити",
    instalarVersaoEReiniciar: "Встановити версію {{versao}} і перезапустити",
    erroTenteDeNovo: "{{erro}} Натисніть, щоб спробувати ще раз.",
    procurando: "Шукаю…",
    emDia: "У вас усе найновіше",
    vaiFechar: "Застосунок зачиниться за мить.",
    comoInstala: "Застосунок закривається, міняє версію і сам відкривається знову. Якщо ви в дзвінку, то вийдете з нього.",
    semServidor: "Не вдалося зв'язатися із сервером версій.",
    procuraSozinho: "Застосунок перевіряє сам під час запуску і кожні шість годин.",
    instalandoReticencias: "Встановлюю…",
    instalandoCurto: "Встановлюю",
    baixandoCurto: "Завантажую",
    tentarDeNovo: "Спробувати ще раз",
    reiniciarAgora: "Перезапустити зараз",
    instalarEReiniciar: "Встановити і перезапустити",
    baixar: "Завантажити",
    procurar: "Перевірити",
    baixarApp: "Завантажити застосунок",
    ariaBotao: "Оновлення застосунку",
  },
  janela: {
    ajustarAltura: "Налаштувати висоту",
    redimensionar: "Змінити розмір вікна",
    ajustarLargura: "Налаштувати ширину",
  },
  dica: {
    rotulo: "Порада:",
    pularConfirmacao: "утримуйте Shift під час кліку, щоб пропустити це підтвердження.",
  },
  cor: {
    pescar: "Узяти колір з екрана",
    hex: "Шістнадцяткове значення",
  },
  imagem: {
    titulo: "Виберіть зображення",
    enviar: "Надіслати зображення",
    escolherGif: "Вибрати GIF",
    buscarGif: "Пошук GIF",
  },
  fonte: {
    rotulo: "Шрифт повідомлення",
    padrao: "Типовий",
    comNome: "Шрифт повідомлення — {{fonte}}",
  },
  recorte: {
    titulo: "Обрізати піктограму",
    detalhe: "Перетягніть, щоб вибрати потрібну частину, і наблизьте повзунком. Піктограма скрізь у застосунку кругла.",
    voltarAoComeco: "Повернутися на початок",
    usar: "Використати це обрізання",
  },
  mais: "Більше",
  carregando: "Завантаження…",
  salvar: "Зберегти",
  salvando: "Збереження…",
  descartar: "Скасувати",
  redefinir: "Скинути",
  naoSalvo: "У вас є незбережені зміни.",
  fechar: "Закрити",
  criar: "Створити",
  nome: "Назва",
  emoji: "Емодзі",
  previa: "Перегляд",
  cancelar: "Скасувати",
  enviar: "Надіслати",
  apagar: "Видалити",
  excluir: "Видалити",
  remover: "Прибрати",
  trocar: "Змінити",
  loginNoApp: {
    titulo: "Усе готово!",
    detalhe: "Ви увійшли в акаунт. Повертайтеся в Ravox Chat — застосунок уже чекає.",
    abrir: "Відкрити Ravox Chat",
    fecharAba: "Цю вкладку можна закрити.",
    falhouTitulo: "Не вдалося увійти",
    falhouDetalhe: "Поверніться в застосунок і спробуйте ще раз.",
    legenda: "Робот махає рукою",
    legendaFalhou: "Котеня плаче",
  },
  ads: {
    label: "Реклама",
    title: "Розмістіть рекламу тут",
    detail: "Напишіть нам і покажіться тим, хто користується Ravox Chat.",
    action: "Хочу рекламуватися",
  },
};
