export const configuracoes = {
  efeitos: {
    titulo: "Ефекти вказівника",
    detalhe: "Слід та іскри, намальовані поверх застосунку. Приходять вимкненими й гаснуть самі, якщо ви просили менше руху.",
    rastro: "Слід курсора",
    rastroDetalhe: "Лінія, що йде за вказівником і тане позаду.",
    faisca: "Іскри при клацанні",
    faiscaDetalhe: "Короткі рисочки, що розлітаються з місця клацання.",
    cor: "Колір",
    espessura: "Товщина",
    comprimento: "Довжина",
    tamanho: "Розмір",
    quantidade: "Кількість",
  },
  email: {
    verificarTitulo: "Підтвердьте свою пошту",
    verificarDetalhe: "Деякі спільноти пускають писати лише підтверджених. Це один клац.",
    enviar: "Надіслати посилання",
    enviado: "Загляньте до пошти. Посилання живе добу.",
    falhou: "Листа надіслати не вдалося.",
    confirmado: "Пошту підтверджено",
    confirmadoDetalhe: "Готово. Тепер ви пишете в будь-якій спільноті, що цього вимагає.",
    linkIncompleto: "Посилання неповне",
    linkIncompletoDetalhe: "В адресі бракує коду. Відкрийте посилання просто з листа.",
    confirmando: "Підтверджуємо…",
    expirou: "Це посилання вже використали або воно протермінувалося.",
    irParaOApp: "До застосунку",
  },
  tema: {
    indisponivel: "Тема недоступна",
    indisponivelDetalhe: "Той, хто її опублікував, видалив її, або посилання хибне.",
    indisponivelLinha: "Тема недоступна. Той, хто її опублікував, видалив її, або посилання хибне.",
    importar: "Імпортувати тему",
    importarCurto: "Імпортувати",
    importarDetalhe: "Це замінить тему, яку ви маєте зараз. Відредагувати її можна потім: Налаштування > Вигляд > Студія тем.",
    porAutor: "автор: {{autor}}",
    umaCorTrocada: "замінено 1 колір",
    coresTrocadas: "замінено кольорів: {{quantas}}",
    avisoDeCss: "Ця тема несе CSS свого автора, а CSS дістає до будь-якого куточка екрана. Імпортуйте лише від людей, яким довіряєте.",
    soCores: "Ця тема міняє тільки кольори. Жодного стороннього CSS.",
    verCss: "Показати CSS",
    esconderCss: "Сховати CSS",
    aplicar: "Застосувати",
    previaSemMotor: "У перегляді рушій не працює. Установіть, щоб побачити.",
    motorAnimado: "{{motor}}, з анімацією",
  },
  sair: "Вийти",
  versoes: {
    termos: "Умови надання послуг",
    privacidade: "Політика конфіденційності",
    copiar: "Натисніть, щоб копіювати",
    copiado: "Скопійовано",
  },
  appColors: {
    title: "Кольори застосунку",
    detail: "Виберіть до трьох кольорів, і весь застосунок отримає цей градієнт.",
    locked: "Редактор кольорів входить до {{plan}}.",
    color: "Колір {{number}}",
    addColor: "Додати колір",
    removeColor: "Прибрати колір",
    surprise: "Здивуй мене",
    direction: "Напрямок градієнта",
    intensity: "Інтенсивність",
    reset: "Скинути",
  },
  subscription: {
    colorsRow: "Редактор кольорів застосунку",
    seePlans: "Переглянути плани",
    upgradeSubtitle: "Більші ліміти й ексклюзивні функції для повідомлень, файлів і трансляцій.",
    perMonth: "на місяць",
    perYear: "на рік",
    save: "Економія {{percent}}%",
    howToPay: "Як ви хочете оплатити?",
    legal: "Повернути гроші можна протягом 7 днів після оплати. Платіж обробляє Stripe; ми ніколи не бачимо номер вашої картки.",
    compare: "Безкоштовно і Infinity",
    featureColumn: "Функція",
    freeColumn: "Безкоштовно",
    messageRow: "Ліміт символів у повідомленні",
    attachmentRow: "Розмір файлу для надсилання",
    screenRow: "Якість відео",
    megabytesValue: "{{value}} МБ",
    screenValue: "{{resolution}} · {{fps}} кадрів/с",
    alreadyPremium: "У вас уже є Infinity до {{date}}.",
    upsell: "Збільшити ліміт з Infinity",
    screenUpsell: "Більше якості з Infinity",
    free: "У вас безкоштовний план.",
    activeUntil: "Infinity активний до {{date}}.",
    renews: "Автоматично продовжиться {{date}}.",
    endsAt: "Підписку скасовано, вона завершиться {{date}}.",
    pastDue: "Останнє списання не пройшло. Оновіть картку, щоб не втратити Infinity.",
    waiting: "Підтверджуємо оплату…",
    subscribe: "Оформити підписку",
    monthly: "Щомісяця",
    yearly: "Щороку",
    automatic: "Картка",
    manage: "Керувати оплатою",
    refund: "Запросити повернення",
    refundDetail: "Відмовитися можна протягом 7 днів після оплати: {{amount}}, до {{date}}.",
    refundConfirm: "Запросити повернення?",
    refundConfirmDetail: "Гроші повернуться тим самим способом оплати, а Infinity завершиться одразу.",
    refunded: "Повернення запрошено.",
    unavailable: "Підписка поки недоступна.",
    success: "Оплату отримано. Дякуємо!",
    canceled: "Оплату скасовано.",
    error: "Щось пішло не так. Спробуйте ще раз.",
    no: "Ні",
    tagRow: "Власний тег користувача",
    guildProfilesRow: "Профілі для спільнот",
    badgeRow: "Значок профілю",
    communitiesRow: "Спільноти",
    savedRow: "Збережені повідомлення",
    animatedEmojiRow: "Анімовані емодзі",
    expressionsRow: "Емодзі й стікери звідусіль",
    animatedProfileRow: "Анімовані аватари й банери",
    earlyAccessRow: "Ранній доступ до новинок",
    themesRow: "Власні теми",
    pixOption: "Pix",
    pixHint: "Відкрийте застосунок банку, виберіть Pix і відскануйте QR-код або скопіюйте код.",
    pixQrAlt: "QR-код Pix",
    pixCopy: "Скопіювати код Pix",
    pixCopied: "Код Pix скопійовано",
    pixWaiting: "Очікуємо оплату",
    pixExpiresIn: "спливає через {{time}}",
    pixExpired: "Термін цього Pix минув. Створіть новий, щоб продовжити.",
    pixNew: "Створити новий Pix",
    pixPaid: "Pix отримано! Infinity вже активний.",
    forMe: "Собі",
    asGift: "У подарунок",
    buyGift: "Купити подарунок",
    giftReady: "Подарунок готовий! Скопіюйте посилання й надішліть кому хочете.",
    giftClaimed: "Подарунок активовано! Infinity вже на вашому акаунті.",
    gifts: "Подарунки",
    giftsEmpty: "Ви ще не купували подарунків.",
    giftCode: "Код подарунка",
    giftRedeem: "Активувати",
    giftCopyLink: "Скопіювати посилання",
    giftLinkCopied: "Посилання скопійовано",
    giftClaimedBy: "активував {{name}}",
    giftHint: "Маєте код подарунка? Активуйте його тут. Куплені подарунки — нижче.",
    cardPaid: "Оплату підтверджено! Ваш Infinity активний.",
    payAmount: "Оплатити {{amount}}",
    giftLinkTitle: "Вам подарували {{plan}}!",
    giftLinkDetail: "Натисніть активувати, і дні з'являться на вашому акаунті.",
    pageTitle: "Відкрийте світ переваг із {{plan}}",
    pageStart: "Головна",
    pageBest: "Найкраще в Infinity",
    pageChoose: "Оберіть свій план",
    fromPrice: "Від {{amount}} на місяць. Скасуйте будь-коли.",
    filesTitle: "Надсилайте файл цілком",
    filesText: "Відео з вечірки, робочий проєкт, тека з фотографіями — усе йде за один раз, без нарізання, без архівів і без посилання на хмару посередині.",
    videoTitle: "Транслюйте в 1080p",
    videoText: "Ваш екран приходить чітким до того, хто дивиться, і з удвічі більшою кількістю кадрів за секунду. Можна читати код і грати разом, а не вдивлятися в розмиту пляму.",
    messageTitle: "Пишіть скільки заманеться",
    messageText: "Удвічі більше символів у кожному повідомленні — для тих випадків, коли історія довга, а розбити її на три частини означало б усе зіпсувати.",
    colorsTitle: "Застосунок із вашим обличчям",
    colorsText: "Обирайте кольори застосунку один за одним, збережіть тему й візьміть її на всі пристрої, де ви входите.",
    profileTitle: "Свій профіль для кожного місця",
    profileText: "Інший псевдонім, інше фото, інший опис у кожній спільноті — і анімоване фото, якщо захочете.",
    freeDetail: "Це безкоштовно й таким залишається.",
    currentPlan: "Ваш поточний план",
    popular: "Обирають найчастіше",
    yearlyDetail: "Виходить {{amount}} на місяць, списується раз на рік.",
    monthlyDetail: "Списується щомісяця, скасування будь-коли.",
    groupStyle: "Покажіть свій стиль",
    groupLook: "Налаштуйте застосунок під себе",
    groupLimits: "Без тісних лімітів",
    closingTitle: "То чого ж ви чекаєте?",
    pagePlans: "Плани",
    pageCompare: "Порівняти",
    giftClaimTitle: "Активувати {{plan}}?",
    giftClaimDetail: "Це {{days}} днів, які з'являться на акаунті зараз.",
    giftFrom: "від {{name}}",
    giftActivate: "Активувати",
    giftHasPlanTitle: "У вас уже є Infinity",
    giftHasPlanDetail: "Ваш план до {{date}}. Збережіть посилання й надішліть другові.",
    giftUsedTitle: "Цей подарунок уже використано",
    giftUsedDetail: "Хтось активував код раніше. Попросіть інший.",
    giftNotFoundTitle: "Код не знайдено",
    giftNotFoundDetail: "Перевірте код або попросіть посилання ще раз.",
    giftDoneTitle: "{{plan}} активовано!",
    giftOpenApp: "Відкрити застосунок",
    giftSignIn: "Увійдіть, щоб активувати",
    giftReviewStep: "Оплата · Перевірка",
    giftTotalToday: "Разом сьогодні",
    giftCardWhy: "Картка потрібна лише щоб підтвердити, що це ви. Зараз нічого не списується і нічого не продовжується саме.",
    giftAgree: "Я прочитав і приймаю умови користування",
    giftActivating: "Активуємо…",
  },
  telas: {
    subscription: "Infinity",
    conta: "Мій обліковий запис",
    privacidade: "Конфіденційність",
    conexoes: "Підключення",
    voz: "Звук",
    video: "Відео",
    avisos: "Сповіщення",
    aplicativos: "Застосунки",
    aparencia: "Вигляд",
    batePapo: "Чат",
    acessibilidade: "Доступність",
    idioma: "Мова",
    aplicativo: "Завантажити застосунок",
    atalhos: "Гарячі клавіші",
    desktop: "Застосунок для комп’ютера",
    avancado: "Додатково",
    servidor: "Сервер",
    comunicado: "Системне оголошення",
    denuncias: "Скарги",
    publicacoes: "Розгортання",
  },
  grupos: {
    conta: "Обліковий запис",
    app: "Налаштування застосунку",
    desenvolvedor: "Розробник",
    administracao: "Адміністрування",
  },
  secoes: {
    coresDoApp: "Кольори застосунку",
    detalhesDeLogin: "Дані для входу",
    dispositivos: "Пристрої",
    usuariosBloqueados: "Заблоковані користувачі",
    aplicativosAutorizados: "Авторизовані застосунки",
    sessoes: "Сеанси",
    amigosEDms: "Друзі та особисті повідомлення",
    compartilhamentoDeAtividade: "Поширення активності",
    visibilidadeDoPerfil: "Видимість профілю",
    exportarDados: "Експорт даних",
    exclusaoDeDados: "Видалення даних",
    tema: "Тема",
    corDeDestaque: "Колір акценту",
    interface: "Інтерфейс",
    listaDeCanais: "Список каналів",
    zoomDoApp: "Масштаб застосунку",
    escalaDaFonte: "Розмір шрифту в чаті",
    modoStreamer: "Приватність під час трансляції",
    cursores: "Курсори",
    movimento: "Рух",
    textoEmVoz: "Текст у мовлення",
    teclado: "Клавіатура",
    formatoDaHora: "Формат часу",
    idiomaDaInterface: "Мова інтерфейсу",
    dispositivosDeVoz: "Пристрої",
    testeDoMicrofone: "Перевірка мікрофона",
    modoDeEntrada: "Режим введення",
    sensibilidade: "Чутливість введення",
    qualidade: "Якість",
    camera: "Камера",
    transmissao: "Трансляція",
    exibicao: "Відображення",
    entrada: "Введення",
    midia: "Медіа",
    geral: "Загальні",
    preferenciaDeMencao: "Налаштування згадок",
    sons: "Звуки",
  },
};
