export const amizades = {
  mensagensDiretas: "Direktemeldinger",
  nova: {
    titulo: "Ny samtale",
    detalhe: "Velg en venn, så åpner samtalen seg.",
    procurar: "Finn en venn",
    semAmigos: "Du har ingen venner her ennå.",
    semResultado: "Ingen venn med det navnet.",
  },
  adicionar: {
    recado: "Skriv et par ord (valgfritt)",
    recadoDica: "Det du skriver her, dukker også opp i samtalen deres hvis dere blir venner.",
    enviadoPara: "Ferdig. Venneforespørselen gikk til {{nome}}.",
    outrosLugares: "Andre steder å bli kjent med folk",
    outrosLugaresDetalhe: "Kommer du ikke på noen? Ta en titt på de åpne fellesskapene, der snakkes det om nesten alt.",
    explorarComunidades: "Utforsk fellesskap",
    titulo: "Legg til venn",
    detalhe: "Du kan legge til venner med brukernavnet deres.",
    exemplo: "Brukernavn, f.eks.: thiago",
    enviando: "Sender…",
    enviar: "Send forespørsel",
  },
  gatinhoChorando: "En gråtende kattunge",
  status: {
    emChamada: "I en samtale",
    emVoz: "I tale",
  },
  menu: {
    chamada: "Start samtale",
    fixar: "Fest øverst",
    desafixar: "Løsne",
    silenciar: "Demp samtalen",
    reativar: "Slå på varsler igjen",
    copiarIdDoCanal: "Kopier kanalens ID",
  },
  ativosAgora: "Aktive nå",
  procurando: "Ser hvem som er her…",
  tudoTranquilo: "Det er stille akkurat nå…",
  tudoTranquiloDetalhe: "Når du eller en venn blir med i en samtale, dukker den opp her — og du kan hoppe inn med ett klikk.",
  emVoz: "I tale",
  voce: "Du",
  soVoce: "Bare du",
  pessoas: "{{quantas}} personer",
  voltarParaChamada: "Tilbake til samtalen",
  entrarNaChamada: "Bli med i samtalen",
  abrirCanal: "Åpne {{canal}} på {{servidor}}",
  encontreConversa: "Finn en samtale",
  amigos: "Venner",
  conversas: "Samtaler",
  semConversas: "Ingen samtaler ennå. Legg til en venn for å komme i gang.",
  semConversaComEsseNome: "Ingen samtale med det navnet.",
  abrirMenu: "Åpne servere og samtaler",
  solicitacoes: "Meldingsforespørsler",
  pedidos: "Forespørsler",
  spam: "Spam",
  pedidosPendentes: "Ventende forespørsler",
  marcadosComoSpam: "Merket som spam",
  aceitar: "Godta",
  ignorar: "Ignorer",
  marcarSpam: "Merk som spam",
  semPedidos: "Ingen forespørsler venter.",
  semPedidosDetalhe: "Den som ikke er vennen din, men deler en server med deg, havner her før det når samtalene dine.",
  semSpam: "Ingenting merket som spam.",
  semSpamDetalhe: "Det spamfilteret siler ut, eller det du merker selv, blir i denne fanen.",
  umServidorEmComum: "1 felles server",
  servidoresEmComum: "{{quantos}} felles servere",
  semServidoresEmComum: "Ingen felles servere",
};
