export const comum = {
  voltar: "Tilbake",
  agoraNao: "Ikke nå",
  erro: {
    tentarDeNovo: "Prøv igjen",
    recarregar: "Last inn på nytt",
    copiarDetalhes: "Kopier detaljene",
    parteQuebrou: "Denne delen av skjermen røk.",
    titulo: "Ravox Chat snublet.",
    detalhe: "Noe røk underveis, og skjermen klarte ikke å tegne seg. Samtalen din er ikke borte — alt ligger på tjeneren.",
  },
  perdido: {
    titulo: "Denne adressen fører ingen steder.",
    detalhe: "Enten er lenken feil, eller så har siden flyttet.",
  },
  conexao: {
    voltou: "Tilkoblet igjen",
    reconectando: "Kobler til igjen",
    tentativaSufixo: " · forsøk {{numero}}",
    aSalvo: "Samtalen ligger trygt på tjeneren. Dette kommer av seg selv så snart forbindelsen er tilbake.",
  },
  avisoDoNavegador: {
    titulo: "Vil du få beskjed om meldinger?",
    detalhe: "Når Ravox Chat ligger bak et annet vindu, roper den på deg.",
  },
  atualizacao: {
    titulo: "Oppdatering",
    semAuto: "Denne versjonen av appen kan ikke oppdatere seg selv. Last ned det nyeste installasjonsprogrammet nedenfor og installer oppå.",
    versaoAtual: "Du har versjon {{versao}}.",
    instalando: "Installerer versjon {{versao}}…",
    prontaVersao: "Versjon {{versao}} er klar til installasjon",
    baixandoVersao: "Laster ned versjon {{versao}}…",
    baixandoComProgresso: "Laster ned versjon {{versao}}… {{porcento}} %",
    saiuVersao: "Versjon {{versao}} er ute",
    saiuVersaoClique: "Versjon {{versao}} er ute — klikk for å laste ned",
    instalarVersaoEReiniciar: "Installer versjon {{versao}} og start på nytt",
    erroTenteDeNovo: "{{erro}} Klikk for å prøve igjen.",
    procurando: "Leter…",
    emDia: "Du er oppdatert",
    vaiFechar: "Appen lukkes om et øyeblikk.",
    comoInstala: "Appen lukkes, bytter versjon og åpner seg selv igjen. Er du i en samtale, forlater du den.",
    semServidor: "Jeg fikk ikke kontakt med versjonstjeneren.",
    procuraSozinho: "Appen ser etter selv ved oppstart og hver sjette time.",
    instalandoReticencias: "Installerer…",
    instalandoCurto: "Installerer",
    baixandoCurto: "Laster ned",
    tentarDeNovo: "Prøv igjen",
    reiniciarAgora: "Start på nytt nå",
    instalarEReiniciar: "Installer og start på nytt",
    baixar: "Last ned",
    procurar: "Se etter",
    baixarApp: "Last ned appen",
    ariaBotao: "Oppdatering av appen",
  },
  janela: {
    ajustarAltura: "Juster høyden",
    redimensionar: "Endre størrelsen på vinduet",
    ajustarLargura: "Juster bredden",
  },
  dica: {
    rotulo: "Tips:",
    pularConfirmacao: "hold Shift mens du klikker for å hoppe over denne bekreftelsen.",
  },
  cor: {
    pescar: "Hent en farge fra skjermen",
    hex: "Heksadesimal verdi",
  },
  imagem: {
    titulo: "Velg et bilde",
    enviar: "Send bilde",
    escolherGif: "Velg GIF",
    buscarGif: "Søk etter GIF",
  },
  fonte: {
    rotulo: "Skrift i meldingen",
    padrao: "Standard",
    comNome: "Skrift i meldingen — {{fonte}}",
  },
  recorte: {
    titulo: "Beskjær ikonet",
    detalhe: "Dra for å velge utsnittet, og bruk glidebryteren for å zoome. Ikonet er rundt overalt i appen.",
    voltarAoComeco: "Tilbake til start",
    usar: "Bruk dette utsnittet",
  },
  mais: "Mer",
  carregando: "Laster…",
  salvar: "Lagre",
  salvando: "Lagrer…",
  descartar: "Forkast",
  redefinir: "Tilbakestill",
  naoSalvo: "Du har ulagrede endringer.",
  fechar: "Lukk",
  criar: "Opprett",
  nome: "Navn",
  emoji: "Emoji",
  previa: "Forhåndsvisning",
  cancelar: "Avbryt",
  enviar: "Send",
  apagar: "Slett",
  excluir: "Slett",
  remover: "Fjern",
  trocar: "Bytt",
  loginNoApp: {
    titulo: "Alt klart!",
    detalhe: "Du er logget inn. Gå tilbake til Ravox Chat, appen venter på deg.",
    abrir: "Åpne Ravox Chat",
    fecharAba: "Du kan lukke denne fanen nå.",
    falhouTitulo: "Innloggingen mislyktes",
    falhouDetalhe: "Gå tilbake til appen og prøv å logge inn igjen.",
    legenda: "En robot som vinker",
    legendaFalhou: "En gråtende kattunge",
  },
  ads: {
    label: "Annonse",
    title: "Annonser her",
    detail: "Snakk med oss og bli sett av dem som bruker Ravox Chat.",
    action: "Jeg vil annonsere",
  },
};
