export const configuracoes = {
  efeitos: {
    titulo: "Effekter for pekeren",
    detalhe: "Spor og gnister tegnet oppå appen. De starter av, og slår seg av selv om du ba om mindre bevegelse.",
    rastro: "Spor etter pekeren",
    rastroDetalhe: "En strek som følger pekeren og falmer bak.",
    faisca: "Gnist ved klikk",
    faiscaDetalhe: "Korte streker som spretter ut fra der du klikket.",
    cor: "Farge",
    espessura: "Tykkelse",
    comprimento: "Lengde",
    tamanho: "Størrelse",
    quantidade: "Antall",
  },
  email: {
    verificarTitulo: "Bekreft e-posten din",
    verificarDetalhe: "Noen fellesskap lar bare de bekreftede skrive. Det tar ett klikk.",
    enviar: "Send lenken",
    enviado: "Se i innboksen. Lenken holder en dag.",
    falhou: "E-posten lot seg ikke sende.",
    confirmado: "E-post bekreftet",
    confirmadoDetalhe: "Ferdig. Nå skriver du i alle fellesskap som krever det.",
    linkIncompleto: "Ufullstendig lenke",
    linkIncompletoDetalhe: "Koden mangler i adressen. Åpne lenken rett fra e-posten.",
    confirmando: "Bekrefter…",
    expirou: "Denne lenken er allerede brukt eller utløpt.",
    irParaOApp: "Gå til appen",
  },
  tema: {
    indisponivel: "Temaet er ikke tilgjengelig",
    indisponivelDetalhe: "Den som la det ut har slettet det, eller lenken er feil.",
    indisponivelLinha: "Temaet er ikke tilgjengelig. Den som la det ut har slettet det, eller lenken er feil.",
    importar: "Importer tema",
    importarCurto: "Importer",
    importarDetalhe: "Dette bytter ut temaet du har nå. Du kan redigere det etterpå i Innstillinger > Utseende > Temastudio.",
    porAutor: "av {{autor}}",
    umaCorTrocada: "1 farge byttet",
    coresTrocadas: "{{quantas}} farger byttet",
    avisoDeCss: "Dette temaet har med seg CSS fra den som skrev det, og CSS når hver krok av skjermen. Importer bare fra folk du stoler på.",
    soCores: "Dette temaet bytter bare farger. Ingen CSS utenfra.",
    verCss: "Vis CSS",
    esconderCss: "Skjul CSS",
    aplicar: "Bruk",
    previaSemMotor: "Forhåndsvisningen kjører ikke motoren. Installer for å se den.",
    motorAnimado: "{{motor}} animert",
  },
  sair: "Logg ut",
  versoes: {
    termos: "Vilkår for bruk",
    privacidade: "Personvernerklæring",
    copiar: "Klikk for å kopiere",
    copiado: "Kopiert",
  },
  appColors: {
    title: "Appens farger",
    detail: "Velg opptil tre farger, så får hele appen den gradienten.",
    locked: "Fargeredigereren hører til {{plan}}.",
    color: "Farge {{number}}",
    addColor: "Legg til farge",
    removeColor: "Fjern farge",
    surprise: "Overrask meg",
    direction: "Retning på gradienten",
    intensity: "Intensitet",
    reset: "Tilbakestill",
  },
  subscription: {
    colorsRow: "Appens fargeredigerer",
    seePlans: "Se planer",
    upgradeSubtitle: "Høyere grenser og eksklusive funksjoner for å skrive, sende filer og strømme.",
    perMonth: "per måned",
    perYear: "per år",
    save: "Spar {{percent}} %",
    howToPay: "Hvordan vil du betale?",
    legal: "Du kan be om refusjon innen 7 dager etter betalingen. Betalingen behandles av Stripe; vi ser aldri kortnummeret ditt.",
    compare: "Gratis mot Infinity",
    featureColumn: "Funksjon",
    freeColumn: "Gratis",
    messageRow: "Tegngrense per melding",
    attachmentRow: "Filstørrelse ved opplasting",
    screenRow: "Videokvalitet",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Du har allerede Infinity til {{date}}.",
    upsell: "Øk grensen med Infinity",
    screenUpsell: "Høyere kvalitet med Infinity",
    free: "Du bruker gratisplanen.",
    activeUntil: "Infinity aktiv til {{date}}.",
    renews: "Fornyes automatisk {{date}}.",
    endsAt: "Abonnementet er avsluttet og slutter {{date}}.",
    pastDue: "Den siste belastningen mislyktes. Oppdater kortet ditt for å beholde Infinity.",
    waiting: "Bekrefter betalingen…",
    subscribe: "Abonner",
    monthly: "Månedlig",
    yearly: "Årlig",
    automatic: "Kort",
    manage: "Administrer betaling",
    refund: "Be om refusjon",
    refundDetail: "Du kan angre innen 7 dager etter betalingen: {{amount}}, til {{date}}.",
    refundConfirm: "Be om refusjon?",
    refundConfirmDetail: "Pengene går tilbake til samme betalingsmåte, og Infinity avsluttes med en gang.",
    refunded: "Refusjon forespurt.",
    unavailable: "Abonnement er ikke tilgjengelig ennå.",
    success: "Betaling mottatt. Takk!",
    canceled: "Betalingen ble avbrutt.",
    error: "Noe gikk galt. Prøv igjen.",
    no: "Nei",
    tagRow: "Egen brukertagg",
    guildProfilesRow: "Profiler per fellesskap",
    badgeRow: "Profilmerke",
    communitiesRow: "Fellesskap",
    savedRow: "Lagrede meldinger",
    animatedEmojiRow: "Bruk animerte emojier",
    expressionsRow: "Bruk emojier og klistremerker overalt",
    animatedProfileRow: "Animerte avatarer og profilbannere",
    earlyAccessRow: "Tidlig tilgang til nyheter",
    themesRow: "Egne temaer",
    pixOption: "Pix",
    pixHint: "Åpne bankappen, velg Pix og skann QR-koden eller bruk kopier og lim inn.",
    pixQrAlt: "Pix-QR-kode",
    pixCopy: "Kopier Pix-kode",
    pixCopied: "Pix-koden er kopiert",
    pixWaiting: "Venter på betaling",
    pixExpiresIn: "utløper om {{time}}",
    pixExpired: "Denne Pix-en har utløpt. Lag en ny for å fortsette.",
    pixNew: "Lag ny Pix",
    pixPaid: "Pix mottatt! Infinity er nå aktivt.",
    forMe: "Til meg",
    asGift: "Som gave",
    buyGift: "Kjøp gave",
    giftReady: "Gaven er klar! Kopier lenken og send den til hvem du vil.",
    giftClaimed: "Gaven er løst inn! Infinity er på kontoen din.",
    gifts: "Gaver",
    giftsEmpty: "Du har ikke kjøpt noen gaver ennå.",
    giftCode: "Gavekode",
    giftRedeem: "Løs inn",
    giftCopyLink: "Kopier lenke",
    giftLinkCopied: "Lenken er kopiert",
    giftClaimedBy: "løst inn av {{name}}",
    giftHint: "Har du en gavekode? Løs den inn her. Gaver du har kjøpt står nedenfor.",
    cardPaid: "Betalingen ble godkjent! Infinity er aktivt.",
    payAmount: "Betal {{amount}}",
    giftLinkTitle: "Du har fått en {{plan}}-gave!",
    giftLinkDetail: "Trykk på løs inn, så havner dagene på kontoen din.",
    pageTitle: "Lås opp en verden av fordeler med {{plan}}",
    pageStart: "Start",
    pageBest: "Det beste med Infinity",
    pageChoose: "Velg planen din",
    fromPrice: "Fra {{amount}} i måneden. Si opp når du vil.",
    filesTitle: "Send hele fila",
    filesText: "Videoen fra festen, jobbprosjektet, mappa med bildene: alt går av gårde i én omgang, uten å dele opp, uten å pakke ned og uten en skylenke innimellom.",
    videoTitle: "Strøm i 1080p",
    videoText: "Skjermen din kommer skarpt fram hos den andre, med dobbelt så mange bilder i sekundet. Du kan lese kode og spille sammen uten at alt blir grøt.",
    messageTitle: "Skriv så mye du vil",
    messageText: "Dobbelt så mange tegn i hver melding, for når historien er lang og tre deler ville ødelagt poenget.",
    colorsTitle: "Appen i dine farger",
    colorsText: "Velg fargene i appen én etter én, lagre temaet og ta det med til alle enhetene du logger inn på.",
    profileTitle: "Én profil for hvert sted",
    profileText: "Et annet kallenavn, et annet bilde, en annen beskrivelse i hvert fellesskap — og levende bilde, om du vil.",
    freeDetail: "Det er gratis, og det fortsetter å være det.",
    currentPlan: "Planen du har nå",
    popular: "Mest valgt",
    yearlyDetail: "Det blir {{amount}} i måneden, trukket én gang i året.",
    monthlyDetail: "Trekkes hver måned, si opp når du vil.",
    groupStyle: "Vis stilen din",
    groupLook: "Gjør appen til din",
    groupLimits: "Ingen trange grenser",
    closingTitle: "Hva venter du på?",
    pagePlans: "Planer",
    pageCompare: "Sammenlign",
    giftClaimTitle: "Aktivere {{plan}}?",
    giftClaimDetail: "Det er {{days}} dager som havner på kontoen din nå.",
    giftFrom: "fra {{name}}",
    giftActivate: "Aktiver",
    giftHasPlanTitle: "Du har allerede Infinity",
    giftHasPlanDetail: "Planen din varer til {{date}}. Ta vare på lenken og send den til en venn.",
    giftUsedTitle: "Denne gaven er allerede brukt",
    giftUsedDetail: "Noen løste inn koden før. Be om en ny.",
    giftNotFoundTitle: "Fant ikke koden",
    giftNotFoundDetail: "Sjekk koden eller be om lenken på nytt.",
    giftDoneTitle: "{{plan}} aktivert!",
    giftOpenApp: "Åpne appen",
    giftSignIn: "Logg inn for å løse inn",
    giftReviewStep: "Betaling · Se over",
    giftTotalToday: "Totalt i dag",
    giftCardWhy: "Kortet er bare for å bekrefte at det er deg. Ingenting trekkes nå, og ingenting fornyes av seg selv.",
    giftAgree: "Jeg har lest og godtar bruksvilkårene",
    giftActivating: "Aktiverer…",
  },
  telas: {
    subscription: "Infinity",
    conta: "Min konto",
    privacidade: "Personvern",
    conexoes: "Tilkoblinger",
    voz: "Lyd",
    video: "Video",
    avisos: "Varsler",
    aplicativos: "Applikasjoner",
    aparencia: "Utseende",
    batePapo: "Chat",
    acessibilidade: "Tilgjengelighet",
    idioma: "Språk",
    aplicativo: "Last ned appen",
    atalhos: "Snarveier",
    desktop: "Skrivebordsapp",
    avancado: "Avansert",
    servidor: "Server",
    comunicado: "Systemmelding",
    denuncias: "Rapporter",
    publicacoes: "Utrullinger",
  },
  grupos: {
    conta: "Konto",
    app: "App-innstillinger",
    desenvolvedor: "Utvikler",
    administracao: "Administrasjon",
  },
  secoes: {
    coresDoApp: "Appens farger",
    detalhesDeLogin: "Innloggingsdetaljer",
    dispositivos: "Enheter",
    usuariosBloqueados: "Blokkerte brukere",
    aplicativosAutorizados: "Autoriserte apper",
    sessoes: "Økter",
    amigosEDms: "Venner og direktemeldinger",
    compartilhamentoDeAtividade: "Aktivitetsdeling",
    visibilidadeDoPerfil: "Profilens synlighet",
    exportarDados: "Eksporter data",
    exclusaoDeDados: "Slett data",
    tema: "Tema",
    corDeDestaque: "Aksentfarge",
    interface: "Grensesnitt",
    listaDeCanais: "Kanalliste",
    zoomDoApp: "Appens zoomnivå",
    escalaDaFonte: "Skriftstørrelse i chatten",
    modoStreamer: "Personvern under strømming",
    cursores: "Markører",
    movimento: "Bevegelse",
    textoEmVoz: "Tekst til tale",
    teclado: "Tastatur",
    formatoDaHora: "Tidsformat",
    idiomaDaInterface: "Grensesnittets språk",
    dispositivosDeVoz: "Enheter",
    testeDoMicrofone: "Mikrofontest",
    modoDeEntrada: "Inndatamodus",
    sensibilidade: "Inndatafølsomhet",
    qualidade: "Kvalitet",
    camera: "Kamera",
    transmissao: "Sending",
    exibicao: "Visning",
    entrada: "Inndata",
    midia: "Medier",
    geral: "Generelt",
    preferenciaDeMencao: "Omtalepreferanse",
    sons: "Lyder",
  },
};
