export const amizades = {
  mensagensDiretas: "Direct messages",
  nova: {
    titulo: "New conversation",
    detalhe: "Pick a friend and the conversation opens.",
    procurar: "Find a friend",
    semAmigos: "You have no friends here yet.",
    semResultado: "No friend by that name.",
  },
  adicionar: {
    recado: "Write a short note (optional)",
    recadoDica: "What you write here also shows up in your conversation, if you become friends.",
    enviadoPara: "Done. The friend request went to {{nome}}.",
    outrosLugares: "Other places to make friends",
    outrosLugaresDetalhe: "No one comes to mind? Take a look at the open communities, people talk about nearly everything there.",
    explorarComunidades: "Explore communities",
    titulo: "Add a friend",
    detalhe: "You can add friends by their username.",
    exemplo: "Username, e.g. thiago",
    enviando: "Sending…",
    enviar: "Send request",
  },
  gatinhoChorando: "A crying kitten",
  status: {
    emChamada: "In a call",
    emVoz: "In voice",
  },
  menu: {
    chamada: "Start a call",
    fixar: "Pin to top",
    desafixar: "Unpin",
    silenciar: "Mute conversation",
    reativar: "Turn notifications back on",
    copiarIdDoCanal: "Copy channel ID",
  },
  ativosAgora: "Active now",
  procurando: "Seeing who's around…",
  tudoTranquilo: "All quiet for now…",
  tudoTranquiloDetalhe: "When you or a friend joins a call, it shows up here — and you can jump in with one click.",
  emVoz: "In voice",
  voce: "You",
  soVoce: "Just you",
  pessoas: "{{quantas}} people",
  voltarParaChamada: "Back to the call",
  entrarNaChamada: "Join the call",
  abrirCanal: "Open {{canal}} in {{servidor}}",
  encontreConversa: "Find a conversation",
  amigos: "Friends",
  conversas: "Conversations",
  semConversas: "No conversations yet. Add a friend to get started.",
  semConversaComEsseNome: "No conversation by that name.",
  abrirMenu: "Open servers and conversations",
  solicitacoes: "Message requests",
  pedidos: "Requests",
  spam: "Spam",
  pedidosPendentes: "Pending requests",
  marcadosComoSpam: "Marked as spam",
  aceitar: "Accept",
  ignorar: "Ignore",
  marcarSpam: "Mark as spam",
  semPedidos: "No requests waiting.",
  semPedidosDetalhe: "People who aren't your friends but share a server with you land here before reaching your conversations.",
  semSpam: "Nothing marked as spam.",
  semSpamDetalhe: "Whatever the spam filter sets aside, or whatever you mark, is kept in this tab.",
  umServidorEmComum: "1 server in common",
  servidoresEmComum: "{{quantos}} servers in common",
  semServidoresEmComum: "No servers in common",
};
