export const configuracoes = {
  efeitos: {
    titulo: "Pointer effects",
    detalhe: "A trail and sparks drawn over the app. They start off, and switch themselves off if you asked for less motion.",
    rastro: "Cursor trail",
    rastroDetalhe: "A line that follows the pointer and fades out behind it.",
    faisca: "Spark on click",
    faiscaDetalhe: "Short lines that fly out from where you clicked.",
    cor: "Colour",
    espessura: "Thickness",
    comprimento: "Length",
    tamanho: "Size",
    quantidade: "Count",
  },
  email: {
    verificarTitulo: "Confirm your email",
    verificarDetalhe: "Some communities only let confirmed people post. It takes one click.",
    enviar: "Send the link",
    enviado: "Check the inbox. The link lasts a day.",
    falhou: "The email could not be sent.",
    confirmado: "Email confirmed",
    confirmadoDetalhe: "Done. Now you can post in any community that asks for it.",
    linkIncompleto: "Incomplete link",
    linkIncompletoDetalhe: "The code is missing from the address. Open the link straight from the email.",
    confirmando: "Confirming…",
    expirou: "This link has already been used or has expired.",
    irParaOApp: "Go to the app",
  },
  tema: {
    indisponivel: "Theme unavailable",
    indisponivelDetalhe: "Whoever published it deleted it, or the link is wrong.",
    indisponivelLinha: "Theme unavailable. Whoever published it deleted it, or the link is wrong.",
    importar: "Import theme",
    importarCurto: "Import",
    importarDetalhe: "This replaces the theme you have now. You can edit it afterwards in Settings > Appearance > Theme studio.",
    porAutor: "by {{autor}}",
    umaCorTrocada: "1 colour swapped",
    coresTrocadas: "{{quantas}} colours swapped",
    avisoDeCss: "This theme carries CSS from whoever wrote it, and CSS reaches every corner of the screen. Only import from people you trust.",
    soCores: "This theme only swaps colours. No CSS from outside.",
    verCss: "View the CSS",
    esconderCss: "Hide the CSS",
    aplicar: "Apply",
    previaSemMotor: "The preview does not run the engine. Install it to see it.",
    motorAnimado: "{{motor}} animated",
  },
  sair: "Log out",
  versoes: {
    termos: "Terms of service",
    privacidade: "Privacy policy",
    copiar: "Click to copy",
    copiado: "Copied",
  },
  appColors: {
    title: "App colours",
    detail: "Pick up to three colours and the whole app takes that gradient.",
    locked: "The colour editor is part of {{plan}}.",
    color: "Colour {{number}}",
    addColor: "Add colour",
    removeColor: "Remove colour",
    surprise: "Surprise me",
    direction: "Gradient direction",
    intensity: "Intensity",
    reset: "Reset",
  },
  subscription: {
    colorsRow: "App colour editor",
    seePlans: "See plans",
    upgradeSubtitle: "Bigger limits and exclusive features for writing, sending files and streaming.",
    perMonth: "per month",
    perYear: "per year",
    save: "Save {{percent}}%",
    howToPay: "How would you like to pay?",
    legal: "You can request a refund within 7 days of payment. Payments are processed by Stripe; we never see your card number.",
    compare: "Free vs Infinity",
    featureColumn: "Feature",
    freeColumn: "Free",
    messageRow: "Message character limit",
    attachmentRow: "Upload file size",
    screenRow: "Video quality",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "You already have Infinity until {{date}}.",
    upsell: "Raise the limit with Infinity",
    screenUpsell: "Unlock higher quality with Infinity",
    free: "You're on the free plan.",
    activeUntil: "Infinity active until {{date}}.",
    renews: "Renews automatically on {{date}}.",
    endsAt: "Your subscription was cancelled and ends on {{date}}.",
    pastDue: "The last charge failed. Update your card to keep Infinity.",
    waiting: "Confirming your payment…",
    subscribe: "Subscribe",
    monthly: "Monthly",
    yearly: "Yearly",
    automatic: "Card",
    manage: "Manage payment",
    refund: "Request a refund",
    refundDetail: "You can cancel within 7 days of payment: {{amount}}, until {{date}}.",
    refundConfirm: "Request a refund?",
    refundConfirmDetail: "The money goes back to the same payment method and Infinity ends straight away.",
    refunded: "Refund requested.",
    unavailable: "Subscriptions aren't available yet.",
    success: "Payment received. Thank you!",
    canceled: "Payment cancelled.",
    error: "Something went wrong. Try again.",
    no: "No",
    tagRow: "Custom user tag",
    guildProfilesRow: "Per-community profiles",
    badgeRow: "Profile badge",
    communitiesRow: "Communities",
    savedRow: "Saved messages",
    animatedEmojiRow: "Use animated emojis",
    expressionsRow: "Global access to emojis and stickers",
    animatedProfileRow: "Animated avatars and profile banners",
    earlyAccessRow: "Early access to new features",
    themesRow: "Custom themes",
    pixOption: "Pix",
    pixHint: "Open your bank app, choose Pix and scan the QR code or use copy and paste.",
    pixQrAlt: "Pix QR code",
    pixCopy: "Copy Pix code",
    pixCopied: "Pix code copied",
    pixWaiting: "Waiting for payment",
    pixExpiresIn: "expires in {{time}}",
    pixExpired: "This Pix has expired. Generate a new one to continue.",
    pixNew: "Generate a new Pix",
    pixPaid: "Pix received! Your Infinity is now active.",
    forMe: "For me",
    asGift: "As a gift",
    buyGift: "Buy gift",
    giftReady: "Gift ready! Copy the link and send it to whoever you want.",
    giftClaimed: "Gift redeemed! Infinity is on your account.",
    gifts: "Gifts",
    giftsEmpty: "You haven't bought any gifts yet.",
    giftCode: "Gift code",
    giftRedeem: "Redeem",
    giftCopyLink: "Copy link",
    giftLinkCopied: "Link copied",
    giftClaimedBy: "redeemed by {{name}}",
    giftHint: "Got a gift code? Redeem it here. Gifts you bought are listed below.",
    cardPaid: "Payment approved! Your Infinity is active.",
    payAmount: "Pay {{amount}}",
    giftLinkTitle: "You got a {{plan}} gift!",
    giftLinkDetail: "Tap redeem and the days land on your account.",
    pageTitle: "Unlock a world of perks with {{plan}}",
    pageStart: "Home",
    pageBest: "The best of Infinity",
    pageChoose: "Choose your plan",
    fromPrice: "From {{amount}} a month. Cancel whenever you want.",
    filesTitle: "Send the whole file",
    filesText: "The party video, the work project, the folder full of photos: it all goes at once, with no splitting, no zipping and no cloud link in between.",
    videoTitle: "Stream in 1080p",
    videoText: "Your screen arrives sharp on the other side, with twice the frames per second. You can read code and play together without it all turning into a blur.",
    messageTitle: "Write as much as you like",
    messageText: "Twice the characters in every message, for when the story is long and breaking it into three parts would ruin it.",
    colorsTitle: "An app that looks like you",
    colorsText: "Pick the app colours one by one, save the theme and take it to every device you sign in on.",
    profileTitle: "A profile for every place",
    profileText: "A different nickname, a different picture, a different description in each community — and an animated picture, if you want one.",
    freeDetail: "It is free and it stays free.",
    currentPlan: "Your current plan",
    popular: "Most chosen",
    yearlyDetail: "Works out at {{amount}} a month, charged once a year.",
    monthlyDetail: "Charged every month, cancel whenever you want.",
    groupStyle: "Show your style",
    groupLook: "Make the app yours",
    groupLimits: "No tight limits",
    closingTitle: "What are you waiting for?",
    pagePlans: "Plans",
    pageCompare: "Compare",
    giftClaimTitle: "Activate {{plan}}?",
    giftClaimDetail: "That's {{days}} days landing on your account now.",
    giftFrom: "from {{name}}",
    giftActivate: "Activate",
    giftHasPlanTitle: "You already have Infinity",
    giftHasPlanDetail: "Your plan runs until {{date}}. Keep the link and send it to a friend.",
    giftUsedTitle: "This gift was already used",
    giftUsedDetail: "Someone redeemed this code before. Ask for another one.",
    giftNotFoundTitle: "Code not found",
    giftNotFoundDetail: "Check the code or ask for the link again.",
    giftDoneTitle: "{{plan}} activated!",
    giftOpenApp: "Open the app",
    giftSignIn: "Sign in to redeem",
    giftReviewStep: "Payment · Review",
    giftTotalToday: "Total today",
    giftCardWhy: "The card is only to confirm it's you. Nothing is charged now and nothing renews on its own.",
    giftAgree: "I have read and accept the terms of use",
    giftActivating: "Activating…",
  },
  telas: {
    subscription: "Infinity",
    conta: "My account",
    privacidade: "Privacy",
    conexoes: "Connections",
    voz: "Audio",
    video: "Video",
    avisos: "Notifications",
    aplicativos: "Applications",
    aparencia: "Appearance",
    batePapo: "Chat",
    acessibilidade: "Accessibility",
    idioma: "Language",
    aplicativo: "Get the app",
    atalhos: "Shortcuts",
    desktop: "Desktop app",
    avancado: "Advanced",
    servidor: "Server",
    comunicado: "System announcement",
    denuncias: "Reports",
    publicacoes: "Deployments",
  },
  grupos: {
    conta: "Account",
    app: "App settings",
    desenvolvedor: "Developer",
    administracao: "Administration",
  },
  secoes: {
    coresDoApp: "App colours",
    detalhesDeLogin: "Login details",
    dispositivos: "Devices",
    usuariosBloqueados: "Blocked users",
    aplicativosAutorizados: "Authorised apps",
    sessoes: "Sessions",
    amigosEDms: "Friends and direct messages",
    compartilhamentoDeAtividade: "Activity sharing",
    visibilidadeDoPerfil: "Profile visibility",
    exportarDados: "Export data",
    exclusaoDeDados: "Delete data",
    tema: "Theme",
    corDeDestaque: "Accent colour",
    interface: "Interface",
    listaDeCanais: "Channel list",
    zoomDoApp: "App zoom level",
    escalaDaFonte: "Chat font scale",
    modoStreamer: "Streaming privacy",
    cursores: "Cursors",
    movimento: "Motion",
    textoEmVoz: "Text to speech",
    teclado: "Keyboard",
    formatoDaHora: "Time format",
    idiomaDaInterface: "Interface language",
    dispositivosDeVoz: "Devices",
    testeDoMicrofone: "Microphone test",
    modoDeEntrada: "Input mode",
    sensibilidade: "Input sensitivity",
    qualidade: "Quality",
    camera: "Camera",
    transmissao: "Streaming",
    exibicao: "Display",
    entrada: "Input",
    midia: "Media",
    geral: "General",
    preferenciaDeMencao: "Mention preference",
    sons: "Sounds",
  },
};
