export const amizades = {
  mensagensDiretas: "Messaggi diretti",
  nova: {
    titulo: "Nuova conversazione",
    detalhe: "Scegli un amico e la conversazione si apre.",
    procurar: "Cerca un amico",
    semAmigos: "Qui non hai ancora amici.",
    semResultado: "Nessun amico con questo nome.",
  },
  adicionar: {
    recado: "Scrivi due righe (facoltativo)",
    recadoDica: "Quello che scrivi qui compare anche nella vostra conversazione, se diventate amici.",
    enviadoPara: "Fatto. La richiesta di amicizia è arrivata a {{nome}}.",
    outrosLugares: "Altri posti per fare amicizia",
    outrosLugaresDetalhe: "Non ti viene in mente nessuno? Dai un'occhiata alle comunità aperte, si parla di quasi tutto.",
    explorarComunidades: "Esplora le comunità",
    titulo: "Aggiungi un amico",
    detalhe: "Puoi aggiungere amici con il loro nome utente.",
    exemplo: "Nome utente, es.: thiago",
    enviando: "Invio…",
    enviar: "Invia richiesta",
  },
  gatinhoChorando: "Un gattino che piange",
  status: {
    emChamada: "In chiamata",
    emVoz: "In vocale",
  },
  menu: {
    chamada: "Avvia chiamata",
    fixar: "Fissa in alto",
    desafixar: "Rimuovi dai fissati",
    silenciar: "Silenzia conversazione",
    reativar: "Riattiva le notifiche",
    copiarIdDoCanal: "Copia l'ID del canale",
  },
  ativosAgora: "Attivi ora",
  procurando: "Vediamo chi c'è in giro…",
  tudoTranquilo: "Tutto tranquillo per ora…",
  tudoTranquiloDetalhe: "Quando tu o un amico entrate in una chiamata, comparirà qui — e potrai unirti con un clic.",
  emVoz: "In vocale",
  voce: "Tu",
  soVoce: "Solo tu",
  pessoas: "{{quantas}} persone",
  voltarParaChamada: "Torna alla chiamata",
  entrarNaChamada: "Entra nella chiamata",
  abrirCanal: "Apri {{canal}} in {{servidor}}",
  encontreConversa: "Trova una conversazione",
  amigos: "Amici",
  conversas: "Conversazioni",
  semConversas: "Ancora nessuna conversazione. Aggiungi un amico per iniziare.",
  semConversaComEsseNome: "Nessuna conversazione con quel nome.",
  abrirMenu: "Apri server e conversazioni",
  solicitacoes: "Richieste di messaggio",
  pedidos: "Richieste",
  spam: "Spam",
  pedidosPendentes: "Richieste in sospeso",
  marcadosComoSpam: "Segnati come spam",
  aceitar: "Accetta",
  ignorar: "Ignora",
  marcarSpam: "Segna come spam",
  semPedidos: "Nessuna richiesta in attesa.",
  semPedidosDetalhe: "Chi non è tuo amico ma condivide un server con te finisce qui prima di arrivare alle tue conversazioni.",
  semSpam: "Niente segnato come spam.",
  semSpamDetalhe: "Quello che il filtro antispam mette da parte, o quello che segni tu, resta in questa scheda.",
  umServidorEmComum: "1 server in comune",
  servidoresEmComum: "{{quantos}} server in comune",
  semServidoresEmComum: "Nessun server in comune",
};
