export const comum = {
  voltar: "Indietro",
  agoraNao: "Non ora",
  erro: {
    tentarDeNovo: "Riprova",
    recarregar: "Ricarica",
    copiarDetalhes: "Copia i dettagli",
    parteQuebrou: "Questa parte dello schermo si è rotta.",
    titulo: "Ravox Chat è inciampato.",
    detalhe: "Qualcosa si è rotto per strada e lo schermo non è riuscito a disegnarsi. La tua conversazione non è persa — è tutto sul server.",
  },
  perdido: {
    titulo: "Questo indirizzo non porta da nessuna parte.",
    detalhe: "O il link è sbagliato, o la pagina è stata spostata.",
  },
  conexao: {
    voltou: "Di nuovo connesso",
    reconectando: "Riconnessione",
    tentativaSufixo: " · tentativo {{numero}}",
    aSalvo: "La conversazione è al sicuro sul server. Torna da sola appena la connessione riparte.",
  },
  avisoDoNavegador: {
    titulo: "Vuoi essere avvisato dei messaggi?",
    detalhe: "Con Ravox Chat dietro un'altra finestra, ti chiama lui.",
  },
  atualizacao: {
    titulo: "Aggiornamento",
    semAuto: "Questa versione dell'app non sa aggiornarsi da sola. Scarica qui sotto l'installer più recente e installalo sopra.",
    versaoAtual: "Sei alla versione {{versao}}.",
    instalando: "Installazione della versione {{versao}}…",
    prontaVersao: "La versione {{versao}} è pronta da installare",
    baixandoVersao: "Download della versione {{versao}}…",
    baixandoComProgresso: "Download della versione {{versao}}… {{porcento}}%",
    saiuVersao: "È uscita la versione {{versao}}",
    saiuVersaoClique: "È uscita la versione {{versao}} — clicca per scaricarla",
    instalarVersaoEReiniciar: "Installa la versione {{versao}} e riavvia",
    erroTenteDeNovo: "{{erro}} Clicca per riprovare.",
    procurando: "Cerco…",
    emDia: "Sei aggiornato",
    vaiFechar: "L'app si chiude tra un istante.",
    comoInstala: "L'app si chiude, cambia versione e si riapre da sola. Se sei in chiamata, ne esci.",
    semServidor: "Non sono riuscito a raggiungere il server delle versioni.",
    procuraSozinho: "L'app controlla da sola all'avvio e ogni sei ore.",
    instalandoReticencias: "Installazione…",
    instalandoCurto: "Installazione",
    baixandoCurto: "Download",
    tentarDeNovo: "Riprova",
    reiniciarAgora: "Riavvia ora",
    instalarEReiniciar: "Installa e riavvia",
    baixar: "Scarica",
    procurar: "Controlla",
    baixarApp: "Scarica l'app",
    ariaBotao: "Aggiornamento dell'app",
  },
  janela: {
    ajustarAltura: "Regola l'altezza",
    redimensionar: "Ridimensiona la finestra",
    ajustarLargura: "Regola la larghezza",
  },
  dica: {
    rotulo: "Suggerimento:",
    pularConfirmacao: "tieni premuto Shift mentre clicchi per saltare questa conferma.",
  },
  cor: {
    pescar: "Preleva un colore dallo schermo",
    hex: "Valore esadecimale",
  },
  imagem: {
    titulo: "Scegli un'immagine",
    enviar: "Invia un'immagine",
    escolherGif: "Scegli una GIF",
    buscarGif: "Cerca GIF",
  },
  fonte: {
    rotulo: "Carattere del messaggio",
    padrao: "Predefinito",
    comNome: "Carattere del messaggio — {{fonte}}",
  },
  recorte: {
    titulo: "Ritaglia l'icona",
    detalhe: "Trascina per scegliere la parte e usa il cursore per ingrandire. L'icona è tonda ovunque nell'app.",
    voltarAoComeco: "Torna all'inizio",
    usar: "Usa questo ritaglio",
  },
  mais: "Altro",
  carregando: "Caricamento…",
  salvar: "Salva",
  salvando: "Salvataggio…",
  descartar: "Annulla",
  redefinir: "Reimposta",
  naoSalvo: "Hai modifiche non salvate.",
  fechar: "Chiudi",
  criar: "Crea",
  nome: "Nome",
  emoji: "Emoji",
  previa: "Anteprima",
  cancelar: "Annulla",
  enviar: "Invia",
  apagar: "Elimina",
  excluir: "Elimina",
  remover: "Rimuovi",
  trocar: "Cambia",
  loginNoApp: {
    titulo: "Tutto a posto!",
    detalhe: "Hai effettuato l'accesso. Torna su Ravox Chat, l'app ti sta già aspettando.",
    abrir: "Apri Ravox Chat",
    fecharAba: "Ora puoi chiudere questa scheda.",
    falhouTitulo: "Accesso non riuscito",
    falhouDetalhe: "Torna nell'app e riprova ad accedere.",
    legenda: "Un robot che saluta",
    legendaFalhou: "Un gattino che piange",
  },
  ads: {
    label: "Pubblicità",
    title: "Fai pubblicità qui",
    detail: "Parla con noi e fatti vedere da chi usa Ravox Chat.",
    action: "Voglio fare pubblicità",
  },
};
