export const configuracoes = {
  efeitos: {
    titulo: "Effetti del puntatore",
    detalhe: "Scia e scintille disegnate sopra l'applicazione. Partono spente e si spengono da sole se hai chiesto meno animazione.",
    rastro: "Scia del cursore",
    rastroDetalhe: "Una linea che segue il puntatore e sfuma dietro.",
    faisca: "Scintilla al clic",
    faiscaDetalhe: "Trattini che partono dal punto in cui hai cliccato.",
    cor: "Colore",
    espessura: "Spessore",
    comprimento: "Lunghezza",
    tamanho: "Dimensione",
    quantidade: "Quantità",
  },
  email: {
    verificarTitulo: "Conferma la tua email",
    verificarDetalhe: "Certe comunità lasciano scrivere solo a chi ha confermato. Basta un clic.",
    enviar: "Manda il link",
    enviado: "Guarda la posta in arrivo. Il link dura un giorno.",
    falhou: "Non è stato possibile mandare l'email.",
    confirmado: "Email confermata",
    confirmadoDetalhe: "Fatto. Ora scrivi in qualunque comunità lo richieda.",
    linkIncompleto: "Link incompleto",
    linkIncompletoDetalhe: "Nell'indirizzo manca il codice. Apri il link direttamente dall'email.",
    confirmando: "Conferma in corso…",
    expirou: "Questo link è già stato usato o è scaduto.",
    irParaOApp: "Vai all'applicazione",
  },
  tema: {
    indisponivel: "Tema non disponibile",
    indisponivelDetalhe: "Chi l'ha pubblicato l'ha cancellato, oppure il link è sbagliato.",
    indisponivelLinha: "Tema non disponibile. Chi l'ha pubblicato l'ha cancellato, oppure il link è sbagliato.",
    importar: "Importa il tema",
    importarCurto: "Importa",
    importarDetalhe: "Questo sostituisce il tema che hai ora. Potrai modificarlo dopo in Impostazioni > Aspetto > Studio dei temi.",
    porAutor: "di {{autor}}",
    umaCorTrocada: "1 colore cambiato",
    coresTrocadas: "{{quantas}} colori cambiati",
    avisoDeCss: "Questo tema porta con sé il CSS di chi l'ha scritto, e il CSS tocca ogni angolo dello schermo. Importa solo da persone di cui ti fidi.",
    soCores: "Questo tema cambia solo i colori. Nessun CSS da fuori.",
    verCss: "Mostra il CSS",
    esconderCss: "Nascondi il CSS",
    aplicar: "Applica",
    previaSemMotor: "L'anteprima non esegue il motore. Installalo per vederlo.",
    motorAnimado: "{{motor}} animato",
  },
  sair: "Esci",
  versoes: {
    termos: "Termini di servizio",
    privacidade: "Informativa sulla privacy",
    copiar: "Clicca per copiare",
    copiado: "Copiato",
  },
  appColors: {
    title: "Colori dell'app",
    detail: "Scegli fino a tre colori e tutta l'app prende quel gradiente.",
    locked: "L'editor di colori fa parte di {{plan}}.",
    color: "Colore {{number}}",
    addColor: "Aggiungi colore",
    removeColor: "Rimuovi colore",
    surprise: "Sorprendimi",
    direction: "Direzione del gradiente",
    intensity: "Intensità",
    reset: "Ripristina",
  },
  subscription: {
    colorsRow: "Editor di colori dell'app",
    seePlans: "Vedi i piani",
    upgradeSubtitle: "Limiti più alti e funzioni esclusive per scrivere, inviare file e trasmettere.",
    perMonth: "al mese",
    perYear: "all'anno",
    save: "Risparmia il {{percent}}%",
    howToPay: "Come vuoi pagare?",
    legal: "Puoi chiedere il rimborso entro 7 giorni dal pagamento. Il pagamento è gestito da Stripe; non vediamo mai il numero della tua carta.",
    compare: "Gratis vs Infinity",
    featureColumn: "Funzione",
    freeColumn: "Gratis",
    messageRow: "Limite di caratteri del messaggio",
    attachmentRow: "Dimensione file da inviare",
    screenRow: "Qualità video",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Hai già Infinity fino al {{date}}.",
    upsell: "Aumenta il limite con Infinity",
    screenUpsell: "Più qualità con Infinity",
    free: "Sei nel piano gratuito.",
    activeUntil: "Infinity attivo fino al {{date}}.",
    renews: "Si rinnova automaticamente il {{date}}.",
    endsAt: "L'abbonamento è stato annullato e termina il {{date}}.",
    pastDue: "L'ultimo addebito non è andato a buon fine. Aggiorna la carta per non perdere il Infinity.",
    waiting: "Conferma del pagamento…",
    subscribe: "Abbonati",
    monthly: "Mensile",
    yearly: "Annuale",
    automatic: "Carta",
    manage: "Gestisci pagamento",
    refund: "Richiedi rimborso",
    refundDetail: "Puoi recedere entro 7 giorni dal pagamento: {{amount}}, fino al {{date}}.",
    refundConfirm: "Richiedere il rimborso?",
    refundConfirmDetail: "Il denaro torna sullo stesso metodo di pagamento e il Infinity termina subito.",
    refunded: "Rimborso richiesto.",
    unavailable: "L'abbonamento non è ancora disponibile.",
    success: "Pagamento ricevuto. Grazie!",
    canceled: "Pagamento annullato.",
    error: "Qualcosa è andato storto. Riprova.",
    no: "No",
    tagRow: "Tag utente personalizzato",
    guildProfilesRow: "Profili per community",
    badgeRow: "Badge del profilo",
    communitiesRow: "Community",
    savedRow: "Messaggi salvati",
    animatedEmojiRow: "Usa emoji animate",
    expressionsRow: "Accesso globale a emoji e sticker",
    animatedProfileRow: "Avatar e banner del profilo animati",
    earlyAccessRow: "Accesso anticipato alle novità",
    themesRow: "Temi personalizzati",
    pixOption: "Pix",
    pixHint: "Apri l'app della banca, scegli Pix e scansiona il QR code o usa copia e incolla.",
    pixQrAlt: "QR code Pix",
    pixCopy: "Copia codice Pix",
    pixCopied: "Codice Pix copiato",
    pixWaiting: "In attesa del pagamento",
    pixExpiresIn: "scade tra {{time}}",
    pixExpired: "Questo Pix è scaduto. Generane un altro per continuare.",
    pixNew: "Genera un altro Pix",
    pixPaid: "Pix ricevuto! Il tuo Infinity è attivo.",
    forMe: "Per me",
    asGift: "Come regalo",
    buyGift: "Compra regalo",
    giftReady: "Regalo pronto! Copia il link e mandalo a chi vuoi.",
    giftClaimed: "Regalo riscattato! Infinity è sul tuo account.",
    gifts: "Regali",
    giftsEmpty: "Non hai ancora comprato nessun regalo.",
    giftCode: "Codice del regalo",
    giftRedeem: "Riscatta",
    giftCopyLink: "Copia link",
    giftLinkCopied: "Link copiato",
    giftClaimedBy: "riscattato da {{name}}",
    giftHint: "Hai un codice regalo? Riscattalo qui. I regali comprati sono qui sotto.",
    cardPaid: "Pagamento approvato! Il tuo Infinity è attivo.",
    payAmount: "Paga {{amount}}",
    giftLinkTitle: "Hai ricevuto un regalo {{plan}}!",
    giftLinkDetail: "Tocca riscatta e i giorni arrivano sul tuo account.",
    pageTitle: "Sblocca un mondo di vantaggi con {{plan}}",
    pageStart: "Home",
    pageBest: "Il meglio di Infinity",
    pageChoose: "Scegli il tuo piano",
    fromPrice: "Da {{amount}} al mese. Disdici quando vuoi.",
    filesTitle: "Manda il file intero",
    filesText: "Il video della festa, il progetto di lavoro, la cartella con le foto: va tutto in una volta, senza tagliare, senza comprimere e senza link al cloud di mezzo.",
    videoTitle: "Trasmetti in 1080p",
    videoText: "Il tuo schermo arriva nitido a chi sta dall'altra parte, con il doppio dei fotogrammi al secondo. Si riesce a leggere il codice e a giocare insieme senza che diventi tutto sfocato.",
    messageTitle: "Scrivi quanto vuoi",
    messageText: "Il doppio dei caratteri in ogni messaggio, per quando la storia è lunga e spezzarla in tre parti rovinerebbe tutto.",
    colorsTitle: "L'app con il tuo stile",
    colorsText: "Scegli i colori dell'app uno a uno, salva il tema e portalo su tutti i dispositivi dove entri.",
    profileTitle: "Un profilo per ogni posto",
    profileText: "Un altro soprannome, un'altra foto, un'altra descrizione in ogni community — e foto animata, se ti va.",
    freeDetail: "È gratis e resta gratis.",
    currentPlan: "Il tuo piano attuale",
    popular: "Il più scelto",
    yearlyDetail: "Sono {{amount}} al mese, addebitati una volta l'anno.",
    monthlyDetail: "Addebitato ogni mese, disdici quando vuoi.",
    groupStyle: "Mostra il tuo stile",
    groupLook: "L'app come piace a te",
    groupLimits: "Senza limiti stretti",
    closingTitle: "Cosa stai aspettando?",
    pagePlans: "Piani",
    pageCompare: "Confronta",
    giftClaimTitle: "Attivare {{plan}}?",
    giftClaimDetail: "Sono {{days}} giorni che arrivano sul tuo account ora.",
    giftFrom: "da {{name}}",
    giftActivate: "Attiva",
    giftHasPlanTitle: "Hai già Infinity",
    giftHasPlanDetail: "Il tuo piano vale fino al {{date}}. Tieni il link e mandalo a un amico.",
    giftUsedTitle: "Questo regalo è già stato usato",
    giftUsedDetail: "Qualcuno ha riscattato questo codice prima. Chiedine un altro.",
    giftNotFoundTitle: "Codice non trovato",
    giftNotFoundDetail: "Controlla il codice o chiedi di nuovo il link.",
    giftDoneTitle: "{{plan}} attivato!",
    giftOpenApp: "Apri l'app",
    giftSignIn: "Accedi per riscattare",
    giftReviewStep: "Pagamento · Verifica",
    giftTotalToday: "Totale di oggi",
    giftCardWhy: "La carta serve solo a confermare che sei tu. Ora non viene addebitato nulla e nulla si rinnova da solo.",
    giftAgree: "Ho letto e accetto i termini d'uso",
    giftActivating: "Attivazione…",
  },
  telas: {
    subscription: "Infinity",
    conta: "Il mio account",
    privacidade: "Privacy",
    conexoes: "Connessioni",
    voz: "Audio",
    video: "Video",
    avisos: "Notifiche",
    aplicativos: "Applicazioni",
    aparencia: "Aspetto",
    batePapo: "Chat",
    acessibilidade: "Accessibilità",
    idioma: "Lingua",
    aplicativo: "Scarica l'app",
    atalhos: "Scorciatoie",
    desktop: "App desktop",
    avancado: "Avanzate",
    servidor: "Server",
    comunicado: "Comunicato di sistema",
    denuncias: "Segnalazioni",
    publicacoes: "Distribuzioni",
  },
  grupos: {
    conta: "Account",
    app: "Impostazioni dell'app",
    desenvolvedor: "Sviluppatore",
    administracao: "Amministrazione",
  },
  secoes: {
    coresDoApp: "Colori dell'app",
    detalhesDeLogin: "Dati di accesso",
    dispositivos: "Dispositivi",
    usuariosBloqueados: "Utenti bloccati",
    aplicativosAutorizados: "App autorizzate",
    sessoes: "Sessioni",
    amigosEDms: "Amici e messaggi diretti",
    compartilhamentoDeAtividade: "Condivisione attività",
    visibilidadeDoPerfil: "Visibilità del profilo",
    exportarDados: "Esporta dati",
    exclusaoDeDados: "Elimina dati",
    tema: "Tema",
    corDeDestaque: "Colore d'accento",
    interface: "Interfaccia",
    listaDeCanais: "Elenco dei canali",
    zoomDoApp: "Livello di zoom dell'app",
    escalaDaFonte: "Scala del carattere della chat",
    modoStreamer: "Privacy in streaming",
    cursores: "Cursori",
    movimento: "Movimento",
    textoEmVoz: "Sintesi vocale",
    teclado: "Tastiera",
    formatoDaHora: "Formato dell'ora",
    idiomaDaInterface: "Lingua dell'interfaccia",
    dispositivosDeVoz: "Dispositivi",
    testeDoMicrofone: "Test del microfono",
    modoDeEntrada: "Modalità di ingresso",
    sensibilidade: "Sensibilità d'ingresso",
    qualidade: "Qualità",
    camera: "Fotocamera",
    transmissao: "Trasmissione",
    exibicao: "Visualizzazione",
    entrada: "Immissione",
    midia: "Media",
    geral: "Generale",
    preferenciaDeMencao: "Preferenza di menzione",
    sons: "Suoni",
  },
};
