export const amizades = {
  mensagensDiretas: "Wiadomości prywatne",
  nova: {
    titulo: "Nowa rozmowa",
    detalhe: "Wybierz znajomego, a rozmowa się otworzy.",
    procurar: "Znajdź znajomego",
    semAmigos: "Nie masz tu jeszcze znajomych.",
    semResultado: "Nie ma znajomego o tym imieniu.",
  },
  adicionar: {
    recado: "Dopisz parę słów (nieobowiązkowe)",
    recadoDica: "To, co tu napiszesz, pojawi się też w waszej rozmowie, jeśli się zaprzyjaźnicie.",
    enviadoPara: "Gotowe. Zaproszenie do znajomych trafiło do {{nome}}.",
    outrosLugares: "Inne miejsca na nowe znajomości",
    outrosLugaresDetalhe: "Nikt ci nie przychodzi do głowy? Zajrzyj do otwartych społeczności, rozmawia się tam prawie o wszystkim.",
    explorarComunidades: "Przeglądaj społeczności",
    titulo: "Dodaj znajomego",
    detalhe: "Znajomych możesz dodać po ich nazwie użytkownika.",
    exemplo: "Nazwa użytkownika, np.: thiago",
    enviando: "Wysyłam…",
    enviar: "Wyślij zaproszenie",
  },
  gatinhoChorando: "Płaczący kotek",
  status: {
    emChamada: "W rozmowie",
    emVoz: "Na głosowym",
  },
  menu: {
    chamada: "Rozpocznij rozmowę",
    fixar: "Przypnij u góry",
    desafixar: "Odepnij",
    silenciar: "Wycisz rozmowę",
    reativar: "Włącz powiadomienia z powrotem",
    copiarIdDoCanal: "Kopiuj ID kanału",
  },
  ativosAgora: "Aktywni teraz",
  procurando: "Sprawdzamy, kto jest w pobliżu…",
  tudoTranquilo: "Na razie jest cicho…",
  tudoTranquiloDetalhe: "Gdy ty albo znajomy dołączycie do rozmowy, pojawi się tutaj — i dołączysz jednym kliknięciem.",
  emVoz: "Na głosowym",
  voce: "Ty",
  soVoce: "Tylko ty",
  pessoas: "{{quantas}} osób",
  voltarParaChamada: "Wróć do rozmowy",
  entrarNaChamada: "Dołącz do rozmowy",
  abrirCanal: "Otwórz {{canal}} na {{servidor}}",
  encontreConversa: "Znajdź rozmowę",
  amigos: "Znajomi",
  conversas: "Rozmowy",
  semConversas: "Jeszcze żadnych rozmów. Dodaj znajomego, żeby zacząć.",
  semConversaComEsseNome: "Brak rozmowy o tej nazwie.",
  abrirMenu: "Otwórz serwery i rozmowy",
  solicitacoes: "Prośby o wiadomość",
  pedidos: "Prośby",
  spam: "Spam",
  pedidosPendentes: "Oczekujące prośby",
  marcadosComoSpam: "Oznaczone jako spam",
  aceitar: "Akceptuj",
  ignorar: "Ignoruj",
  marcarSpam: "Oznacz jako spam",
  semPedidos: "Brak oczekujących próśb.",
  semPedidosDetalhe: "Kto nie jest twoim znajomym, ale dzieli z tobą serwer, trafia tutaj, zanim dotrze do twoich rozmów.",
  semSpam: "Nic nie oznaczono jako spam.",
  semSpamDetalhe: "To, co odsieje filtr spamu, albo to, co sam oznaczysz, zostaje w tej zakładce.",
  umServidorEmComum: "1 wspólny serwer",
  servidoresEmComum: "Wspólne serwery: {{quantos}}",
  semServidoresEmComum: "Brak wspólnych serwerów",
};
