export const comum = {
  voltar: "Wstecz",
  agoraNao: "Nie teraz",
  erro: {
    tentarDeNovo: "Spróbuj ponownie",
    recarregar: "Wczytaj ponownie",
    copiarDetalhes: "Skopiuj szczegóły",
    parteQuebrou: "Ta część ekranu się zepsuła.",
    titulo: "Ravox Chat się potknął.",
    detalhe: "Coś zepsuło się po drodze i ekran nie zdołał się narysować. Twoja rozmowa nie przepadła — wszystko jest na serwerze.",
  },
  perdido: {
    titulo: "Ten adres donikąd nie prowadzi.",
    detalhe: "Albo link jest błędny, albo strona zmieniła miejsce.",
  },
  conexao: {
    voltou: "Znowu połączono",
    reconectando: "Łączę ponownie",
    tentativaSufixo: " · próba {{numero}}",
    aSalvo: "Rozmowa jest bezpieczna na serwerze. Wszystko wróci samo, gdy tylko wróci połączenie.",
  },
  avisoDoNavegador: {
    titulo: "Chcesz powiadomienia o wiadomościach?",
    detalhe: "Gdy Ravox Chat jest za innym oknem, da ci znać.",
  },
  atualizacao: {
    titulo: "Aktualizacja",
    semAuto: "Ta wersja aplikacji nie potrafi się sama aktualizować. Pobierz poniżej najnowszy instalator i zainstaluj go na wierzchu.",
    versaoAtual: "Masz wersję {{versao}}.",
    instalando: "Instalowanie wersji {{versao}}…",
    prontaVersao: "Wersja {{versao}} jest gotowa do instalacji",
    baixandoVersao: "Pobieranie wersji {{versao}}…",
    baixandoComProgresso: "Pobieranie wersji {{versao}}… {{porcento}}%",
    saiuVersao: "Wyszła wersja {{versao}}",
    saiuVersaoClique: "Wyszła wersja {{versao}} — kliknij, aby pobrać",
    instalarVersaoEReiniciar: "Zainstaluj wersję {{versao}} i uruchom ponownie",
    erroTenteDeNovo: "{{erro}} Kliknij, aby spróbować ponownie.",
    procurando: "Szukam…",
    emDia: "Masz najnowszą wersję",
    vaiFechar: "Aplikacja zamknie się za chwilę.",
    comoInstala: "Aplikacja zamyka się, podmienia wersję i sama otwiera się z powrotem. Jeśli jesteś w rozmowie, opuścisz ją.",
    semServidor: "Nie udało się połączyć z serwerem wersji.",
    procuraSozinho: "Aplikacja sprawdza sama przy uruchomieniu i co sześć godzin.",
    instalandoReticencias: "Instalowanie…",
    instalandoCurto: "Instalowanie",
    baixandoCurto: "Pobieranie",
    tentarDeNovo: "Spróbuj ponownie",
    reiniciarAgora: "Uruchom ponownie teraz",
    instalarEReiniciar: "Zainstaluj i uruchom ponownie",
    baixar: "Pobierz",
    procurar: "Sprawdź",
    baixarApp: "Pobierz aplikację",
    ariaBotao: "Aktualizacja aplikacji",
  },
  janela: {
    ajustarAltura: "Dostosuj wysokość",
    redimensionar: "Zmień rozmiar okna",
    ajustarLargura: "Dostosuj szerokość",
  },
  dica: {
    rotulo: "Wskazówka:",
    pularConfirmacao: "przytrzymaj Shift przy kliknięciu, aby pominąć to potwierdzenie.",
  },
  cor: {
    pescar: "Pobierz kolor z ekranu",
    hex: "Wartość szesnastkowa",
  },
  imagem: {
    titulo: "Wybierz obraz",
    enviar: "Wyślij obraz",
    escolherGif: "Wybierz GIF",
    buscarGif: "Szukaj GIF-ów",
  },
  fonte: {
    rotulo: "Czcionka wiadomości",
    padrao: "Domyślna",
    comNome: "Czcionka wiadomości — {{fonte}}",
  },
  recorte: {
    titulo: "Przytnij ikonę",
    detalhe: "Przeciągnij, aby wybrać fragment, i przybliż suwakiem. Ikona wszędzie w aplikacji jest okrągła.",
    voltarAoComeco: "Wróć na początek",
    usar: "Użyj tego kadru",
  },
  mais: "Więcej",
  carregando: "Wczytywanie…",
  salvar: "Zapisz",
  salvando: "Zapisywanie…",
  descartar: "Odrzuć",
  redefinir: "Przywróć",
  naoSalvo: "Masz niezapisane zmiany.",
  fechar: "Zamknij",
  criar: "Utwórz",
  nome: "Nazwa",
  emoji: "Emoji",
  previa: "Podgląd",
  cancelar: "Anuluj",
  enviar: "Wyślij",
  apagar: "Usuń",
  excluir: "Usuń",
  remover: "Usuń",
  trocar: "Zmień",
  loginNoApp: {
    titulo: "Wszystko gotowe!",
    detalhe: "Zalogowano. Wróć do Ravox Chat, aplikacja już na ciebie czeka.",
    abrir: "Otwórz Ravox Chat",
    fecharAba: "Możesz już zamknąć tę kartę.",
    falhouTitulo: "Logowanie się nie udało",
    falhouDetalhe: "Wróć do aplikacji i spróbuj zalogować się ponownie.",
    legenda: "Machający robot",
    legendaFalhou: "Płaczący kotek",
  },
  ads: {
    label: "Reklama",
    title: "Reklamuj się tutaj",
    detail: "Napisz do nas i pokaż się tym, którzy używają Ravox Chat.",
    action: "Chcę się reklamować",
  },
};
