export const configuracoes = {
  efeitos: {
    titulo: "Efekty wskaźnika",
    detalhe: "Smuga i iskry rysowane na wierzchu aplikacji. Startują wyłączone i same gasną, jeśli poprosiłeś o mniej ruchu.",
    rastro: "Smuga kursora",
    rastroDetalhe: "Kreska, która idzie za wskaźnikiem i blednie z tyłu.",
    faisca: "Iskry przy kliknięciu",
    faiscaDetalhe: "Krótkie kreski wylatujące z miejsca kliknięcia.",
    cor: "Kolor",
    espessura: "Grubość",
    comprimento: "Długość",
    tamanho: "Rozmiar",
    quantidade: "Liczba",
  },
  email: {
    verificarTitulo: "Potwierdź swój e-mail",
    verificarDetalhe: "Część społeczności pozwala pisać tylko potwierdzonym. To jedno kliknięcie.",
    enviar: "Wyślij odnośnik",
    enviado: "Zajrzyj do skrzynki. Odnośnik działa przez dobę.",
    falhou: "Nie udało się wysłać wiadomości.",
    confirmado: "E-mail potwierdzony",
    confirmadoDetalhe: "Gotowe. Piszesz już w każdej społeczności, która tego wymaga.",
    linkIncompleto: "Niepełny odnośnik",
    linkIncompletoDetalhe: "W adresie brakuje kodu. Otwórz odnośnik prosto z wiadomości.",
    confirmando: "Potwierdzanie…",
    expirou: "Ten odnośnik został już użyty albo stracił ważność.",
    irParaOApp: "Przejdź do aplikacji",
  },
  tema: {
    indisponivel: "Motyw niedostępny",
    indisponivelDetalhe: "Ten, kto go opublikował, usunął go, albo odnośnik jest zły.",
    indisponivelLinha: "Motyw niedostępny. Ten, kto go opublikował, usunął go, albo odnośnik jest zły.",
    importar: "Zaimportuj motyw",
    importarCurto: "Zaimportuj",
    importarDetalhe: "To zastąpi motyw, który masz teraz. Potem możesz go zmienić w Ustawienia > Wygląd > Studio motywów.",
    porAutor: "autor: {{autor}}",
    umaCorTrocada: "1 zmieniony kolor",
    coresTrocadas: "zmienione kolory: {{quantas}}",
    avisoDeCss: "Ten motyw niesie CSS od swojego autora, a CSS sięga każdego zakątka ekranu. Importuj tylko od ludzi, którym ufasz.",
    soCores: "Ten motyw zmienia tylko kolory. Żadnego CSS z zewnątrz.",
    verCss: "Pokaż CSS",
    esconderCss: "Ukryj CSS",
    aplicar: "Zastosuj",
    previaSemMotor: "Podgląd nie uruchamia silnika. Zainstaluj, żeby go zobaczyć.",
    motorAnimado: "{{motor}} animowany",
  },
  sair: "Wyloguj się",
  versoes: {
    termos: "Warunki korzystania",
    privacidade: "Polityka prywatności",
    copiar: "Kliknij, aby skopiować",
    copiado: "Skopiowano",
  },
  appColors: {
    title: "Kolory aplikacji",
    detail: "Wybierz do trzech kolorów, a cała aplikacja dostanie ten gradient.",
    locked: "Edytor kolorów należy do {{plan}}.",
    color: "Kolor {{number}}",
    addColor: "Dodaj kolor",
    removeColor: "Usuń kolor",
    surprise: "Zaskocz mnie",
    direction: "Kierunek gradientu",
    intensity: "Intensywność",
    reset: "Przywróć",
  },
  subscription: {
    colorsRow: "Edytor kolorów aplikacji",
    seePlans: "Zobacz plany",
    upgradeSubtitle: "Wyższe limity i wyjątkowe funkcje do pisania, wysyłania plików i transmisji.",
    perMonth: "miesięcznie",
    perYear: "rocznie",
    save: "Oszczędź {{percent}}%",
    howToPay: "Jak chcesz zapłacić?",
    legal: "Możesz poprosić o zwrot w ciągu 7 dni od płatności. Płatność obsługuje Stripe; nigdy nie widzimy numeru Twojej karty.",
    compare: "Darmowy vs Infinity",
    featureColumn: "Funkcja",
    freeColumn: "Darmowy",
    messageRow: "Limit znaków w wiadomości",
    attachmentRow: "Rozmiar wysyłanego pliku",
    screenRow: "Jakość wideo",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} kl./s",
    alreadyPremium: "Masz już Infinity do {{date}}.",
    upsell: "Zwiększ limit z Infinity",
    screenUpsell: "Wyższa jakość z Infinity",
    free: "Korzystasz z planu darmowego.",
    activeUntil: "Infinity aktywne do {{date}}.",
    renews: "Odnawia się automatycznie {{date}}.",
    endsAt: "Subskrypcja została anulowana i kończy się {{date}}.",
    pastDue: "Ostatnie obciążenie nie powiodło się. Zaktualizuj kartę, aby nie stracić Infinity.",
    waiting: "Potwierdzanie płatności…",
    subscribe: "Subskrybuj",
    monthly: "Miesięcznie",
    yearly: "Rocznie",
    automatic: "Karta",
    manage: "Zarządzaj płatnością",
    refund: "Poproś o zwrot",
    refundDetail: "Możesz zrezygnować w ciągu 7 dni od płatności: {{amount}}, do {{date}}.",
    refundConfirm: "Poprosić o zwrot?",
    refundConfirmDetail: "Pieniądze wrócą tą samą metodą płatności, a Infinity skończy się od razu.",
    refunded: "Poproszono o zwrot.",
    unavailable: "Subskrypcja nie jest jeszcze dostępna.",
    success: "Płatność otrzymana. Dziękujemy!",
    canceled: "Płatność anulowana.",
    error: "Coś poszło nie tak. Spróbuj ponownie.",
    no: "Nie",
    tagRow: "Własny tag użytkownika",
    guildProfilesRow: "Profile dla społeczności",
    badgeRow: "Odznaka profilu",
    communitiesRow: "Społeczności",
    savedRow: "Zapisane wiadomości",
    animatedEmojiRow: "Animowane emoji",
    expressionsRow: "Emoji i naklejki z każdego serwera",
    animatedProfileRow: "Animowane awatary i banery profilu",
    earlyAccessRow: "Wcześniejszy dostęp do nowości",
    themesRow: "Własne motywy",
    pixOption: "Pix",
    pixHint: "Otwórz aplikację banku, wybierz Pix i zeskanuj kod QR albo użyj kopiuj i wklej.",
    pixQrAlt: "Kod QR Pix",
    pixCopy: "Kopiuj kod Pix",
    pixCopied: "Skopiowano kod Pix",
    pixWaiting: "Czekamy na płatność",
    pixExpiresIn: "wygasa za {{time}}",
    pixExpired: "Ten Pix wygasł. Wygeneruj nowy, aby kontynuować.",
    pixNew: "Wygeneruj nowy Pix",
    pixPaid: "Pix otrzymany! Twoje Infinity jest aktywne.",
    forMe: "Dla mnie",
    asGift: "Na prezent",
    buyGift: "Kup prezent",
    giftReady: "Prezent gotowy! Skopiuj link i wyślij komu chcesz.",
    giftClaimed: "Prezent odebrany! Infinity jest już na Twoim koncie.",
    gifts: "Prezenty",
    giftsEmpty: "Nie kupiłeś jeszcze żadnego prezentu.",
    giftCode: "Kod prezentu",
    giftRedeem: "Odbierz",
    giftCopyLink: "Kopiuj link",
    giftLinkCopied: "Skopiowano link",
    giftClaimedBy: "odebrany przez {{name}}",
    giftHint: "Masz kod prezentu? Odbierz go tutaj. Kupione prezenty są poniżej.",
    cardPaid: "Płatność zatwierdzona! Twoje Infinity jest aktywne.",
    payAmount: "Zapłać {{amount}}",
    giftLinkTitle: "Dostałeś prezent {{plan}}!",
    giftLinkDetail: "Dotknij odbierz, a dni trafią na Twoje konto.",
    pageTitle: "Odblokuj świat korzyści z {{plan}}",
    pageStart: "Start",
    pageBest: "To, co najlepsze w Infinity",
    pageChoose: "Wybierz swój plan",
    fromPrice: "Od {{amount}} miesięcznie. Anuluj, kiedy chcesz.",
    filesTitle: "Wyślij cały plik",
    filesText: "Film z imprezy, projekt z pracy, folder ze zdjęciami: wszystko leci za jednym razem, bez dzielenia, bez pakowania i bez linku do chmury po drodze.",
    videoTitle: "Transmituj w 1080p",
    videoText: "Twój ekran dociera do drugiej strony ostry, z dwa razy większą liczbą klatek na sekundę. Da się czytać kod i grać razem bez rozmazanej plamy.",
    messageTitle: "Pisz do woli",
    messageText: "Dwa razy więcej znaków w każdej wiadomości — na chwile, gdy historia jest długa, a dzielenie jej na trzy części zepsułoby cały efekt.",
    colorsTitle: "Aplikacja w Twoich kolorach",
    colorsText: "Wybierz kolory aplikacji jeden po drugim, zapisz motyw i zabierz go na wszystkie urządzenia, na których się logujesz.",
    profileTitle: "Inny profil w każdym miejscu",
    profileText: "Inny pseudonim, inne zdjęcie, inny opis w każdej społeczności — i ruchome zdjęcie, jeśli chcesz.",
    freeDetail: "Jest za darmo i tak zostanie.",
    currentPlan: "Twój obecny plan",
    popular: "Najczęściej wybierany",
    yearlyDetail: "Wychodzi {{amount}} miesięcznie, płatne raz w roku.",
    monthlyDetail: "Płatne co miesiąc, anulujesz, kiedy chcesz.",
    groupStyle: "Pokaż swój styl",
    groupLook: "Ustaw aplikację po swojemu",
    groupLimits: "Bez ciasnych limitów",
    closingTitle: "Na co czekasz?",
    pagePlans: "Plany",
    pageCompare: "Porównaj",
    giftClaimTitle: "Aktywować {{plan}}?",
    giftClaimDetail: "To {{days}} dni, które trafiają teraz na Twoje konto.",
    giftFrom: "od {{name}}",
    giftActivate: "Aktywuj",
    giftHasPlanTitle: "Masz już Infinity",
    giftHasPlanDetail: "Twój plan działa do {{date}}. Zachowaj link i wyślij go znajomemu.",
    giftUsedTitle: "Ten prezent został już użyty",
    giftUsedDetail: "Ktoś wcześniej odebrał ten kod. Poproś o inny.",
    giftNotFoundTitle: "Nie znaleziono kodu",
    giftNotFoundDetail: "Sprawdź kod albo poproś o link jeszcze raz.",
    giftDoneTitle: "{{plan}} aktywowane!",
    giftOpenApp: "Otwórz aplikację",
    giftSignIn: "Zaloguj się, aby odebrać",
    giftReviewStep: "Płatność · Sprawdzenie",
    giftTotalToday: "Razem dzisiaj",
    giftCardWhy: "Karta służy tylko do potwierdzenia, że to ty. Nic nie jest teraz pobierane i nic nie odnawia się samo.",
    giftAgree: "Przeczytałem i akceptuję warunki korzystania",
    giftActivating: "Aktywowanie…",
  },
  telas: {
    subscription: "Infinity",
    conta: "Moje konto",
    privacidade: "Prywatność",
    conexoes: "Połączenia",
    voz: "Dźwięk",
    video: "Wideo",
    avisos: "Powiadomienia",
    aplicativos: "Aplikacje",
    aparencia: "Wygląd",
    batePapo: "Czat",
    acessibilidade: "Dostępność",
    idioma: "Język",
    aplicativo: "Pobierz aplikację",
    atalhos: "Skróty klawiszowe",
    desktop: "Aplikacja na komputer",
    avancado: "Zaawansowane",
    servidor: "Serwer",
    comunicado: "Komunikat systemowy",
    denuncias: "Zgłoszenia",
    publicacoes: "Wdrożenia",
  },
  grupos: {
    conta: "Konto",
    app: "Ustawienia aplikacji",
    desenvolvedor: "Deweloper",
    administracao: "Administracja",
  },
  secoes: {
    coresDoApp: "Kolory aplikacji",
    detalhesDeLogin: "Dane logowania",
    dispositivos: "Urządzenia",
    usuariosBloqueados: "Zablokowani użytkownicy",
    aplicativosAutorizados: "Autoryzowane aplikacje",
    sessoes: "Sesje",
    amigosEDms: "Znajomi i wiadomości prywatne",
    compartilhamentoDeAtividade: "Udostępnianie aktywności",
    visibilidadeDoPerfil: "Widoczność profilu",
    exportarDados: "Eksportuj dane",
    exclusaoDeDados: "Usuń dane",
    tema: "Motyw",
    corDeDestaque: "Kolor akcentu",
    interface: "Interfejs",
    listaDeCanais: "Lista kanałów",
    zoomDoApp: "Poziom powiększenia aplikacji",
    escalaDaFonte: "Rozmiar czcionki czatu",
    modoStreamer: "Prywatność podczas transmisji",
    cursores: "Kursory",
    movimento: "Ruch",
    textoEmVoz: "Zamiana tekstu na mowę",
    teclado: "Klawiatura",
    formatoDaHora: "Format godziny",
    idiomaDaInterface: "Język interfejsu",
    dispositivosDeVoz: "Urządzenia",
    testeDoMicrofone: "Test mikrofonu",
    modoDeEntrada: "Tryb wejścia",
    sensibilidade: "Czułość wejścia",
    qualidade: "Jakość",
    camera: "Kamera",
    transmissao: "Transmisja",
    exibicao: "Wyświetlanie",
    entrada: "Wprowadzanie",
    midia: "Multimedia",
    geral: "Ogólne",
    preferenciaDeMencao: "Preferencje wzmianek",
    sons: "Dźwięki",
  },
};
