export const amizades = {
  mensagensDiretas: "הודעות ישירות",
  nova: {
    titulo: "שיחה חדשה",
    detalhe: "בחרו חבר והשיחה תיפתח.",
    procurar: "חיפוש חבר",
    semAmigos: "אין לכם עדיין חברים כאן.",
    semResultado: "אין חבר בשם הזה.",
  },
  adicionar: {
    recado: "כתבו כמה מילים (לא חובה)",
    recadoDica: "מה שתכתבו כאן יופיע גם בשיחה ביניכם, אם תהיו חברים.",
    enviadoPara: "מוכן! בקשת החברות הגיעה אל {{nome}}.",
    outrosLugares: "מקומות נוספים להכיר אנשים",
    outrosLugaresDetalhe: "לא עולה אף אחד בראש? הציצו בקהילות הפתוחות, מדברים שם כמעט על הכול.",
    explorarComunidades: "גילוי קהילות",
    titulo: "הוספת חבר",
    detalhe: "אפשר להוסיף חברים לפי שם המשתמש שלהם.",
    exemplo: "שם משתמש, למשל: thiago",
    enviando: "שולח…",
    enviar: "שליחת בקשה",
  },
  gatinhoChorando: "חתלתול בוכה",
  status: {
    emChamada: "בשיחה",
    emVoz: "בקול",
  },
  menu: {
    chamada: "התחלת שיחה",
    fixar: "הצמדה למעלה",
    desafixar: "ביטול הצמדה",
    silenciar: "השתקת השיחה",
    reativar: "ביטול ההשתקה",
    copiarIdDoCanal: "העתקת מזהה הערוץ",
  },
  ativosAgora: "פעילים עכשיו",
  procurando: "בודקים מי נמצא…",
  tudoTranquilo: "הכול שקט כרגע…",
  tudoTranquiloDetalhe: "כשאתה או חבר תצטרפו לשיחה, היא תופיע כאן — ותוכל להצטרף בלחיצה אחת.",
  emVoz: "בשיחה קולית",
  voce: "אתה",
  soVoce: "רק אתה",
  pessoas: "{{quantas}} אנשים",
  voltarParaChamada: "חזרה לשיחה",
  entrarNaChamada: "הצטרפות לשיחה",
  abrirCanal: "פתיחת {{canal}} ב־{{servidor}}",
  encontreConversa: "מצא שיחה",
  amigos: "חברים",
  conversas: "שיחות",
  semConversas: "עדיין אין שיחות. הוסף חבר כדי להתחיל.",
  semConversaComEsseNome: "אין שיחה בשם הזה.",
  abrirMenu: "פתיחת שרתים ושיחות",
  solicitacoes: "בקשות הודעה",
  pedidos: "בקשות",
  spam: "ספאם",
  pedidosPendentes: "בקשות ממתינות",
  marcadosComoSpam: "סומנו כספאם",
  aceitar: "אישור",
  ignorar: "התעלמות",
  marcarSpam: "סימון כספאם",
  semPedidos: "אין בקשות ממתינות.",
  semPedidosDetalhe: "מי שאינו חבר שלך אך חולק איתך שרת מגיע לכאן לפני שהוא מגיע לשיחות שלך.",
  semSpam: "שום דבר לא סומן כספאם.",
  semSpamDetalhe: "מה שמסנן הספאם מפריד, או מה שאתה מסמן, נשאר בלשונית הזו.",
  umServidorEmComum: "שרת משותף אחד",
  servidoresEmComum: "{{quantos}} שרתים משותפים",
  semServidoresEmComum: "אין שרתים משותפים",
};
