export const comum = {
  voltar: "חזרה",
  agoraNao: "לא עכשיו",
  erro: {
    tentarDeNovo: "לנסות שוב",
    recarregar: "טעינה מחדש",
    copiarDetalhes: "העתקת הפרטים",
    parteQuebrou: "החלק הזה במסך נשבר.",
    titulo: "Ravox Chat מעד.",
    detalhe: "משהו נשבר בדרך והמסך לא הצליח להצטייר. השיחה שלכם לא אבדה — הכול נמצא בשרת.",
  },
  perdido: {
    titulo: "הכתובת הזאת לא מובילה לשום מקום.",
    detalhe: "או שהקישור שגוי, או שהעמוד עבר מקום.",
  },
  conexao: {
    voltou: "מחוברים שוב",
    reconectando: "מתחבר מחדש",
    tentativaSufixo: " · ניסיון {{numero}}",
    aSalvo: "השיחה שמורה בבטחה בשרת. הכול חוזר לבד ברגע שהחיבור חוזר.",
  },
  avisoDoNavegador: {
    titulo: "רוצים לקבל התראות על הודעות?",
    detalhe: "כש‑Ravox Chat מאחורי חלון אחר, הוא קורא לכם.",
  },
  atualizacao: {
    titulo: "עדכון",
    semAuto: "הגרסה הזו של האפליקציה לא יודעת לעדכן את עצמה. הורידו למטה את קובץ ההתקנה החדש והתקינו מעליה.",
    versaoAtual: "אתם בגרסה {{versao}}.",
    instalando: "מתקין את גרסה {{versao}}…",
    prontaVersao: "גרסה {{versao}} מוכנה להתקנה",
    baixandoVersao: "מוריד את גרסה {{versao}}…",
    baixandoComProgresso: "מוריד את גרסה {{versao}}… {{porcento}}%",
    saiuVersao: "יצאה גרסה {{versao}}",
    saiuVersaoClique: "יצאה גרסה {{versao}} — לחצו כדי להוריד",
    instalarVersaoEReiniciar: "להתקין את גרסה {{versao}} ולהפעיל מחדש",
    erroTenteDeNovo: "{{erro}} לחצו כדי לנסות שוב.",
    procurando: "מחפש…",
    emDia: "אתם מעודכנים",
    vaiFechar: "האפליקציה תיסגר עוד רגע.",
    comoInstala: "האפליקציה נסגרת, מחליפה גרסה ונפתחת שוב לבד. אם אתם בשיחה, תצאו ממנה.",
    semServidor: "לא הצלחתי להגיע לשרת הגרסאות.",
    procuraSozinho: "האפליקציה בודקת לבד בפתיחה ואחת לשש שעות.",
    instalandoReticencias: "מתקין…",
    instalandoCurto: "מתקין",
    baixandoCurto: "מוריד",
    tentarDeNovo: "לנסות שוב",
    reiniciarAgora: "להפעיל מחדש עכשיו",
    instalarEReiniciar: "להתקין ולהפעיל מחדש",
    baixar: "הורדה",
    procurar: "בדיקה",
    baixarApp: "הורדת האפליקציה",
    ariaBotao: "עדכון האפליקציה",
  },
  janela: {
    ajustarAltura: "כוונון הגובה",
    redimensionar: "שינוי גודל החלון",
    ajustarLargura: "כוונון הרוחב",
  },
  dica: {
    rotulo: "טיפ:",
    pularConfirmacao: "החזיקו Shift בזמן הלחיצה כדי לדלג על האישור הזה.",
  },
  cor: {
    pescar: "דגימת צבע מהמסך",
    hex: "ערך הקסדצימלי",
  },
  imagem: {
    titulo: "בחרו תמונה",
    enviar: "שליחת תמונה",
    escolherGif: "בחירת GIF",
    buscarGif: "חיפוש GIF",
  },
  fonte: {
    rotulo: "גופן ההודעה",
    padrao: "ברירת מחדל",
    comNome: "גופן ההודעה — {{fonte}}",
  },
  recorte: {
    titulo: "חיתוך הסמל",
    detalhe: "גררו כדי לבחור את החלק והשתמשו במחוון כדי להתקרב. הסמל עגול בכל מקום באפליקציה.",
    voltarAoComeco: "חזרה להתחלה",
    usar: "להשתמש בחיתוך הזה",
  },
  mais: "עוד",
  carregando: "טוען…",
  salvar: "שמור",
  salvando: "שומר…",
  descartar: "בטל",
  redefinir: "אפס",
  naoSalvo: "יש לך שינויים שלא נשמרו.",
  fechar: "סגירה",
  criar: "יצירה",
  nome: "שם",
  emoji: "אימוג'י",
  previa: "תצוגה מקדימה",
  cancelar: "ביטול",
  enviar: "שליחה",
  apagar: "מחיקה",
  excluir: "מחיקה",
  remover: "הסרה",
  trocar: "החלפה",
  loginNoApp: {
    titulo: "הכול מוכן!",
    detalhe: "נכנסת לחשבון. אפשר לחזור ל-Ravox Chat, האפליקציה כבר מחכה לך.",
    abrir: "פתיחת Ravox Chat",
    fecharAba: "אפשר לסגור את הכרטיסייה הזו.",
    falhouTitulo: "הכניסה לא הצליחה",
    falhouDetalhe: "חזרו לאפליקציה ונסו להיכנס שוב.",
    legenda: "רובוט מנופף",
    legendaFalhou: "חתלתול בוכה",
  },
  ads: {
    label: "פרסומת",
    title: "פרסמו כאן",
    detail: "דברו איתנו והופיעו מול מי שמשתמש ב-Ravox Chat.",
    action: "אני רוצה לפרסם",
  },
};
