export const configuracoes = {
  efeitos: {
    titulo: "אפקטים של הסמן",
    detalhe: "שובל וניצוצות שמצוירים מעל היישום. מתחילים כבויים, ונכבים מעצמם אם ביקשתם פחות תנועה.",
    rastro: "שובל הסמן",
    rastroDetalhe: "קו שעוקב אחרי הסמן ודועך מאחוריו.",
    faisca: "ניצוץ בלחיצה",
    faiscaDetalhe: "קווים קצרים שיוצאים מהנקודה שלחצתם בה.",
    cor: "צבע",
    espessura: "עובי",
    comprimento: "אורך",
    tamanho: "גודל",
    quantidade: "כמות",
  },
  email: {
    verificarTitulo: "אשרו את האימייל שלכם",
    verificarDetalhe: "יש קהילות שנותנות לכתוב רק למי שאישר. זה לחיצה אחת.",
    enviar: "שליחת הקישור",
    enviado: "הציצו בתיבה. הקישור תקף ליום.",
    falhou: "לא הצלחנו לשלוח את האימייל.",
    confirmado: "האימייל אושר",
    confirmadoDetalhe: "זהו. עכשיו אפשר לכתוב בכל קהילה שדורשת את זה.",
    linkIncompleto: "קישור חלקי",
    linkIncompletoDetalhe: "חסר הקוד בכתובת. פתחו את הקישור ישירות מהאימייל.",
    confirmando: "מאשרים…",
    expirou: "הקישור הזה כבר נוצל או שפג תוקפו.",
    irParaOApp: "לאפליקציה",
  },
  tema: {
    indisponivel: "ערכת הנושא לא זמינה",
    indisponivelDetalhe: "מי שפרסם אותה מחק אותה, או שהקישור שגוי.",
    indisponivelLinha: "ערכת הנושא לא זמינה. מי שפרסם אותה מחק אותה, או שהקישור שגוי.",
    importar: "ייבוא ערכת נושא",
    importarCurto: "ייבוא",
    importarDetalhe: "זה מחליף את ערכת הנושא שיש לכם עכשיו. אפשר לערוך אותה אחר כך בהגדרות > מראה > אולפן ערכות הנושא.",
    porAutor: "מאת {{autor}}",
    umaCorTrocada: "צבע אחד הוחלף",
    coresTrocadas: "{{quantas}} צבעים הוחלפו",
    avisoDeCss: "ערכת הנושא הזו מביאה CSS ממי שכתב אותה, ו‑CSS נוגע בכל פינה במסך. ייבאו רק מאנשים שאתם סומכים עליהם.",
    soCores: "ערכת הנושא הזו מחליפה צבעים בלבד. בלי CSS מבחוץ.",
    verCss: "הצגת ה-CSS",
    esconderCss: "הסתרת ה-CSS",
    aplicar: "החלה",
    previaSemMotor: "התצוגה המקדימה לא מריצה את המנוע. התקינו כדי לראות.",
    motorAnimado: "{{motor}} מונפש",
  },
  sair: "התנתקות",
  versoes: {
    termos: "תנאי השירות",
    privacidade: "מדיניות הפרטיות",
    copiar: "לחץ כדי להעתיק",
    copiado: "הועתק",
  },
  appColors: {
    title: "צבעי האפליקציה",
    detail: "בחר עד שלושה צבעים וכל האפליקציה תקבל את המעבר הזה.",
    locked: "עורך הצבעים הוא חלק מ-{{plan}}.",
    color: "צבע {{number}}",
    addColor: "הוספת צבע",
    removeColor: "הסרת צבע",
    surprise: "הפתע אותי",
    direction: "כיוון המעבר",
    intensity: "עוצמה",
    reset: "איפוס",
  },
  subscription: {
    colorsRow: "עורך צבעי האפליקציה",
    seePlans: "לצפייה בתוכניות",
    upgradeSubtitle: "מגבלות גבוהות יותר ותכונות בלעדיות לכתיבה, שליחת קבצים ושידור.",
    perMonth: "לחודש",
    perYear: "לשנה",
    save: "חיסכון של {{percent}}%",
    howToPay: "איך תרצה לשלם?",
    legal: "אפשר לבקש החזר עד 7 ימים אחרי התשלום. התשלום מעובד על ידי Stripe; אנחנו אף פעם לא רואים את מספר הכרטיס שלך.",
    compare: "חינמי מול Infinity",
    featureColumn: "תכונה",
    freeColumn: "חינמי",
    messageRow: "מגבלת תווים בהודעה",
    attachmentRow: "גודל קובץ לשליחה",
    screenRow: "איכות וידאו",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "כבר יש לך Infinity עד {{date}}.",
    upsell: "להגדיל את המגבלה עם Infinity",
    screenUpsell: "איכות גבוהה יותר עם Infinity",
    free: "אתה בתוכנית החינמית.",
    activeUntil: "Infinity פעיל עד {{date}}.",
    renews: "מתחדש אוטומטית ב-{{date}}.",
    endsAt: "המינוי בוטל ויסתיים ב-{{date}}.",
    pastDue: "החיוב האחרון נכשל. עדכן את הכרטיס כדי לא לאבד את הInfinity.",
    waiting: "מאשרים את התשלום…",
    subscribe: "הצטרפות למינוי",
    monthly: "חודשי",
    yearly: "שנתי",
    automatic: "כרטיס",
    manage: "ניהול התשלום",
    refund: "בקשת החזר",
    refundDetail: "אפשר לבטל עד 7 ימים אחרי התשלום: {{amount}}, עד {{date}}.",
    refundConfirm: "לבקש החזר?",
    refundConfirmDetail: "הכסף יחזור לאותו אמצעי תשלום והInfinity יסתיים מיד.",
    refunded: "בקשת ההחזר נשלחה.",
    unavailable: "המינוי עדיין לא זמין.",
    success: "התשלום התקבל. תודה!",
    canceled: "התשלום בוטל.",
    error: "משהו השתבש. נסה שוב.",
    no: "לא",
    tagRow: "תג משתמש מותאם",
    guildProfilesRow: "פרופילים לכל קהילה",
    badgeRow: "תג פרופיל",
    communitiesRow: "קהילות",
    savedRow: "הודעות שמורות",
    animatedEmojiRow: "אימוג'ים מונפשים",
    expressionsRow: "אימוג'ים ומדבקות מכל מקום",
    animatedProfileRow: "תמונות ובאנרים מונפשים",
    earlyAccessRow: "גישה מוקדמת לחידושים",
    themesRow: "ערכות נושא מותאמות",
    pixOption: "Pix",
    pixHint: "פתח את אפליקציית הבנק, בחר Pix וסרוק את קוד ה-QR או השתמש בהעתקה והדבקה.",
    pixQrAlt: "קוד QR של Pix",
    pixCopy: "העתקת קוד Pix",
    pixCopied: "קוד ה-Pix הועתק",
    pixWaiting: "ממתינים לתשלום",
    pixExpiresIn: "יפוג בעוד {{time}}",
    pixExpired: "תוקף ה-Pix הזה פג. צור חדש כדי להמשיך.",
    pixNew: "יצירת Pix חדש",
    pixPaid: "ה-Pix התקבל! Infinity פעיל.",
    forMe: "בשבילי",
    asGift: "כמתנה",
    buyGift: "קניית מתנה",
    giftReady: "המתנה מוכנה! העתק את הקישור ושלח למי שתרצה.",
    giftClaimed: "המתנה מומשה! Infinity בחשבון שלך.",
    gifts: "מתנות",
    giftsEmpty: "עוד לא קנית מתנות.",
    giftCode: "קוד המתנה",
    giftRedeem: "מימוש",
    giftCopyLink: "העתקת קישור",
    giftLinkCopied: "הקישור הועתק",
    giftClaimedBy: "מומש על ידי {{name}}",
    giftHint: "יש לך קוד מתנה? ממש אותו כאן. המתנות שקנית מופיעות למטה.",
    cardPaid: "התשלום אושר! ה-Infinity שלך פעיל.",
    payAmount: "לשלם {{amount}}",
    giftLinkTitle: "קיבלת מתנת {{plan}}!",
    giftLinkDetail: "הקש על מימוש והימים ייכנסו לחשבון שלך.",
    pageTitle: "פתח עולם של הטבות עם {{plan}}",
    pageStart: "דף הבית",
    pageBest: "הכי טוב ב-Infinity",
    pageChoose: "בחר את התוכנית שלך",
    fromPrice: "החל מ-{{amount}} לחודש. אפשר לבטל מתי שרוצים.",
    filesTitle: "שלח את הקובץ השלם",
    filesText: "הסרטון מהמסיבה, הפרויקט מהעבודה, התיקייה עם התמונות: הכול נשלח בבת אחת, בלי לחתוך, בלי לדחוס ובלי קישור לענן באמצע.",
    videoTitle: "שדר ב-1080p",
    videoText: "המסך שלך מגיע חד לצד השני, עם כפול פריימים בשנייה. אפשר לקרוא קוד ולשחק ביחד בלי שהכול ייראה מרוח.",
    messageTitle: "כתוב כאוות נפשך",
    messageText: "כפול תווים בכל הודעה, בשביל הפעמים שהסיפור ארוך ופיצול לשלושה חלקים היה הורס אותו.",
    colorsTitle: "אפליקציה בסגנון שלך",
    colorsText: "בחר את צבעי האפליקציה אחד אחד, שמור את ערכת הנושא וקח אותה לכל המכשירים שאתה נכנס מהם.",
    profileTitle: "פרופיל לכל מקום",
    profileText: "כינוי אחר, תמונה אחרת ותיאור אחר בכל קהילה — וגם תמונה מונפשת, אם תרצה.",
    freeDetail: "זה בחינם וזה נשאר בחינם.",
    currentPlan: "התוכנית הנוכחית שלך",
    popular: "הכי נבחר",
    yearlyDetail: "יוצא {{amount}} לחודש, בחיוב אחד בשנה.",
    monthlyDetail: "חיוב כל חודש, אפשר לבטל מתי שרוצים.",
    groupStyle: "הצג את הסגנון שלך",
    groupLook: "עצב את האפליקציה כרצונך",
    groupLimits: "בלי מגבלות צרות",
    closingTitle: "אז למה אתה מחכה?",
    pagePlans: "תוכניות",
    pageCompare: "השוואה",
    giftClaimTitle: "להפעיל {{plan}}?",
    giftClaimDetail: "זה {{days}} ימים שנכנסים לחשבון שלך עכשיו.",
    giftFrom: "מאת {{name}}",
    giftActivate: "הפעלה",
    giftHasPlanTitle: "כבר יש לך Infinity",
    giftHasPlanDetail: "התוכנית שלך בתוקף עד {{date}}. שמור את הקישור ושלח לחבר.",
    giftUsedTitle: "המתנה הזו כבר נוצלה",
    giftUsedDetail: "מישהו מימש את הקוד קודם. בקש קוד אחר.",
    giftNotFoundTitle: "הקוד לא נמצא",
    giftNotFoundDetail: "בדוק את הקוד או בקש שוב את הקישור.",
    giftDoneTitle: "{{plan}} הופעל!",
    giftOpenApp: "לפתוח את האפליקציה",
    giftSignIn: "התחבר כדי לממש",
    giftReviewStep: "תשלום · בדיקה",
    giftTotalToday: "סך הכול היום",
    giftCardWhy: "הכרטיס משמש רק כדי לאשר שזה אתה. לא נגבה שום דבר עכשיו ושום דבר לא מתחדש מעצמו.",
    giftAgree: "קראתי ואני מקבל את תנאי השימוש",
    giftActivating: "מפעילים…",
  },
  telas: {
    subscription: "Infinity",
    conta: "החשבון שלי",
    privacidade: "פרטיות",
    conexoes: "חיבורים",
    voz: "שמע",
    video: "וידאו",
    avisos: "התראות",
    aplicativos: "יישומים",
    aparencia: "מראה",
    batePapo: "צ'אט",
    acessibilidade: "נגישות",
    idioma: "שפה",
    aplicativo: "הורדת האפליקציה",
    atalhos: "קיצורי מקלדת",
    desktop: "אפליקציית שולחן עבודה",
    avancado: "מתקדם",
    servidor: "שרת",
    comunicado: "הודעת מערכת",
    denuncias: "דיווחים",
    publicacoes: "פריסות",
  },
  grupos: {
    conta: "חשבון",
    app: "הגדרות האפליקציה",
    desenvolvedor: "מפתח",
    administracao: "ניהול",
  },
  secoes: {
    coresDoApp: "צבעי האפליקציה",
    detalhesDeLogin: "פרטי כניסה",
    dispositivos: "מכשירים",
    usuariosBloqueados: "משתמשים חסומים",
    aplicativosAutorizados: "אפליקציות מורשות",
    sessoes: "הפעלות",
    amigosEDms: "חברים והודעות ישירות",
    compartilhamentoDeAtividade: "שיתוף פעילות",
    visibilidadeDoPerfil: "נראות הפרופיל",
    exportarDados: "ייצוא נתונים",
    exclusaoDeDados: "מחיקת נתונים",
    tema: "ערכת נושא",
    corDeDestaque: "צבע הדגשה",
    interface: "ממשק",
    listaDeCanais: "רשימת ערוצים",
    zoomDoApp: "רמת הזום של האפליקציה",
    escalaDaFonte: "גודל הגופן בצ'אט",
    modoStreamer: "פרטיות בשידור",
    cursores: "סמנים",
    movimento: "תנועה",
    textoEmVoz: "טקסט לדיבור",
    teclado: "מקלדת",
    formatoDaHora: "תבנית שעה",
    idiomaDaInterface: "שפת הממשק",
    dispositivosDeVoz: "מכשירים",
    testeDoMicrofone: "בדיקת מיקרופון",
    modoDeEntrada: "מצב קלט",
    sensibilidade: "רגישות הקלט",
    qualidade: "איכות",
    camera: "מצלמה",
    transmissao: "שידור",
    exibicao: "תצוגה",
    entrada: "קלט",
    midia: "מדיה",
    geral: "כללי",
    preferenciaDeMencao: "העדפת אזכורים",
    sons: "צלילים",
  },
};
