export const amizades = {
  mensagensDiretas: "Direktmeddelanden",
  nova: {
    titulo: "Nytt samtal",
    detalhe: "Välj en vän, så öppnas samtalet.",
    procurar: "Hitta en vän",
    semAmigos: "Du har inga vänner här än.",
    semResultado: "Ingen vän med det namnet.",
  },
  adicionar: {
    recado: "Skriv ett par ord (frivilligt)",
    recadoDica: "Det du skriver här syns också i ert samtal, om ni blir vänner.",
    enviadoPara: "Klart. Vänförfrågan gick i väg till {{nome}}.",
    outrosLugares: "Andra ställen att lära känna folk",
    outrosLugaresDetalhe: "Kommer du inte på någon? Titta på de öppna gemenskaperna, där pratas det om nästan allt.",
    explorarComunidades: "Utforska gemenskaper",
    titulo: "Lägg till vän",
    detalhe: "Du kan lägga till vänner med deras användarnamn.",
    exemplo: "Användarnamn, t.ex.: thiago",
    enviando: "Skickar…",
    enviar: "Skicka förfrågan",
  },
  gatinhoChorando: "En gråtande kattunge",
  status: {
    emChamada: "I ett samtal",
    emVoz: "I röst",
  },
  menu: {
    chamada: "Starta ett samtal",
    fixar: "Fäst högst upp",
    desafixar: "Lossa",
    silenciar: "Tysta konversationen",
    reativar: "Slå på aviseringar igen",
    copiarIdDoCanal: "Kopiera kanalens ID",
  },
  ativosAgora: "Aktiva nu",
  procurando: "Kollar vilka som är här…",
  tudoTranquilo: "Det är lugnt just nu…",
  tudoTranquiloDetalhe: "När du eller en vän går med i ett samtal dyker det upp här — och du hoppar in med ett klick.",
  emVoz: "I röstkanal",
  voce: "Du",
  soVoce: "Bara du",
  pessoas: "{{quantas}} personer",
  voltarParaChamada: "Tillbaka till samtalet",
  entrarNaChamada: "Gå med i samtalet",
  abrirCanal: "Öppna {{canal}} på {{servidor}}",
  encontreConversa: "Hitta en konversation",
  amigos: "Vänner",
  conversas: "Konversationer",
  semConversas: "Inga konversationer än. Lägg till en vän för att komma igång.",
  semConversaComEsseNome: "Ingen konversation med det namnet.",
  abrirMenu: "Öppna servrar och konversationer",
  solicitacoes: "Meddelandeförfrågningar",
  pedidos: "Förfrågningar",
  spam: "Skräppost",
  pedidosPendentes: "Väntande förfrågningar",
  marcadosComoSpam: "Markerade som skräppost",
  aceitar: "Acceptera",
  ignorar: "Ignorera",
  marcarSpam: "Markera som skräppost",
  semPedidos: "Inga förfrågningar väntar.",
  semPedidosDetalhe: "Den som inte är din vän men delar en server med dig hamnar här innan det når dina konversationer.",
  semSpam: "Inget markerat som skräppost.",
  semSpamDetalhe: "Det skräppostfiltret sorterar bort, eller det du markerar själv, stannar i den här fliken.",
  umServidorEmComum: "1 gemensam server",
  servidoresEmComum: "{{quantos}} gemensamma servrar",
  semServidoresEmComum: "Inga gemensamma servrar",
};
