export const comum = {
  voltar: "Tillbaka",
  agoraNao: "Inte nu",
  erro: {
    tentarDeNovo: "Försök igen",
    recarregar: "Läs in på nytt",
    copiarDetalhes: "Kopiera detaljerna",
    parteQuebrou: "Den här delen av skärmen gick sönder.",
    titulo: "Ravox Chat snubblade.",
    detalhe: "Något gick sönder på vägen och skärmen kunde inte rita upp sig. Ditt samtal är inte borta — allt ligger på servern.",
  },
  perdido: {
    titulo: "Den här adressen leder ingenstans.",
    detalhe: "Antingen blev länken fel, eller så har sidan flyttat.",
  },
  conexao: {
    voltou: "Ansluten igen",
    reconectando: "Ansluter igen",
    tentativaSufixo: " · försök {{numero}}",
    aSalvo: "Samtalet ligger tryggt på servern. Det kommer tillbaka av sig självt så fort anslutningen är tillbaka.",
  },
  avisoDoNavegador: {
    titulo: "Vill du få veta när det kommer meddelanden?",
    detalhe: "När Ravox Chat ligger bakom ett annat fönster ropar den på dig.",
  },
  atualizacao: {
    titulo: "Uppdatering",
    semAuto: "Den här versionen av appen kan inte uppdatera sig själv. Hämta det nyaste installationsprogrammet nedan och installera ovanpå.",
    versaoAtual: "Du har version {{versao}}.",
    instalando: "Installerar version {{versao}}…",
    prontaVersao: "Version {{versao}} är redo att installeras",
    baixandoVersao: "Hämtar version {{versao}}…",
    baixandoComProgresso: "Hämtar version {{versao}}… {{porcento}} %",
    saiuVersao: "Version {{versao}} är ute",
    saiuVersaoClique: "Version {{versao}} är ute — klicka för att hämta",
    instalarVersaoEReiniciar: "Installera version {{versao}} och starta om",
    erroTenteDeNovo: "{{erro}} Klicka för att försöka igen.",
    procurando: "Letar…",
    emDia: "Du är uppdaterad",
    vaiFechar: "Appen stängs om ett ögonblick.",
    comoInstala: "Appen stängs, byter version och öppnas av sig själv igen. Är du i ett samtal lämnar du det.",
    semServidor: "Jag nådde inte versionsservern.",
    procuraSozinho: "Appen letar själv vid start och var sjätte timme.",
    instalandoReticencias: "Installerar…",
    instalandoCurto: "Installerar",
    baixandoCurto: "Hämtar",
    tentarDeNovo: "Försök igen",
    reiniciarAgora: "Starta om nu",
    instalarEReiniciar: "Installera och starta om",
    baixar: "Hämta",
    procurar: "Sök",
    baixarApp: "Hämta appen",
    ariaBotao: "Uppdatering av appen",
  },
  janela: {
    ajustarAltura: "Justera höjden",
    redimensionar: "Ändra fönstrets storlek",
    ajustarLargura: "Justera bredden",
  },
  dica: {
    rotulo: "Tips:",
    pularConfirmacao: "håll ned Shift när du klickar för att hoppa över den här bekräftelsen.",
  },
  cor: {
    pescar: "Plocka en färg från skärmen",
    hex: "Hexadecimalt värde",
  },
  imagem: {
    titulo: "Välj en bild",
    enviar: "Skicka bild",
    escolherGif: "Välj GIF",
    buscarGif: "Sök GIF",
  },
  fonte: {
    rotulo: "Meddelandets typsnitt",
    padrao: "Standard",
    comNome: "Meddelandets typsnitt — {{fonte}}",
  },
  recorte: {
    titulo: "Beskär ikonen",
    detalhe: "Dra för att välja biten och använd reglaget för att zooma. Ikonen är rund överallt i appen.",
    voltarAoComeco: "Tillbaka till början",
    usar: "Använd den här beskärningen",
  },
  mais: "Mer",
  carregando: "Läser in…",
  salvar: "Spara",
  salvando: "Sparar…",
  descartar: "Släng",
  redefinir: "Återställ",
  naoSalvo: "Du har osparade ändringar.",
  fechar: "Stäng",
  criar: "Skapa",
  nome: "Namn",
  emoji: "Emoji",
  previa: "Förhandsvisning",
  cancelar: "Avbryt",
  enviar: "Skicka",
  apagar: "Radera",
  excluir: "Radera",
  remover: "Ta bort",
  trocar: "Byt",
  loginNoApp: {
    titulo: "Allt klart!",
    detalhe: "Du är inloggad. Gå tillbaka till Ravox Chat, appen väntar på dig.",
    abrir: "Öppna Ravox Chat",
    fecharAba: "Du kan stänga den här fliken nu.",
    falhouTitulo: "Inloggningen misslyckades",
    falhouDetalhe: "Gå tillbaka till appen och försök logga in igen.",
    legenda: "En robot som vinkar",
    legendaFalhou: "En gråtande kattunge",
  },
  ads: {
    label: "Annons",
    title: "Annonsera här",
    detail: "Prata med oss och synas för dem som använder Ravox Chat.",
    action: "Jag vill annonsera",
  },
};
