export const configuracoes = {
  efeitos: {
    titulo: "Effekter för pekaren",
    detalhe: "Ett spår och gnistor ritade ovanpå appen. De börjar avstängda och slår av sig själva om du bad om mindre rörelse.",
    rastro: "Pekarens spår",
    rastroDetalhe: "En linje som följer pekaren och bleknar bakom.",
    faisca: "Gnista vid klick",
    faiscaDetalhe: "Korta streck som far ut från där du klickade.",
    cor: "Färg",
    espessura: "Tjocklek",
    comprimento: "Längd",
    tamanho: "Storlek",
    quantidade: "Antal",
  },
  email: {
    verificarTitulo: "Bekräfta din e-post",
    verificarDetalhe: "En del gemenskaper låter bara de bekräftade skriva. Det tar ett klick.",
    enviar: "Skicka länken",
    enviado: "Titta i inkorgen. Länken håller ett dygn.",
    falhou: "E-posten gick inte att skicka.",
    confirmado: "E-posten är bekräftad",
    confirmadoDetalhe: "Klart. Nu skriver du i varje gemenskap som kräver det.",
    linkIncompleto: "Ofullständig länk",
    linkIncompletoDetalhe: "Koden saknas i adressen. Öppna länken direkt från e-posten.",
    confirmando: "Bekräftar…",
    expirou: "Den här länken är redan använd eller har gått ut.",
    irParaOApp: "Till appen",
  },
  tema: {
    indisponivel: "Temat är inte tillgängligt",
    indisponivelDetalhe: "Den som publicerade det har tagit bort det, eller så är länken fel.",
    indisponivelLinha: "Temat är inte tillgängligt. Den som publicerade det har tagit bort det, eller så är länken fel.",
    importar: "Importera tema",
    importarCurto: "Importera",
    importarDetalhe: "Det här ersätter temat du har nu. Du kan redigera det efteråt i Inställningar > Utseende > Temastudio.",
    porAutor: "av {{autor}}",
    umaCorTrocada: "1 färg utbytt",
    coresTrocadas: "{{quantas}} färger utbytta",
    avisoDeCss: "Det här temat bär med sig CSS från den som skrev det, och CSS når varje hörn av skärmen. Importera bara från folk du litar på.",
    soCores: "Det här temat byter bara färger. Ingen CSS utifrån.",
    verCss: "Visa CSS",
    esconderCss: "Dölj CSS",
    aplicar: "Använd",
    previaSemMotor: "Förhandsvisningen kör inte motorn. Installera för att se den.",
    motorAnimado: "{{motor}} animerad",
  },
  sair: "Logga ut",
  versoes: {
    termos: "Användarvillkor",
    privacidade: "Integritetspolicy",
    copiar: "Klicka för att kopiera",
    copiado: "Kopierat",
  },
  appColors: {
    title: "Appens färger",
    detail: "Välj upp till tre färger så får hela appen den gradienten.",
    locked: "Färgredigeraren ingår i {{plan}}.",
    color: "Färg {{number}}",
    addColor: "Lägg till färg",
    removeColor: "Ta bort färg",
    surprise: "Överraska mig",
    direction: "Gradientens riktning",
    intensity: "Intensitet",
    reset: "Återställ",
  },
  subscription: {
    colorsRow: "Appens färgredigerare",
    seePlans: "Se planer",
    upgradeSubtitle: "Högre gränser och exklusiva funktioner för att skriva, skicka filer och strömma.",
    perMonth: "per månad",
    perYear: "per år",
    save: "Spara {{percent}} %",
    howToPay: "Hur vill du betala?",
    legal: "Du kan begära återbetalning inom 7 dagar efter betalningen. Betalningen hanteras av Stripe; vi ser aldrig ditt kortnummer.",
    compare: "Gratis mot Infinity",
    featureColumn: "Funktion",
    freeColumn: "Gratis",
    messageRow: "Teckengräns per meddelande",
    attachmentRow: "Filstorlek vid uppladdning",
    screenRow: "Videokvalitet",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Du har redan Infinity till {{date}}.",
    upsell: "Höj gränsen med Infinity",
    screenUpsell: "Högre kvalitet med Infinity",
    free: "Du har gratisplanen.",
    activeUntil: "Infinity aktivt till {{date}}.",
    renews: "Förnyas automatiskt {{date}}.",
    endsAt: "Prenumerationen har avslutats och slutar {{date}}.",
    pastDue: "Den senaste debiteringen misslyckades. Uppdatera ditt kort för att behålla Infinity.",
    waiting: "Bekräftar betalningen…",
    subscribe: "Prenumerera",
    monthly: "Månadsvis",
    yearly: "Årsvis",
    automatic: "Kort",
    manage: "Hantera betalning",
    refund: "Begär återbetalning",
    refundDetail: "Du kan ångra dig inom 7 dagar efter betalningen: {{amount}}, till {{date}}.",
    refundConfirm: "Begära återbetalning?",
    refundConfirmDetail: "Pengarna går tillbaka till samma betalsätt och Infinity upphör direkt.",
    refunded: "Återbetalning begärd.",
    unavailable: "Prenumerationer är inte tillgängliga än.",
    success: "Betalning mottagen. Tack!",
    canceled: "Betalningen avbröts.",
    error: "Något gick fel. Försök igen.",
    no: "Nej",
    tagRow: "Egen användartagg",
    guildProfilesRow: "Profiler per community",
    badgeRow: "Profilmärke",
    communitiesRow: "Communityn",
    savedRow: "Sparade meddelanden",
    animatedEmojiRow: "Använd animerade emojis",
    expressionsRow: "Använd emojis och klistermärken överallt",
    animatedProfileRow: "Animerade avatarer och profilbanners",
    earlyAccessRow: "Tidig tillgång till nyheter",
    themesRow: "Egna teman",
    pixOption: "Pix",
    pixHint: "Öppna bankappen, välj Pix och skanna QR-koden eller använd kopiera och klistra in.",
    pixQrAlt: "Pix-QR-kod",
    pixCopy: "Kopiera Pix-kod",
    pixCopied: "Pix-koden kopierades",
    pixWaiting: "Väntar på betalning",
    pixExpiresIn: "går ut om {{time}}",
    pixExpired: "Den här Pix-betalningen har gått ut. Skapa en ny för att fortsätta.",
    pixNew: "Skapa ny Pix",
    pixPaid: "Pix mottagen! Ditt Infinity är nu aktivt.",
    forMe: "För mig",
    asGift: "Som present",
    buyGift: "Köp present",
    giftReady: "Presenten är klar! Kopiera länken och skicka till vem du vill.",
    giftClaimed: "Presenten är inlöst! Infinity finns på ditt konto.",
    gifts: "Presenter",
    giftsEmpty: "Du har inte köpt några presenter än.",
    giftCode: "Presentkod",
    giftRedeem: "Lös in",
    giftCopyLink: "Kopiera länk",
    giftLinkCopied: "Länken kopierades",
    giftClaimedBy: "inlöst av {{name}}",
    giftHint: "Har du en presentkod? Lös in den här. Presenter du köpt visas nedan.",
    cardPaid: "Betalningen godkändes! Ditt Infinity är aktivt.",
    payAmount: "Betala {{amount}}",
    giftLinkTitle: "Du har fått en {{plan}}-present!",
    giftLinkDetail: "Tryck på lös in så hamnar dagarna på ditt konto.",
    pageTitle: "Lås upp en värld av förmåner med {{plan}}",
    pageStart: "Start",
    pageBest: "Det bästa i Infinity",
    pageChoose: "Välj din plan",
    fromPrice: "Från {{amount}} i månaden. Avsluta när du vill.",
    filesTitle: "Skicka hela filen",
    filesText: "Festvideon, jobbprojektet, mappen med bilderna: allt går i väg på en gång, utan att delas upp, packas ihop eller gå via en molnlänk.",
    videoTitle: "Sänd i 1080p",
    videoText: "Din skärm kommer fram skarp hos den som tittar, med dubbelt så många bilder per sekund. Det går att läsa kod och spela ihop utan att allt blir grötigt.",
    messageTitle: "Skriv så mycket du vill",
    messageText: "Dubbelt så många tecken i varje meddelande, för när historien är lång och skulle tappa sin poäng av att delas i tre.",
    colorsTitle: "Appen med din prägel",
    colorsText: "Välj appens färger en och en, spara temat och ta med det till alla enheter där du loggar in.",
    profileTitle: "En profil för varje ställe",
    profileText: "Ett annat smeknamn, en annan bild, en annan beskrivning i varje gemenskap — och animerad bild om du vill.",
    freeDetail: "Det är gratis och förblir gratis.",
    currentPlan: "Din nuvarande plan",
    popular: "Populärast",
    yearlyDetail: "Blir {{amount}} i månaden, dras en gång om året.",
    monthlyDetail: "Dras varje månad, avsluta när du vill.",
    groupStyle: "Visa din stil",
    groupLook: "Gör appen till din",
    groupLimits: "Inga snäva gränser",
    closingTitle: "Vad väntar du på?",
    pagePlans: "Planer",
    pageCompare: "Jämför",
    giftClaimTitle: "Aktivera {{plan}}?",
    giftClaimDetail: "Det är {{days}} dagar som läggs till ditt konto nu.",
    giftFrom: "från {{name}}",
    giftActivate: "Aktivera",
    giftHasPlanTitle: "Du har redan Infinity",
    giftHasPlanDetail: "Din plan gäller till {{date}}. Spara länken och skicka den till en vän.",
    giftUsedTitle: "Den här presenten är redan använd",
    giftUsedDetail: "Någon har löst in koden tidigare. Be om en ny.",
    giftNotFoundTitle: "Koden hittades inte",
    giftNotFoundDetail: "Kolla koden eller be om länken igen.",
    giftDoneTitle: "{{plan}} aktiverat!",
    giftOpenApp: "Öppna appen",
    giftSignIn: "Logga in för att lösa in",
    giftReviewStep: "Betalning · Granska",
    giftTotalToday: "Totalt i dag",
    giftCardWhy: "Kortet är bara för att bekräfta att det är du. Inget dras nu och inget förnyas av sig självt.",
    giftAgree: "Jag har läst och accepterar användarvillkoren",
    giftActivating: "Aktiverar…",
  },
  telas: {
    subscription: "Infinity",
    conta: "Mitt konto",
    privacidade: "Integritet",
    conexoes: "Anslutningar",
    voz: "Ljud",
    video: "Video",
    avisos: "Aviseringar",
    aplicativos: "Applikationer",
    aparencia: "Utseende",
    batePapo: "Chatt",
    acessibilidade: "Tillgänglighet",
    idioma: "Språk",
    aplicativo: "Ladda ner appen",
    atalhos: "Kortkommandon",
    desktop: "Skrivbordsapp",
    avancado: "Avancerat",
    servidor: "Server",
    comunicado: "Systemmeddelande",
    denuncias: "Rapporter",
    publicacoes: "Distributioner",
  },
  grupos: {
    conta: "Konto",
    app: "Appinställningar",
    desenvolvedor: "Utvecklare",
    administracao: "Administration",
  },
  secoes: {
    coresDoApp: "Appens färger",
    detalhesDeLogin: "Inloggningsuppgifter",
    dispositivos: "Enheter",
    usuariosBloqueados: "Blockerade användare",
    aplicativosAutorizados: "Auktoriserade appar",
    sessoes: "Sessioner",
    amigosEDms: "Vänner och direktmeddelanden",
    compartilhamentoDeAtividade: "Aktivitetsdelning",
    visibilidadeDoPerfil: "Profilens synlighet",
    exportarDados: "Exportera data",
    exclusaoDeDados: "Radera data",
    tema: "Tema",
    corDeDestaque: "Accentfärg",
    interface: "Gränssnitt",
    listaDeCanais: "Kanallista",
    zoomDoApp: "Appens zoomnivå",
    escalaDaFonte: "Teckenstorlek i chatten",
    modoStreamer: "Integritet vid strömning",
    cursores: "Markörer",
    movimento: "Rörelse",
    textoEmVoz: "Text till tal",
    teclado: "Tangentbord",
    formatoDaHora: "Tidsformat",
    idiomaDaInterface: "Gränssnittets språk",
    dispositivosDeVoz: "Enheter",
    testeDoMicrofone: "Mikrofontest",
    modoDeEntrada: "Inmatningsläge",
    sensibilidade: "Inmatningskänslighet",
    qualidade: "Kvalitet",
    camera: "Kamera",
    transmissao: "Sändning",
    exibicao: "Visning",
    entrada: "Inmatning",
    midia: "Media",
    geral: "Allmänt",
    preferenciaDeMencao: "Omnämnandeinställning",
    sons: "Ljud",
  },
};
