export const comum = {
  voltar: "Zpět",
  agoraNao: "Teď ne",
  erro: {
    tentarDeNovo: "Zkusit znovu",
    recarregar: "Načíst znovu",
    copiarDetalhes: "Zkopírovat podrobnosti",
    parteQuebrou: "Tahle část obrazovky se rozbila.",
    titulo: "Ravox Chat klopýtl.",
    detalhe: "Něco se cestou rozbilo a obrazovka se nedokázala vykreslit. Vaše konverzace se neztratila — vše je na serveru.",
  },
  perdido: {
    titulo: "Tahle adresa nikam nevede.",
    detalhe: "Buď je odkaz špatně, nebo se stránka přesunula.",
  },
  conexao: {
    voltou: "Zase připojeno",
    reconectando: "Připojuji znovu",
    tentativaSufixo: " · pokus {{numero}}",
    aSalvo: "Konverzace je v bezpečí na serveru. Jakmile se spojení vrátí, vše naskočí samo.",
  },
  avisoDoNavegador: {
    titulo: "Chcete upozornění na zprávy?",
    detalhe: "Když je Ravox Chat za jiným oknem, ozve se vám.",
  },
  atualizacao: {
    titulo: "Aktualizace",
    semAuto: "Tato verze aplikace se neumí aktualizovat sama. Stáhněte níže nejnovější instalátor a nainstalujte ho přes ni.",
    versaoAtual: "Máte verzi {{versao}}.",
    instalando: "Instaluje se verze {{versao}}…",
    prontaVersao: "Verze {{versao}} je připravená k instalaci",
    baixandoVersao: "Stahuje se verze {{versao}}…",
    baixandoComProgresso: "Stahuje se verze {{versao}}… {{porcento}} %",
    saiuVersao: "Vyšla verze {{versao}}",
    saiuVersaoClique: "Vyšla verze {{versao}} — kliknutím ji stáhnete",
    instalarVersaoEReiniciar: "Nainstalovat verzi {{versao}} a restartovat",
    erroTenteDeNovo: "{{erro}} Kliknutím to zkuste znovu.",
    procurando: "Hledám…",
    emDia: "Máte vše aktuální",
    vaiFechar: "Aplikace se za okamžik zavře.",
    comoInstala: "Aplikace se zavře, vymění verzi a sama se znovu otevře. Pokud jste v hovoru, opustíte ho.",
    semServidor: "Nepodařilo se spojit se serverem verzí.",
    procuraSozinho: "Aplikace hledá sama při spuštění a každých šest hodin.",
    instalandoReticencias: "Instaluji…",
    instalandoCurto: "Instaluji",
    baixandoCurto: "Stahuji",
    tentarDeNovo: "Zkusit znovu",
    reiniciarAgora: "Restartovat hned",
    instalarEReiniciar: "Nainstalovat a restartovat",
    baixar: "Stáhnout",
    procurar: "Zkontrolovat",
    baixarApp: "Stáhnout aplikaci",
    ariaBotao: "Aktualizace aplikace",
  },
  janela: {
    ajustarAltura: "Upravit výšku",
    redimensionar: "Změnit velikost okna",
    ajustarLargura: "Upravit šířku",
  },
  dica: {
    rotulo: "Tip:",
    pularConfirmacao: "podržte Shift při kliknutí a toto potvrzení se přeskočí.",
  },
  cor: {
    pescar: "Nabrat barvu z obrazovky",
    hex: "Hexadecimální hodnota",
  },
  imagem: {
    titulo: "Vyberte obrázek",
    enviar: "Odeslat obrázek",
    escolherGif: "Vybrat GIF",
    buscarGif: "Hledat GIF",
  },
  fonte: {
    rotulo: "Písmo zprávy",
    padrao: "Výchozí",
    comNome: "Písmo zprávy — {{fonte}}",
  },
  recorte: {
    titulo: "Oříznout ikonu",
    detalhe: "Tažením vyberte výřez a posuvníkem přibližte. Ikona je v celé aplikaci kulatá.",
    voltarAoComeco: "Zpět na začátek",
    usar: "Použít tento výřez",
  },
  mais: "Více",
  carregando: "Načítání…",
  salvar: "Uložit",
  salvando: "Ukládání…",
  descartar: "Zahodit",
  redefinir: "Obnovit",
  naoSalvo: "Máš neuložené změny.",
  fechar: "Zavřít",
  criar: "Vytvořit",
  nome: "Název",
  emoji: "Emoji",
  previa: "Náhled",
  cancelar: "Zrušit",
  enviar: "Odeslat",
  apagar: "Smazat",
  excluir: "Smazat",
  remover: "Odebrat",
  trocar: "Změnit",
  loginNoApp: {
    titulo: "Hotovo!",
    detalhe: "Jste přihlášeni. Vraťte se do Ravox Chat, aplikace už na vás čeká.",
    abrir: "Otevřít Ravox Chat",
    fecharAba: "Tuto kartu už můžete zavřít.",
    falhouTitulo: "Přihlášení se nezdařilo",
    falhouDetalhe: "Vraťte se do aplikace a zkuste se přihlásit znovu.",
    legenda: "Mávající robot",
    legendaFalhou: "Plačící koťátko",
  },
  ads: {
    label: "Reklama",
    title: "Inzerujte zde",
    detail: "Ozvěte se nám a ukažte se těm, kdo používají Ravox Chat.",
    action: "Chci inzerovat",
  },
};
