export const configuracoes = {
  efeitos: {
    titulo: "Efekty ukazatele",
    detalhe: "Stopa a jiskry kreslené přes aplikaci. Přicházejí vypnuté a samy zmizí, když jste si řekli o méně pohybu.",
    rastro: "Stopa kurzoru",
    rastroDetalhe: "Čára, která jde za ukazatelem a vzadu bledne.",
    faisca: "Jiskry při kliknutí",
    faiscaDetalhe: "Krátké čárky vyletující z místa, kam jste klikli.",
    cor: "Barva",
    espessura: "Tloušťka",
    comprimento: "Délka",
    tamanho: "Velikost",
    quantidade: "Počet",
  },
  email: {
    verificarTitulo: "Potvrďte svůj e-mail",
    verificarDetalhe: "Některé komunity nechají psát jen potvrzené. Je to na jedno kliknutí.",
    enviar: "Poslat odkaz",
    enviado: "Mrkněte do schránky. Odkaz platí jeden den.",
    falhou: "E-mail se nepodařilo odeslat.",
    confirmado: "E-mail potvrzen",
    confirmadoDetalhe: "Hotovo. Teď píšete i tam, kde to komunita vyžaduje.",
    linkIncompleto: "Neúplný odkaz",
    linkIncompletoDetalhe: "V adrese chybí kód. Otevřete odkaz přímo z e-mailu.",
    confirmando: "Potvrzuje se…",
    expirou: "Tento odkaz už byl použit nebo mu vypršela platnost.",
    irParaOApp: "Přejít do aplikace",
  },
  tema: {
    indisponivel: "Motiv není dostupný",
    indisponivelDetalhe: "Ten, kdo ho zveřejnil, ho smazal, nebo je odkaz špatně.",
    indisponivelLinha: "Motiv není dostupný. Ten, kdo ho zveřejnil, ho smazal, nebo je odkaz špatně.",
    importar: "Importovat motiv",
    importarCurto: "Importovat",
    importarDetalhe: "Tímto nahradíte motiv, který máte teď. Upravit ho můžete později v Nastavení > Vzhled > Studio motivů.",
    porAutor: "od {{autor}}",
    umaCorTrocada: "1 vyměněná barva",
    coresTrocadas: "{{quantas}} vyměněných barev",
    avisoDeCss: "Tenhle motiv nese CSS od svého autora a CSS sahá do každého kouta obrazovky. Importujte jen od lidí, kterým věříte.",
    soCores: "Tenhle motiv mění jen barvy. Žádné cizí CSS.",
    verCss: "Zobrazit CSS",
    esconderCss: "Skrýt CSS",
    aplicar: "Použít",
    previaSemMotor: "Náhled motor nespouští. Nainstalujte si ho, ať ho uvidíte.",
    motorAnimado: "{{motor}} animovaný",
  },
  sair: "Odhlásit se",
  versoes: {
    termos: "Podmínky služby",
    privacidade: "Zásady ochrany soukromí",
    copiar: "Klikni pro kopírování",
    copiado: "Zkopírováno",
  },
  appColors: {
    title: "Barvy aplikace",
    detail: "Vyberte až tři barvy a celá aplikace dostane tento přechod.",
    locked: "Editor barev patří k {{plan}}.",
    color: "Barva {{number}}",
    addColor: "Přidat barvu",
    removeColor: "Odebrat barvu",
    surprise: "Překvap mě",
    direction: "Směr přechodu",
    intensity: "Intenzita",
    reset: "Obnovit",
  },
  subscription: {
    colorsRow: "Editor barev aplikace",
    seePlans: "Zobrazit tarify",
    upgradeSubtitle: "Vyšší limity a exkluzivní funkce pro psaní, posílání souborů a vysílání.",
    perMonth: "měsíčně",
    perYear: "ročně",
    save: "Ušetříte {{percent}} %",
    howToPay: "Jak chcete zaplatit?",
    legal: "O vrácení peněz můžete požádat do 7 dnů od platby. Platbu zpracovává Stripe; číslo vaší karty nikdy nevidíme.",
    compare: "Zdarma vs. Infinity",
    featureColumn: "Funkce",
    freeColumn: "Zdarma",
    messageRow: "Limit znaků zprávy",
    attachmentRow: "Velikost odesílaného souboru",
    screenRow: "Kvalita videa",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Infinity už máte do {{date}}.",
    upsell: "Zvýšit limit s Infinity",
    screenUpsell: "Vyšší kvalita s Infinity",
    free: "Máte bezplatný tarif.",
    activeUntil: "Infinity aktivní do {{date}}.",
    renews: "Automaticky se obnoví {{date}}.",
    endsAt: "Předplatné bylo zrušeno a končí {{date}}.",
    pastDue: "Poslední platba se nezdařila. Aktualizujte kartu, abyste o Infinity nepřišli.",
    waiting: "Potvrzování platby…",
    subscribe: "Předplatit",
    monthly: "Měsíčně",
    yearly: "Ročně",
    automatic: "Karta",
    manage: "Spravovat platbu",
    refund: "Požádat o vrácení peněz",
    refundDetail: "Můžete odstoupit do 7 dnů od platby: {{amount}}, do {{date}}.",
    refundConfirm: "Požádat o vrácení peněz?",
    refundConfirmDetail: "Peníze se vrátí stejným způsobem platby a Infinity hned skončí.",
    refunded: "Žádost o vrácení odeslána.",
    unavailable: "Předplatné zatím není k dispozici.",
    success: "Platba přijata. Děkujeme!",
    canceled: "Platba zrušena.",
    error: "Něco se nepovedlo. Zkuste to znovu.",
    no: "Ne",
    tagRow: "Vlastní uživatelský štítek",
    guildProfilesRow: "Profily pro komunity",
    badgeRow: "Odznak profilu",
    communitiesRow: "Komunity",
    savedRow: "Uložené zprávy",
    animatedEmojiRow: "Animované emoji",
    expressionsRow: "Emoji a nálepky odkudkoli",
    animatedProfileRow: "Animované avatary a bannery profilu",
    earlyAccessRow: "Předběžný přístup k novinkám",
    themesRow: "Vlastní motivy",
    pixOption: "Pix",
    pixHint: "Otevřete bankovní aplikaci, zvolte Pix a naskenujte QR kód nebo použijte kopírovat a vložit.",
    pixQrAlt: "QR kód Pix",
    pixCopy: "Kopírovat kód Pix",
    pixCopied: "Kód Pix zkopírován",
    pixWaiting: "Čekáme na platbu",
    pixExpiresIn: "vyprší za {{time}}",
    pixExpired: "Tento Pix vypršel. Vytvořte nový a pokračujte.",
    pixNew: "Vytvořit nový Pix",
    pixPaid: "Pix přijat! Vaše Infinity je aktivní.",
    forMe: "Pro mě",
    asGift: "Jako dárek",
    buyGift: "Koupit dárek",
    giftReady: "Dárek je připravený! Zkopírujte odkaz a pošlete komu chcete.",
    giftClaimed: "Dárek uplatněn! Infinity máte na účtu.",
    gifts: "Dárky",
    giftsEmpty: "Zatím jste nekoupili žádný dárek.",
    giftCode: "Kód dárku",
    giftRedeem: "Uplatnit",
    giftCopyLink: "Kopírovat odkaz",
    giftLinkCopied: "Odkaz zkopírován",
    giftClaimedBy: "uplatnil {{name}}",
    giftHint: "Máte kód dárku? Uplatněte ho tady. Koupené dárky jsou níže.",
    cardPaid: "Platba schválena! Vaše Infinity je aktivní.",
    payAmount: "Zaplatit {{amount}}",
    giftLinkTitle: "Dostali jste dárek {{plan}}!",
    giftLinkDetail: "Klepněte na uplatnit a dny přistanou na vašem účtu.",
    pageTitle: "Odemkněte svět výhod s {{plan}}",
    pageStart: "Úvod",
    pageBest: "To nejlepší z Infinity",
    pageChoose: "Vyberte si tarif",
    fromPrice: "Od {{amount}} měsíčně. Zrušíte, kdykoli budete chtít.",
    filesTitle: "Pošlete celý soubor",
    filesText: "Video z oslavy, pracovní projekt, složka s fotkami: odejde všechno najednou, bez dělení, bez balení do archivu a bez odkazu na cloud po cestě.",
    videoTitle: "Vysílejte v 1080p",
    videoText: "Vaše obrazovka dorazí na druhou stranu ostrá, s dvojnásobným počtem snímků za sekundu. Dá se číst kód i hrát spolu, aniž by se všechno rozmazalo.",
    messageTitle: "Pište, jak je vám libo",
    messageText: "Dvojnásobek znaků v každé zprávě — pro chvíle, kdy je příběh dlouhý a rozdělit ho na tři části by zkazilo pointu.",
    colorsTitle: "Aplikace k vašemu obrazu",
    colorsText: "Vyberte barvy aplikace jednu po druhé, uložte motiv a vezměte si ho do všech zařízení, odkud se přihlašujete.",
    profileTitle: "Jiný profil pro každé místo",
    profileText: "Jiná přezdívka, jiná fotka, jiný popis v každé komunitě — a animovaná fotka, pokud chcete.",
    freeDetail: "Je zdarma a zůstane zdarma.",
    currentPlan: "Váš současný tarif",
    popular: "Nejčastější volba",
    yearlyDetail: "Vychází to na {{amount}} měsíčně, účtováno jednou ročně.",
    monthlyDetail: "Účtuje se každý měsíc, zrušíte, kdykoli budete chtít.",
    groupStyle: "Ukažte svůj styl",
    groupLook: "Aplikace po vašem",
    groupLimits: "Žádné těsné limity",
    closingTitle: "Na co ještě čekáte?",
    pagePlans: "Tarify",
    pageCompare: "Porovnat",
    giftClaimTitle: "Aktivovat {{plan}}?",
    giftClaimDetail: "Na váš účet teď přijde {{days}} dnů.",
    giftFrom: "od {{name}}",
    giftActivate: "Aktivovat",
    giftHasPlanTitle: "Infinity už máte",
    giftHasPlanDetail: "Váš tarif platí do {{date}}. Nechte si odkaz a pošlete ho kamarádovi.",
    giftUsedTitle: "Tento dárek už byl použit",
    giftUsedDetail: "Někdo kód uplatnil dřív. Požádejte o jiný.",
    giftNotFoundTitle: "Kód nenalezen",
    giftNotFoundDetail: "Zkontrolujte kód nebo si znovu vyžádejte odkaz.",
    giftDoneTitle: "{{plan}} aktivováno!",
    giftOpenApp: "Otevřít aplikaci",
    giftSignIn: "Přihlaste se a uplatněte",
    giftReviewStep: "Platba · Kontrola",
    giftTotalToday: "Dnes celkem",
    giftCardWhy: "Karta slouží jen k potvrzení, že jsi to ty. Teď se nic nestrhává a nic se samo neobnovuje.",
    giftAgree: "Přečetl jsem si podmínky použití a souhlasím s nimi",
    giftActivating: "Aktivuje se…",
  },
  telas: {
    subscription: "Infinity",
    conta: "Můj účet",
    privacidade: "Soukromí",
    conexoes: "Připojení",
    voz: "Zvuk",
    video: "Video",
    avisos: "Oznámení",
    aplicativos: "Aplikace",
    aparencia: "Vzhled",
    batePapo: "Chat",
    acessibilidade: "Přístupnost",
    idioma: "Jazyk",
    aplicativo: "Stáhnout aplikaci",
    atalhos: "Klávesové zkratky",
    desktop: "Aplikace pro počítač",
    avancado: "Pokročilé",
    servidor: "Server",
    comunicado: "Systémové oznámení",
    denuncias: "Nahlášení",
    publicacoes: "Nasazení",
  },
  grupos: {
    conta: "Účet",
    app: "Nastavení aplikace",
    desenvolvedor: "Vývojář",
    administracao: "Správa",
  },
  secoes: {
    coresDoApp: "Barvy aplikace",
    detalhesDeLogin: "Přihlašovací údaje",
    dispositivos: "Zařízení",
    usuariosBloqueados: "Blokovaní uživatelé",
    aplicativosAutorizados: "Autorizované aplikace",
    sessoes: "Relace",
    amigosEDms: "Přátelé a přímé zprávy",
    compartilhamentoDeAtividade: "Sdílení aktivity",
    visibilidadeDoPerfil: "Viditelnost profilu",
    exportarDados: "Exportovat data",
    exclusaoDeDados: "Smazat data",
    tema: "Motiv",
    corDeDestaque: "Barva zvýraznění",
    interface: "Rozhraní",
    listaDeCanais: "Seznam kanálů",
    zoomDoApp: "Úroveň přiblížení aplikace",
    escalaDaFonte: "Velikost písma chatu",
    modoStreamer: "Soukromí při vysílání",
    cursores: "Kurzory",
    movimento: "Pohyb",
    textoEmVoz: "Převod textu na řeč",
    teclado: "Klávesnice",
    formatoDaHora: "Formát času",
    idiomaDaInterface: "Jazyk rozhraní",
    dispositivosDeVoz: "Zařízení",
    testeDoMicrofone: "Test mikrofonu",
    modoDeEntrada: "Režim vstupu",
    sensibilidade: "Citlivost vstupu",
    qualidade: "Kvalita",
    camera: "Kamera",
    transmissao: "Vysílání",
    exibicao: "Zobrazení",
    entrada: "Zadávání",
    midia: "Média",
    geral: "Obecné",
    preferenciaDeMencao: "Předvolba zmínek",
    sons: "Zvuky",
  },
};
