export const amizades = {
  mensagensDiretas: "Pesan langsung",
  nova: {
    titulo: "Obrolan baru",
    detalhe: "Pilih seorang teman, obrolannya langsung terbuka.",
    procurar: "Cari teman",
    semAmigos: "Kamu belum punya teman di sini.",
    semResultado: "Tidak ada teman dengan nama itu.",
  },
  adicionar: {
    recado: "Tulis pesan singkat (opsional)",
    recadoDica: "Apa yang kamu tulis di sini juga muncul di obrolan kalian, kalau jadi berteman.",
    enviadoPara: "Beres! Permintaan pertemanan sudah sampai ke {{nome}}.",
    outrosLugares: "Tempat lain untuk cari teman",
    outrosLugaresDetalhe: "Tidak terpikir siapa pun? Lihat komunitas terbuka, di sana orang membahas hampir semua hal.",
    explorarComunidades: "Jelajahi komunitas",
    titulo: "Tambah teman",
    detalhe: "Kamu bisa menambahkan teman lewat nama pengguna mereka.",
    exemplo: "Nama pengguna, mis.: thiago",
    enviando: "Mengirim…",
    enviar: "Kirim permintaan",
  },
  gatinhoChorando: "Anak kucing yang menangis",
  status: {
    emChamada: "Sedang menelepon",
    emVoz: "Di suara",
  },
  menu: {
    chamada: "Mulai panggilan",
    fixar: "Sematkan di atas",
    desafixar: "Lepas sematan",
    silenciar: "Bisukan percakapan",
    reativar: "Bunyikan lagi notifikasi",
    copiarIdDoCanal: "Salin ID kanal",
  },
  ativosAgora: "Aktif sekarang",
  procurando: "Melihat siapa yang ada…",
  tudoTranquilo: "Untuk sekarang sepi…",
  tudoTranquiloDetalhe: "Saat kamu atau teman masuk ke panggilan, itu muncul di sini — dan kamu bisa ikut dengan satu klik.",
  emVoz: "Di suara",
  voce: "Kamu",
  soVoce: "Hanya kamu",
  pessoas: "{{quantas}} orang",
  voltarParaChamada: "Kembali ke panggilan",
  entrarNaChamada: "Gabung panggilan",
  abrirCanal: "Buka {{canal}} di {{servidor}}",
  encontreConversa: "Cari percakapan",
  amigos: "Teman",
  conversas: "Percakapan",
  semConversas: "Belum ada percakapan. Tambahkan teman untuk mulai.",
  semConversaComEsseNome: "Tidak ada percakapan dengan nama itu.",
  abrirMenu: "Buka server dan percakapan",
  solicitacoes: "Permintaan pesan",
  pedidos: "Permintaan",
  spam: "Spam",
  pedidosPendentes: "Permintaan tertunda",
  marcadosComoSpam: "Ditandai sebagai spam",
  aceitar: "Terima",
  ignorar: "Abaikan",
  marcarSpam: "Tandai sebagai spam",
  semPedidos: "Tidak ada permintaan menunggu.",
  semPedidosDetalhe: "Orang yang bukan temanmu tapi satu server denganmu mendarat di sini sebelum sampai ke percakapanmu.",
  semSpam: "Tidak ada yang ditandai sebagai spam.",
  semSpamDetalhe: "Apa yang disaring filter spam, atau yang kamu tandai sendiri, tetap di tab ini.",
  umServidorEmComum: "1 server bersama",
  servidoresEmComum: "{{quantos}} server bersama",
  semServidoresEmComum: "Tidak ada server bersama",
};
