export const configuracoes = {
  efeitos: {
    titulo: "Efek penunjuk",
    detalhe: "Jejak dan percikan digambar di atas aplikasi. Datang dalam keadaan mati, dan padam sendiri kalau kamu minta lebih sedikit gerak.",
    rastro: "Jejak kursor",
    rastroDetalhe: "Garis yang mengikuti penunjuk dan memudar di belakangnya.",
    faisca: "Percikan saat diklik",
    faiscaDetalhe: "Garis pendek yang menyembur dari titik klik.",
    cor: "Warna",
    espessura: "Ketebalan",
    comprimento: "Panjang",
    tamanho: "Ukuran",
    quantidade: "Jumlah",
  },
  email: {
    verificarTitulo: "Konfirmasi surelmu",
    verificarDetalhe: "Sebagian komunitas hanya memperbolehkan yang sudah dikonfirmasi menulis. Cukup sekali klik.",
    enviar: "Kirim tautannya",
    enviado: "Lihat kotak masuk. Tautan berlaku sehari.",
    falhou: "Surel tidak bisa dikirim.",
    confirmado: "Surel dikonfirmasi",
    confirmadoDetalhe: "Beres. Sekarang kamu bisa menulis di komunitas mana pun yang memintanya.",
    linkIncompleto: "Tautan tidak lengkap",
    linkIncompletoDetalhe: "Kode di alamatnya hilang. Buka tautan langsung dari surelnya.",
    confirmando: "Mengonfirmasi…",
    expirou: "Tautan ini sudah dipakai atau kedaluwarsa.",
    irParaOApp: "Ke aplikasi",
  },
  tema: {
    indisponivel: "Tema tidak tersedia",
    indisponivelDetalhe: "Yang menerbitkannya sudah menghapusnya, atau tautannya salah.",
    indisponivelLinha: "Tema tidak tersedia. Yang menerbitkannya sudah menghapusnya, atau tautannya salah.",
    importar: "Impor tema",
    importarCurto: "Impor",
    importarDetalhe: "Ini menggantikan tema yang kamu punya sekarang. Nanti bisa diubah di Pengaturan > Tampilan > Studio tema.",
    porAutor: "oleh {{autor}}",
    umaCorTrocada: "1 warna ditukar",
    coresTrocadas: "{{quantas}} warna ditukar",
    avisoDeCss: "Tema ini membawa CSS dari penulisnya, dan CSS menjangkau setiap sudut layar. Impor hanya dari orang yang kamu percaya.",
    soCores: "Tema ini hanya menukar warna. Tanpa CSS dari luar.",
    verCss: "Lihat CSS",
    esconderCss: "Sembunyikan CSS",
    aplicar: "Terapkan",
    previaSemMotor: "Pratinjau tidak menjalankan mesinnya. Pasang dulu untuk melihatnya.",
    motorAnimado: "{{motor}} beranimasi",
  },
  sair: "Keluar",
  versoes: {
    termos: "Ketentuan layanan",
    privacidade: "Kebijakan privasi",
    copiar: "Klik untuk menyalin",
    copiado: "Disalin",
  },
  appColors: {
    title: "Warna aplikasi",
    detail: "Pilih hingga tiga warna dan seluruh aplikasi memakai gradasi itu.",
    locked: "Editor warna adalah fitur {{plan}}.",
    color: "Warna {{number}}",
    addColor: "Tambah warna",
    removeColor: "Hapus warna",
    surprise: "Kejutkan aku",
    direction: "Arah gradasi",
    intensity: "Intensitas",
    reset: "Setel ulang",
  },
  subscription: {
    colorsRow: "Editor warna aplikasi",
    seePlans: "Lihat paket",
    upgradeSubtitle: "Batas lebih besar dan fitur eksklusif untuk menulis, mengirim file, dan streaming.",
    perMonth: "per bulan",
    perYear: "per tahun",
    save: "Hemat {{percent}}%",
    howToPay: "Mau bayar dengan cara apa?",
    legal: "Kamu bisa meminta pengembalian dana dalam 7 hari setelah pembayaran. Pembayaran diproses oleh Stripe; kami tidak pernah melihat nomor kartumu.",
    compare: "Gratis vs Infinity",
    featureColumn: "Fitur",
    freeColumn: "Gratis",
    messageRow: "Batas karakter pesan",
    attachmentRow: "Ukuran file kiriman",
    screenRow: "Kualitas video",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Kamu sudah punya Infinity sampai {{date}}.",
    upsell: "Naikkan batas dengan Infinity",
    screenUpsell: "Kualitas lebih tinggi dengan Infinity",
    free: "Kamu memakai paket gratis.",
    activeUntil: "Infinity aktif sampai {{date}}.",
    renews: "Diperpanjang otomatis pada {{date}}.",
    endsAt: "Langganan dibatalkan dan berakhir pada {{date}}.",
    pastDue: "Tagihan terakhir gagal. Perbarui kartu agar Infinity tidak hilang.",
    waiting: "Mengonfirmasi pembayaran…",
    subscribe: "Berlangganan",
    monthly: "Bulanan",
    yearly: "Tahunan",
    automatic: "Kartu",
    manage: "Kelola pembayaran",
    refund: "Minta pengembalian dana",
    refundDetail: "Kamu bisa membatalkan dalam 7 hari setelah pembayaran: {{amount}}, sampai {{date}}.",
    refundConfirm: "Minta pengembalian dana?",
    refundConfirmDetail: "Uang kembali ke metode pembayaran yang sama dan Infinity langsung berakhir.",
    refunded: "Pengembalian dana diminta.",
    unavailable: "Langganan belum tersedia.",
    success: "Pembayaran diterima. Terima kasih!",
    canceled: "Pembayaran dibatalkan.",
    error: "Terjadi kesalahan. Coba lagi.",
    no: "Tidak",
    tagRow: "Tag pengguna khusus",
    guildProfilesRow: "Profil per komunitas",
    badgeRow: "Lencana profil",
    communitiesRow: "Komunitas",
    savedRow: "Pesan tersimpan",
    animatedEmojiRow: "Emoji animasi",
    expressionsRow: "Emoji dan stiker dari mana saja",
    animatedProfileRow: "Avatar dan banner profil animasi",
    earlyAccessRow: "Akses awal ke fitur baru",
    themesRow: "Tema khusus",
    pixOption: "Pix",
    pixHint: "Buka aplikasi bank, pilih Pix, lalu pindai kode QR atau salin-tempel kodenya.",
    pixQrAlt: "Kode QR Pix",
    pixCopy: "Salin kode Pix",
    pixCopied: "Kode Pix disalin",
    pixWaiting: "Menunggu pembayaran",
    pixExpiresIn: "berakhir dalam {{time}}",
    pixExpired: "Pix ini sudah kedaluwarsa. Buat yang baru untuk melanjutkan.",
    pixNew: "Buat Pix baru",
    pixPaid: "Pix diterima! Infinity kamu sudah aktif.",
    forMe: "Untuk saya",
    asGift: "Sebagai hadiah",
    buyGift: "Beli hadiah",
    giftReady: "Hadiah siap! Salin tautannya dan kirim ke siapa pun.",
    giftClaimed: "Hadiah ditukarkan! Infinity sudah ada di akunmu.",
    gifts: "Hadiah",
    giftsEmpty: "Kamu belum membeli hadiah apa pun.",
    giftCode: "Kode hadiah",
    giftRedeem: "Tukarkan",
    giftCopyLink: "Salin tautan",
    giftLinkCopied: "Tautan disalin",
    giftClaimedBy: "ditukarkan oleh {{name}}",
    giftHint: "Punya kode hadiah? Tukarkan di sini. Hadiah yang kamu beli ada di bawah.",
    cardPaid: "Pembayaran disetujui! Infinity kamu aktif.",
    payAmount: "Bayar {{amount}}",
    giftLinkTitle: "Kamu menerima hadiah {{plan}}!",
    giftLinkDetail: "Ketuk tukarkan dan harinya masuk ke akunmu.",
    pageTitle: "Buka dunia keuntungan dengan {{plan}}",
    pageStart: "Beranda",
    pageBest: "Yang terbaik dari Infinity",
    pageChoose: "Pilih paketmu",
    fromPrice: "Mulai {{amount}} per bulan. Batalkan kapan saja.",
    filesTitle: "Kirim file utuh",
    filesText: "Video pesta, proyek kantor, folder foto: semua berangkat sekali jalan, tanpa dipotong, tanpa dikompres dan tanpa tautan cloud di tengahnya.",
    videoTitle: "Streaming 1080p",
    videoText: "Layarmu sampai dengan tajam ke orang di seberang, dengan frame per detik dua kali lipat. Bisa baca kode dan main bareng tanpa jadi buram.",
    messageTitle: "Tulis sepuasnya",
    messageText: "Dua kali lipat karakter di tiap pesan, untuk saat ceritanya panjang dan memecahnya jadi tiga bagian merusak serunya.",
    colorsTitle: "Aplikasi dengan gayamu",
    colorsText: "Pilih warna aplikasi satu per satu, simpan temanya dan bawa ke semua perangkat tempat kamu masuk.",
    profileTitle: "Satu profil untuk tiap tempat",
    profileText: "Nama panggilan lain, foto lain, deskripsi lain di tiap komunitas — dan foto bergerak, kalau kamu mau.",
    freeDetail: "Gratis dan tetap gratis.",
    currentPlan: "Paketmu saat ini",
    popular: "Paling dipilih",
    yearlyDetail: "Setara {{amount}} per bulan, ditagih sekali setahun.",
    monthlyDetail: "Ditagih tiap bulan, batalkan kapan saja.",
    groupStyle: "Tunjukkan gayamu",
    groupLook: "Bikin aplikasinya jadi milikmu",
    groupLimits: "Tanpa batas yang sempit",
    closingTitle: "Tunggu apa lagi?",
    pagePlans: "Paket",
    pageCompare: "Bandingkan",
    giftClaimTitle: "Aktifkan {{plan}}?",
    giftClaimDetail: "Ada {{days}} hari yang masuk ke akunmu sekarang.",
    giftFrom: "dari {{name}}",
    giftActivate: "Aktifkan",
    giftHasPlanTitle: "Kamu sudah punya Infinity",
    giftHasPlanDetail: "Paketmu berlaku sampai {{date}}. Simpan tautannya dan kirim ke teman.",
    giftUsedTitle: "Hadiah ini sudah dipakai",
    giftUsedDetail: "Seseorang menukarkan kode ini lebih dulu. Minta yang lain.",
    giftNotFoundTitle: "Kode tidak ditemukan",
    giftNotFoundDetail: "Periksa kodenya atau minta tautannya lagi.",
    giftDoneTitle: "{{plan}} aktif!",
    giftOpenApp: "Buka aplikasi",
    giftSignIn: "Masuk untuk menukarkan",
    giftReviewStep: "Pembayaran · Tinjau",
    giftTotalToday: "Total hari ini",
    giftCardWhy: "Kartu hanya untuk memastikan ini memang kamu. Tidak ada yang ditagih sekarang dan tidak ada yang diperpanjang sendiri.",
    giftAgree: "Saya sudah membaca dan menerima ketentuan penggunaan",
    giftActivating: "Mengaktifkan…",
  },
  telas: {
    subscription: "Infinity",
    conta: "Akun saya",
    privacidade: "Privasi",
    conexoes: "Koneksi",
    voz: "Audio",
    video: "Video",
    avisos: "Notifikasi",
    aplicativos: "Aplikasi",
    aparencia: "Tampilan",
    batePapo: "Obrolan",
    acessibilidade: "Aksesibilitas",
    idioma: "Bahasa",
    aplicativo: "Unduh aplikasi",
    atalhos: "Pintasan",
    desktop: "Aplikasi desktop",
    avancado: "Lanjutan",
    servidor: "Server",
    comunicado: "Pengumuman sistem",
    denuncias: "Laporan",
    publicacoes: "Penerapan",
  },
  grupos: {
    conta: "Akun",
    app: "Pengaturan aplikasi",
    desenvolvedor: "Pengembang",
    administracao: "Administrasi",
  },
  secoes: {
    coresDoApp: "Warna aplikasi",
    detalhesDeLogin: "Detail masuk",
    dispositivos: "Perangkat",
    usuariosBloqueados: "Pengguna diblokir",
    aplicativosAutorizados: "Aplikasi resmi",
    sessoes: "Sesi",
    amigosEDms: "Teman dan pesan langsung",
    compartilhamentoDeAtividade: "Berbagi aktivitas",
    visibilidadeDoPerfil: "Visibilitas profil",
    exportarDados: "Ekspor data",
    exclusaoDeDados: "Hapus data",
    tema: "Tema",
    corDeDestaque: "Warna aksen",
    interface: "Antarmuka",
    listaDeCanais: "Daftar kanal",
    zoomDoApp: "Tingkat zoom aplikasi",
    escalaDaFonte: "Ukuran font obrolan",
    modoStreamer: "Privasi saat siaran",
    cursores: "Kursor",
    movimento: "Gerakan",
    textoEmVoz: "Teks ke ucapan",
    teclado: "Papan ketik",
    formatoDaHora: "Format waktu",
    idiomaDaInterface: "Bahasa antarmuka",
    dispositivosDeVoz: "Perangkat",
    testeDoMicrofone: "Uji mikrofon",
    modoDeEntrada: "Mode masukan",
    sensibilidade: "Sensitivitas masukan",
    qualidade: "Kualitas",
    camera: "Kamera",
    transmissao: "Siaran",
    exibicao: "Tampilan",
    entrada: "Masukan",
    midia: "Media",
    geral: "Umum",
    preferenciaDeMencao: "Preferensi sebutan",
    sons: "Suara",
  },
};
