export const amizades = {
  mensagensDiretas: "다이렉트 메시지",
  nova: {
    titulo: "새 대화",
    detalhe: "친구를 고르면 대화가 열립니다.",
    procurar: "친구 찾기",
    semAmigos: "아직 여기 친구가 없습니다.",
    semResultado: "그런 이름의 친구가 없습니다.",
  },
  adicionar: {
    recado: "한마디 적어 보세요 (선택)",
    recadoDica: "여기 적은 말은 친구가 되면 두 사람의 대화에도 나타납니다.",
    enviadoPara: "보냈습니다. 친구 요청이 {{nome}}에게 갔습니다.",
    outrosLugares: "친구를 만날 다른 곳",
    outrosLugaresDetalhe: "떠오르는 사람이 없나요? 열린 커뮤니티를 둘러보세요. 거의 모든 이야기가 오갑니다.",
    explorarComunidades: "커뮤니티 둘러보기",
    titulo: "친구 추가",
    detalhe: "사용자 이름으로 친구를 추가할 수 있습니다.",
    exemplo: "사용자 이름, 예: thiago",
    enviando: "보내는 중…",
    enviar: "요청 보내기",
  },
  gatinhoChorando: "우는 새끼 고양이",
  status: {
    emChamada: "통화 중",
    emVoz: "음성 중",
  },
  menu: {
    chamada: "통화 시작",
    fixar: "맨 위에 고정",
    desafixar: "고정 해제",
    silenciar: "대화 음소거",
    reativar: "알림 다시 켜기",
    copiarIdDoCanal: "채널 ID 복사",
  },
  ativosAgora: "지금 활동 중",
  procurando: "누가 있는지 보는 중…",
  tudoTranquilo: "지금은 조용합니다…",
  tudoTranquiloDetalhe: "당신이나 친구가 통화에 참여하면 여기에 표시되고, 한 번의 클릭으로 함께할 수 있습니다.",
  emVoz: "음성 중",
  voce: "당신",
  soVoce: "당신뿐",
  pessoas: "{{quantas}}명",
  voltarParaChamada: "통화로 돌아가기",
  entrarNaChamada: "통화 참여",
  abrirCanal: "{{servidor}}의 {{canal}} 열기",
  encontreConversa: "대화 찾기",
  amigos: "친구",
  conversas: "대화",
  semConversas: "아직 대화가 없습니다. 친구를 추가해 시작하세요.",
  semConversaComEsseNome: "그런 이름의 대화가 없습니다.",
  abrirMenu: "서버와 대화 열기",
  solicitacoes: "메시지 요청",
  pedidos: "요청",
  spam: "스팸",
  pedidosPendentes: "대기 중인 요청",
  marcadosComoSpam: "스팸으로 표시됨",
  aceitar: "수락",
  ignorar: "무시",
  marcarSpam: "스팸으로 표시",
  semPedidos: "대기 중인 요청이 없습니다.",
  semPedidosDetalhe: "친구는 아니지만 같은 서버에 있는 사람은 당신의 대화에 닿기 전에 여기로 옵니다.",
  semSpam: "스팸으로 표시된 것이 없습니다.",
  semSpamDetalhe: "스팸 필터가 걸러낸 것, 또는 직접 표시한 것은 이 탭에 남습니다.",
  umServidorEmComum: "공통 서버 1개",
  servidoresEmComum: "공통 서버 {{quantos}}개",
  semServidoresEmComum: "공통 서버 없음",
};
