export const comum = {
  voltar: "뒤로",
  agoraNao: "나중에",
  erro: {
    tentarDeNovo: "다시 시도",
    recarregar: "새로 고침",
    copiarDetalhes: "자세한 내용 복사",
    parteQuebrou: "화면의 이 부분이 망가졌습니다.",
    titulo: "Ravox Chat가 넘어졌습니다.",
    detalhe: "도중에 뭔가 망가져서 화면을 그리지 못했습니다. 대화는 사라지지 않았습니다 — 전부 서버에 있습니다.",
  },
  perdido: {
    titulo: "이 주소는 어디로도 이어지지 않아요.",
    detalhe: "링크가 잘못됐거나 페이지가 옮겨졌어요.",
  },
  conexao: {
    voltou: "다시 연결됨",
    reconectando: "다시 연결하는 중",
    tentativaSufixo: " · {{numero}}번째 시도",
    aSalvo: "대화는 서버에 안전하게 있습니다. 연결이 돌아오면 저절로 복구됩니다.",
  },
  avisoDoNavegador: {
    titulo: "메시지 알림을 받을까요?",
    detalhe: "Ravox Chat가 다른 창 뒤에 있어도 알려 줍니다.",
  },
  atualizacao: {
    titulo: "업데이트",
    semAuto: "이 버전의 앱은 스스로 업데이트하지 못합니다. 아래에서 최신 설치 파일을 받아 덮어써서 설치하세요.",
    versaoAtual: "현재 버전은 {{versao}}입니다.",
    instalando: "{{versao}} 버전 설치 중…",
    prontaVersao: "{{versao}} 버전을 설치할 준비가 됐습니다",
    baixandoVersao: "{{versao}} 버전 내려받는 중…",
    baixandoComProgresso: "{{versao}} 버전 내려받는 중… {{porcento}}%",
    saiuVersao: "{{versao}} 버전이 나왔습니다",
    saiuVersaoClique: "{{versao}} 버전이 나왔습니다 — 눌러서 내려받기",
    instalarVersaoEReiniciar: "{{versao}} 버전 설치하고 다시 시작",
    erroTenteDeNovo: "{{erro}} 눌러서 다시 시도하세요.",
    procurando: "확인 중…",
    emDia: "최신 상태입니다",
    vaiFechar: "곧 앱이 닫힙니다.",
    comoInstala: "앱이 닫히고 버전을 바꾼 뒤 스스로 다시 열립니다. 통화 중이면 통화에서 나가게 됩니다.",
    semServidor: "버전 서버에 닿지 못했습니다.",
    procuraSozinho: "앱이 시작할 때와 여섯 시간마다 스스로 확인합니다.",
    instalandoReticencias: "설치 중…",
    instalandoCurto: "설치 중",
    baixandoCurto: "내려받는 중",
    tentarDeNovo: "다시 시도",
    reiniciarAgora: "지금 다시 시작",
    instalarEReiniciar: "설치하고 다시 시작",
    baixar: "내려받기",
    procurar: "확인",
    baixarApp: "앱 내려받기",
    ariaBotao: "앱 업데이트",
  },
  janela: {
    ajustarAltura: "높이 조절",
    redimensionar: "창 크기 조절",
    ajustarLargura: "너비 조절",
  },
  dica: {
    rotulo: "팁:",
    pularConfirmacao: "클릭할 때 Shift를 누르고 있으면 이 확인을 건너뜁니다.",
  },
  cor: {
    pescar: "화면에서 색 추출",
    hex: "16진수 값",
  },
  imagem: {
    titulo: "이미지 선택",
    enviar: "이미지 보내기",
    escolherGif: "GIF 고르기",
    buscarGif: "GIF 검색",
  },
  fonte: {
    rotulo: "메시지 글꼴",
    padrao: "기본값",
    comNome: "메시지 글꼴 — {{fonte}}",
  },
  recorte: {
    titulo: "아이콘 자르기",
    detalhe: "드래그해서 원하는 부분을 고르고 슬라이더로 확대하세요. 아이콘은 앱 어디에서나 둥글게 보입니다.",
    voltarAoComeco: "처음으로 되돌리기",
    usar: "이 영역 사용",
  },
  mais: "더 보기",
  carregando: "불러오는 중…",
  salvar: "저장",
  salvando: "저장 중…",
  descartar: "취소",
  redefinir: "초기화",
  naoSalvo: "저장하지 않은 변경 사항이 있습니다.",
  fechar: "닫기",
  criar: "만들기",
  nome: "이름",
  emoji: "이모지",
  previa: "미리 보기",
  cancelar: "취소",
  enviar: "보내기",
  apagar: "삭제",
  excluir: "삭제",
  remover: "빼기",
  trocar: "바꾸기",
  loginNoApp: {
    titulo: "모두 준비됐어요!",
    detalhe: "로그인했어요. Ravox Chat로 돌아가세요. 앱이 기다리고 있어요.",
    abrir: "Ravox Chat 열기",
    fecharAba: "이제 이 탭을 닫아도 돼요.",
    falhouTitulo: "로그인하지 못했어요",
    falhouDetalhe: "앱으로 돌아가서 다시 로그인해 보세요.",
    legenda: "손을 흔드는 로봇",
    legendaFalhou: "울고 있는 고양이",
  },
  ads: {
    label: "광고",
    title: "여기에 광고하세요",
    detail: "저희에게 연락하고 Ravox Chat을 쓰는 사람들 앞에 나타나세요.",
    action: "광고하고 싶어요",
  },
};
