export const configuracoes = {
  efeitos: {
    titulo: "포인터 효과",
    detalhe: "화면 위에 그려지는 자취와 불꽃입니다. 처음엔 꺼져 있고, 움직임을 줄여 달라고 했다면 알아서 꺼집니다.",
    rastro: "커서 자취",
    rastroDetalhe: "포인터를 따라오며 뒤에서 옅어지는 선입니다.",
    faisca: "클릭 불꽃",
    faiscaDetalhe: "누른 자리에서 튀어 나가는 짧은 선입니다.",
    cor: "색",
    espessura: "굵기",
    comprimento: "길이",
    tamanho: "크기",
    quantidade: "개수",
  },
  email: {
    verificarTitulo: "이메일을 확인해 주세요",
    verificarDetalhe: "확인한 사람만 글을 쓸 수 있는 커뮤니티가 있습니다. 한 번만 누르면 됩니다.",
    enviar: "링크 보내기",
    enviado: "받은 편지함을 보세요. 링크는 하루 동안 유효합니다.",
    falhou: "이메일을 보내지 못했습니다.",
    confirmado: "이메일을 확인했습니다",
    confirmadoDetalhe: "끝났습니다. 이제 확인을 요구하는 커뮤니티에서도 글을 씁니다.",
    linkIncompleto: "주소가 잘렸습니다",
    linkIncompletoDetalhe: "주소에 코드가 없습니다. 이메일의 링크를 바로 열어 주세요.",
    confirmando: "확인하는 중…",
    expirou: "이 링크는 이미 썼거나 기한이 지났습니다.",
    irParaOApp: "앱으로 가기",
  },
  tema: {
    indisponivel: "테마를 열 수 없습니다",
    indisponivelDetalhe: "올린 사람이 지웠거나, 링크가 잘못됐습니다.",
    indisponivelLinha: "테마를 열 수 없습니다. 올린 사람이 지웠거나, 링크가 잘못됐습니다.",
    importar: "테마 가져오기",
    importarCurto: "가져오기",
    importarDetalhe: "지금 쓰는 테마를 대체합니다. 나중에 설정 > 모양 > 테마 스튜디오에서 고칠 수 있습니다.",
    porAutor: "만든이 {{autor}}",
    umaCorTrocada: "색 1개 교체",
    coresTrocadas: "색 {{quantas}}개 교체",
    avisoDeCss: "이 테마에는 만든 사람의 CSS가 들어 있고, CSS는 화면 구석구석에 손을 댑니다. 믿을 만한 사람의 것만 가져오세요.",
    soCores: "이 테마는 색만 바꿉니다. 외부 CSS는 없습니다.",
    verCss: "CSS 보기",
    esconderCss: "CSS 숨기기",
    aplicar: "적용",
    previaSemMotor: "미리보기에서는 엔진이 돌지 않습니다. 설치하면 볼 수 있습니다.",
    motorAnimado: "{{motor}} 애니메이션",
  },
  sair: "로그아웃",
  versoes: {
    termos: "서비스 약관",
    privacidade: "개인정보 처리방침",
    copiar: "클릭해서 복사",
    copiado: "복사됨",
  },
  appColors: {
    title: "앱 색상",
    detail: "최대 세 가지 색을 고르면 앱 전체가 그 그라데이션을 씁니다.",
    locked: "색상 편집기는 {{plan}} 기능입니다.",
    color: "색 {{number}}",
    addColor: "색 추가",
    removeColor: "색 제거",
    surprise: "랜덤으로",
    direction: "그라데이션 방향",
    intensity: "강도",
    reset: "초기화",
  },
  subscription: {
    colorsRow: "앱 색상 편집기",
    seePlans: "플랜 보기",
    upgradeSubtitle: "글쓰기, 파일 전송, 방송 한도가 커지고 전용 기능을 쓸 수 있어요.",
    perMonth: "월",
    perYear: "년",
    save: "{{percent}}% 절약",
    howToPay: "어떻게 결제할까요?",
    legal: "결제 후 7일 이내에 환불을 요청할 수 있습니다. 결제는 Stripe가 처리하며 저희는 카드 번호를 절대 볼 수 없습니다.",
    compare: "무료 vs Infinity",
    featureColumn: "기능",
    freeColumn: "무료",
    messageRow: "메시지 글자 수 한도",
    attachmentRow: "전송 파일 크기",
    screenRow: "동영상 화질",
    megabytesValue: "{{value}}MB",
    screenValue: "{{resolution}} · {{fps}}fps",
    alreadyPremium: "이미 {{date}}까지 Infinity를 이용 중입니다.",
    upsell: "Infinity로 한도 늘리기",
    screenUpsell: "Infinity로 더 높은 화질",
    free: "무료 플랜을 사용 중입니다.",
    activeUntil: "Infinity가 {{date}}까지 활성화되어 있습니다.",
    renews: "{{date}}에 자동으로 갱신됩니다.",
    endsAt: "구독이 취소되었으며 {{date}}에 종료됩니다.",
    pastDue: "최근 결제에 실패했습니다. Infinity를 유지하려면 카드를 업데이트하세요.",
    waiting: "결제를 확인하는 중…",
    subscribe: "구독하기",
    monthly: "월간",
    yearly: "연간",
    automatic: "카드",
    manage: "결제 관리",
    refund: "환불 요청",
    refundDetail: "결제 후 7일 이내에 취소할 수 있습니다: {{amount}}, {{date}}까지.",
    refundConfirm: "환불을 요청할까요?",
    refundConfirmDetail: "같은 결제 수단으로 환불되며 Infinity는 즉시 종료됩니다.",
    refunded: "환불을 요청했습니다.",
    unavailable: "구독은 아직 이용할 수 없습니다.",
    success: "결제가 완료되었습니다. 감사합니다!",
    canceled: "결제가 취소되었습니다.",
    error: "문제가 발생했습니다. 다시 시도하세요.",
    no: "없음",
    tagRow: "사용자 지정 태그",
    guildProfilesRow: "커뮤니티별 프로필",
    badgeRow: "프로필 배지",
    communitiesRow: "커뮤니티",
    savedRow: "저장한 메시지",
    animatedEmojiRow: "움직이는 이모지",
    expressionsRow: "어디서나 이모지와 스티커",
    animatedProfileRow: "움직이는 아바타와 배너",
    earlyAccessRow: "새 기능 미리 사용",
    themesRow: "사용자 지정 테마",
    pixOption: "Pix",
    pixHint: "은행 앱에서 Pix를 선택하고 QR 코드를 스캔하거나 코드를 복사해 붙여 넣으세요.",
    pixQrAlt: "Pix QR 코드",
    pixCopy: "Pix 코드 복사",
    pixCopied: "Pix 코드를 복사했습니다",
    pixWaiting: "결제를 기다리는 중",
    pixExpiresIn: "{{time}} 후 만료",
    pixExpired: "이 Pix는 만료되었습니다. 계속하려면 새로 만드세요.",
    pixNew: "새 Pix 만들기",
    pixPaid: "Pix를 받았습니다! Infinity가 활성화되었습니다.",
    forMe: "나를 위해",
    asGift: "선물하기",
    buyGift: "선물 구매",
    giftReady: "선물이 준비됐어요! 링크를 복사해 원하는 사람에게 보내세요.",
    giftClaimed: "선물을 사용했어요! Infinity가 계정에 적용됐습니다.",
    gifts: "선물",
    giftsEmpty: "아직 구매한 선물이 없습니다.",
    giftCode: "선물 코드",
    giftRedeem: "사용하기",
    giftCopyLink: "링크 복사",
    giftLinkCopied: "링크를 복사했습니다",
    giftClaimedBy: "{{name}} 님이 사용",
    giftHint: "선물 코드가 있나요? 여기서 사용하세요. 구매한 선물은 아래에 있습니다.",
    cardPaid: "결제가 승인됐습니다! Infinity가 활성화됐습니다.",
    payAmount: "{{amount}} 결제",
    giftLinkTitle: "{{plan}} 선물을 받았어요!",
    giftLinkDetail: "사용하기를 누르면 기간이 계정에 추가됩니다.",
    pageTitle: "{{plan}}으로 다양한 혜택을 즐기세요",
    pageStart: "홈",
    pageBest: "Infinity의 좋은 점",
    pageChoose: "플랜을 골라 보세요",
    fromPrice: "월 {{amount}}부터. 언제든 해지할 수 있어요.",
    filesTitle: "파일을 통째로 보내요",
    filesText: "파티 영상, 업무 프로젝트, 사진 폴더까지 한 번에 그대로 갑니다. 자르지도, 압축하지도, 클라우드 링크를 거치지도 않아요.",
    videoTitle: "1080p로 방송해요",
    videoText: "화면이 상대에게 선명하게 닿고, 초당 프레임은 두 배예요. 코드를 읽고 같이 게임해도 뭉개지지 않아요.",
    messageTitle: "마음껏 쓰세요",
    messageText: "메시지마다 글자 수가 두 배예요. 이야기가 길어서 세 조각으로 나누면 김이 새는 순간을 위해.",
    colorsTitle: "내 취향대로 만든 앱",
    colorsText: "앱 색을 하나씩 고르고 테마를 저장해서, 로그인하는 모든 기기로 가져가세요.",
    profileTitle: "장소마다 다른 프로필",
    profileText: "커뮤니티마다 다른 별명, 다른 사진, 다른 소개 — 원하면 움직이는 사진까지.",
    freeDetail: "무료이고, 앞으로도 무료예요.",
    currentPlan: "현재 플랜",
    popular: "가장 많이 선택",
    yearlyDetail: "월 {{amount}} 꼴이고, 1년에 한 번 결제돼요.",
    monthlyDetail: "매달 결제되고, 언제든 해지할 수 있어요.",
    groupStyle: "내 스타일 보여주기",
    groupLook: "앱을 내 방식대로",
    groupLimits: "빡빡한 한도 없이",
    closingTitle: "무엇을 기다리고 있나요?",
    pagePlans: "플랜",
    pageCompare: "비교",
    giftClaimTitle: "{{plan}}을 활성화할까요?",
    giftClaimDetail: "{{days}}일이 지금 계정에 추가됩니다.",
    giftFrom: "{{name}} 님이 보냄",
    giftActivate: "활성화",
    giftHasPlanTitle: "이미 Infinity가 있습니다",
    giftHasPlanDetail: "플랜이 {{date}}까지예요. 링크는 친구에게 보내세요.",
    giftUsedTitle: "이미 사용된 선물입니다",
    giftUsedDetail: "다른 사람이 먼저 사용했어요. 새 코드를 요청하세요.",
    giftNotFoundTitle: "코드를 찾을 수 없습니다",
    giftNotFoundDetail: "코드를 확인하거나 링크를 다시 받아 보세요.",
    giftDoneTitle: "{{plan}} 활성화됨!",
    giftOpenApp: "앱 열기",
    giftSignIn: "로그인하고 사용하기",
    giftReviewStep: "결제 · 확인",
    giftTotalToday: "오늘 합계",
    giftCardWhy: "카드는 본인 확인용일 뿐이에요. 지금 청구되는 건 없고 저절로 갱신되지도 않아요.",
    giftAgree: "이용약관을 읽었고 동의합니다",
    giftActivating: "활성화하는 중…",
  },
  telas: {
    subscription: "Infinity",
    conta: "내 계정",
    privacidade: "개인정보",
    conexoes: "연결",
    voz: "오디오",
    video: "비디오",
    avisos: "알림",
    aplicativos: "애플리케이션",
    aparencia: "모양",
    batePapo: "채팅",
    acessibilidade: "접근성",
    idioma: "언어",
    aplicativo: "앱 받기",
    atalhos: "단축키",
    desktop: "데스크톱 앱",
    avancado: "고급",
    servidor: "서버",
    comunicado: "시스템 공지",
    denuncias: "신고",
    publicacoes: "배포",
  },
  grupos: {
    conta: "계정",
    app: "앱 설정",
    desenvolvedor: "개발자",
    administracao: "관리",
  },
  secoes: {
    coresDoApp: "앱 색상",
    detalhesDeLogin: "로그인 정보",
    dispositivos: "기기",
    usuariosBloqueados: "차단한 사용자",
    aplicativosAutorizados: "승인된 앱",
    sessoes: "세션",
    amigosEDms: "친구 및 다이렉트 메시지",
    compartilhamentoDeAtividade: "활동 공유",
    visibilidadeDoPerfil: "프로필 공개 범위",
    exportarDados: "데이터 내보내기",
    exclusaoDeDados: "데이터 삭제",
    tema: "테마",
    corDeDestaque: "강조 색상",
    interface: "인터페이스",
    listaDeCanais: "채널 목록",
    zoomDoApp: "앱 확대 수준",
    escalaDaFonte: "채팅 글꼴 크기",
    modoStreamer: "방송 개인정보",
    cursores: "커서",
    movimento: "모션",
    textoEmVoz: "텍스트 음성 변환",
    teclado: "키보드",
    formatoDaHora: "시간 형식",
    idiomaDaInterface: "인터페이스 언어",
    dispositivosDeVoz: "기기",
    testeDoMicrofone: "마이크 테스트",
    modoDeEntrada: "입력 모드",
    sensibilidade: "입력 감도",
    qualidade: "품질",
    camera: "카메라",
    transmissao: "방송",
    exibicao: "표시",
    entrada: "입력",
    midia: "미디어",
    geral: "일반",
    preferenciaDeMencao: "멘션 설정",
    sons: "소리",
  },
};
