export const comum = {
  voltar: "返回",
  agoraNao: "暂时不用",
  erro: {
    tentarDeNovo: "重试",
    recarregar: "重新加载",
    copiarDetalhes: "复制详情",
    parteQuebrou: "屏幕的这一块坏掉了。",
    titulo: "Ravox Chat 绊了一跤。",
    detalhe: "半路上出了问题，界面画不出来。你的会话没有丢 — 一切都在服务器上。",
  },
  perdido: {
    titulo: "这个地址哪儿也去不了。",
    detalhe: "可能是链接错了，或者页面换了地方。",
  },
  conexao: {
    voltou: "重新连上了",
    reconectando: "正在重连",
    tentativaSufixo: " · 第 {{numero}} 次",
    aSalvo: "会话安全地存在服务器上。网络一恢复，这里就会自己回来。",
  },
  avisoDoNavegador: {
    titulo: "要接收消息通知吗？",
    detalhe: "当 Ravox Chat 被别的窗口挡住时，它会叫你。",
  },
  atualizacao: {
    titulo: "更新",
    semAuto: "这个版本的应用不会自动更新。请在下面下载最新的安装程序，覆盖安装。",
    versaoAtual: "你当前是 {{versao}} 版。",
    instalando: "正在安装 {{versao}} 版…",
    prontaVersao: "{{versao}} 版已可安装",
    baixandoVersao: "正在下载 {{versao}} 版…",
    baixandoComProgresso: "正在下载 {{versao}} 版… {{porcento}}%",
    saiuVersao: "{{versao}} 版发布了",
    saiuVersaoClique: "{{versao}} 版发布了 — 点击下载",
    instalarVersaoEReiniciar: "安装 {{versao}} 版并重启",
    erroTenteDeNovo: "{{erro}} 点击重试。",
    procurando: "正在查找…",
    emDia: "你已是最新版",
    vaiFechar: "应用马上就会关闭。",
    comoInstala: "应用会关闭、换版本，然后自己重新打开。如果你在通话中，会退出通话。",
    semServidor: "联系不上版本服务器。",
    procuraSozinho: "应用会在启动时以及每六小时自己查一次。",
    instalandoReticencias: "正在安装…",
    instalandoCurto: "正在安装",
    baixandoCurto: "正在下载",
    tentarDeNovo: "重试",
    reiniciarAgora: "立即重启",
    instalarEReiniciar: "安装并重启",
    baixar: "下载",
    procurar: "查找",
    baixarApp: "下载应用",
    ariaBotao: "应用更新",
  },
  janela: {
    ajustarAltura: "调整高度",
    redimensionar: "调整窗口大小",
    ajustarLargura: "调整宽度",
  },
  dica: {
    rotulo: "提示：",
    pularConfirmacao: "点击时按住 Shift 可以跳过这个确认。",
  },
  cor: {
    pescar: "从屏幕上取色",
    hex: "十六进制值",
  },
  imagem: {
    titulo: "选择一张图片",
    enviar: "发送图片",
    escolherGif: "选择 GIF",
    buscarGif: "搜索 GIF",
  },
  fonte: {
    rotulo: "消息字体",
    padrao: "默认",
    comNome: "消息字体 — {{fonte}}",
  },
  recorte: {
    titulo: "裁剪图标",
    detalhe: "拖动选取想要的部分，用滑块缩放。图标在应用里到处都是圆形。",
    voltarAoComeco: "回到最初",
    usar: "使用这个裁剪",
  },
  mais: "更多",
  carregando: "加载中…",
  salvar: "保存",
  salvando: "正在保存…",
  descartar: "放弃",
  redefinir: "重置",
  naoSalvo: "你有尚未保存的更改。",
  fechar: "关闭",
  criar: "创建",
  nome: "名称",
  emoji: "表情",
  previa: "预览",
  cancelar: "取消",
  enviar: "发送",
  apagar: "删除",
  excluir: "删除",
  remover: "移除",
  trocar: "更换",
  loginNoApp: {
    titulo: "一切就绪！",
    detalhe: "你已登录。回到 Ravox Chat 吧，应用正在等你。",
    abrir: "打开 Ravox Chat",
    fecharAba: "现在可以关闭此标签页了。",
    falhouTitulo: "登录失败",
    falhouDetalhe: "请回到应用并重新登录。",
    legenda: "挥手的机器人",
    legendaFalhou: "哭泣的小猫",
  },
  ads: {
    label: "广告",
    title: "在这里投放广告",
    detail: "联系我们，出现在使用 Ravox Chat 的人面前。",
    action: "我想投放广告",
  },
};
