export const configuracoes = {
  efeitos: {
    titulo: "指针效果",
    detalhe: "画在界面上层的拖尾和火花。默认关着，你要求减少动效时它们会自己退场。",
    rastro: "光标拖尾",
    rastroDetalhe: "跟着指针跑、在后面渐渐淡掉的一条线。",
    faisca: "点击火花",
    faiscaDetalhe: "从你点下去的地方甩出来的短线。",
    cor: "颜色",
    espessura: "粗细",
    comprimento: "长度",
    tamanho: "大小",
    quantidade: "数量",
  },
  email: {
    verificarTitulo: "确认你的邮箱",
    verificarDetalhe: "有些社区只让确认过的人发言。点一下就好。",
    enviar: "发送链接",
    enviado: "去收件箱看看。链接一天内有效。",
    falhou: "邮件没能发出去。",
    confirmado: "邮箱已确认",
    confirmadoDetalhe: "好了。凡是要求这一步的社区，你现在都能发言。",
    linkIncompleto: "链接不完整",
    linkIncompletoDetalhe: "地址里少了验证码。请直接从邮件里打开链接。",
    confirmando: "确认中…",
    expirou: "这个链接已经用过，或者过期了。",
    irParaOApp: "前往应用",
  },
  tema: {
    indisponivel: "主题不可用",
    indisponivelDetalhe: "发布的人删掉了，或者链接错了。",
    indisponivelLinha: "主题不可用。发布的人删掉了，或者链接错了。",
    importar: "导入主题",
    importarCurto: "导入",
    importarDetalhe: "这会替换你现在的主题。之后可以在 设置 > 外观 > 主题工作室 里修改。",
    porAutor: "作者 {{autor}}",
    umaCorTrocada: "换了 1 种颜色",
    coresTrocadas: "换了 {{quantas}} 种颜色",
    avisoDeCss: "这个主题带着作者写的 CSS，而 CSS 能碰到屏幕的每个角落。只从你信得过的人那里导入。",
    soCores: "这个主题只换颜色，没有外来的 CSS。",
    verCss: "查看 CSS",
    esconderCss: "隐藏 CSS",
    aplicar: "应用",
    previaSemMotor: "预览不会跑引擎，装上才看得到。",
    motorAnimado: "{{motor}} 动态",
  },
  sair: "退出登录",
  versoes: {
    termos: "服务条款",
    privacidade: "隐私政策",
    copiar: "点击复制",
    copiado: "已复制",
  },
  appColors: {
    title: "应用颜色",
    detail: "最多选三种颜色，整个应用都会用这个渐变。",
    locked: "颜色编辑器是 {{plan}} 的功能。",
    color: "颜色 {{number}}",
    addColor: "添加颜色",
    removeColor: "移除颜色",
    surprise: "随便来一个",
    direction: "渐变方向",
    intensity: "强度",
    reset: "重置",
  },
  subscription: {
    colorsRow: "应用颜色编辑器",
    seePlans: "查看方案",
    upgradeSubtitle: "写消息、发文件和直播都有更高上限和专属功能。",
    perMonth: "每月",
    perYear: "每年",
    save: "省 {{percent}}%",
    howToPay: "你想怎么付款？",
    legal: "付款后 7 天内可申请退款。付款由 Stripe 处理，我们永远看不到你的卡号。",
    compare: "免费 vs Infinity",
    featureColumn: "功能",
    freeColumn: "免费",
    messageRow: "消息字数上限",
    attachmentRow: "可发送的文件大小",
    screenRow: "视频画质",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} 帧",
    alreadyPremium: "你的 Infinity 有效期至 {{date}}。",
    upsell: "用 Infinity 提高上限",
    screenUpsell: "用 Infinity 获得更高画质",
    free: "你正在使用免费方案。",
    activeUntil: "Infinity 有效期至 {{date}}。",
    renews: "将于 {{date}} 自动续订。",
    endsAt: "订阅已取消，将于 {{date}} 结束。",
    pastDue: "上次扣款失败。请更新银行卡以免失去Infinity。",
    waiting: "正在确认付款…",
    subscribe: "订阅",
    monthly: "按月",
    yearly: "按年",
    automatic: "银行卡",
    manage: "管理付款",
    refund: "申请退款",
    refundDetail: "付款后 7 天内可以撤销：{{amount}}，截至 {{date}}。",
    refundConfirm: "要申请退款吗？",
    refundConfirmDetail: "款项将退回原支付方式，Infinity 会立即结束。",
    refunded: "已申请退款。",
    unavailable: "订阅暂不可用。",
    success: "已收到付款，谢谢！",
    canceled: "付款已取消。",
    error: "出了点问题，请重试。",
    no: "否",
    tagRow: "自定义用户标签",
    guildProfilesRow: "按社区设置的资料",
    badgeRow: "资料徽章",
    communitiesRow: "社区",
    savedRow: "已保存的消息",
    animatedEmojiRow: "动态表情",
    expressionsRow: "随处使用表情和贴纸",
    animatedProfileRow: "动态头像和横幅",
    earlyAccessRow: "抢先体验新功能",
    themesRow: "自定义主题",
    pixOption: "Pix",
    pixHint: "打开银行 App，选择 Pix，扫描二维码或复制粘贴代码。",
    pixQrAlt: "Pix 二维码",
    pixCopy: "复制 Pix 代码",
    pixCopied: "已复制 Pix 代码",
    pixWaiting: "等待付款",
    pixExpiresIn: "{{time}} 后过期",
    pixExpired: "此 Pix 已过期，请重新生成后继续。",
    pixNew: "重新生成 Pix",
    pixPaid: "已收到 Pix！你的 Infinity 已生效。",
    forMe: "给自己",
    asGift: "作为礼物",
    buyGift: "购买礼物",
    giftReady: "礼物已就绪！复制链接发给你想送的人。",
    giftClaimed: "礼物已兑换！Infinity 已加入你的账号。",
    gifts: "礼物",
    giftsEmpty: "你还没有购买过礼物。",
    giftCode: "礼物码",
    giftRedeem: "兑换",
    giftCopyLink: "复制链接",
    giftLinkCopied: "已复制链接",
    giftClaimedBy: "由 {{name}} 兑换",
    giftHint: "有礼物码？在这里兑换。你购买的礼物显示在下方。",
    cardPaid: "支付成功！你的 Infinity 已生效。",
    payAmount: "支付 {{amount}}",
    giftLinkTitle: "你收到了一份 {{plan}} 礼物！",
    giftLinkDetail: "点击兑换，天数就会加到你的账号。",
    pageTitle: "用 {{plan}} 解锁更多特权",
    pageStart: "首页",
    pageBest: "Infinity 的精华",
    pageChoose: "选择你的方案",
    fromPrice: "每月 {{amount}} 起，随时可以取消。",
    filesTitle: "整个文件直接发",
    filesText: "聚会的视频、工作的项目、装满照片的文件夹，一次就发完，不用切分、不用压缩，中间也不用夹一个网盘链接。",
    videoTitle: "用 1080p 直播",
    videoText: "你的画面清清楚楚地传到对面，每秒帧数翻倍，代码看得清，一起玩也不糊。",
    messageTitle: "想写多长写多长",
    messageText: "每条消息的字数翻倍，故事长的时候，拆成三段就没味道了。",
    colorsTitle: "打造你自己的应用",
    colorsText: "一个一个挑好应用的颜色，存成主题，带到你登录的每一台设备上。",
    profileTitle: "每个地方一个身份",
    profileText: "每个社区都能换昵称、换头像、换简介，想要的话头像还能动起来。",
    freeDetail: "免费，而且一直免费。",
    currentPlan: "你当前的方案",
    popular: "最多人选",
    yearlyDetail: "折合每月 {{amount}}，一年收一次。",
    monthlyDetail: "每月扣费，随时可以取消。",
    groupStyle: "秀出你的风格",
    groupLook: "让应用变成你的样子",
    groupLimits: "没有紧巴巴的上限",
    closingTitle: "还在等什么？",
    pagePlans: "方案",
    pageCompare: "对比",
    giftClaimTitle: "要启用 {{plan}} 吗？",
    giftClaimDetail: "{{days}} 天会立刻加到你的账号。",
    giftFrom: "来自 {{name}}",
    giftActivate: "启用",
    giftHasPlanTitle: "你已经有 Infinity 了",
    giftHasPlanDetail: "你的方案到 {{date}}。把链接留着送给朋友吧。",
    giftUsedTitle: "这份礼物已被使用",
    giftUsedDetail: "有人先兑换了这个码，请再要一个。",
    giftNotFoundTitle: "找不到该码",
    giftNotFoundDetail: "检查一下码，或者重新索取链接。",
    giftDoneTitle: "{{plan}} 已启用！",
    giftOpenApp: "打开应用",
    giftSignIn: "登录后兑换",
    giftReviewStep: "付款 · 确认",
    giftTotalToday: "今日合计",
    giftCardWhy: "卡片只是用来确认是你本人。现在不会扣款，也不会自动续费。",
    giftAgree: "我已阅读并同意使用条款",
    giftActivating: "正在激活…",
  },
  telas: {
    subscription: "Infinity",
    conta: "我的账号",
    privacidade: "隐私",
    conexoes: "连接",
    voz: "音频",
    video: "视频",
    avisos: "通知",
    aplicativos: "应用程序",
    aparencia: "外观",
    batePapo: "聊天",
    acessibilidade: "无障碍",
    idioma: "语言",
    aplicativo: "下载应用",
    atalhos: "快捷键",
    desktop: "桌面应用",
    avancado: "高级",
    servidor: "服务器",
    comunicado: "系统公告",
    denuncias: "举报",
    publicacoes: "部署",
  },
  grupos: {
    conta: "账号",
    app: "应用设置",
    desenvolvedor: "开发者",
    administracao: "管理",
  },
  secoes: {
    coresDoApp: "应用颜色",
    detalhesDeLogin: "登录信息",
    dispositivos: "设备",
    usuariosBloqueados: "已屏蔽的用户",
    aplicativosAutorizados: "已授权的应用",
    sessoes: "会话",
    amigosEDms: "好友与私信",
    compartilhamentoDeAtividade: "活动共享",
    visibilidadeDoPerfil: "个人资料可见性",
    exportarDados: "导出数据",
    exclusaoDeDados: "删除数据",
    tema: "主题",
    corDeDestaque: "强调色",
    interface: "界面",
    listaDeCanais: "频道列表",
    zoomDoApp: "应用缩放级别",
    escalaDaFonte: "聊天字体大小",
    modoStreamer: "直播隐私",
    cursores: "光标",
    movimento: "动效",
    textoEmVoz: "文字转语音",
    teclado: "键盘",
    formatoDaHora: "时间格式",
    idiomaDaInterface: "界面语言",
    dispositivosDeVoz: "设备",
    testeDoMicrofone: "麦克风测试",
    modoDeEntrada: "输入模式",
    sensibilidade: "输入灵敏度",
    qualidade: "画质",
    camera: "摄像头",
    transmissao: "推流",
    exibicao: "显示",
    entrada: "输入",
    midia: "媒体",
    geral: "常规",
    preferenciaDeMencao: "提及偏好",
    sons: "声音",
  },
};
