export const comum = {
  voltar: "Quay lại",
  agoraNao: "Để sau",
  erro: {
    tentarDeNovo: "Thử lại",
    recarregar: "Tải lại",
    copiarDetalhes: "Sao chép chi tiết",
    parteQuebrou: "Phần này của màn hình đã hỏng.",
    titulo: "Ravox Chat vấp một cái.",
    detalhe: "Có gì đó hỏng giữa đường và màn hình không vẽ được. Cuộc trò chuyện của bạn không mất — mọi thứ đều nằm trên máy chủ.",
  },
  perdido: {
    titulo: "Địa chỉ này không dẫn đến đâu cả.",
    detalhe: "Hoặc là liên kết bị sai, hoặc là trang đã chuyển chỗ.",
  },
  conexao: {
    voltou: "Đã kết nối lại",
    reconectando: "Đang kết nối lại",
    tentativaSufixo: " · lần thử {{numero}}",
    aSalvo: "Cuộc trò chuyện vẫn an toàn trên máy chủ. Mọi thứ sẽ tự trở lại ngay khi có kết nối.",
  },
  avisoDoNavegador: {
    titulo: "Bạn muốn được báo khi có tin nhắn chứ?",
    detalhe: "Khi Ravox Chat nằm sau một cửa sổ khác, nó sẽ gọi bạn.",
  },
  atualizacao: {
    titulo: "Cập nhật",
    semAuto: "Phiên bản ứng dụng này không tự cập nhật được. Hãy tải bộ cài mới nhất bên dưới và cài đè lên.",
    versaoAtual: "Bạn đang dùng phiên bản {{versao}}.",
    instalando: "Đang cài phiên bản {{versao}}…",
    prontaVersao: "Phiên bản {{versao}} đã sẵn sàng để cài",
    baixandoVersao: "Đang tải phiên bản {{versao}}…",
    baixandoComProgresso: "Đang tải phiên bản {{versao}}… {{porcento}}%",
    saiuVersao: "Phiên bản {{versao}} đã ra mắt",
    saiuVersaoClique: "Phiên bản {{versao}} đã ra mắt — bấm để tải",
    instalarVersaoEReiniciar: "Cài phiên bản {{versao}} và khởi động lại",
    erroTenteDeNovo: "{{erro}} Bấm để thử lại.",
    procurando: "Đang tìm…",
    emDia: "Bạn đang dùng bản mới nhất",
    vaiFechar: "Ứng dụng sẽ đóng trong giây lát.",
    comoInstala: "Ứng dụng đóng lại, đổi phiên bản rồi tự mở lên. Nếu bạn đang trong cuộc gọi thì sẽ rời khỏi cuộc gọi.",
    semServidor: "Không liên lạc được với máy chủ phiên bản.",
    procuraSozinho: "Ứng dụng tự kiểm tra khi mở và cứ sáu giờ một lần.",
    instalandoReticencias: "Đang cài…",
    instalandoCurto: "Đang cài",
    baixandoCurto: "Đang tải",
    tentarDeNovo: "Thử lại",
    reiniciarAgora: "Khởi động lại ngay",
    instalarEReiniciar: "Cài và khởi động lại",
    baixar: "Tải về",
    procurar: "Kiểm tra",
    baixarApp: "Tải ứng dụng",
    ariaBotao: "Cập nhật ứng dụng",
  },
  janela: {
    ajustarAltura: "Chỉnh chiều cao",
    redimensionar: "Đổi kích thước cửa sổ",
    ajustarLargura: "Chỉnh chiều rộng",
  },
  dica: {
    rotulo: "Mẹo:",
    pularConfirmacao: "giữ Shift khi bấm để bỏ qua xác nhận này.",
  },
  cor: {
    pescar: "Lấy màu từ màn hình",
    hex: "Giá trị thập lục phân",
  },
  imagem: {
    titulo: "Chọn một ảnh",
    enviar: "Gửi ảnh",
    escolherGif: "Chọn GIF",
    buscarGif: "Tìm GIF",
  },
  fonte: {
    rotulo: "Phông chữ tin nhắn",
    padrao: "Mặc định",
    comNome: "Phông chữ tin nhắn — {{fonte}}",
  },
  recorte: {
    titulo: "Cắt biểu tượng",
    detalhe: "Kéo để chọn phần bạn muốn và dùng thanh trượt để phóng to. Biểu tượng luôn tròn ở mọi nơi trong ứng dụng.",
    voltarAoComeco: "Về lại ban đầu",
    usar: "Dùng phần cắt này",
  },
  mais: "Thêm",
  carregando: "Đang tải…",
  salvar: "Lưu",
  salvando: "Đang lưu…",
  descartar: "Bỏ",
  redefinir: "Đặt lại",
  naoSalvo: "Bạn có thay đổi chưa lưu.",
  fechar: "Đóng",
  criar: "Tạo",
  nome: "Tên",
  emoji: "Biểu tượng cảm xúc",
  previa: "Xem trước",
  cancelar: "Hủy",
  enviar: "Gửi",
  apagar: "Xóa",
  excluir: "Xóa",
  remover: "Gỡ",
  trocar: "Đổi",
  loginNoApp: {
    titulo: "Xong rồi!",
    detalhe: "Bạn đã đăng nhập. Quay lại Ravox Chat nhé, ứng dụng đang chờ bạn.",
    abrir: "Mở Ravox Chat",
    fecharAba: "Bạn có thể đóng tab này.",
    falhouTitulo: "Đăng nhập không thành công",
    falhouDetalhe: "Quay lại ứng dụng và thử đăng nhập lại.",
    legenda: "Một chú robot vẫy tay",
    legendaFalhou: "Một chú mèo con đang khóc",
  },
  ads: {
    label: "Quảng cáo",
    title: "Quảng cáo tại đây",
    detail: "Liên hệ với chúng tôi và xuất hiện trước những người dùng Ravox Chat.",
    action: "Tôi muốn quảng cáo",
  },
};
