export const configuracoes = {
  efeitos: {
    titulo: "Hiệu ứng con trỏ",
    detalhe: "Vệt và tia được vẽ đè lên ứng dụng. Ban đầu tắt, và tự tắt nếu bạn đã xin bớt chuyển động.",
    rastro: "Vệt con trỏ",
    rastroDetalhe: "Một đường đi theo con trỏ rồi nhạt dần phía sau.",
    faisca: "Tia khi bấm",
    faiscaDetalhe: "Những nét ngắn bắn ra từ chỗ bạn bấm.",
    cor: "Màu",
    espessura: "Độ dày",
    comprimento: "Độ dài",
    tamanho: "Cỡ",
    quantidade: "Số lượng",
  },
  email: {
    verificarTitulo: "Xác nhận email của bạn",
    verificarDetalhe: "Vài cộng đồng chỉ cho người đã xác nhận lên tiếng. Chỉ một cú nhấp.",
    enviar: "Gửi liên kết",
    enviado: "Xem hộp thư đến. Liên kết dùng được trong một ngày.",
    falhou: "Không gửi được email.",
    confirmado: "Đã xác nhận email",
    confirmadoDetalhe: "Xong rồi. Giờ bạn nhắn được ở mọi cộng đồng có yêu cầu này.",
    linkIncompleto: "Liên kết bị thiếu",
    linkIncompletoDetalhe: "Địa chỉ thiếu mã. Hãy mở liên kết thẳng từ email.",
    confirmando: "Đang xác nhận…",
    expirou: "Liên kết này đã dùng rồi hoặc đã hết hạn.",
    irParaOApp: "Vào ứng dụng",
  },
  tema: {
    indisponivel: "Không dùng được chủ đề này",
    indisponivelDetalhe: "Người đăng đã xoá, hoặc liên kết bị sai.",
    indisponivelLinha: "Không dùng được chủ đề này. Người đăng đã xoá, hoặc liên kết bị sai.",
    importar: "Nhập chủ đề",
    importarCurto: "Nhập",
    importarDetalhe: "Việc này thay thế chủ đề bạn đang dùng. Bạn có thể sửa sau ở Cài đặt > Giao diện > Xưởng chủ đề.",
    porAutor: "bởi {{autor}}",
    umaCorTrocada: "đổi 1 màu",
    coresTrocadas: "đổi {{quantas}} màu",
    avisoDeCss: "Chủ đề này mang theo CSS của người viết, mà CSS chạm tới mọi ngóc ngách của màn hình. Chỉ nhập từ người bạn tin tưởng.",
    soCores: "Chủ đề này chỉ đổi màu. Không có CSS từ bên ngoài.",
    verCss: "Xem CSS",
    esconderCss: "Ẩn CSS",
    aplicar: "Áp dụng",
    previaSemMotor: "Bản xem trước không chạy engine. Cài vào mới thấy được.",
    motorAnimado: "{{motor}} có hoạt ảnh",
  },
  sair: "Đăng xuất",
  versoes: {
    termos: "Điều khoản dịch vụ",
    privacidade: "Chính sách quyền riêng tư",
    copiar: "Nhấn để sao chép",
    copiado: "Đã sao chép",
  },
  appColors: {
    title: "Màu của ứng dụng",
    detail: "Chọn tối đa ba màu và cả ứng dụng sẽ dùng dải màu đó.",
    locked: "Trình chỉnh màu thuộc {{plan}}.",
    color: "Màu {{number}}",
    addColor: "Thêm màu",
    removeColor: "Bỏ màu",
    surprise: "Gợi ý ngẫu nhiên",
    direction: "Hướng dải màu",
    intensity: "Độ đậm",
    reset: "Đặt lại",
  },
  subscription: {
    colorsRow: "Trình chỉnh màu ứng dụng",
    seePlans: "Xem các gói",
    upgradeSubtitle: "Giới hạn cao hơn và tính năng độc quyền để viết, gửi tệp và phát trực tiếp.",
    perMonth: "mỗi tháng",
    perYear: "mỗi năm",
    save: "Tiết kiệm {{percent}}%",
    howToPay: "Bạn muốn thanh toán thế nào?",
    legal: "Bạn có thể yêu cầu hoàn tiền trong vòng 7 ngày sau khi thanh toán. Thanh toán do Stripe xử lý; chúng tôi không bao giờ thấy số thẻ của bạn.",
    compare: "Miễn phí và Infinity",
    featureColumn: "Tính năng",
    freeColumn: "Miễn phí",
    messageRow: "Giới hạn ký tự tin nhắn",
    attachmentRow: "Kích thước tệp gửi",
    screenRow: "Chất lượng video",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Bạn đã có Infinity đến {{date}}.",
    upsell: "Tăng giới hạn với Infinity",
    screenUpsell: "Chất lượng cao hơn với Infinity",
    free: "Bạn đang dùng gói miễn phí.",
    activeUntil: "Infinity có hiệu lực đến {{date}}.",
    renews: "Tự động gia hạn vào {{date}}.",
    endsAt: "Gói đăng ký đã bị hủy và kết thúc vào {{date}}.",
    pastDue: "Lần thanh toán gần nhất thất bại. Hãy cập nhật thẻ để không mất Infinity.",
    waiting: "Đang xác nhận thanh toán…",
    subscribe: "Đăng ký",
    monthly: "Hằng tháng",
    yearly: "Hằng năm",
    automatic: "Thẻ",
    manage: "Quản lý thanh toán",
    refund: "Yêu cầu hoàn tiền",
    refundDetail: "Bạn có thể hủy trong vòng 7 ngày sau khi thanh toán: {{amount}}, đến {{date}}.",
    refundConfirm: "Yêu cầu hoàn tiền?",
    refundConfirmDetail: "Tiền sẽ được hoàn về phương thức thanh toán cũ và Infinity kết thúc ngay.",
    refunded: "Đã yêu cầu hoàn tiền.",
    unavailable: "Gói đăng ký chưa khả dụng.",
    success: "Đã nhận thanh toán. Cảm ơn bạn!",
    canceled: "Đã hủy thanh toán.",
    error: "Đã xảy ra lỗi. Hãy thử lại.",
    no: "Không",
    tagRow: "Thẻ người dùng tùy chỉnh",
    guildProfilesRow: "Hồ sơ theo cộng đồng",
    badgeRow: "Huy hiệu hồ sơ",
    communitiesRow: "Cộng đồng",
    savedRow: "Tin nhắn đã lưu",
    animatedEmojiRow: "Emoji động",
    expressionsRow: "Emoji và nhãn dán ở mọi nơi",
    animatedProfileRow: "Ảnh đại diện và biểu ngữ động",
    earlyAccessRow: "Truy cập sớm tính năng mới",
    themesRow: "Chủ đề tùy chỉnh",
    pixOption: "Pix",
    pixHint: "Mở ứng dụng ngân hàng, chọn Pix và quét mã QR hoặc sao chép mã.",
    pixQrAlt: "Mã QR Pix",
    pixCopy: "Sao chép mã Pix",
    pixCopied: "Đã sao chép mã Pix",
    pixWaiting: "Đang chờ thanh toán",
    pixExpiresIn: "hết hạn sau {{time}}",
    pixExpired: "Mã Pix này đã hết hạn. Tạo mã mới để tiếp tục.",
    pixNew: "Tạo mã Pix mới",
    pixPaid: "Đã nhận Pix! Infinity của bạn đã được kích hoạt.",
    forMe: "Cho tôi",
    asGift: "Làm quà",
    buyGift: "Mua quà",
    giftReady: "Quà đã sẵn sàng! Sao chép liên kết và gửi cho ai bạn muốn.",
    giftClaimed: "Đã dùng quà! Infinity đã có trong tài khoản của bạn.",
    gifts: "Quà tặng",
    giftsEmpty: "Bạn chưa mua món quà nào.",
    giftCode: "Mã quà tặng",
    giftRedeem: "Dùng mã",
    giftCopyLink: "Sao chép liên kết",
    giftLinkCopied: "Đã sao chép liên kết",
    giftClaimedBy: "được {{name}} sử dụng",
    giftHint: "Có mã quà tặng? Dùng tại đây. Quà bạn đã mua ở bên dưới.",
    cardPaid: "Thanh toán đã được duyệt! Infinity của bạn đang hoạt động.",
    payAmount: "Thanh toán {{amount}}",
    giftLinkTitle: "Bạn nhận được quà {{plan}}!",
    giftLinkDetail: "Chạm dùng mã và số ngày sẽ vào tài khoản của bạn.",
    pageTitle: "Mở ra thế giới đặc quyền với {{plan}}",
    pageStart: "Trang chính",
    pageBest: "Những gì hay nhất của Infinity",
    pageChoose: "Chọn gói của bạn",
    fromPrice: "Từ {{amount}} mỗi tháng. Hủy bất cứ lúc nào.",
    filesTitle: "Gửi trọn vẹn cả tệp",
    filesText: "Video bữa tiệc, dự án ở công ty, thư mục ảnh: tất cả đi một lần, không cắt nhỏ, không nén và không cần link đám mây ở giữa.",
    videoTitle: "Phát ở 1080p",
    videoText: "Màn hình của bạn đến với người xem thật sắc nét, với số khung hình mỗi giây gấp đôi. Đọc code và chơi cùng nhau mà không bị nhòe.",
    messageTitle: "Viết thoải mái",
    messageText: "Gấp đôi số ký tự trong mỗi tin nhắn, cho những lúc câu chuyện dài mà chia làm ba phần thì mất hết cái hay.",
    colorsTitle: "Ứng dụng mang dấu ấn của bạn",
    colorsText: "Chọn từng màu của ứng dụng, lưu chủ đề lại và mang theo tới mọi thiết bị bạn đăng nhập.",
    profileTitle: "Mỗi nơi một hồ sơ",
    profileText: "Biệt danh khác, ảnh khác, mô tả khác ở từng cộng đồng — và ảnh động, nếu bạn muốn.",
    freeDetail: "Miễn phí và vẫn sẽ miễn phí.",
    currentPlan: "Gói hiện tại của bạn",
    popular: "Được chọn nhiều nhất",
    yearlyDetail: "Tính ra {{amount}} mỗi tháng, thu một lần mỗi năm.",
    monthlyDetail: "Thu mỗi tháng, hủy bất cứ lúc nào.",
    groupStyle: "Khoe phong cách của bạn",
    groupLook: "Chỉnh ứng dụng theo ý bạn",
    groupLimits: "Không còn giới hạn chật chội",
    closingTitle: "Bạn còn chờ gì nữa?",
    pagePlans: "Gói",
    pageCompare: "So sánh",
    giftClaimTitle: "Kích hoạt {{plan}}?",
    giftClaimDetail: "{{days}} ngày sẽ vào tài khoản của bạn ngay bây giờ.",
    giftFrom: "từ {{name}}",
    giftActivate: "Kích hoạt",
    giftHasPlanTitle: "Bạn đã có Infinity",
    giftHasPlanDetail: "Gói của bạn dùng đến {{date}}. Giữ liên kết và gửi cho bạn bè.",
    giftUsedTitle: "Quà này đã được dùng",
    giftUsedDetail: "Ai đó đã dùng mã này trước. Hãy xin mã khác.",
    giftNotFoundTitle: "Không tìm thấy mã",
    giftNotFoundDetail: "Kiểm tra mã hoặc xin lại liên kết.",
    giftDoneTitle: "Đã kích hoạt {{plan}}!",
    giftOpenApp: "Mở ứng dụng",
    giftSignIn: "Đăng nhập để dùng mã",
    giftReviewStep: "Thanh toán · Xem lại",
    giftTotalToday: "Tổng hôm nay",
    giftCardWhy: "Thẻ chỉ để xác nhận đúng là bạn. Bây giờ không trừ gì cả và không có gì tự gia hạn.",
    giftAgree: "Tôi đã đọc và chấp nhận điều khoản sử dụng",
    giftActivating: "Đang kích hoạt…",
  },
  telas: {
    subscription: "Infinity",
    conta: "Tài khoản của tôi",
    privacidade: "Quyền riêng tư",
    conexoes: "Kết nối",
    voz: "Âm thanh",
    video: "Video",
    avisos: "Thông báo",
    aplicativos: "Ứng dụng",
    aparencia: "Giao diện",
    batePapo: "Trò chuyện",
    acessibilidade: "Trợ năng",
    idioma: "Ngôn ngữ",
    aplicativo: "Tải ứng dụng",
    atalhos: "Phím tắt",
    desktop: "Ứng dụng máy tính",
    avancado: "Nâng cao",
    servidor: "Máy chủ",
    comunicado: "Thông báo hệ thống",
    denuncias: "Báo cáo",
    publicacoes: "Triển khai",
  },
  grupos: {
    conta: "Tài khoản",
    app: "Cài đặt ứng dụng",
    desenvolvedor: "Nhà phát triển",
    administracao: "Quản trị",
  },
  secoes: {
    coresDoApp: "Màu của ứng dụng",
    detalhesDeLogin: "Thông tin đăng nhập",
    dispositivos: "Thiết bị",
    usuariosBloqueados: "Người dùng bị chặn",
    aplicativosAutorizados: "Ứng dụng đã ủy quyền",
    sessoes: "Phiên đăng nhập",
    amigosEDms: "Bạn bè và tin nhắn riêng",
    compartilhamentoDeAtividade: "Chia sẻ hoạt động",
    visibilidadeDoPerfil: "Hiển thị hồ sơ",
    exportarDados: "Xuất dữ liệu",
    exclusaoDeDados: "Xóa dữ liệu",
    tema: "Chủ đề",
    corDeDestaque: "Màu nhấn",
    interface: "Giao diện",
    listaDeCanais: "Danh sách kênh",
    zoomDoApp: "Mức thu phóng của ứng dụng",
    escalaDaFonte: "Cỡ chữ trong trò chuyện",
    modoStreamer: "Quyền riêng tư khi phát trực tiếp",
    cursores: "Con trỏ",
    movimento: "Chuyển động",
    textoEmVoz: "Chuyển văn bản thành giọng nói",
    teclado: "Bàn phím",
    formatoDaHora: "Định dạng giờ",
    idiomaDaInterface: "Ngôn ngữ giao diện",
    dispositivosDeVoz: "Thiết bị",
    testeDoMicrofone: "Kiểm tra micrô",
    modoDeEntrada: "Chế độ đầu vào",
    sensibilidade: "Độ nhạy đầu vào",
    qualidade: "Chất lượng",
    camera: "Máy ảnh",
    transmissao: "Phát trực tiếp",
    exibicao: "Hiển thị",
    entrada: "Nhập liệu",
    midia: "Đa phương tiện",
    geral: "Chung",
    preferenciaDeMencao: "Tùy chọn nhắc đến",
    sons: "Âm thanh",
  },
};
