export const amizades = {
  mensagensDiretas: "ข้อความส่วนตัว",
  nova: {
    titulo: "คุยใหม่",
    detalhe: "เลือกเพื่อนสักคน แล้วห้องคุยจะเปิดขึ้น",
    procurar: "หาเพื่อน",
    semAmigos: "คุณยังไม่มีเพื่อนที่นี่",
    semResultado: "ไม่มีเพื่อนชื่อนี้",
  },
  adicionar: {
    recado: "เขียนสักหน่อย (ไม่บังคับ)",
    recadoDica: "สิ่งที่เขียนตรงนี้จะโผล่ในห้องคุยของคุณสองคนด้วย ถ้าได้เป็นเพื่อนกัน",
    enviadoPara: "เรียบร้อย คำขอเป็นเพื่อนไปถึง {{nome}} แล้ว",
    outrosLugares: "ที่อื่นสำหรับหาเพื่อน",
    outrosLugaresDetalhe: "นึกไม่ออกว่าจะชวนใคร ลองดูชุมชนเปิด ที่นั่นคุยกันแทบทุกเรื่อง",
    explorarComunidades: "สำรวจชุมชน",
    titulo: "เพิ่มเพื่อน",
    detalhe: "คุณเพิ่มเพื่อนได้จากชื่อผู้ใช้ของเขา",
    exemplo: "ชื่อผู้ใช้ เช่น thiago",
    enviando: "กำลังส่ง…",
    enviar: "ส่งคำขอ",
  },
  gatinhoChorando: "ลูกแมวกำลังร้องไห้",
  status: {
    emChamada: "อยู่ในสาย",
    emVoz: "อยู่ในห้องเสียง",
  },
  menu: {
    chamada: "เริ่มการโทร",
    fixar: "ปักหมุดไว้ด้านบน",
    desafixar: "เลิกปักหมุด",
    silenciar: "ปิดเสียงการสนทนา",
    reativar: "เปิดเสียงการสนทนา",
    copiarIdDoCanal: "คัดลอก ID ช่อง",
  },
  ativosAgora: "ใช้งานอยู่ตอนนี้",
  procurando: "กำลังดูว่าใครอยู่บ้าง…",
  tudoTranquilo: "ตอนนี้เงียบอยู่…",
  tudoTranquiloDetalhe: "เมื่อคุณหรือเพื่อนเข้าร่วมสาย มันจะขึ้นตรงนี้ — และคุณเข้าร่วมได้ด้วยคลิกเดียว",
  emVoz: "อยู่ในห้องเสียง",
  voce: "คุณ",
  soVoce: "มีแค่คุณ",
  pessoas: "{{quantas}} คน",
  voltarParaChamada: "กลับไปที่สาย",
  entrarNaChamada: "เข้าร่วมสาย",
  abrirCanal: "เปิด {{canal}} ใน {{servidor}}",
  encontreConversa: "ค้นหาการสนทนา",
  amigos: "เพื่อน",
  conversas: "การสนทนา",
  semConversas: "ยังไม่มีการสนทนา เพิ่มเพื่อนเพื่อเริ่มต้น",
  semConversaComEsseNome: "ไม่มีการสนทนาชื่อนั้น",
  abrirMenu: "เปิดเซิร์ฟเวอร์และการสนทนา",
  solicitacoes: "คำขอส่งข้อความ",
  pedidos: "คำขอ",
  spam: "สแปม",
  pedidosPendentes: "คำขอที่รออยู่",
  marcadosComoSpam: "ทำเครื่องหมายว่าสแปม",
  aceitar: "ยอมรับ",
  ignorar: "เพิกเฉย",
  marcarSpam: "ทำเครื่องหมายว่าสแปม",
  semPedidos: "ไม่มีคำขอรออยู่",
  semPedidosDetalhe: "คนที่ไม่ใช่เพื่อนคุณแต่อยู่เซิร์ฟเวอร์เดียวกันจะมาอยู่ตรงนี้ก่อนถึงการสนทนาของคุณ",
  semSpam: "ไม่มีอะไรถูกทำเครื่องหมายว่าสแปม",
  semSpamDetalhe: "สิ่งที่ตัวกรองสแปมคัดออก หรือสิ่งที่คุณทำเครื่องหมายเอง จะเก็บอยู่ในแท็บนี้",
  umServidorEmComum: "มีเซิร์ฟเวอร์ร่วมกัน 1 แห่ง",
  servidoresEmComum: "มีเซิร์ฟเวอร์ร่วมกัน {{quantos}} แห่ง",
  semServidoresEmComum: "ไม่มีเซิร์ฟเวอร์ร่วมกัน",
};
