export const comum = {
  voltar: "ย้อนกลับ",
  agoraNao: "ไว้ก่อน",
  erro: {
    tentarDeNovo: "ลองอีกครั้ง",
    recarregar: "โหลดใหม่",
    copiarDetalhes: "คัดลอกรายละเอียด",
    parteQuebrou: "ส่วนนี้ของหน้าจอพัง",
    titulo: "Ravox Chat สะดุด",
    detalhe: "มีบางอย่างพังระหว่างทางและหน้าจอวาดตัวเองไม่ได้ บทสนทนาของคุณไม่หายไป — ทุกอย่างอยู่บนเซิร์ฟเวอร์",
  },
  perdido: {
    titulo: "ที่อยู่นี้ไม่พาไปไหนเลย",
    detalhe: "ลิงก์อาจผิด หรือหน้านี้ย้ายที่ไปแล้ว",
  },
  conexao: {
    voltou: "เชื่อมต่อได้อีกครั้ง",
    reconectando: "กำลังเชื่อมต่อใหม่",
    tentativaSufixo: " · ครั้งที่ {{numero}}",
    aSalvo: "บทสนทนาปลอดภัยอยู่บนเซิร์ฟเวอร์ ทุกอย่างจะกลับมาเองทันทีที่การเชื่อมต่อกลับมา",
  },
  avisoDoNavegador: {
    titulo: "อยากให้แจ้งเตือนข้อความไหม",
    detalhe: "เวลา Ravox Chat อยู่หลังหน้าต่างอื่น มันจะเรียกคุณ",
  },
  atualizacao: {
    titulo: "การอัปเดต",
    semAuto: "แอปรุ่นนี้อัปเดตตัวเองไม่ได้ ดาวน์โหลดตัวติดตั้งรุ่นใหม่ล่าสุดด้านล่างแล้วติดตั้งทับ",
    versaoAtual: "คุณอยู่ที่รุ่น {{versao}}",
    instalando: "กำลังติดตั้งรุ่น {{versao}}…",
    prontaVersao: "รุ่น {{versao}} พร้อมติดตั้งแล้ว",
    baixandoVersao: "กำลังดาวน์โหลดรุ่น {{versao}}…",
    baixandoComProgresso: "กำลังดาวน์โหลดรุ่น {{versao}}… {{porcento}}%",
    saiuVersao: "รุ่น {{versao}} ออกแล้ว",
    saiuVersaoClique: "รุ่น {{versao}} ออกแล้ว — คลิกเพื่อดาวน์โหลด",
    instalarVersaoEReiniciar: "ติดตั้งรุ่น {{versao}} แล้วเริ่มใหม่",
    erroTenteDeNovo: "{{erro}} คลิกเพื่อลองอีกครั้ง",
    procurando: "กำลังค้นหา…",
    emDia: "คุณใช้รุ่นล่าสุดอยู่แล้ว",
    vaiFechar: "แอปจะปิดในอีกครู่",
    comoInstala: "แอปจะปิด เปลี่ยนรุ่น แล้วเปิดขึ้นมาเองใหม่ ถ้าคุณอยู่ในสายก็จะออกจากสาย",
    semServidor: "ติดต่อเซิร์ฟเวอร์รุ่นไม่ได้",
    procuraSozinho: "แอปจะตรวจเองตอนเปิดและทุกหกชั่วโมง",
    instalandoReticencias: "กำลังติดตั้ง…",
    instalandoCurto: "กำลังติดตั้ง",
    baixandoCurto: "กำลังดาวน์โหลด",
    tentarDeNovo: "ลองอีกครั้ง",
    reiniciarAgora: "เริ่มใหม่ตอนนี้",
    instalarEReiniciar: "ติดตั้งแล้วเริ่มใหม่",
    baixar: "ดาวน์โหลด",
    procurar: "ตรวจหา",
    baixarApp: "ดาวน์โหลดแอป",
    ariaBotao: "การอัปเดตแอป",
  },
  janela: {
    ajustarAltura: "ปรับความสูง",
    redimensionar: "ปรับขนาดหน้าต่าง",
    ajustarLargura: "ปรับความกว้าง",
  },
  dica: {
    rotulo: "เคล็ดลับ:",
    pularConfirmacao: "กด Shift ค้างไว้ขณะคลิกเพื่อข้ามการยืนยันนี้",
  },
  cor: {
    pescar: "ดูดสีจากหน้าจอ",
    hex: "ค่าเลขฐานสิบหก",
  },
  imagem: {
    titulo: "เลือกรูปภาพ",
    enviar: "ส่งรูปภาพ",
    escolherGif: "เลือก GIF",
    buscarGif: "ค้นหา GIF",
  },
  fonte: {
    rotulo: "ฟอนต์ของข้อความ",
    padrao: "ค่าเริ่มต้น",
    comNome: "ฟอนต์ของข้อความ — {{fonte}}",
  },
  recorte: {
    titulo: "ครอบตัดไอคอน",
    detalhe: "ลากเพื่อเลือกส่วนที่ต้องการ และใช้แถบเลื่อนเพื่อซูม ไอคอนจะกลมทุกที่ในแอป",
    voltarAoComeco: "กลับไปเริ่มใหม่",
    usar: "ใช้การครอบตัดนี้",
  },
  mais: "เพิ่มเติม",
  carregando: "กำลังโหลด…",
  salvar: "บันทึก",
  salvando: "กำลังบันทึก…",
  descartar: "ทิ้ง",
  redefinir: "รีเซ็ต",
  naoSalvo: "คุณมีการเปลี่ยนแปลงที่ยังไม่ได้บันทึก",
  fechar: "ปิด",
  criar: "สร้าง",
  nome: "ชื่อ",
  emoji: "อีโมจิ",
  previa: "ตัวอย่าง",
  cancelar: "ยกเลิก",
  enviar: "ส่ง",
  apagar: "ลบ",
  excluir: "ลบ",
  remover: "เอาออก",
  trocar: "เปลี่ยน",
  loginNoApp: {
    titulo: "เรียบร้อยแล้ว!",
    detalhe: "คุณเข้าสู่ระบบแล้ว กลับไปที่ Ravox Chat ได้เลย แอปกำลังรออยู่",
    abrir: "เปิด Ravox Chat",
    fecharAba: "ปิดแท็บนี้ได้เลย",
    falhouTitulo: "เข้าสู่ระบบไม่สำเร็จ",
    falhouDetalhe: "กลับไปที่แอปแล้วลองเข้าสู่ระบบอีกครั้ง",
    legenda: "หุ่นยนต์โบกมือ",
    legendaFalhou: "ลูกแมวร้องไห้",
  },
  ads: {
    label: "โฆษณา",
    title: "ลงโฆษณาที่นี่",
    detail: "คุยกับเราแล้วปรากฏต่อผู้ที่ใช้ Ravox Chat",
    action: "ฉันต้องการลงโฆษณา",
  },
};
