export const configuracoes = {
  efeitos: {
    titulo: "เอฟเฟกต์ของตัวชี้",
    detalhe: "เส้นตามและประกายที่วาดทับบนแอป เริ่มต้นปิดไว้ และดับเองถ้าคุณขอให้เคลื่อนไหวน้อยลง",
    rastro: "เส้นตามเคอร์เซอร์",
    rastroDetalhe: "เส้นที่วิ่งตามตัวชี้แล้วจางหายด้านหลัง",
    faisca: "ประกายตอนคลิก",
    faiscaDetalhe: "เส้นสั้น ๆ ที่พุ่งออกจากจุดที่คุณคลิก",
    cor: "สี",
    espessura: "ความหนา",
    comprimento: "ความยาว",
    tamanho: "ขนาด",
    quantidade: "จำนวน",
  },
  email: {
    verificarTitulo: "ยืนยันอีเมลของคุณ",
    verificarDetalhe: "บางชุมชนให้เฉพาะคนที่ยืนยันแล้วพูดได้ กดครั้งเดียวก็เสร็จ",
    enviar: "ส่งลิงก์",
    enviado: "ดูในกล่องจดหมาย ลิงก์ใช้ได้หนึ่งวัน",
    falhou: "ส่งอีเมลไม่ได้",
    confirmado: "ยืนยันอีเมลแล้ว",
    confirmadoDetalhe: "เรียบร้อย ตอนนี้พูดได้ในทุกชุมชนที่ขอสิ่งนี้",
    linkIncompleto: "ลิงก์ไม่ครบ",
    linkIncompletoDetalhe: "ที่อยู่ขาดรหัส เปิดลิงก์จากในอีเมลโดยตรง",
    confirmando: "กำลังยืนยัน…",
    expirou: "ลิงก์นี้ถูกใช้ไปแล้วหรือหมดอายุ",
    irParaOApp: "ไปที่แอป",
  },
  tema: {
    indisponivel: "ใช้ธีมนี้ไม่ได้",
    indisponivelDetalhe: "คนที่เผยแพร่ลบไปแล้ว หรือลิงก์ผิด",
    indisponivelLinha: "ใช้ธีมนี้ไม่ได้ คนที่เผยแพร่ลบไปแล้ว หรือลิงก์ผิด",
    importar: "นำเข้าธีม",
    importarCurto: "นำเข้า",
    importarDetalhe: "การทำแบบนี้จะแทนที่ธีมที่คุณใช้อยู่ แก้ไขทีหลังได้ที่ การตั้งค่า > รูปลักษณ์ > สตูดิโอธีม",
    porAutor: "โดย {{autor}}",
    umaCorTrocada: "เปลี่ยนสี 1 สี",
    coresTrocadas: "เปลี่ยนสี {{quantas}} สี",
    avisoDeCss: "ธีมนี้พก CSS ของคนเขียนมาด้วย และ CSS แตะได้ทุกซอกทุกมุมของหน้าจอ นำเข้าเฉพาะจากคนที่คุณไว้ใจเท่านั้น",
    soCores: "ธีมนี้เปลี่ยนแค่สี ไม่มี CSS จากข้างนอก",
    verCss: "ดู CSS",
    esconderCss: "ซ่อน CSS",
    aplicar: "ใช้",
    previaSemMotor: "ตัวอย่างไม่ได้รันเอนจิน ติดตั้งก่อนจึงจะเห็น",
    motorAnimado: "{{motor}} แบบเคลื่อนไหว",
  },
  sair: "ออกจากระบบ",
  versoes: {
    termos: "ข้อกำหนดในการให้บริการ",
    privacidade: "นโยบายความเป็นส่วนตัว",
    copiar: "คลิกเพื่อคัดลอก",
    copiado: "คัดลอกแล้ว",
  },
  appColors: {
    title: "สีของแอป",
    detail: "เลือกได้สูงสุดสามสี แล้วทั้งแอปจะใช้ไล่สีนั้น",
    locked: "ตัวแก้ไขสีเป็นของ {{plan}}",
    color: "สีที่ {{number}}",
    addColor: "เพิ่มสี",
    removeColor: "ลบสี",
    surprise: "สุ่มให้หน่อย",
    direction: "ทิศทางไล่สี",
    intensity: "ความเข้ม",
    reset: "รีเซ็ต",
  },
  subscription: {
    colorsRow: "ตัวแก้ไขสีของแอป",
    seePlans: "ดูแพ็กเกจ",
    upgradeSubtitle: "ขีดจำกัดที่สูงขึ้นและฟีเจอร์พิเศษสำหรับการเขียน ส่งไฟล์ และสตรีม",
    perMonth: "ต่อเดือน",
    perYear: "ต่อปี",
    save: "ประหยัด {{percent}}%",
    howToPay: "คุณต้องการชำระเงินแบบไหน",
    legal: "ขอคืนเงินได้ภายใน 7 วันหลังชำระเงิน การชำระเงินดำเนินการโดย Stripe เราไม่เคยเห็นหมายเลขบัตรของคุณ",
    compare: "ฟรี กับ Infinity",
    featureColumn: "ฟีเจอร์",
    freeColumn: "ฟรี",
    messageRow: "จำนวนตัวอักษรต่อข้อความ",
    attachmentRow: "ขนาดไฟล์ที่ส่ง",
    screenRow: "คุณภาพวิดีโอ",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "คุณมี Infinity อยู่แล้วถึง {{date}}",
    upsell: "เพิ่มขีดจำกัดด้วย Infinity",
    screenUpsell: "คุณภาพสูงขึ้นด้วย Infinity",
    free: "คุณใช้แพ็กเกจฟรีอยู่",
    activeUntil: "Infinity ใช้งานได้ถึง {{date}}",
    renews: "ต่ออายุอัตโนมัติวันที่ {{date}}",
    endsAt: "ยกเลิกการสมัครแล้ว จะสิ้นสุดวันที่ {{date}}",
    pastDue: "การเรียกเก็บเงินครั้งล่าสุดไม่สำเร็จ อัปเดตบัตรเพื่อไม่ให้เสียInfinity",
    waiting: "กำลังยืนยันการชำระเงิน…",
    subscribe: "สมัครสมาชิก",
    monthly: "รายเดือน",
    yearly: "รายปี",
    automatic: "บัตร",
    manage: "จัดการการชำระเงิน",
    refund: "ขอคืนเงิน",
    refundDetail: "คุณยกเลิกได้ภายใน 7 วันหลังชำระเงิน: {{amount}} ถึง {{date}}",
    refundConfirm: "ขอคืนเงินไหม",
    refundConfirmDetail: "เงินจะคืนไปยังช่องทางชำระเดิม และ Infinity จะสิ้นสุดทันที",
    refunded: "ส่งคำขอคืนเงินแล้ว",
    unavailable: "ยังไม่เปิดให้สมัครสมาชิก",
    success: "ได้รับการชำระเงินแล้ว ขอบคุณ!",
    canceled: "ยกเลิกการชำระเงินแล้ว",
    error: "มีบางอย่างผิดพลาด ลองอีกครั้ง",
    no: "ไม่",
    tagRow: "แท็กผู้ใช้แบบกำหนดเอง",
    guildProfilesRow: "โปรไฟล์แยกตามชุมชน",
    badgeRow: "ป้ายโปรไฟล์",
    communitiesRow: "ชุมชน",
    savedRow: "ข้อความที่บันทึก",
    animatedEmojiRow: "อีโมจิเคลื่อนไหว",
    expressionsRow: "อีโมจิและสติกเกอร์จากทุกที่",
    animatedProfileRow: "อวาตาร์และแบนเนอร์เคลื่อนไหว",
    earlyAccessRow: "เข้าถึงฟีเจอร์ใหม่ก่อนใคร",
    themesRow: "ธีมแบบกำหนดเอง",
    pixOption: "Pix",
    pixHint: "เปิดแอปธนาคาร เลือก Pix แล้วสแกน QR code หรือคัดลอกรหัสไปวาง",
    pixQrAlt: "QR code ของ Pix",
    pixCopy: "คัดลอกรหัส Pix",
    pixCopied: "คัดลอกรหัส Pix แล้ว",
    pixWaiting: "กำลังรอการชำระเงิน",
    pixExpiresIn: "หมดอายุใน {{time}}",
    pixExpired: "Pix นี้หมดอายุแล้ว สร้างใหม่เพื่อดำเนินการต่อ",
    pixNew: "สร้าง Pix ใหม่",
    pixPaid: "ได้รับ Pix แล้ว! Infinity ของคุณใช้งานได้แล้ว",
    forMe: "สำหรับฉัน",
    asGift: "เป็นของขวัญ",
    buyGift: "ซื้อของขวัญ",
    giftReady: "ของขวัญพร้อมแล้ว! คัดลอกลิงก์แล้วส่งให้ใครก็ได้",
    giftClaimed: "ใช้ของขวัญแล้ว! Infinity อยู่ในบัญชีของคุณแล้ว",
    gifts: "ของขวัญ",
    giftsEmpty: "คุณยังไม่ได้ซื้อของขวัญ",
    giftCode: "รหัสของขวัญ",
    giftRedeem: "ใช้รหัส",
    giftCopyLink: "คัดลอกลิงก์",
    giftLinkCopied: "คัดลอกลิงก์แล้ว",
    giftClaimedBy: "ใช้โดย {{name}}",
    giftHint: "มีรหัสของขวัญไหม ใช้ที่นี่ ของขวัญที่คุณซื้ออยู่ด้านล่าง",
    cardPaid: "อนุมัติการชำระเงินแล้ว! Infinity ของคุณใช้งานได้แล้ว",
    payAmount: "จ่าย {{amount}}",
    giftLinkTitle: "คุณได้รับของขวัญ {{plan}}!",
    giftLinkDetail: "แตะใช้รหัส แล้ววันจะเข้าบัญชีของคุณ",
    pageTitle: "ปลดล็อกโลกแห่งสิทธิพิเศษด้วย {{plan}}",
    pageStart: "หน้าแรก",
    pageBest: "สิ่งที่ดีที่สุดของ Infinity",
    pageChoose: "เลือกแพ็กเกจของคุณ",
    fromPrice: "เริ่มต้น {{amount}} ต่อเดือน ยกเลิกเมื่อไหร่ก็ได้",
    filesTitle: "ส่งไฟล์ทั้งก้อน",
    filesText: "วิดีโองานปาร์ตี้ โปรเจกต์ที่ทำงาน โฟลเดอร์รูปภาพ ส่งไปทีเดียวจบ ไม่ต้องตัด ไม่ต้องบีบอัด และไม่ต้องมีลิงก์คลาวด์มาคั่นกลาง",
    videoTitle: "สตรีมที่ 1080p",
    videoText: "หน้าจอของคุณไปถึงอีกฝั่งอย่างคมชัด ด้วยจำนวนเฟรมต่อวินาทีเป็นสองเท่า อ่านโค้ดและเล่นเกมด้วยกันได้โดยไม่กลายเป็นภาพเบลอ",
    messageTitle: "เขียนได้เต็มที่",
    messageText: "ตัวอักษรในแต่ละข้อความเป็นสองเท่า สำหรับตอนที่เรื่องยาวและการตัดเป็นสามท่อนจะทำให้เสียอรรถรส",
    colorsTitle: "แอปในแบบของคุณ",
    colorsText: "เลือกสีของแอปทีละสี บันทึกธีมเอาไว้ แล้วพกไปใช้ได้ทุกเครื่องที่คุณเข้าใช้งาน",
    profileTitle: "โปรไฟล์แยกสำหรับแต่ละที่",
    profileText: "คนละชื่อเล่น คนละรูป คนละคำอธิบายในแต่ละคอมมูนิตี้ และรูปเคลื่อนไหวได้ถ้าคุณต้องการ",
    freeDetail: "ฟรีและฟรีต่อไป",
    currentPlan: "แพ็กเกจปัจจุบันของคุณ",
    popular: "คนเลือกมากที่สุด",
    yearlyDetail: "เฉลี่ยเดือนละ {{amount}} เก็บเงินปีละครั้ง",
    monthlyDetail: "เก็บเงินทุกเดือน ยกเลิกเมื่อไหร่ก็ได้",
    groupStyle: "โชว์สไตล์ของคุณ",
    groupLook: "ปรับแอปให้เป็นของคุณ",
    groupLimits: "ไม่มีขีดจำกัดคับแคบ",
    closingTitle: "รออะไรอยู่",
    pagePlans: "แพ็กเกจ",
    pageCompare: "เปรียบเทียบ",
    giftClaimTitle: "เปิดใช้ {{plan}} ไหม",
    giftClaimDetail: "จะเพิ่ม {{days}} วันเข้าบัญชีของคุณทันที",
    giftFrom: "จาก {{name}}",
    giftActivate: "เปิดใช้งาน",
    giftHasPlanTitle: "คุณมี Infinity อยู่แล้ว",
    giftHasPlanDetail: "แพ็กเกจของคุณใช้ได้ถึง {{date}} เก็บลิงก์ไว้ส่งให้เพื่อน",
    giftUsedTitle: "ของขวัญนี้ถูกใช้ไปแล้ว",
    giftUsedDetail: "มีคนใช้รหัสนี้ก่อนแล้ว ขออันใหม่",
    giftNotFoundTitle: "ไม่พบรหัส",
    giftNotFoundDetail: "ตรวจสอบรหัสหรือขอลิงก์อีกครั้ง",
    giftDoneTitle: "เปิดใช้ {{plan}} แล้ว!",
    giftOpenApp: "เปิดแอป",
    giftSignIn: "เข้าสู่ระบบเพื่อใช้รหัส",
    giftReviewStep: "ชำระเงิน · ตรวจสอบ",
    giftTotalToday: "รวมวันนี้",
    giftCardWhy: "บัตรใช้เพื่อยืนยันว่าเป็นคุณเท่านั้น ตอนนี้ไม่มีการเรียกเก็บเงิน และไม่มีการต่ออายุเอง",
    giftAgree: "ฉันได้อ่านและยอมรับเงื่อนไขการใช้งาน",
    giftActivating: "กำลังเปิดใช้งาน…",
  },
  telas: {
    subscription: "Infinity",
    conta: "บัญชีของฉัน",
    privacidade: "ความเป็นส่วนตัว",
    conexoes: "การเชื่อมต่อ",
    voz: "เสียง",
    video: "วิดีโอ",
    avisos: "การแจ้งเตือน",
    aplicativos: "แอปพลิเคชัน",
    aparencia: "รูปลักษณ์",
    batePapo: "แชท",
    acessibilidade: "การเข้าถึง",
    idioma: "ภาษา",
    aplicativo: "ดาวน์โหลดแอป",
    atalhos: "ทางลัด",
    desktop: "แอปเดสก์ท็อป",
    avancado: "ขั้นสูง",
    servidor: "เซิร์ฟเวอร์",
    comunicado: "ประกาศจากระบบ",
    denuncias: "รายงาน",
    publicacoes: "การปรับใช้",
  },
  grupos: {
    conta: "บัญชี",
    app: "การตั้งค่าแอป",
    desenvolvedor: "นักพัฒนา",
    administracao: "การดูแลระบบ",
  },
  secoes: {
    coresDoApp: "สีของแอป",
    detalhesDeLogin: "ข้อมูลเข้าสู่ระบบ",
    dispositivos: "อุปกรณ์",
    usuariosBloqueados: "ผู้ใช้ที่ถูกบล็อก",
    aplicativosAutorizados: "แอปที่ได้รับอนุญาต",
    sessoes: "เซสชัน",
    amigosEDms: "เพื่อนและข้อความส่วนตัว",
    compartilhamentoDeAtividade: "การแชร์กิจกรรม",
    visibilidadeDoPerfil: "การมองเห็นโปรไฟล์",
    exportarDados: "ส่งออกข้อมูล",
    exclusaoDeDados: "ลบข้อมูล",
    tema: "ธีม",
    corDeDestaque: "สีเน้น",
    interface: "อินเทอร์เฟซ",
    listaDeCanais: "รายการช่อง",
    zoomDoApp: "ระดับการซูมของแอป",
    escalaDaFonte: "ขนาดตัวอักษรในแชท",
    modoStreamer: "ความเป็นส่วนตัวขณะสตรีม",
    cursores: "เคอร์เซอร์",
    movimento: "การเคลื่อนไหว",
    textoEmVoz: "ข้อความเป็นเสียง",
    teclado: "แป้นพิมพ์",
    formatoDaHora: "รูปแบบเวลา",
    idiomaDaInterface: "ภาษาของอินเทอร์เฟซ",
    dispositivosDeVoz: "อุปกรณ์",
    testeDoMicrofone: "ทดสอบไมโครโฟน",
    modoDeEntrada: "โหมดอินพุต",
    sensibilidade: "ความไวของอินพุต",
    qualidade: "คุณภาพ",
    camera: "กล้อง",
    transmissao: "การถ่ายทอด",
    exibicao: "การแสดงผล",
    entrada: "การป้อนข้อมูล",
    midia: "สื่อ",
    geral: "ทั่วไป",
    preferenciaDeMencao: "การตั้งค่าการกล่าวถึง",
    sons: "เสียง",
  },
};
