export const amizades = {
  mensagensDiretas: "私訊",
  nova: {
    titulo: "新的對話",
    detalhe: "挑一個好友，對話就打開了。",
    procurar: "找一個好友",
    semAmigos: "你在這裡還沒有好友。",
    semResultado: "沒有叫這個名字的好友。",
  },
  adicionar: {
    recado: "寫句話（可不寫）",
    recadoDica: "你在這裡寫的，成為好友後也會出現在你們的對話裡。",
    enviadoPara: "好了，好友邀請已經發給 {{nome}}。",
    outrosLugares: "還能在哪兒認識人",
    outrosLugaresDetalhe: "想不起找誰？去看看開放的社群，那裡幾乎什麼都聊。",
    explorarComunidades: "逛逛社群",
    titulo: "加好友",
    detalhe: "你可以用對方的使用者名稱加好友。",
    exemplo: "使用者名稱，例如：thiago",
    enviando: "正在傳送…",
    enviar: "傳送邀請",
  },
  gatinhoChorando: "一隻在哭的小貓",
  status: {
    emChamada: "通話中",
    emVoz: "語音中",
  },
  menu: {
    chamada: "發起通話",
    fixar: "置頂對話",
    desafixar: "取消置頂",
    silenciar: "靜音對話",
    reativar: "取消靜音對話",
    copiarIdDoCanal: "複製頻道 ID",
  },
  ativosAgora: "目前活躍",
  procurando: "看看誰在…",
  tudoTranquilo: "暫時很安靜…",
  tudoTranquiloDetalhe: "當你或朋友加入通話時，會顯示在這裡，一鍵就能加入。",
  emVoz: "語音中",
  voce: "你",
  soVoce: "只有你",
  pessoas: "{{quantas}} 人",
  voltarParaChamada: "回到通話",
  entrarNaChamada: "加入通話",
  abrirCanal: "在 {{servidor}} 開啟 {{canal}}",
  encontreConversa: "尋找對話",
  amigos: "好友",
  conversas: "對話",
  semConversas: "還沒有對話。加個好友開始吧。",
  semConversaComEsseNome: "沒有這個名字的對話。",
  abrirMenu: "開啟伺服器和對話",
  solicitacoes: "訊息請求",
  pedidos: "請求",
  spam: "垃圾",
  pedidosPendentes: "待處理請求",
  marcadosComoSpam: "已標記為垃圾",
  aceitar: "接受",
  ignorar: "忽略",
  marcarSpam: "標記為垃圾",
  semPedidos: "沒有待處理的請求。",
  semPedidosDetalhe: "不是你好友但與你在同一伺服器的人，會先到這裡，再進入你的對話。",
  semSpam: "沒有標記為垃圾的內容。",
  semSpamDetalhe: "垃圾過濾器挑出來的，或你自己標記的，都留在這個分頁裡。",
  umServidorEmComum: "1 個共同伺服器",
  servidoresEmComum: "{{quantos}} 個共同伺服器",
  semServidoresEmComum: "沒有共同伺服器",
};
