export const comum = {
  voltar: "返回",
  agoraNao: "暫時不用",
  erro: {
    tentarDeNovo: "重試",
    recarregar: "重新載入",
    copiarDetalhes: "複製詳細資訊",
    parteQuebrou: "畫面的這一塊壞掉了。",
    titulo: "Ravox Chat 絆了一跤。",
    detalhe: "半路上出了問題，畫面畫不出來。你的會話沒有遺失 — 一切都在伺服器上。",
  },
  perdido: {
    titulo: "這個網址哪裡也去不了。",
    detalhe: "可能是連結錯了，或者頁面換了位置。",
  },
  conexao: {
    voltou: "重新連上了",
    reconectando: "正在重新連線",
    tentativaSufixo: " · 第 {{numero}} 次",
    aSalvo: "會話安全地存在伺服器上。網路一恢復，這裡就會自己回來。",
  },
  avisoDoNavegador: {
    titulo: "要接收訊息通知嗎？",
    detalhe: "當 Ravox Chat 被別的視窗擋住時，它會叫你。",
  },
  atualizacao: {
    titulo: "更新",
    semAuto: "這個版本的應用程式不會自動更新。請在下面下載最新的安裝程式，覆蓋安裝。",
    versaoAtual: "你目前是 {{versao}} 版。",
    instalando: "正在安裝 {{versao}} 版…",
    prontaVersao: "{{versao}} 版已可安裝",
    baixandoVersao: "正在下載 {{versao}} 版…",
    baixandoComProgresso: "正在下載 {{versao}} 版… {{porcento}}%",
    saiuVersao: "{{versao}} 版發布了",
    saiuVersaoClique: "{{versao}} 版發布了 — 點擊下載",
    instalarVersaoEReiniciar: "安裝 {{versao}} 版並重新啟動",
    erroTenteDeNovo: "{{erro}} 點擊重試。",
    procurando: "正在尋找…",
    emDia: "你已是最新版",
    vaiFechar: "應用程式馬上就會關閉。",
    comoInstala: "應用程式會關閉、換版本，然後自己重新開啟。如果你在通話中，會退出通話。",
    semServidor: "聯絡不上版本伺服器。",
    procuraSozinho: "應用程式會在啟動時以及每六小時自己查一次。",
    instalandoReticencias: "正在安裝…",
    instalandoCurto: "正在安裝",
    baixandoCurto: "正在下載",
    tentarDeNovo: "重試",
    reiniciarAgora: "立即重新啟動",
    instalarEReiniciar: "安裝並重新啟動",
    baixar: "下載",
    procurar: "尋找",
    baixarApp: "下載應用程式",
    ariaBotao: "應用程式更新",
  },
  janela: {
    ajustarAltura: "調整高度",
    redimensionar: "調整視窗大小",
    ajustarLargura: "調整寬度",
  },
  dica: {
    rotulo: "提示：",
    pularConfirmacao: "點擊時按住 Shift 可以略過這個確認。",
  },
  cor: {
    pescar: "從螢幕上取色",
    hex: "十六進位值",
  },
  imagem: {
    titulo: "選擇一張圖片",
    enviar: "傳送圖片",
    escolherGif: "選擇 GIF",
    buscarGif: "搜尋 GIF",
  },
  fonte: {
    rotulo: "訊息字型",
    padrao: "預設",
    comNome: "訊息字型 — {{fonte}}",
  },
  recorte: {
    titulo: "裁切圖示",
    detalhe: "拖曳選取想要的部分，用滑桿縮放。圖示在應用程式裡到處都是圓形。",
    voltarAoComeco: "回到最初",
    usar: "使用這個裁切",
  },
  mais: "更多",
  carregando: "載入中…",
  salvar: "儲存",
  salvando: "正在儲存…",
  descartar: "捨棄",
  redefinir: "重設",
  naoSalvo: "你有尚未儲存的變更。",
  fechar: "關閉",
  criar: "建立",
  nome: "名稱",
  emoji: "表情符號",
  previa: "預覽",
  cancelar: "取消",
  enviar: "傳送",
  apagar: "刪除",
  excluir: "刪除",
  remover: "移除",
  trocar: "更換",
  loginNoApp: {
    titulo: "一切就緒！",
    detalhe: "你已登入。回到 Ravox Chat 吧，應用程式正在等你。",
    abrir: "開啟 Ravox Chat",
    fecharAba: "現在可以關閉此分頁了。",
    falhouTitulo: "登入失敗",
    falhouDetalhe: "請回到應用程式並重新登入。",
    legenda: "揮手的機器人",
    legendaFalhou: "哭泣的小貓",
  },
  ads: {
    label: "廣告",
    title: "在這裡刊登廣告",
    detail: "與我們聯絡，出現在使用 Ravox Chat 的人面前。",
    action: "我想刊登廣告",
  },
};
