export const configuracoes = {
  efeitos: {
    titulo: "指標效果",
    detalhe: "畫在介面上層的拖尾和火花。預設關著，你要求減少動效時它們會自己退場。",
    rastro: "游標拖尾",
    rastroDetalhe: "跟著指標跑、在後面漸漸淡掉的一條線。",
    faisca: "點擊火花",
    faiscaDetalhe: "從你點下去的地方甩出來的短線。",
    cor: "顏色",
    espessura: "粗細",
    comprimento: "長度",
    tamanho: "大小",
    quantidade: "數量",
  },
  email: {
    verificarTitulo: "確認你的信箱",
    verificarDetalhe: "有些社群只讓確認過的人發言。點一下就好。",
    enviar: "發送連結",
    enviado: "去收件匣看看。連結一天內有效。",
    falhou: "郵件沒能寄出去。",
    confirmado: "信箱已確認",
    confirmadoDetalhe: "好了。凡是要求這一步的社群，你現在都能發言。",
    linkIncompleto: "連結不完整",
    linkIncompletoDetalhe: "網址裡少了驗證碼。請直接從郵件裡開啟連結。",
    confirmando: "確認中…",
    expirou: "這個連結已經用過，或者過期了。",
    irParaOApp: "前往應用",
  },
  tema: {
    indisponivel: "主題無法使用",
    indisponivelDetalhe: "發布的人刪掉了，或者連結錯了。",
    indisponivelLinha: "主題無法使用。發布的人刪掉了，或者連結錯了。",
    importar: "匯入主題",
    importarCurto: "匯入",
    importarDetalhe: "這會取代你現在的主題。之後可以在 設定 > 外觀 > 主題工作室 裡修改。",
    porAutor: "作者 {{autor}}",
    umaCorTrocada: "換了 1 種顏色",
    coresTrocadas: "換了 {{quantas}} 種顏色",
    avisoDeCss: "這個主題帶著作者寫的 CSS，而 CSS 能碰到畫面的每個角落。只從你信得過的人那裡匯入。",
    soCores: "這個主題只換顏色，沒有外來的 CSS。",
    verCss: "檢視 CSS",
    esconderCss: "隱藏 CSS",
    aplicar: "套用",
    previaSemMotor: "預覽不會跑引擎，裝上才看得到。",
    motorAnimado: "{{motor}} 動態",
  },
  sair: "登出",
  versoes: {
    termos: "服務條款",
    privacidade: "隱私政策",
    copiar: "點一下複製",
    copiado: "已複製",
  },
  appColors: {
    title: "應用程式顏色",
    detail: "最多選三種顏色，整個應用程式都會用這個漸層。",
    locked: "顏色編輯器是 {{plan}} 的功能。",
    color: "顏色 {{number}}",
    addColor: "新增顏色",
    removeColor: "移除顏色",
    surprise: "隨機來一個",
    direction: "漸層方向",
    intensity: "強度",
    reset: "重設",
  },
  subscription: {
    colorsRow: "應用程式顏色編輯器",
    seePlans: "查看方案",
    upgradeSubtitle: "寫訊息、傳檔案和直播都有更高上限與專屬功能。",
    perMonth: "每月",
    perYear: "每年",
    save: "省 {{percent}}%",
    howToPay: "你想怎麼付款？",
    legal: "付款後 7 天內可申請退款。付款由 Stripe 處理，我們永遠看不到你的卡號。",
    compare: "免費 vs Infinity",
    featureColumn: "功能",
    freeColumn: "免費",
    messageRow: "訊息字數上限",
    attachmentRow: "可傳送的檔案大小",
    screenRow: "影片畫質",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "你的 Infinity 有效至 {{date}}。",
    upsell: "用 Infinity 提高上限",
    screenUpsell: "用 Infinity 獲得更高畫質",
    free: "你正在使用免費方案。",
    activeUntil: "Infinity 有效至 {{date}}。",
    renews: "將於 {{date}} 自動續訂。",
    endsAt: "訂閱已取消，將於 {{date}} 結束。",
    pastDue: "上次扣款失敗。請更新卡片以免失去Infinity。",
    waiting: "正在確認付款…",
    subscribe: "訂閱",
    monthly: "按月",
    yearly: "按年",
    automatic: "卡片",
    manage: "管理付款",
    refund: "申請退款",
    refundDetail: "付款後 7 天內可以撤銷：{{amount}}，截至 {{date}}。",
    refundConfirm: "要申請退款嗎？",
    refundConfirmDetail: "款項會退回原付款方式，Infinity 會立即結束。",
    refunded: "已申請退款。",
    unavailable: "訂閱尚未開放。",
    success: "已收到付款，謝謝！",
    canceled: "付款已取消。",
    error: "發生錯誤，請再試一次。",
    no: "否",
    tagRow: "自訂使用者標籤",
    guildProfilesRow: "依社群設定的個人檔案",
    badgeRow: "個人檔案徽章",
    communitiesRow: "社群",
    savedRow: "已儲存的訊息",
    animatedEmojiRow: "動態表情",
    expressionsRow: "隨處使用表情和貼圖",
    animatedProfileRow: "動態頭像和橫幅",
    earlyAccessRow: "搶先體驗新功能",
    themesRow: "自訂主題",
    pixOption: "Pix",
    pixHint: "打開銀行 App，選擇 Pix，掃描 QR code 或複製貼上代碼。",
    pixQrAlt: "Pix QR code",
    pixCopy: "複製 Pix 代碼",
    pixCopied: "已複製 Pix 代碼",
    pixWaiting: "等待付款",
    pixExpiresIn: "{{time}} 後到期",
    pixExpired: "這筆 Pix 已到期，請重新產生後繼續。",
    pixNew: "重新產生 Pix",
    pixPaid: "已收到 Pix！你的 Infinity 已啟用。",
    forMe: "給自己",
    asGift: "當作禮物",
    buyGift: "購買禮物",
    giftReady: "禮物已就緒！複製連結傳給你想送的人。",
    giftClaimed: "禮物已兌換！Infinity 已加入你的帳號。",
    gifts: "禮物",
    giftsEmpty: "你還沒有購買過禮物。",
    giftCode: "禮物碼",
    giftRedeem: "兌換",
    giftCopyLink: "複製連結",
    giftLinkCopied: "已複製連結",
    giftClaimedBy: "由 {{name}} 兌換",
    giftHint: "有禮物碼嗎？在這裡兌換。你購買的禮物顯示在下方。",
    cardPaid: "付款成功！你的 Infinity 已啟用。",
    payAmount: "支付 {{amount}}",
    giftLinkTitle: "你收到了一份 {{plan}} 禮物！",
    giftLinkDetail: "點擊兌換，天數就會加到你的帳號。",
    pageTitle: "用 {{plan}} 解鎖更多特權",
    pageStart: "首頁",
    pageBest: "Infinity 的精華",
    pageChoose: "選擇你的方案",
    fromPrice: "每月 {{amount}} 起，隨時可以取消。",
    filesTitle: "整個檔案直接傳",
    filesText: "派對的影片、工作的專案、裝滿照片的資料夾，一次就傳完，不用切割、不用壓縮，中間也不用夾一個雲端連結。",
    videoTitle: "用 1080p 直播",
    videoText: "你的畫面清清楚楚傳到對面，每秒影格數加倍，程式碼看得清楚，一起玩也不會糊掉。",
    messageTitle: "想寫多長就寫多長",
    messageText: "每則訊息的字數加倍，故事長的時候，拆成三段就沒味道了。",
    colorsTitle: "打造你自己的應用程式",
    colorsText: "一個一個挑好應用程式的顏色，存成主題，帶到你登入的每一台裝置上。",
    profileTitle: "每個地方一個身分",
    profileText: "每個社群都能換暱稱、換頭像、換簡介，想要的話頭像還能動起來。",
    freeDetail: "免費，而且一直免費。",
    currentPlan: "你目前的方案",
    popular: "最多人選",
    yearlyDetail: "折合每月 {{amount}}，一年收一次。",
    monthlyDetail: "每月扣款，隨時可以取消。",
    groupStyle: "秀出你的風格",
    groupLook: "讓應用程式變成你的樣子",
    groupLimits: "沒有綁手綁腳的上限",
    closingTitle: "還在等什麼？",
    pagePlans: "方案",
    pageCompare: "比較",
    giftClaimTitle: "要啟用 {{plan}} 嗎？",
    giftClaimDetail: "{{days}} 天會立刻加到你的帳號。",
    giftFrom: "來自 {{name}}",
    giftActivate: "啟用",
    giftHasPlanTitle: "你已經有 Infinity 了",
    giftHasPlanDetail: "你的方案到 {{date}}。把連結留著送給朋友吧。",
    giftUsedTitle: "這份禮物已被使用",
    giftUsedDetail: "有人先兌換了這組碼，請再要一組。",
    giftNotFoundTitle: "找不到這組碼",
    giftNotFoundDetail: "檢查一下碼，或重新索取連結。",
    giftDoneTitle: "{{plan}} 已啟用！",
    giftOpenApp: "開啟應用程式",
    giftSignIn: "登入後兌換",
    giftReviewStep: "付款 · 確認",
    giftTotalToday: "今日合計",
    giftCardWhy: "卡片只是用來確認是你本人。現在不會扣款，也不會自動續約。",
    giftAgree: "我已閱讀並同意使用條款",
    giftActivating: "正在啟用…",
  },
  telas: {
    subscription: "Infinity",
    conta: "我的帳號",
    privacidade: "隱私",
    conexoes: "連結",
    voz: "音訊",
    video: "視訊",
    avisos: "通知",
    aplicativos: "應用程式",
    aparencia: "外觀",
    batePapo: "聊天",
    acessibilidade: "無障礙",
    idioma: "語言",
    aplicativo: "下載應用程式",
    atalhos: "快捷鍵",
    desktop: "桌面應用程式",
    avancado: "進階",
    servidor: "伺服器",
    comunicado: "系統公告",
    denuncias: "檢舉",
    publicacoes: "部署",
  },
  grupos: {
    conta: "帳號",
    app: "應用程式設定",
    desenvolvedor: "開發者",
    administracao: "管理",
  },
  secoes: {
    coresDoApp: "應用程式顏色",
    detalhesDeLogin: "登入資訊",
    dispositivos: "裝置",
    usuariosBloqueados: "已封鎖的使用者",
    aplicativosAutorizados: "已授權的應用程式",
    sessoes: "工作階段",
    amigosEDms: "好友與私訊",
    compartilhamentoDeAtividade: "活動分享",
    visibilidadeDoPerfil: "個人檔案可見度",
    exportarDados: "匯出資料",
    exclusaoDeDados: "刪除資料",
    tema: "主題",
    corDeDestaque: "強調色",
    interface: "介面",
    listaDeCanais: "頻道清單",
    zoomDoApp: "應用程式縮放層級",
    escalaDaFonte: "聊天字型大小",
    modoStreamer: "直播隱私",
    cursores: "游標",
    movimento: "動態效果",
    textoEmVoz: "文字轉語音",
    teclado: "鍵盤",
    formatoDaHora: "時間格式",
    idiomaDaInterface: "介面語言",
    dispositivosDeVoz: "裝置",
    testeDoMicrofone: "麥克風測試",
    modoDeEntrada: "輸入模式",
    sensibilidade: "輸入靈敏度",
    qualidade: "品質",
    camera: "攝影機",
    transmissao: "直播",
    exibicao: "顯示",
    entrada: "輸入",
    midia: "媒體",
    geral: "一般",
    preferenciaDeMencao: "提及偏好",
    sons: "音效",
  },
};
