export const amizades = {
  mensagensDiretas: "Mensagens diretas",
  nova: {
    titulo: "Nova conversa",
    detalhe: "Escolha um amigo para abrir a conversa.",
    procurar: "Procurar um amigo",
    semAmigos: "Você ainda não tem amigos por aqui.",
    semResultado: "Nenhum amigo com esse nome.",
  },
  adicionar: {
    recado: "Escreva um recado (opcional)",
    recadoDica: "O que você escrever aqui também aparece na conversa de vocês, se virarem amigos.",
    enviadoPara: "Pronto! O pedido de amizade foi para {{nome}}.",
    outrosLugares: "Outros lugares para fazer amizade",
    outrosLugaresDetalhe: "Não lembra de ninguém? Dê uma olhada nas comunidades abertas, tem gente falando de quase tudo.",
    explorarComunidades: "Explorar comunidades",
    titulo: "Adicionar amigo",
    detalhe: "Você pode adicionar amigos pelo nome de usuário deles.",
    exemplo: "Nome de usuário, ex: thiago",
    enviando: "Enviando…",
    enviar: "Enviar pedido",
  },
  gatinhoChorando: "Um gatinho chorando",
  status: {
    emChamada: "Em uma chamada",
    emVoz: "Em voz",
  },
  menu: {
    chamada: "Iniciar chamada",
    fixar: "Fixar no topo",
    desafixar: "Desafixar",
    silenciar: "Silenciar conversa",
    reativar: "Reativar os avisos",
    copiarIdDoCanal: "Copiar ID do canal",
  },
  ativosAgora: "Ativo agora",
  procurando: "Vendo quem está por aí…",
  tudoTranquilo: "Está tudo tranquilo por enquanto…",
  tudoTranquiloDetalhe:
    "Quando você ou um amigo entrar numa chamada, ela aparece aqui — e dá pra entrar junto com um clique.",
  emVoz: "Em voz",
  voce: "Você",
  soVoce: "Só você",
  pessoas: "{{quantas}} pessoas",
  voltarParaChamada: "Voltar para a chamada",
  entrarNaChamada: "Entrar na chamada",
  abrirCanal: "Abrir {{canal}} em {{servidor}}",

  encontreConversa: "Encontre uma conversa",
  amigos: "Amigos",
  conversas: "Conversas",
  semConversas: "Nenhuma conversa ainda. Adicione um amigo para começar.",
  semConversaComEsseNome: "Nenhuma conversa com esse nome.",
  abrirMenu: "Abrir servidores e conversas",

  solicitacoes: "Solicitações de mensagens",
  pedidos: "Pedidos",
  spam: "Spam",
  pedidosPendentes: "Pedidos pendentes",
  marcadosComoSpam: "Marcados como spam",
  aceitar: "Aceitar",
  ignorar: "Ignorar",
  marcarSpam: "Marcar spam",
  semPedidos: "Nenhum pedido esperando.",
  semPedidosDetalhe:
    "Quem não é seu amigo mas divide um servidor com você cai aqui antes de chegar às suas conversas.",
  semSpam: "Nada marcado como spam.",
  semSpamDetalhe:
    "O que o filtro de spam separar, ou o que você marcar, fica guardado nesta aba.",
  umServidorEmComum: "1 servidor em comum",
  servidoresEmComum: "{{quantos}} servidores em comum",
  semServidoresEmComum: "Sem servidores em comum",
};
