
export const comum = {
  voltar: "Voltar",
  agoraNao: "Agora não",
  erro: {
    tentarDeNovo: "Tentar de novo",
    recarregar: "Recarregar",
    copiarDetalhes: "Copiar detalhes",
    parteQuebrou: "Esta parte da tela quebrou.",
    titulo: "O Ravox Chat tropeçou.",
    detalhe: "Alguma coisa quebrou no meio do caminho e a tela não conseguiu se desenhar. Sua conversa não se perdeu — está tudo no servidor.",
  },
  perdido: {
    titulo: "Esse endereço não leva a lugar nenhum.",
    detalhe: "Ou o link veio errado, ou a página mudou de lugar.",
  },
  conexao: {
    voltou: "Conectado de novo",
    reconectando: "Reconectando",
    tentativaSufixo: " · tentativa {{numero}}",
    aSalvo: "A conversa está a salvo no servidor. Isto volta sozinho assim que a conexão voltar.",
  },
  avisoDoNavegador: {
    titulo: "Quer ser avisado das mensagens?",
    detalhe: "Com o Ravox Chat atrás de outra janela, ele te chama.",
  },
  atualizacao: {
    titulo: "Atualização",
    semAuto: "Esta versão do aplicativo não sabe se atualizar sozinha. Baixe o instalador mais novo abaixo e instale por cima.",
    versaoAtual: "Você está na versão {{versao}}.",
    instalando: "Instalando a versão {{versao}}…",
    prontaVersao: "Versão {{versao}} pronta para instalar",
    baixandoVersao: "Baixando a versão {{versao}}…",
    baixandoComProgresso: "Baixando a versão {{versao}}… {{porcento}}%",
    saiuVersao: "Saiu a versão {{versao}}",
    saiuVersaoClique: "Saiu a versão {{versao}} — clique para baixar",
    instalarVersaoEReiniciar: "Instalar a versão {{versao}} e reiniciar",
    erroTenteDeNovo: "{{erro}} Clique para tentar de novo.",
    procurando: "Procurando…",
    emDia: "Você está em dia",
    vaiFechar: "O aplicativo vai fechar em instantes.",
    comoInstala: "O aplicativo fecha, troca a versão e reabre sozinho. Sai da chamada se você estiver em uma.",
    semServidor: "Não consegui falar com o servidor de versões.",
    procuraSozinho: "O aplicativo procura sozinho na abertura e a cada seis horas.",
    instalandoReticencias: "Instalando…",
    instalandoCurto: "Instalando",
    baixandoCurto: "Baixando",
    tentarDeNovo: "Tentar de novo",
    reiniciarAgora: "Reiniciar agora",
    instalarEReiniciar: "Instalar e reiniciar",
    baixar: "Baixar",
    procurar: "Procurar",
    baixarApp: "Baixar o aplicativo",
    ariaBotao: "Atualização do aplicativo",
  },
  janela: {
    ajustarAltura: "Ajustar a altura",
    redimensionar: "Redimensionar a janela",
    ajustarLargura: "Ajustar a largura",
  },
  dica: {
    rotulo: "Dica:",
    pularConfirmacao: "segure Shift ao clicar para pular esta confirmação.",
  },
  cor: {
    pescar: "Pescar uma cor da tela",
    hex: "Valor em hexadecimal",
  },
  imagem: {
    titulo: "Selecione uma imagem",
    enviar: "Enviar imagem",
    escolherGif: "Escolher GIF",
    buscarGif: "Buscar GIF",
  },
  fonte: {
    rotulo: "Fonte da mensagem",
    padrao: "Padrão",
    comNome: "Fonte da mensagem — {{fonte}}",
  },
  recorte: {
    titulo: "Recortar o ícone",
    detalhe: "Arraste para escolher o pedaço e use a barra para aproximar. O ícone fica redondo em todo lugar do app.",
    voltarAoComeco: "Voltar ao começo",
    usar: "Usar este recorte",
  },
  mais: "Mais",
  carregando: "Carregando…",
  salvar: "Salvar",
  salvando: "Salvando…",
  descartar: "Descartar",
  redefinir: "Redefinir",
  naoSalvo: "Você tem alterações não salvas.",
  fechar: "Fechar",
  criar: "Criar",
  nome: "Nome",
  emoji: "Emoji",
  previa: "Prévia",
  cancelar: "Cancelar",
  enviar: "Enviar",
  apagar: "Apagar",
  excluir: "Excluir",
  remover: "Remover",
  trocar: "Trocar",
  loginNoApp: {
    titulo: "Tudo certo!",
    detalhe: "Você entrou com a sua conta. Pode voltar pro Ravox Chat, o aplicativo já está te esperando.",
    abrir: "Abrir o Ravox Chat",
    fecharAba: "Já pode fechar esta aba.",
    falhouTitulo: "O login não deu certo",
    falhouDetalhe: "Volte pro aplicativo e tente entrar de novo.",
    legenda: "Um robô acenando",
    legendaFalhou: "Um gatinho chorando",
  },
  ads: {
    label: "Publicidade",
    title: "Anuncie aqui",
    detail: "Fale com a gente e apareça para quem usa o Ravox Chat.",
    action: "Quero anunciar",
  },
};
