
export const configuracoes = {
  efeitos: {
    titulo: "Efeitos do ponteiro",
    detalhe: "Rastro e faísca desenhados por cima do app. Nascem desligados, e somem sozinhos se você pediu menos animação.",
    rastro: "Rastro do cursor",
    rastroDetalhe: "Um risco que segue o ponteiro e vai apagando atrás.",
    faisca: "Faísca ao clicar",
    faiscaDetalhe: "Riscos curtos que saem do ponto onde você clicou.",
    cor: "Cor",
    espessura: "Espessura",
    comprimento: "Comprimento",
    tamanho: "Tamanho",
    quantidade: "Quantidade",
  },
  email: {
    verificarTitulo: "Confirme o seu e-mail",
    verificarDetalhe: "Algumas comunidades só deixam falar quem confirmou. Leva um clique.",
    enviar: "Mandar o link",
    enviado: "Olhe a caixa de entrada. O link vale por um dia.",
    falhou: "Não deu para mandar o e-mail.",
    confirmado: "E-mail confirmado",
    confirmadoDetalhe: "Pronto. Agora você fala em qualquer comunidade que exija isso.",
    linkIncompleto: "Link incompleto",
    linkIncompletoDetalhe: "Falta o código no endereço. Abra o link direto do e-mail.",
    confirmando: "Confirmando…",
    expirou: "Este link já foi usado ou passou da validade.",
    irParaOApp: "Ir para o aplicativo",
  },
  tema: {
    indisponivel: "Tema indisponível",
    indisponivelDetalhe: "Quem publicou apagou, ou o link está errado.",
    indisponivelLinha: "Tema indisponível. Quem publicou apagou, ou o link está errado.",
    importar: "Importar tema",
    importarCurto: "Importar",
    importarDetalhe: "Isso substitui o tema que você tem agora. Dá para editar depois em Configurações > Aparência > Estúdio de temas.",
    porAutor: "por {{autor}}",
    umaCorTrocada: "1 cor trocada",
    coresTrocadas: "{{quantas}} cores trocadas",
    avisoDeCss: "Este tema traz CSS de quem escreveu, e CSS mexe em qualquer canto da tela. Só importe de gente em quem você confia.",
    soCores: "Este tema só troca cores. Nada de CSS de fora.",
    verCss: "Ver o CSS",
    esconderCss: "Esconder o CSS",
    aplicar: "Aplicar",
    previaSemMotor: "A prévia não roda o motor. Instale para ver.",
    motorAnimado: "{{motor}} animado",
  },
  sair: "Sair",
  versoes: {
    termos: "Termos de serviço",
    privacidade: "Política de privacidade",
    copiar: "Clique para copiar",
    copiado: "Copiado",
  },
  appColors: {
    title: "Cores do app",
    detail: "Escolha até três cores e o app inteiro ganha esse degradê.",
    locked: "O editor de cores é do {{plan}}.",
    color: "Cor {{number}}",
    addColor: "Adicionar cor",
    removeColor: "Remover cor",
    surprise: "Surpreenda-me",
    direction: "Direção do degradê",
    intensity: "Intensidade",
    reset: "Redefinir",
  },
  subscription: {
    colorsRow: "Editor de cores do app",
    seePlans: "Ver planos",
    upgradeSubtitle: "Limites maiores e recursos exclusivos para quem escreve, manda arquivo e transmite.",
    perMonth: "por mês",
    perYear: "por ano",
    save: "Economize {{percent}}%",
    howToPay: "Como você quer pagar?",
    legal: "Você pode pedir reembolso em até 7 dias depois do pagamento. O pagamento é processado pela Stripe; nunca vemos o número do seu cartão.",
    compare: "Grátis × Infinity",
    featureColumn: "Recurso",
    freeColumn: "Grátis",
    messageRow: "Limite de caracteres da mensagem",
    attachmentRow: "Tamanho de arquivo para envio",
    screenRow: "Qualidade do vídeo",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Você já tem o Infinity até {{date}}.",
    upsell: "Aumentar o limite com o Infinity",
    screenUpsell: "Liberar mais qualidade com o Infinity",
    free: "Você está no plano grátis.",
    activeUntil: "Infinity ativo até {{date}}.",
    renews: "Renova sozinho em {{date}}.",
    endsAt: "A assinatura foi cancelada e termina em {{date}}.",
    pastDue: "A última cobrança falhou. Atualize o cartão para não perder o Infinity.",
    waiting: "Confirmando o pagamento…",
    subscribe: "Assinar",
    monthly: "Mensal",
    yearly: "Anual",
    automatic: "Cartão",
    manage: "Gerenciar pagamento",
    refund: "Pedir reembolso",
    refundDetail: "Dá para desistir em até 7 dias depois do pagamento: {{amount}}, até {{date}}.",
    refundConfirm: "Pedir o reembolso?",
    refundConfirmDetail: "O dinheiro volta pela mesma forma de pagamento e o Infinity acaba na hora.",
    refunded: "Reembolso pedido.",
    unavailable: "A assinatura ainda não está disponível.",
    success: "Pagamento recebido. Obrigado!",
    canceled: "Pagamento cancelado.",
    error: "Não deu certo. Tente de novo.",
    no: "Não",
    tagRow: "Tag de usuário personalizada",
    guildProfilesRow: "Perfis por comunidade",
    badgeRow: "Selo do perfil",
    communitiesRow: "Comunidades",
    savedRow: "Mensagens salvas",
    animatedEmojiRow: "Usar emojis animados",
    expressionsRow: "Acesso global a emojis e figurinhas",
    animatedProfileRow: "Avatares e banners de perfil animados",
    earlyAccessRow: "Acesso antecipado a novos recursos",
    themesRow: "Temas personalizados",
    pixOption: "Pix",
    pixHint: "Abra o app do banco, escolha Pix e leia o QR code ou use o copia e cola.",
    pixQrAlt: "QR code do Pix",
    pixCopy: "Copiar código Pix",
    pixCopied: "Código Pix copiado",
    pixWaiting: "Aguardando o pagamento",
    pixExpiresIn: "vence em {{time}}",
    pixExpired: "Esse Pix venceu. Gere outro para continuar.",
    pixNew: "Gerar outro Pix",
    pixPaid: "Pix recebido! Seu Infinity já está ativo.",
    forMe: "Para mim",
    asGift: "De presente",
    buyGift: "Comprar presente",
    giftReady: "Presente pronto! Copie o link e mande para quem você quiser.",
    giftClaimed: "Presente resgatado! O Infinity já está na sua conta.",
    gifts: "Presentes",
    giftsEmpty: "Você ainda não comprou nenhum presente.",
    giftCode: "Código do presente",
    giftRedeem: "Resgatar",
    giftCopyLink: "Copiar link",
    giftLinkCopied: "Link copiado",
    giftClaimedBy: "resgatado por {{name}}",
    giftHint: "Tem um código de presente? Resgate aqui. Os presentes que você comprou aparecem abaixo.",
    cardPaid: "Pagamento aprovado! Seu Infinity já está ativo.",
    payAmount: "Pagar {{amount}}",
    giftLinkTitle: "Você recebeu um presente do {{plan}}!",
    giftLinkDetail: "Toque em resgatar e os dias entram na sua conta.",
    pageTitle: "Desbloqueie um mundo de vantagens com o {{plan}}",
    pageStart: "Início",
    pageBest: "O melhor do Infinity",
    pageChoose: "Escolha seu plano",
    fromPrice: "A partir de {{amount}} por mês. Cancele quando quiser.",
    filesTitle: "Mande o arquivo inteiro",
    filesText: "O vídeo da festa, o projeto do trabalho, a pasta com as fotos: vai tudo de uma vez, sem cortar, sem compactar e sem link de nuvem no meio.",
    videoTitle: "Transmita em 1080p",
    videoText: "A sua tela chega nítida para quem está do outro lado, com o dobro de quadros por segundo. Dá para ler código e jogar junto sem virar borrão.",
    messageTitle: "Escreva à vontade",
    messageText: "O dobro de caracteres em cada mensagem, para quando a história é longa e quebrar em três partes estragaria a graça.",
    colorsTitle: "O app com a sua cara",
    colorsText: "Escolha as cores do aplicativo uma a uma, salve o tema e leve para todos os aparelhos onde você entra.",
    profileTitle: "Um perfil para cada lugar",
    profileText: "Outro apelido, outra foto, outra descrição em cada comunidade — e foto animada, se você quiser.",
    freeDetail: "É de graça e continua sendo.",
    currentPlan: "Seu plano atual",
    popular: "Mais escolhido",
    yearlyDetail: "Sai {{amount}} por mês, cobrado uma vez por ano.",
    monthlyDetail: "Cobrado todo mês, cancela quando quiser.",
    groupStyle: "Mostre o seu estilo",
    groupLook: "Deixe o app do seu jeito",
    groupLimits: "Sem limites apertados",
    closingTitle: "O que você está esperando?",
    pagePlans: "Planos",
    pageCompare: "Comparar",
    giftClaimTitle: "Ativar o {{plan}}?",
    giftClaimDetail: "São {{days}} dias que entram na sua conta agora.",
    giftFrom: "de {{name}}",
    giftActivate: "Ativar",
    giftHasPlanTitle: "Você já tem o Infinity",
    giftHasPlanDetail: "Seu plano vale até {{date}}. Guarde o link e mande para um amigo aproveitar.",
    giftUsedTitle: "Esse presente já foi usado",
    giftUsedDetail: "Alguém resgatou esse código antes. Peça outro a quem te mandou.",
    giftNotFoundTitle: "Código não encontrado",
    giftNotFoundDetail: "Confira se o código está certo ou peça o link de novo.",
    giftDoneTitle: "{{plan}} ativado!",
    giftOpenApp: "Abrir o app",
    giftSignIn: "Entrar para resgatar",
    giftReviewStep: "Pagamento · Revisar",
    giftTotalToday: "Total de hoje",
    giftCardWhy: "O cartão é só para confirmar que é você. Nada é cobrado agora e nada renova sozinho.",
    giftAgree: "Li e aceito os termos de uso",
    giftActivating: "Ativando…",
  },
  telas: {
    subscription: "Infinity",
    conta: "Minha conta",
    privacidade: "Privacidade",
    conexoes: "Conexões",
    voz: "Áudio",
    video: "Vídeo",
    avisos: "Notificações",
    aplicativos: "Aplicativos",
    aparencia: "Aparência",
    batePapo: "Bate-papo",
    acessibilidade: "Acessibilidade",
    idioma: "Idioma",
    aplicativo: "Baixar o app",
    atalhos: "Atalhos",
    desktop: "Aplicativo desktop",
    avancado: "Avançado",
    servidor: "Servidor",
    comunicado: "Comunicado do sistema",
    denuncias: "Denúncias",
    publicacoes: "Publicações",
  },
  grupos: {
    conta: "Conta",
    app: "Configurações do app",
    desenvolvedor: "Desenvolvedor",
    administracao: "Administração",
  },
  secoes: {
    coresDoApp: "Cores do app",
    detalhesDeLogin: "Detalhes de login",
    dispositivos: "Dispositivos",
    usuariosBloqueados: "Usuários bloqueados",
    aplicativosAutorizados: "Aplicativos autorizados",
    sessoes: "Sessões",
    amigosEDms: "Amigos e mensagens diretas",
    compartilhamentoDeAtividade: "Compartilhamento de atividade",
    visibilidadeDoPerfil: "Visibilidade do perfil",
    exportarDados: "Exportar dados",
    exclusaoDeDados: "Exclusão de dados",
    tema: "Tema",
    corDeDestaque: "Cor de destaque",
    interface: "Interface",
    listaDeCanais: "Lista de canais",
    zoomDoApp: "Nível de zoom do app",
    escalaDaFonte: "Escala da fonte do chat",
    modoStreamer: "Privacidade de transmissão",
    cursores: "Cursores",
    movimento: "Movimento",
    textoEmVoz: "Texto em voz",
    teclado: "Teclado",
    formatoDaHora: "Formato da hora",
    idiomaDaInterface: "Idioma da interface",
    dispositivosDeVoz: "Dispositivos",
    testeDoMicrofone: "Teste do microfone",
    modoDeEntrada: "Modo de entrada",
    sensibilidade: "Sensibilidade de entrada",
    qualidade: "Qualidade",
    camera: "Câmera",
    transmissao: "Transmissão",
    exibicao: "Exibição",
    entrada: "Entrada",
    midia: "Mídia",
    geral: "Geral",
    preferenciaDeMencao: "Preferência de menção",
    sons: "Sons",
  },
};
