export const amizades = {
  mensagensDiretas: "सीधे संदेश",
  nova: {
    titulo: "नई बातचीत",
    detalhe: "किसी दोस्त को चुनिए, बातचीत खुल जाएगी।",
    procurar: "दोस्त खोजें",
    semAmigos: "यहाँ आपके अभी कोई दोस्त नहीं हैं।",
    semResultado: "इस नाम का कोई दोस्त नहीं।",
  },
  adicionar: {
    recado: "दो लाइन लिखिए (ज़रूरी नहीं)",
    recadoDica: "यहाँ जो लिखेंगे वह आपकी बातचीत में भी दिखेगा, अगर आप दोस्त बन गए।",
    enviadoPara: "हो गया! दोस्ती की दरख़्वास्त {{nome}} तक पहुँच गई।",
    outrosLugares: "दोस्त बनाने की और जगहें",
    outrosLugaresDetalhe: "कोई याद नहीं आ रहा? खुली कम्युनिटी देखिए, वहाँ लगभग हर चीज़ पर बात होती है।",
    explorarComunidades: "कम्युनिटी देखें",
    titulo: "दोस्त जोड़ें",
    detalhe: "आप दोस्तों को उनके यूज़रनेम से जोड़ सकते हैं।",
    exemplo: "यूज़रनेम, जैसे: thiago",
    enviando: "भेज रहे हैं…",
    enviar: "अनुरोध भेजें",
  },
  gatinhoChorando: "रोता हुआ बिल्ली का बच्चा",
  status: {
    emChamada: "कॉल पर",
    emVoz: "वॉइस में",
  },
  menu: {
    chamada: "कॉल शुरू करें",
    fixar: "ऊपर पिन करें",
    desafixar: "पिन हटाएँ",
    silenciar: "बातचीत म्यूट करें",
    reativar: "बातचीत अनम्यूट करें",
    copiarIdDoCanal: "चैनल आईडी कॉपी करें",
  },
  ativosAgora: "अभी सक्रिय",
  procurando: "देख रहे हैं कौन है…",
  tudoTranquilo: "अभी सब शांत है…",
  tudoTranquiloDetalhe: "जब आप या कोई दोस्त कॉल में आएंगे, वह यहाँ दिखेगी — और आप एक क्लिक में जुड़ सकते हैं।",
  emVoz: "वॉइस में",
  voce: "आप",
  soVoce: "सिर्फ आप",
  pessoas: "{{quantas}} लोग",
  voltarParaChamada: "कॉल पर लौटें",
  entrarNaChamada: "कॉल में शामिल हों",
  abrirCanal: "{{servidor}} में {{canal}} खोलें",
  encontreConversa: "बातचीत खोजें",
  amigos: "दोस्त",
  conversas: "बातचीत",
  semConversas: "अभी कोई बातचीत नहीं। शुरू करने के लिए एक दोस्त जोड़ें।",
  semConversaComEsseNome: "उस नाम की कोई बातचीत नहीं।",
  abrirMenu: "सर्वर और बातचीत खोलें",
  solicitacoes: "संदेश अनुरोध",
  pedidos: "अनुरोध",
  spam: "स्पैम",
  pedidosPendentes: "लंबित अनुरोध",
  marcadosComoSpam: "स्पैम के रूप में चिह्नित",
  aceitar: "स्वीकारें",
  ignorar: "अनदेखा करें",
  marcarSpam: "स्पैम चिह्नित करें",
  semPedidos: "कोई अनुरोध लंबित नहीं।",
  semPedidosDetalhe: "जो आपका दोस्त नहीं है पर आपके साथ एक सर्वर साझा करता है, वह आपकी बातचीत तक पहुँचने से पहले यहाँ आता है।",
  semSpam: "कुछ भी स्पैम चिह्नित नहीं।",
  semSpamDetalhe: "स्पैम फ़िल्टर जो अलग करे, या आप जो चिह्नित करें, वह इस टैब में रहता है।",
  umServidorEmComum: "1 साझा सर्वर",
  servidoresEmComum: "{{quantos}} साझा सर्वर",
  semServidoresEmComum: "कोई साझा सर्वर नहीं",
};
