export const comum = {
  voltar: "वापस",
  agoraNao: "अभी नहीं",
  erro: {
    tentarDeNovo: "फिर से कोशिश करें",
    recarregar: "फिर से लोड करें",
    copiarDetalhes: "ब्योरा कॉपी करें",
    parteQuebrou: "स्क्रीन का यह हिस्सा टूट गया।",
    titulo: "Ravox Chat लड़खड़ा गया।",
    detalhe: "रास्ते में कुछ टूट गया और स्क्रीन खुद को बना नहीं पाई। आपकी बातचीत खोई नहीं है — सब कुछ सर्वर पर है।",
  },
  perdido: {
    titulo: "यह पता कहीं नहीं ले जाता।",
    detalhe: "या तो लिंक गलत है, या पेज कहीं और चला गया।",
  },
  conexao: {
    voltou: "फिर से जुड़ गए",
    reconectando: "फिर से जोड़ रहे हैं",
    tentativaSufixo: " · कोशिश {{numero}}",
    aSalvo: "बातचीत सर्वर पर सुरक्षित है। कनेक्शन लौटते ही यह खुद ही वापस आ जाएगा।",
  },
  avisoDoNavegador: {
    titulo: "संदेशों की सूचना चाहिए?",
    detalhe: "Ravox Chat किसी और विंडो के पीछे हो तो वह आपको बुला लेगा।",
  },
  atualizacao: {
    titulo: "अपडेट",
    semAuto: "ऐप का यह संस्करण खुद को अपडेट करना नहीं जानता। नीचे से सबसे नया इंस्टॉलर डाउनलोड करें और उसी के ऊपर इंस्टॉल करें।",
    versaoAtual: "आप संस्करण {{versao}} पर हैं।",
    instalando: "संस्करण {{versao}} इंस्टॉल हो रहा है…",
    prontaVersao: "संस्करण {{versao}} इंस्टॉल के लिए तैयार है",
    baixandoVersao: "संस्करण {{versao}} डाउनलोड हो रहा है…",
    baixandoComProgresso: "संस्करण {{versao}} डाउनलोड हो रहा है… {{porcento}}%",
    saiuVersao: "संस्करण {{versao}} आ गया",
    saiuVersaoClique: "संस्करण {{versao}} आ गया — डाउनलोड करने के लिए क्लिक करें",
    instalarVersaoEReiniciar: "संस्करण {{versao}} इंस्टॉल करें और फिर से चालू करें",
    erroTenteDeNovo: "{{erro}} फिर से कोशिश करने के लिए क्लिक करें।",
    procurando: "खोज रहे हैं…",
    emDia: "आप अपडेटेड हैं",
    vaiFechar: "ऐप कुछ ही पल में बंद हो जाएगा।",
    comoInstala: "ऐप बंद होता है, संस्करण बदलता है और खुद ही फिर खुल जाता है। अगर आप कॉल में हैं तो वह छूट जाएगी।",
    semServidor: "संस्करण सर्वर से बात नहीं हो पाई।",
    procuraSozinho: "ऐप खुलने पर और हर छह घंटे में खुद ही देखता है।",
    instalandoReticencias: "इंस्टॉल हो रहा है…",
    instalandoCurto: "इंस्टॉल हो रहा है",
    baixandoCurto: "डाउनलोड हो रहा है",
    tentarDeNovo: "फिर से कोशिश करें",
    reiniciarAgora: "अभी फिर से चालू करें",
    instalarEReiniciar: "इंस्टॉल करें और फिर से चालू करें",
    baixar: "डाउनलोड",
    procurar: "जाँचें",
    baixarApp: "ऐप डाउनलोड करें",
    ariaBotao: "ऐप का अपडेट",
  },
  janela: {
    ajustarAltura: "ऊँचाई समायोजित करें",
    redimensionar: "विंडो का आकार बदलें",
    ajustarLargura: "चौड़ाई समायोजित करें",
  },
  dica: {
    rotulo: "सुझाव:",
    pularConfirmacao: "क्लिक करते समय Shift दबाए रखें और यह पुष्टि छूट जाएगी।",
  },
  cor: {
    pescar: "स्क्रीन से रंग उठाएँ",
    hex: "हेक्साडेसिमल मान",
  },
  imagem: {
    titulo: "एक तस्वीर चुनें",
    enviar: "तस्वीर भेजें",
    escolherGif: "GIF चुनें",
    buscarGif: "GIF खोजें",
  },
  fonte: {
    rotulo: "संदेश का फ़ॉन्ट",
    padrao: "डिफ़ॉल्ट",
    comNome: "संदेश का फ़ॉन्ट — {{fonte}}",
  },
  recorte: {
    titulo: "आइकॉन काटें",
    detalhe: "मनचाहा हिस्सा चुनने के लिए खींचें और ज़ूम के लिए स्लाइडर का इस्तेमाल करें। ऐप में हर जगह आइकॉन गोल दिखता है।",
    voltarAoComeco: "शुरुआत पर लौटें",
    usar: "यही कटाव इस्तेमाल करें",
  },
  mais: "और",
  carregando: "लोड हो रहा है…",
  salvar: "सहेजें",
  salvando: "सहेजा जा रहा है…",
  descartar: "छोड़ें",
  redefinir: "रीसेट करें",
  naoSalvo: "आपके पास बिना सहेजे बदलाव हैं।",
  fechar: "बंद करें",
  criar: "बनाएँ",
  nome: "नाम",
  emoji: "इमोजी",
  previa: "झलक",
  cancelar: "रद्द करें",
  enviar: "भेजें",
  apagar: "मिटाएँ",
  excluir: "मिटाएँ",
  remover: "हटाएँ",
  trocar: "बदलें",
  loginNoApp: {
    titulo: "सब तैयार है!",
    detalhe: "आपने साइन इन कर लिया है। Ravox Chat पर वापस जाएँ, ऐप आपका इंतज़ार कर रहा है।",
    abrir: "Ravox Chat खोलें",
    fecharAba: "अब आप यह टैब बंद कर सकते हैं।",
    falhouTitulo: "साइन इन नहीं हो सका",
    falhouDetalhe: "ऐप पर वापस जाएँ और फिर से साइन इन करें।",
    legenda: "हाथ हिलाता रोबोट",
    legendaFalhou: "रोता हुआ बिल्ली का बच्चा",
  },
  ads: {
    label: "विज्ञापन",
    title: "यहाँ विज्ञापन दें",
    detail: "हमसे बात करें और Ravox Chat इस्तेमाल करने वालों तक पहुँचें।",
    action: "मुझे विज्ञापन देना है",
  },
};
